### ISSUE TITLE
Раздел: Видео

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#1]
_Раздел планируется, тут обсуждается как реализовывать._

**Раздел:** Видео.
**Статус:** Запланирован.
**Описание:**
Раздел в котором будут выкладываться видеоролики на Drupal тематику. В нашем случае, это будут видео уроки, рекламные Drupal-ролики (по типу ассоциации), видео докладов, любительские (с кафе и кемпов)

**У видео будет:**
-  Заголовок;
-  Описание;
-  Вставка ссылки на ролик (YouTube, Vimeo?);
-  Привязка к проектам, а затем дальнейший вывод видео непосредственно на странице проекта;
-  Категория (Search API, Form API…);
-  Тип видео (Доклад, видеоурок…).

**Comment by xandeadx** [comment]
Не нужно. Есть drupal-tv.ru. Да и видео выходят крайне редко, а на русском - практически нет.

**Comment by Samodelkin777** [comment]
Согласен, не в первую очередь как минимум.

**Comment by pselfin** [comment]
http://drupal-tv.ru/ - за 2015 последний залив.
Нужен раздел, нужен...
