### ISSUE TITLE
Раздел: Статья-ссылка

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#10]
_Раздел планируется, тут обсуждается как реализовывать._

**Раздел:** Статья-ссылка.
**Статус:** Запланирован.
**Описание:**
Принцип как у публикаций. Заголовок, краткой описание и поле для ссылки. Выводится как тизер, при нажатии на заголовок переходит на страницу с полным содержимым. Можно также оставить открытым комментирование в сообществе, мало ли ссылка будет вести на закрытый сайт, типа хабра, либо разрешать публиковать только свои материалы.

**Comment by adubovskoy** [comment]
в nofollow не забыть только. а так можно

**Comment by Niklan** [comment]
https://tjournal.ru/c/17611-ford-nauchit-telefoni-zavodit-mashini Как пример
