### ISSUE TITLE
В новой теме отсутствует маркер "лучшего" вопроса

### ISSUE THREAD

**Issue by drupby** [Niklan/Dru.io#100]
В новой теме на странице вопросов (http://dru.io/question) никак не маркируются вопросы решенные, помеченные как лучшие. Пример решенного вопроса http://dru.io/question/1098. Я бы заменил .question.teaser .question__right h2 a:before с иконки вопроса на иконку решенного вопроса, если такой имеется.

**Comment by Niklan** [comment]
Добавлен
