### ISSUE TITLE
Подсветка кода не работает

### ISSUE THREAD

**Issue by semyondragunov** [Niklan/Dru.io#103]
сабж

**Comment by Niklan** [comment]
Где именно

**Comment by semyondragunov** [comment]
Везде:
http://dru.io/question/1115
http://dru.io/question/1120

**Comment by Niklan** [comment]
Ок, отключил сжатие js

**Comment by drupby** [comment]
"Ок, отключил сжатие js"
Что же за подсветка кода, которая работает только при выключенной агрегации скриптов?

**Comment by Niklan** [comment]
highlight.js (он кстати язык сам отлично понимает и не обязательно указывать language-php), надо заметить select2.js тоже отвалился при аггрегации. Мои подозрения падают на Advagg модуль

**Comment by adubovskoy** [comment]
reopen, сейчас опять

**Comment by Niklan** [comment]
А чем я помогу? Я ничего не трогал как я баг найду? Надо смотреть опять же после какого коммита навернулось. Могу лишь сказать что там highlightjs

И думаю надо серьезно уже подумать о запрете пуша без проверки на тесте. С новым функционалом валится старый - значит ничего не тестится .

**Comment by Niklan** [comment]
По всей видимости js пашет, стили отвалились.

**Comment by adubovskoy** [comment]
починилось
