### ISSUE TITLE
Предпросмотр при редактирование вопроса?

### ISSUE THREAD

**Issue by RuZniki** [Niklan/Dru.io#104]
Не могу найти как это сделать.
Может кнопка в WYSIWYG есть, но я её не нашел.
![dru io-preview](https://cloud.githubusercontent.com/assets/1125080/7113217/3863ce20-e1da-11e4-8a91-a0bed5f876d8.png)

**Comment by Niklan** [comment]
> Она утонула

А вообще, её нет :( Надо бы к BUEditor подцепить её
