### ISSUE TITLE
У комментариев к вопросу нет ссылок изменить/ответить/удалить

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#105]
сабж

**Comment by RuZniki** [comment]
![2015-04-14 22_13_03- - options _ _ dru io](https://cloud.githubusercontent.com/assets/1125080/7145273/c177e04c-e2f3-11e4-9e93-bfdd8a266678.png)
+1

**Comment by Niklan** [comment]
Вернул, видимо забыл при переносе вытащить поле.
