### ISSUE TITLE
Скрыть vertical tabs в форме добавления ответа

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#106]
При создании ответа они не нужны, только при редактировании

![2015-04-13_210121](https://cloud.githubusercontent.com/assets/845389/7121879/421e9076-e220-11e4-90e4-ec1b24ecc684.png)

**Comment by xandeadx** [comment]
И в форме добавления вопроса то же можно скрыть

**Comment by Niklan** [comment]
Но это только же для модеров\админов, как это мешает обычным?)

Какой best practice по их "пряткам"? Не было необходимости раньше их прятать админам.

**Comment by xandeadx** [comment]
```
$form['additional_settings']['#access'] = FALSE;
```

**Comment by Niklan** [comment]
@xandeadx спасибо, сделаю. И действительно же) Вечно забываю что табы эти - элементы формы.
