### ISSUE TITLE
Сменить виждет поля "Версия Drupal" на чекбоксы

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#107]
Select2 там совершенно не нужен, хватит обычных чекбоксов в линию

**Comment by xandeadx** [comment]
Можно вообще сделать поле single-value, а виджет сменить на select. Смысла в нескольких версиях друпала особо не вижу.

**Comment by Niklan** [comment]
Думаю вполне удобно покачто. Если что, кому не удобен селект2 там, тож пишите, открою.
