### ISSUE TITLE
UI: перенести ссылки комментариев в шапку коммента

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#109]
Глаза мозолят. Плюс сделать их на пиксель меньше текста комментария. Можно даже их скрыть и показывать только при наведении.

Было:

![2015-04-14_213417](https://cloud.githubusercontent.com/assets/845389/7144491/9c98838a-e2ee-11e4-8a19-e193a01d3367.png)

Стало:

![2015-04-14_213740](https://cloud.githubusercontent.com/assets/845389/7144494/a175d376-e2ee-11e4-98b7-56b701b97729.png)

**Comment by semyondragunov** [comment]
ИМХО, лучше по наведению.

**Comment by Niklan** [comment]
Был редизайн, данный ишью более не актуален.
