### ISSUE TITLE
Раздел: Промо-страница Drupal

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#11]
_Раздел планируется, тут обсуждается как реализовывать._

**Раздел:** Промо-страница.
**Статус:** Запланирован.
**Описание:**
Красивая посадочная и показушная страница что такое Друпал, что может, чем знаменит, в общем  то что любят заказчики но не могут найти в русском интернете нигде.

**Comment by semyondragunov** [comment]
Не считаю целесообразным. Т.к. каждая контора/человек по своему будет представлять друпал в нужном ему свете.

**Comment by Niklan** [comment]
Лол, именно поэтому и нужна данная страница, чтобы все представляли в едином стиле. А каждая конторка\человек выделит наиболее важные или вообще другие плюсы системы, если потребуется.

Люди мало знаот о друпале, нам нужно рассказывать о нем, и доступно, в видео промо-странички. Не будут же потенциальные заказчики обращаться  в студии чтобы про друпал узнать.

**Comment by adubovskoy** [comment]
Можно просто перевести drupal.com

**Comment by Niklan** [comment]
Да, для начала отличный вариант. Но в дальнейшем, думаю надо будет хорошо поработать над страничкой, сделать разделы для заказчиков и программистов где будет целевая информация.

Сейчас же, на drupal.com достаточно скудно всё, а всё потому, что он в рекламе за рубежом не нуждается.

**Comment by semyondragunov** [comment]
Ну если нефиг делать будет запилите!) Пока не принципиально, так как ЦУ (целевая аудитория) у сообщества это прогеры.

**Comment by Niklan** [comment]
У нас наоборот же ЦУ начинающие разрабы и заказчики. Прогеры отностятся к начинающим, если не знают друпал и он тоже им должен быть представлен. А если прогер уже друпалер, ему и сообщество то как таковое не нужно, т.е. по сути ни оден раздел кроме мероприятий и заказов.

**Comment by semyondragunov** [comment]
А как ты заказчиков будешь зазывать на сайт? Сами они фиг его найдут, ну во всяком случае не в первые полгода-год. Тут могут помочь конечно коммерческие конторы, но из-за ващего фриланс раздела это палка о двух концах. Других вариантов я не вижу. Да и вообще это отдельный разговор для отдельной темы.

С прогерами та же кухня кстати. Все на друру попадают.

**Comment by Niklan** [comment]
А зачем нам чтобы уже завтра они были. Пока особо огромного наплыва и не нужно, легче будет менять всё и улучшать.

Если контент появится, начнут попадать, куда денутся. Если так пессемистично смотреть, то ни одно бы альтернативное сообщество не взлетело, а их уймы. 

Уже вроде давно стало понято, что drupal.ru как домен нам нафиг не вперся. Да он клевый, но если концетрация будет на другом ресурсе, никакой домен не поможет.

**Comment by semyondragunov** [comment]
Я про домен, то что он весь поиск забил. Ну не весь но ОЧЕНЬ большую часть. Ладно, разговор не об этом.

**Comment by Niklan** [comment]
Ну будет он первым, сообщество, допустим вторым, какая разница то. Человек в 99.9% не найдет ответа по первой ссылке, пойдет по второй, а мы его уже тут ловить будем)
