### ISSUE TITLE
Материалы пользователя в профиле: вопросы, блоги

### ISSUE THREAD

**Issue by tlito** [Niklan/Dru.io#111]
Мне важны мои вопросы, на которые мне дали ответы. Я хочу видеть в своем профиле все мои вопросы. Поэтому предлагаю сделать все материалы в профиле видными по вкладкам: на главной странице профиля - вопросы, потом вкладка Блоги.

**Comment by greeneyesmi** [comment]
Может и сделают. Вьюсов накрошить на это дело не долго, просто заняты все, вероятно

**Comment by SemanticsPRO** [comment]
ну в общем, либо я, либо Саша, кто первый добежит до админки

**Comment by Niklan** [comment]
Уже имеется.
