### ISSUE TITLE
Теги при добавлении вопроса

### ISSUE THREAD

**Issue by tlito** [Niklan/Dru.io#112]
Теги очень важны для поисковой  оптимизации и удобства попадания на нужную страницу ищущих в поисковиках посетителей. Добавьте еще одно поле в форму вопроса - теги, свои собственные теги, автодополняемая область ввода

**Comment by Niklan** [comment]
Ненеужно, отказались. Мы теги заменили категориями. Все что нужно содержится в воросе и ответе (ключевые слова). 90% не сможет грамотно заполнить теги, они будут состоять из: нужна помощь, помогите, не могу решить, как сделать ... и т.п. Смысла - 0.

Может тут есть другие мнения? Отписывайтесь.

**Comment by xandeadx** [comment]
Теги зло. Вы категорию то правильно с трудом можете выбрать, а что будет с тегами представить легко :)

**Comment by SemanticsPRO** [comment]
все мы видели теги на д.ру.
Только в дру.ио нет Василия Пинчука, который готов их лопатить

**Comment by Niklan** [comment]
Ну тут всё ясно. Закрываем. Если есть реально дельные предложения, пишите, переоткроем. Хотя, как говорилось, уже обсуждалось, теги были, и обсуждение пришло к том что мы сейчас и имеем - категории. И всё отлично.
