### ISSUE TITLE
Обмен печеньками в веб

### ISSUE THREAD

**Issue by tlito** [Niklan/Dru.io#113]
Некоторые вопросы могут иметь стоимость решения. Спрашивающий может предложить какую-нибудь печеньку, в частности, размещение ссылки автора лучшего правильного ответа у себя или другие, например, бесплатный дизайн или вёрстку для нового проекта отвечающего по требованию. Возможно, это редкая функция, но продумайте как вопрошающие могут поощрять отвечающих  за ответы на свои вопросы.

**Comment by adubovskoy** [comment]
тяжело реализовать. Вероятно придется отложить, пока не будет:
- проработанная концепция, как что и зачем (техзадание)
- дизайн

возьметесь продумать/сделать?)

**Comment by Niklan** [comment]
В общем то нечто подобное обсуждалось уже. Все скатится к тому что те кто реально может помочь будут игнорить пока не будет назначена награда.

**Comment by SemanticsPRO** [comment]
Честно говоря, я лично хотел бы получать заказы с dru.io, но сайт на данный момент никак к этому не приспособлен. Имхо.

Если пойти от обратного.
Запилить что-то типа статуса у разраба.
Дать возможность желающим указывать, что они могут оказывать платные услуги.
Например, вот так.
Миша, извини, ты под руку попался.
![png 908 x 493](https://cloud.githubusercontent.com/assets/1708410/7219704/4b57bbb0-e6b5-11e4-8864-55132cac8efa.png)

**Comment by Niklan** [comment]
Интересная идея со статусом. Надо писать его как сказал Виктор, только на ответе. Отличная м мотивация появляется помогать. Только мне кажется это уже относится непосредственно к изюма о профилях.

**Comment by Niklan** [comment]
#32 может туда статус перекатимся обсуждать?

**Comment by SemanticsPRO** [comment]
Ну, может.
Хотя, мне кажется, что вопрос "Статусов" довольно широкий и под него отдельный тикет надо завести.
Т.е. статус это или фиксированный набор и т.п.

**Comment by Niklan** [comment]
Заведи с синим своим. А то с мобилы неудобно а этот ишью не в тему

**Comment by SemanticsPRO** [comment]
Заведу попозже, уезжаю

**Comment by Niklan** [comment]
#124

**Comment by drupby** [comment]
Информацию по пользователю также и неплохо было бы добавить и на страницу профиля. Контактную информацию: твиттер, скайп, сайт, d.org профиль, github профиль, email и т.д. Ну и плюс текстовое поле "О себе" ("Кратко о себе"). На данный момент страница юзера слишком уныла и пуста.
