### ISSUE TITLE
Трекер для анонимов

### ISSUE THREAD

**Issue by SemanticsPRO** [Niklan/Dru.io#114]
Считаю, что в целях улучшения индексации и всего такого нужно запилить трекер для анонимов.
Сейчас им показывается, что нет нефига.

**Comment by Niklan** [comment]
Надо писать либо доступа нет, либо редиректить на форуму авторизации. ТРекер для анонимов это бесполезная штука. У нас анонимы не спрашивать не отвечать не могут.

**Comment by SemanticsPRO** [comment]
Д.ру через анонимный трекер только так и читается.
- Индексация

**Comment by Niklan** [comment]
Может я чего не понял. Ну ладно)

**Comment by drupby** [comment]
Трекер для анонимов - http://dru.io/question

**Comment by SemanticsPRO** [comment]
Трекер на то и трекер, что там не один вид контента должен присутствовать, да и обратной хронологической сортировки не вижу
