### ISSUE TITLE
UI: выделить картинки в контенте

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#116]
надо добавить рамку и желательно тень, чтобы было понятно где текст, а где картинка

**Comment by semyondragunov** [comment]
Ещё бы загрузку картинок неплохо было б. И увеличение при клике на фронт-енде.

**Comment by adubovskoy** [comment]
Есть варианты стороннего файлового хостинга для картинок? С друпалом что удобнее будет связать? Хранить на серваке - со временем разрастется, накладно очень будет.

**Comment by SemanticsPRO** [comment]
Когда разрастётся - тогда и переносить, имхо

**Comment by xandeadx** [comment]
вихтор прав
