### ISSUE TITLE
Отправка по CTRL+Enter

### ISSUE THREAD

**Issue by SemanticsPRO** [Niklan/Dru.io#117]
Хочу как на гитхабе

**Comment by Niklan** [comment]
Это как реализуется. На js ловим нажатие и .submit(), или есть более элегантный способ?

**Comment by SemanticsPRO** [comment]
Да врядли что-то круче есть, ну кроме того, что 100 пудов есть какой-нить jq плагин

**Comment by adubovskoy** [comment]
блин, там 1 строчка) какой плагин?)

**Comment by SemanticsPRO** [comment]
это был сарказм

**Comment by adubovskoy** [comment]
http://vanilla-js.com/ с гибкой системой плагинов)
