### ISSUE TITLE
Личка на dru.io

### ISSUE THREAD

**Issue by SemanticsPRO** [Niklan/Dru.io#118]
Что за комунити без лички?!?!?!?77777

**Comment by Niklan** [comment]
На нод.жэЭс надо сделать

**Comment by SemanticsPRO** [comment]
Да уж какие-нить, потом и ноду на друпальные сверху накрутить можно

**Comment by greeneyesmi** [comment]
Поддерживаю

**Comment by adubovskoy** [comment]
а https://www.drupal.org/project/privatemsg dev ветку (2x) кто смотрел?

**Comment by SemanticsPRO** [comment]
Потыкал, ни нашёл списка с киллер-фичами второй ветки

**Comment by adubovskoy** [comment]
аналогично, вот интересно. надо будет развернуть обе, посмотреть

**Comment by xandeadx** [comment]
я против лички.
имхо хватит формы обратной связи, а дальше общение по e-mail

**Comment by fortis** [comment]
тоже против, в разделе заказчиков это должны быть отклики

**Comment by Niklan** [comment]
Пока закрываю. Нет необходимости в любом случае. Что бы мы сейчас не сделали, это в любом случае будет хуже уже имеющихся решений. Контакты есть в профиле, каждый указывает как ему удобнее связаться и уже общение идет удобным способом.
