### ISSUE TITLE
Почтовая рассылка

### ISSUE THREAD

**Issue by SemanticsPRO** [Niklan/Dru.io#119]
Аналогичный тикет не искал, но хорошо бы раз в 1-2 недели пулять почтовой рассылкой с самым интересным и изменениями на сайте.

**Comment by Niklan** [comment]
Да, нужно. 
Особо вопросом не занимался. Есть что-то достойное кроме Simplenews и Mass Sender? Не думаю что нам нужны сторонние сервисы рассылки, через мандрил на отличненько всё уйдет.

**Comment by SemanticsPRO** [comment]
Людей мало, я бы через майлчимп бы слал

**Comment by adubovskoy** [comment]
мейлчимп в общем при увеличении нагрузки -- сомнительное решение, если будет пара тысяч человек, лучше через себя.

**Comment by SemanticsPRO** [comment]
Ты в пару тысяч человек в ближайшей перспективе веришь?
Когда придёт пора платить за мейлчимп - забираем базу и шлём другим способом

**Comment by adubovskoy** [comment]
я верю, мы ж по всем зарегистрированным будем слать например, так что возможная цифра. Да и симплньюс быстрее в настройке. mass contact не пробовал.

**Comment by SemanticsPRO** [comment]
Слать по всем зареганным - моветон

**Comment by adubovskoy** [comment]
согласен. ну, можно через mandrill как сейчас, он сам очереди формирует и т.п.

**Comment by semyondragunov** [comment]
ИМХО mass contact тут в кассу. Просто и удобно. А чтобы не слать по всем, поставить галочку в профиле, не слать. В mass contact можно создавать группы рассылки.

**Comment by Niklan** [comment]
Всем зареганым и новым ставить галку по умолчанию, но сделать отключаемой. Слать без отключения жесть какая-то.

**Comment by xandeadx** [comment]
вам не кажется что рассылки давно моветон? есть же rss

**Comment by adubovskoy** [comment]
В общем да, так многим удобнее. И в твиттер и социалки.
Сделал ишью, этот закрываю. https://github.com/Niklan/Dru.io/issues/122

**Comment by pselfin** [comment]
Апну тему. 
А не думали о рассылках про мероприятия например?
Конечно, при согласии пользователей, чтоб не посчитали это дело спамом.

**Comment by fortis** [comment]
надо опрос создать и по итогам всем разослать
