### ISSUE TITLE
Раздел: Подборки Drupal

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#12]
_Раздел планируется, тут обсуждается как реализовывать._

**Раздел:** Подборки.
**Статус:** Запланирован.
**Описание:**
Многие наверное видели подобные статьи на хабре, где куча ссылок на разные и интересные ресурсы, гайды, скрипты и т.д. Идея та же, сделать отдельный раздел, и публиковать их от имени сообщества. Каждый может предложить ссылку с кратким описанием. При накоплении достаточной информации, публикуется набор с указанием всех юзеров кто кидал ссылки.

**Comment by xandeadx** [comment]
если за ссылки будут начисляться какая-нибудь карма, то нормально :)

**Comment by Niklan** [comment]
Можно даже кажду такую ссылку в сущность отделить, и у каждой ссылки будет свой рейтинг. Также её добавить категорию. Следовательно, автор спокойно сможет получать заветные плюсики)

Т.е. это всё можно на автоматизм поставить полный.

**Comment by xandeadx** [comment]
с рейтингом не очень. представь сотню ссылок и у каждой рейтинг

**Comment by xandeadx** [comment]
думаю так:
1. есть форма для добавления ссылки и краткого описания
2. кто-то модерит ссылки
3. каждую неделю ссылки собираются в дайжест и авторам начисляется циферка

**Comment by Niklan** [comment]
Тогда еще вариант. У подборки свой рейтинг. Указать всех кто участвовал в составлении подборки не сложно, а также какой влкад (кол-во ссылок) сделал юзер. Затем по формуле, от рейтинга статьи % отдавать юзеру, соответсвующий % от всех ссылок.

Или просто определенное кол-во начислять как-то.
