### ISSUE TITLE
Трекер не работает нормально (

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#120]
У меня по крайней мере он не пишет. Может что с кэшем, надо разобраться.

**Comment by SemanticsPRO** [comment]
Брось его

**Comment by adubovskoy** [comment]
у меня это.... гештальт не закрыт) в общем, пусть тикет пока висит, если там альтернативный не заработает, надо будет лезть.

**Comment by drupby** [comment]
А зачем вообще нужна ссылка "Трекер", переходя по которой постоянно видишь надпись "Нет ответов в ваших материалах."?

**Comment by semyondragunov** [comment]
Трекер работает, но не полностью. Если к примеру комментят твой ответ, он не работает.

**Comment by tlito** [comment]
в Трекере висят активными оповещения о комментариях в удаленной теме, и Трекер в статусе "Есть новое" постоянно
![_078](https://cloud.githubusercontent.com/assets/11997227/18954315/192f8ffe-865b-11e6-8d4b-6f912fa53b71.png)

**Comment by tlito** [comment]
пустой трекер - иконка "есть новые".
![_079](https://cloud.githubusercontent.com/assets/11997227/19224501/1d238e5c-8e90-11e6-905f-072f6da4b1a0.png)

**Comment by adubovskoy** [comment]
ага. @tlito спасибо!
