### ISSUE TITLE
Совместная разработка dru.io

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#121]
Давайте подумаем, как нам организовать удобную совместную разработку dru.io. Кто работает в команде, делитесь опытом.

Так понимаю сейчас процесс выглядит так:
1. Создаётся локальная копия с продакшена (ftp/ssh)
2. Вместо /sites/all клонируется этот репозиторий
3. В локальную версию вносятся правки
4. Если всё готово, то оповещаются другие разработчики, что сейчас будет обновляться продакшен.
5. Правки вносятся в продакшен (накликивается функционал, заливаются файлы)
6. Файловые правки пушатся на гитхаб

Для дальнейших правок повторяем с пункта 1.

**Comment by Niklan** [comment]
Разве что кроме локальной был dev.dru.io, как понадобится сделаем опять. Или у кого есть доступы сами спокойно могут развернуть что угодно) 

Вообще, реально очень неудобно семерку девелопить совместно. Может мы можем как-то вагрант задействовать или что-то подобное? @fortis может быть опытом поделится, я так понимаю он у него уже имеется.

**Comment by fortis** [comment]
да не особо он и поможет в совместной разработке, свою среду тут каждый поднять может, докер это или ламп на серваке не важно. гит и ветки, что еще нужно) а мерджить лучше Никите чтобы видеть код, или еще одному двум это доверить

**Comment by SemanticsPRO** [comment]
Хаспада, я щитаю, что прежде всего надо в таком случае договориться об именовании веток, коммитов и т.п.
коммитить в мастер может каждый, конечно, но сие нехорошо, когда есть всякие труЪинтерпрайзные штуки типа git flow http://habrahabr.ru/post/106912/

**Comment by fortis** [comment]
ветки именовать можно по номеру issue ref000121 например, каждый коммит начинать тоже с номера "1021: hack core"

**Comment by xandeadx** [comment]
Чтобы что-то пушить в гит, надо для начала держать всю конфигурацию в файлах. Без фич похоже никак не обойтись. Или мучатся с hook_update_N().

**Comment by fortis** [comment]
новые ветки создаются от develop.

дев версия сайта может показывать какую-нибудь актуальную ветку например ref0001021 для тестов или побочную в которую сливают несколько задач для приемки, 

проверенные ветки мерджим с веткой develop и уже от нее будем новые последующие ветки создавать. а разработка в локальной среде

**Comment by fortis** [comment]
нам ведь не придется менять название сайта кодом или другие конфигурации, только вьюшки проблема, но чем дальше тем меньше их будем трогать

**Comment by xandeadx** [comment]
Вьюшки, поля, флаги, настройки отображения и много другого чего.

**Comment by SemanticsPRO** [comment]
> новые ветки создаются от develop.
> Это всё описано по моему линку на хабру

**Comment by Niklan** [comment]
Еще не забывайте что все построено на Display Suite, а там кастомные поля и как сказал @xandeadx - "Управление отображением". Всё это дело не экспортируется у DS и хранится в базе.

**Comment by adubovskoy** [comment]
http://habrahabr.ru/post/127213/ вот вполне рабочая схема. 
Пара правил при ней:
никто не правит файлы на production, все через гит. 1 маленькое изменение испортит всем жизнь. А также надо внимательно пройтись по gitignore и вписать все места где могут быть генерируемые файлы (кэш, пользовательское файло, sass-cache и т.п.)

Базу забирать ручками (да хоть через вебморду bam-backup). Соответственно - вся работа у себя локально, как объем изменений есть рабочий - push, а далее заходим под админом на production и если есть изменения в базе - накликиваем. Если это долго - включает maintenance mode пока правим.

При желании - можно добавить еще 1 прослойку в виде тестинг-сервера. Пушиться будет сразу туда, а уж оттуда ручками - в продакшн (неудобство -- два раза мы будем базу накликивать).

**Comment by adubovskoy** [comment]
> а мерджить лучше Никите чтобы видеть код, или еще одному двум это доверить

@fortis тут вопрос в том что если изменения затрагивают накликанные изменения в админке, никто кроме автора смержить это не сможет.

**Comment by xandeadx** [comment]
Кто с фичами активно работает, возможно ли такой подход, когда весь сайт упаковывается в одну большую фичи? Какие проблемы будут?

**Comment by SemanticsPRO** [comment]
Ну сайт в одну большую это не айс, имхо.
Но вот фичи, как минимум, на что-то новое, альтернативный трекер, раздел мероприятий, ещё что-нить - вполне имеет право на жизнь

**Comment by adubovskoy** [comment]
А не все получится упаковать. они потом разрастутся, будут скорее мешать. Тогда уж на https://www.drupal.org/project/configuration посмотреть, но я не пробовал его вживую.

**Comment by xandeadx** [comment]
@adubovskoy какая разница — много маленьких фич или одна большая

**Comment by SemanticsPRO** [comment]
да и вообще, проблема высосана из пальца, не такая и бурная разработка

**Comment by xandeadx** [comment]
потому и не бурная

**Comment by Niklan** [comment]
Я по опыту Drupalife Store могу сказать. Что когда кол-во фич разрастается, их становится поддерживать даже сложнее. Проблема в том, что они далеко не все экспортируют в себя. Как же нам тут 8-ки не хватает :(

**Comment by Niklan** [comment]
При этом не всегда ясно что именно не "запаковалось". Так что я больше их не юзаю, ибо если что-то более-менее крупное на них переносить, это всеравно возвращение к мышкокликанью. Хоть и сохраняют время фичи на том что они забирают, зато потом вызывают путанницу, что они тащут за собой а что в коде или руками проделано. 

В принципе мы можем их тут задействовать. Тут ничего неординарного нету, как в коммерце, поэтому утащит всё. Единственное, надо понять, тащат ли они за собой конфиги DisplaySuite, его полей, настроек екстра, расположений, отображений и т.д. Если нет - они (фичи) не нужны.

**Comment by fortis** [comment]
нужно просто начать, а по ходу будем принимать решения, работа с нодами и полями программно не проблема, вручную создаем новый тип и поля, настраиваем, а в апдейте пишем хук с экспортированным массивом. 

таким же образом можно будет и с вьюхами наработать подход, к примеру складывать в каталог экспорт вьюхи добавляя его в коммит и в имени файла используя номер апдейта, а в хуке апдейта импортить новую версию вьюхи

**Comment by Niklan** [comment]
Вот ещё что нашел, по сути то же самое что тут и предлагали: http://drupal.stackexchange.com/a/34147

**Comment by fortis** [comment]
не так часто мы будем добавлять новые типы и разделы на сайте =) уж для выката нового раздела в сообществе можно и накодить

**Comment by Niklan** [comment]
Идея @fortis мне нравится. По крайней мере тем что там нету фич. 

Да я не думаю что сейчас нам стоит так заморачиваться. Давайте базовые правила выработаем и начнем на них. У нас тут никогда навреное не бывает чтобы 2 человека сразу работали над сообществом. В основном я там ковыряюсь и Дубовской.

**Comment by Niklan** [comment]
Кто что может сказать о следующем проекте: https://www.drupal.org/project/configuration
- вот что нашел https://shanetully.com/2014/04/drupal-and-the-holy-grail-of-workflows/

**Comment by Niklan** [comment]
Потыкал configuration по сути полноценный бэкпорт из 8-ки. Только в .inc файлах хранит все.

Пример экспорта стандартных данных для друпала.
https://drive.google.com/file/d/0B1gk5NclOtkUVm5MMGlyRG9xRDQ/view?usp=sharing

**Comment by adubovskoy** [comment]
Занятно. Тестнем?)

**Comment by adubovskoy** [comment]
Все в конфигурации складывать, но сам импорт ручками производить. А потом, если будет все ок, написать на post-receive правило чтоб автоматом импортились.
Еще вопрос как их мержить при конфликтах, но не факт что нам понадобится такое.

**Comment by xandeadx** [comment]
Интересно как он решает такие проблемы - я поставил модуль, модуль добавил таблицу в бд. Это же не конфигурация.

**Comment by fortis** [comment]
This module is under active development.

**Comment by Niklan** [comment]
Отлично же, разве нет.

**Comment by adubovskoy** [comment]
1. На гитхаб залит dru.io целиком (кроме кэшей всяких и settings ессно).
2. Есть идея выложит и базу (https://docs.acquia.com/articles/scrubbing-drupal-database-environment).  и на pre-commit hook на серваке повесить создание актуальной базы.
3. Сам процесс сейчас происходит как - клоните с гитхаба, тянете ручками базу с dru.io. Работаете локально, пушите изменения на гитхаб, если есть права -- заходите в рабочую директорию на серваке и оттуда тянете git pull с гитхаба.
4. Поставили, но еще не тестировали configurations. Пока непонятно.

**Comment by Niklan** [comment]
Не забывайте к git pull еще добавить `--author "Name <email@example.com>"` ибо иначе, пуш будет от моего имени.

**Comment by SemanticsPRO** [comment]
Если локально прописано имя и мыло, то разве нужно дополнительно указывать?

**Comment by Niklan** [comment]
А, точно. Я подумал мало ли кто там прямо на серваке коммиты мутить соберется. Что-то не подумал.

**Comment by adubovskoy** [comment]
Кстати, configurations нормально не заработали, те же мероприятия переносил фичей (вручную очень уж долго выходило).

**Comment by Chi-teck** [comment]
> возможно ли такой подход, когда весь сайт упаковывается в одну большую фичи?

Я так делал на небольшом сайте. Вполне нормально работало. Одна фича не значит один файл. Каждый компонент хранится в отдельном файле (поля, представления, переменные). Так что проблем с ревертом или обновлением не возникало. Даже если они будут, то всегда можно добавить еще одну или несколько фич. Единственный недостаток это бОльшая вероятность  конфликта слияния. Если два человека одновременно редактируют один компонент, то тот кто коммитит последним будет вынужден разруливать конфликт в файле этого компонента. При больших изменениях это может быть не просто, особенно для панельных фич.

**Comment by Chi-teck** [comment]
_Configuration Management_ не очень стабилен и практически не поддерживается. У меня были проблемы с ревертом компонентов и с драш интеграцией. Но основной работает. Желательно ставить _dev_ версию и накатить некоторые патчи из трэкера. Основное приемущество перед фичами это скорость работы (update/revert). Ну и то что конфиграция экспотируется в обычные файлы, а не в модули, которые потом нужно держать включенными на сайте.

**Comment by Chi-teck** [comment]
> а в хуке апдейта импортить новую версию вьюхи

Так ведь есть [hook_views_default_views](https://api.drupal.org/api/views/views.api.php/function/hook_views_default_views/7). В фичах как раз он и используется.
P.S. _Features/Configuration_ полезны не только для деплоя конфигурации, но и для отслеживания её состояния на сайте. А так же для отката изменений которые не были закомичены.

**Comment by holyorb2** [comment]
По поводу фич:
- Делать одну большую фичу - НЕЛЬЗЯ, категорически!
  Проблема не в самой возможности, а в дальнейшей работе с фичей.
  1. Если 2 разработчика правят один код, то кто-то из них перезатрет код другого
  2. Чем больше фича, тем больше вероятность того что при экспорте часть старого кода будет меняться местами. Т.е. я правлю только имя поля, а в фиче дополнительно 30 строк кода поменяли свое место, грубо говоря ничего не изменилось, а отследить стало сложно.

Мне понравилось как мы на одном проекте работали:
- фича это отдельная функциональность
- в файлы фичи разработчики могут писать кастомный код (файл *.module)
- есть еще 1 фича в которую вливается то что нельзя классифицировать (или не имеет смысла классифицировать)

Какие есть плюсы:
- все красиво по фичам
- меньше кастомных модулей
- правка функционала в большинстве случаев только в одном модуле/фиче
- разные команды работают с разными фичами и никто ни кому не мешает.

**Comment by Chi-teck** [comment]
> Если 2 разработчика правят один код, то кто-то из них перезатрет код другого

Как же он перезатрет если этот код в гите?

**Comment by holyorb2** [comment]
Мы говорим про фичи ;)

Разработчик 1 - приступил к работе в 8 утра и правил фичу, в 16.00 закончил работу и сохранил фичу в ГИТ.

Разработчик 2 - начал работать в 12 часов, обновился с репозитория, сделал свою работу и закомитил в 15.00 свою работу.

Теперь если разработчик 1 в 16.00 закомитит туже фичу что и разраб2, то он затрет его изменения. Если сначала обновиться, то он получит изменения в фиче. но что бы их применить к состоянию в базе данных нужно сбросить фичи, то есть все что он делал весь день.

Вот и выходит если 2 разработчика работают с одной фичей, то они друг другу мешают. 

> Как же он перезатрет если этот код в гите?

Фичи - это состояние базы данных, которое записано в код, но что бы его получить на мой локальный сайт, нужно запустить сброс фич к коду (т.е. сбросить все мои ручные правки)

**Comment by Chi-teck** [comment]
> Теперь если разработчик 1 в 16.00 закомитит туже фичу что и разраб2, то он затрет его изменения. 

Так ведь коммит локальный. Как же он затрёт изменения которые еще не полученны с удалённого репозитория? При попытке сделать git pull этот разработчик получит git конфликт, который он должен разрешить так, чтобы не потерялись изменения сделанные другим разработчиком.  Это обычная ситуация, которая относится не только фичам, но и к любому другому коду.

**Comment by holyorb2** [comment]
А вы пробовали разобраться в файлах ФИЧ у которых автоматически нагенерировано тысячи строк кода. Там поля созданы, дисплей сюиты пересортированы и так далее.
В большинстве случаев проще сбросить весь код и сделать заново - разве это не есть то что мой код затерли?

Вариант номер 2 - я принял изменения и пока конфликта нету. ведь мои изменения то в базе. И тут я нажимаю сгенерировать фичу и я записываю в фичу уже свое состояние базы. И если например, разработчик 2 создал свое поле, то в моей базе этого поля нету и я сделаю фичу без данного поля - вышло я затер чужие изменения и нету конфликта.

**Comment by Chi-teck** [comment]
> А вы пробовали разобраться в файлах ФИЧ у которых автоматически нагенерировано тысячи строк кода.

Пробовал, не очень приятное занятие особенно в панельных фичах.

>  вышло я затер чужие изменения и нету конфликта.

Ну так получается что вы их осознано затерли. И эти изменения будут зафиксиованы в git истории. Нужно делать реверт фич сразу после пулла (если нет изменений в базе), либо ДО пулла обновлять фичи и делать коммит что бы получить конфликт. Компоненты реализованые через CTools exportables (Views, Panels и т.д.) можно экспортировать во временный файл, а потом после пулла и реверта импортировать обратно. Тогда не придется разруливать конфликт или пересоздавать конфигурацию в ручную.

В общем случае "тонкие" фичи конечно уменьшают сложность конфликтов и вероятность их возникновения, но не решают проблему полностью. К примеру, если два разработчика одновременно правят одну и туже вьюху, то конфликта не избежать при любой кофигурации фич.

И еще нужно учитывать масштаб проекта. Если коммитят только 1-2 человека в день, то проблема конфликтов мало актуальна.
https://github.com/Niklan/Dru.io/commits/master

**Comment by holyorb2** [comment]
> Ну так получается что вы их осознано затерли

Совместная разработка ... всякое бывает. Многие взглядом определяют что там в фиче менялось и типа тоже это проделывают, но не всегда угадывают.

Многие специально затирают, а потом пытаются отдельно повторить изменения.

> Компоненты реализованые через CTools exportables (Views, Panels и т.д.) можно экспортировать во временный файл, а потом после пулла и реверта импортировать обратно.

Ну круто, че ... это потратить фиг пару часов что бы выяснить что пересекается, вынести в файл ... но мы же говорим что в файл мы выносим только свою часть работы, ну так она то все равно перетрет чужие правки - что даст то что они в отдельном файле лежать то будут?

фичи или экспорт в отдельный файл - это состояние базы. Эти файлы не мержатся между собой в очень большом количестве случаев.

**Comment by afi13** [comment]
Разделите фичи максимально на модули, так чтобы каждый контент тип был в отдельном модуле (если есть поля которые используются сразу в нескольких типах их надо вынести в отдельную фичу для field bases), каждая вьюха в отдельном модуле и т.д. Сгруппируйте их по пакетам: Content types, Views, и т.д., чтоб легче было искать. Так будет намного меньше конфликтов и проще в них разбираться и мержить если придется. И сливать фичи только с сервака и сразу же их коммитить

**Comment by adubovskoy** [comment]
Есть мысль начать смотреть на миграцию на D8. Фактически, сейчас нам не хватает только votingapi, все остальное либо в ядре, либо в уже готовом контрибе. Пока это размышления, после rc1 я подробно хочу промониторить и, может, завести отдельную ветку. Как минимум миграции подготовить и тему. По факту конфигурации D8 нам всем сильно упростят жизнь.

**Comment by xandeadx** [comment]
@adubovskoy надеюсь выкините sass, это сильно упростит жизнь рахработчикам

**Comment by Niklan** [comment]
@xandeadx наоборот усложнит. Недавно статистику публиковали по использованию на ТОП N сайтов в сети. Она говорит за себя. Отказываться нет смысла.
![image](https://cloud.githubusercontent.com/assets/2356744/10266897/8ebc8480-6a95-11e5-8dd0-f05d79d378fa.png)

Вообще я сложностей и проблем не вижу. Скорее тут проблемы с его комплияцией. Я не знаю как на винде, но на linux он компилится на раз два без гемороя. Всё что касается написания стилей, по факту тот же CSS писать голый можно, а можно и задействовать функционал SASS. Кто не знает, напишет как может, потом кто-нибудь перепишет как надо. Так что единственное, что, по моему мнению, отталкивает - компиляция.

Везде те же действия.
- Ставится node.js на систему.
- Далее ставится 2 пакета `npm install gulp` `npm install gulp-sass`
- Переходим в папку с темой и `gulp watch`

Всё. В дальнейшем только `gulp watch` и придется писать пока ОС не сменится. На виндах это очевидно может стать геомройнее, но это собственно не проблемы sass или gulp или еще чего. Руби там явно геморойнее разворачивать чем nodejs + gulp. И работать раз в 100 медленнее будет.

Если есть PhpStorm, у него есть интеграция с гулпом. Т.е. даже watch писать не придется после настройки. Он сам будет  все делать.

**Comment by Niklan** [comment]
Данный ишью уже не актуален. Вроде более-менее наладили процесс деплоя. Дальше только 8-ка. Там свои проблемы, свои решения и обсуждения. Следовательно текущий более не актуален, и делать его уже явно никто не будет.
