### ISSUE TITLE
Статус юзера

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#124]
Как было предложено @SemanticsPRO в #113 можно добавить статусы и выводить их в ответах 

![](https://cloud.githubusercontent.com/assets/1708410/7219704/4b57bbb0-e6b5-11e4-8864-55132cac8efa.png)

Отличная мотивация для ответов.

**Comment by drupby** [comment]
Информацию по пользователю также и неплохо было бы добавить и на страницу профиля. Контактную информацию: твиттер, скайп, сайт, d.org профиль, github профиль, email и т.д. Ну и плюс текстовое поле "О себе" ("Кратко о себе"). На данный момент страница юзера слишком уныла и пуста.

**Comment by Niklan** [comment]
@drupby это уже отсюда #32 

@SemanticsPRO предложил статус отделить в отдельный ишью.
