### ISSUE TITLE
Небольшой рефакторинг и улучшения

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#125]
В общем назрела такая идея у меня и хочется её сделать.

Начнем с того что модуль dlcommunity надо рефакторнуть в druio, но это мелочи.

В общем сейчас у нас весь вывод построен на DisplaySuite, а также задействован DisplaySuite FIelds, который позвляет делать кастомные поля. И они активно используются, ибо это чертовски удобно и круто. 

Вот текущий список всех наших полей
![_006](https://cloud.githubusercontent.com/assets/2356744/7273531/0f8db87c-e90e-11e4-93e4-5a27d9cf6644.png)

Вроде бы всё ок, но внутри там DisplaySuite format code, а в нём, php. Для обычных сайтеков сойдет, но нам развивать и поддерживать и порой там нехилые куски кода, которые, в случае чего, дебажить мы не сможем. Хотя там и будет указано что ошибка в поле ds кастомном, но ни поля, ни строки, никакой конкретики.

Для того чтобы облегчить дебаг, да и сделать этот код видимым в гитхабе, я предлагаю следующий вариант:

Я создам файлик в нашем модуле druio_ds_fields.inc в котором будут функции только для кастомных полей DisplaySuite. И именвать их следующим образом. Если поле называется question_answers, то делаю функцию druio_ds_field_question_answers() которая и будет возвращать нужный нам результат. А в поле только дергать соответствующую функцию.

Может идеи есть поинтереснее? Но думаю это отлично. Мы сразу убьем нескольких зайцев:
1.  По сути избавимся от php кода в админке (останется вызов функции).
2.  Код будет виден на GitHub, легче будет другим его поправить, если они будут знать оптимальное решение, или найти уязвимость. Также можно будет его править через IDE, а то в админке делать - ад.

Собственно, если нет возражений или других вариантов это все сделать лучше, я это сделаю.

**Comment by Niklan** [comment]
Кстати, если у кого есть опыт как легко и безболезнено рефакторнуть модуль, готов выслушать. По сути функций вызываемых в иных местах кроме самого же модуля нет. Поэтому можно, как я считаю, копи-паст, переименовать всё, включать новый, выключить старый. Удалить dlcommunity.

**Comment by adubovskoy** [comment]
Может просто забьем на эту админку и опишем все в  field_create_field() /  field_create_instance() ? Будет понятней в коде.

**Comment by Niklan** [comment]
@adubovskoy не слишком ли заморочено получится?

**Comment by adubovskoy** [comment]
да будет то же поле, просто в нормальном коде.)

**Comment by Niklan** [comment]
Погоди, но ведь оно будет доступно в редактировании ноды? Или им можно создать поля для DS?

**Comment by adubovskoy** [comment]
https://ohthehugemanatee.org/blog/2014/04/02/how-to-create-a-custom-display-suite-field/

**Comment by Niklan** [comment]
То что нужно!

Походу придется дев поднимать для такого уже.

**Comment by Niklan** [comment]
[Сделал](https://github.com/Niklan/Dru.io/tree/Issue-%23125/sites/all/modules/custom/druio_ds_fields) на в ветке Issue-#125.  Вот думаю там же и рефакторнуть dlcommunity в druio или как.

**Comment by Niklan** [comment]
Осталось только включить ;) Сделаю в даунтайм или после, ишью готов, рефакторинг основного модуля будет отдельно.
