### ISSUE TITLE
Адаптивный дизайн

### ISSUE THREAD

**Issue by UksusoFF** [Niklan/Dru.io#126]
Вроде бы в первой версии новой темы было все нормально.
Я просто оставлю это здесь:
![screenshot_2015-04-23-00-02-52](https://cloud.githubusercontent.com/assets/1931442/7302373/05acd3aa-e9fa-11e4-8e9f-240837959116.png)

**Comment by Niklan** [comment]
Тут похоже кеш или еще чего. Такого в принципе не может быть оно должно исчезать. Больше похоже что версия без кеша подгружается или меда квери не отрабатывают.

**Comment by UksusoFF** [comment]
Этот скрин был из Dolphin Browser, кэш чистил. В Firefox вроде все получше:
![screenshot_2015-04-23-22-09-50](https://cloud.githubusercontent.com/assets/1931442/7304593/880860c6-ea09-11e4-9430-48707629e9b6.png)

**Comment by Niklan** [comment]
Тогда скорее вопросы к браузеру а не к нам) Там ничего "навороченного" нет, обычные меди квери. Попробуй обновить браузер, тут мы никак не поможем.

**Comment by UksusoFF** [comment]
Ну не знаю, мой сайт на Zen. Нормально срабатывают все медиа квери... Версия браузера последняя, там вроде как обычный WebKit.

**Comment by adubovskoy** [comment]
reopen issue, надо тестить. у меня на андроиде/хроме андроида аналогично.

**Comment by UksusoFF** [comment]
Я бы еще добавил что поля с бекграундом можно вообще убрать на мобильных. Места много занимают полезного.

**Comment by Niklan** [comment]
Надо бы переделать вообще адаптивный дизайн. Делался чтобы был) Хотя у меня на лисе и хрмое на андроиде всё ок.

**Comment by greeneyesmi** [comment]
У меня на андроиде нормально отображалось. Хотя менюшки для медиа-скрин можно спрятать по кнопки. но лучше тогда закосить их под визуализацию мобильного приложения, чтобы слева просто выезжала панелька с абсолютным позиционированием по кнопке. О! надо у себя такое замутить.

**Comment by adubovskoy** [comment]
Мы пока отключили адаптивную для моб. Будем переделывать.

**Comment by greeneyesmi** [comment]
вот здесь профили прикольно оформлены 
http://www.materialup.com/

**Comment by i-amdroid** [comment]
> Мы пока отключили адаптивную для моб. Будем переделывать.

отключили адаптив, отключите и 

```
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
```

совершенно невозможно читать с телефона
