### ISSUE TITLE
По умолчанию у всех 7 или я в профиле укажу преференции

### ISSUE THREAD

**Issue by tlito** [Niklan/Dru.io#127]
Предлагаю упростить форму отправки вопроса и сразу по умолчанию делать версию друпала 7, я сомневаюсь что много вопросов относятся к другим релизам.
или что не делается просто так а уже из области настроек виджета сайта для пользователя - сделать в профиле преференции пользователя и добавить поле:
В моих вопросах автоматически выбирать версию Друпал:
и всем поставить 7ку. ) или даже ставить тем кто больше 5 вопросов задал с 7кой. это я у меня все такие.

**Comment by Niklan** [comment]
В 2 клика ставится 7-ая версия. Не вижу смысла в принудительном выборе. Это может сбить других с толку. Да и вопросы вы задаете на каждую минуту чтобы это начало быть уязвимым местом, да и вообще 1-2 секунды, которые требуются на это не сыграют роли. А когда человек захочет задавать вопрос для иной версии. Ему надо сначала убрать, а потом добавить нужню - что еще хуже. Новички могут впасть в ступор и выбрать случайно 2 версии, или не понять что 7ая выбрана, и выбрать 2ой раз (а это удаляет первую метку).

Подождем других мнений, но не думаю что они будут сильно отличаться. 8-ка на носу, и это станет ненужно уже совсем скоро.

**Comment by semyondragunov** [comment]
Абсолютно не нужно этого делать.

**Comment by SemanticsPRO** [comment]
Не имеет смысла
