### ISSUE TITLE
Сокращения для ссылок

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#128]
Предлагаю написать фильтры для сокращений.

@username - линк на профиль пользователя.
#12345 - id ноды. Но тут есть проблема, что если нужно линкануть не на ноду, а комментарий, или же вообще иную сущность? Тут можно, как мне кажется, обойтись таким решением. По дефолту #000 - это для ноды, для других сущностей введем сокращения, например для коммментов можно сделать #c-444 или что-то подобное?

Может ещё чего такого сделать нам? По крайней мере с юзерами точно удобно будет.

**Comment by SemanticsPRO** [comment]
есть это уже готовое, ща найду

**Comment by SemanticsPRO** [comment]
https://www.drupal.org/project/mentions

**Comment by SemanticsPRO** [comment]
По поводу ноды.
Не такие и бурные обсуждения, пусть будет по номеру ответа, а не коммента
