### ISSUE TITLE
Раздел: Хостинги и VPS

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#13]
_Раздел планируется, тут обсуждается как реализовывать._

**Раздел:** Хостинги и VPS.
**Статус:** Заморожен из-за ненужности
**Описание:**
Каждый может написать отзыв и поставить рейтинг, всё просто. Разумеется, опираясь на производительность друпала

**Comment by SemanticsPRO** [comment]
Может добавить туда же "Производительность и масштабирование", отчасти пересекается

**Comment by Niklan** [comment]
А что будет в "Производительность и масштабирование"?

Имеется ввиду там будет список хостинговых компаний, юзеры будут рейтинги пилить.

**Comment by SemanticsPRO** [comment]
А, ок, я чота прогнал.
Тогда предлагаю сделать типа мана по бенчмарку хостингов и добыче инфы оттуда.
Чтобы отзывы были полны

**Comment by Niklan** [comment]
Ну это вполне можно в раздел гайды будет запилить статью. Как мерить производительость, и дать ссылку на неё при добавлении отзыва, чтобы по гайду прогнали лишний раз.

**Comment by xandeadx** [comment]
хостинг это ж дико субъективно и зависит от опыта, пока непонятна перспектива

**Comment by Niklan** [comment]
Как минимум удобный лист где поддерживается друпал и отзывы местных. На друпал.ру регулярно же пролетают вопросы, а где мне сайт то держать?

**Comment by adubovskoy** [comment]
Если стоит вопрос хостинга под это дело - могу площадку предоставить на наших машинках)

**Comment by SemanticsPRO** [comment]
Ты скорее SOLR предоставишь

**Comment by adubovskoy** [comment]
solr можно.
p.s. а тут разве не elasticsearch?)

**Comment by SemanticsPRO** [comment]
Да время покажет.
Я за SOLR, Никита за эластик.

**Comment by Niklan** [comment]
Никита уже за solr, но пока руки не дошли погонять его, как только разберусь на виртуалке, подключу к сайту. Но подключу если получиться настроить русскую морфологию.

Эластик хорош, но модули дубовые, а свой писать долго будет. Они фильтры не поддерживаются которые нужны для морфологии в нём.

**Comment by SemanticsPRO** [comment]
Ну так давай у Саши возьмём, всего-то за кнопку в подвале 110х50 пикселей.

**Comment by adubovskoy** [comment]
зачем кнопкой дизайн портить?)

**Comment by SemanticsPRO** [comment]
Ну нахаляву давай значит

**Comment by Niklan** [comment]
Мимокоммент, переведено на Solr от ra-don.ru

**Comment by holyorb2** [comment]
Не вижу смысла.
Такие разделы мало эффективны:
- оценки субъективны
- оценки не верны! У хостинга много серверов, у кого сервер не загружен у того летает, у кого напакован - тот кипит от ярости. Или так - клиент приходит на хостинг и попадает на новый сервер, который еще пустой, через 3 месяца сервер полный и уже тормозит.
- хостеры когда видят смысл в рейтинге, делают ботов и накручивают рейтинги (боты = работники суппорта)

**Comment by adubovskoy** [comment]
https://github.com/Niklan/Dru.io/issues/6

**Comment by fortis** [comment]
суть не в рейтинге, спецам итак все понятно с хостингом уже перетыкали, да и рекомендации, либо просто отзыв от действующих участников сообщества не накрутишь.

сложный раздел не нужен, нужна страница со списком, пусть ограниченным, чтобы новичек пришел и выбрал уже сам, попробовал потыкался.

это можно сделать ридонли разделом, как выбор редакции. список наиболее популярных с достоинствами, недостатки не нужны, количественная оценка тоже не нужна

**Comment by drupby** [comment]
Кстати, а если на данный момент какой либо хостер решит разместить свое предложение на dru.io, где он сможет это сделать? В публикациях? Так вроде они не для того. На друру то они размещаются и до сих пор.

**Comment by Niklan** [comment]
Раздел явно нужен, но не в приоритете
