### ISSUE TITLE
Галочка для "Вопрос решен"

### ISSUE THREAD

**Issue by semyondragunov** [Niklan/Dru.io#132]
Может сделать её более видной или как-то по другому выделить? А то в _не отмеченном_ состоянии можно и проморгать. Я думаю именно по этому многие не ставят **Вопрос решен.**

**Comment by semyondragunov** [comment]
Куда вообще делать отметка **Вопрос решен**?

**Comment by Niklan** [comment]
Поменял метку решенного вопроса в тизерах. В ответах не вижу смысла менять.

**Comment by semyondragunov** [comment]
Я не про это. Где вообще нажать на кнопку что-бы пометить, что **Вопрос решен**. Куда кнопка пропала?

**Comment by Niklan** [comment]
Действительно же.

**Comment by drupby** [comment]
"Поменял метку решенного вопроса в тизерах."
Зачем?
