### ISSUE TITLE
Последние комментарии или популярные вопросы

### ISSUE THREAD

**Issue by ialexandri** [Niklan/Dru.io#133]
Добрый вечер уважаемые!
Писал вопрос на dru.io. Вот он http://dru.io/question/52

Но после его публикации небыло времени заниматся проектом. Были причины. Сейчас вернулся. Попробовал то что порекомендовали. Не работает. По крейней мери я с отсутствием опыа работы с хуками и в меру общего знакомства с PHP не смог разобратся.

Дописал комментарий к вопросу, но вопрос то так и остался лежать на последней странице где его никто не увидит! Новый писать глупо! 

Логично вывести гдето в блоке последние комментарии. А также наиболее популярные вопросы и нерешенные вопросы..

Что скажете господа!?

**Comment by SemanticsPRO** [comment]
Скажу, что закрыто, ждите альтернативного трекера(тм)
