### ISSUE TITLE
Фильтр "Вопросы без ответа"

### ISSUE THREAD

**Issue by ttenz** [Niklan/Dru.io#134]
Неплохо бы добавить фильтр "Вопросы без ответа", иногда хочется поотвечать, а найти без ответа вопросов нет возвожности.

**Comment by SemanticsPRO** [comment]
Дубль не помню кого, но с трекером связано

**Comment by adubovskoy** [comment]
Вот с этим https://github.com/Niklan/Dru.io/issues/28.

**Comment by adubovskoy** [comment]
http://dru.io/question вообще просто в общем списке, все что без галочки -- скорее всего без ответа, а там где значок кол-ва ответов "0", те уж наверняка.
