### ISSUE TITLE
Вывод автора и даты вопросов/ответов  

### ISSUE THREAD

**Issue by drupby** [Niklan/Dru.io#135]
Как то необычно и непривычно выглядит отсутствие даты и авторов вопросов/ответов. Хотя у комментов выводится.

**Comment by Niklan** [comment]
Вернул. Вчера тоже втыкал, думал странно что даты нет, не обратил что и автора тоже. ПОдумал что я уже устал и просто сам туплю, оказалось реально нету)

**Comment by drupby** [comment]
Ну хорошо, автор и дата выводятся, но так ведь у ответов rate отсутствует теперь.

**Comment by Niklan** [comment]
@drupby уже поправил. Это из-за #138 как-то прокатилось что задело строчку кода, хотя я вообще не вьехал каким образом. Но уже починено.

Кэш видимо держит. Уже проверил.
