### ISSUE TITLE
"Обратите внимание! Вы являетесь автором вопроса."???

### ISSUE THREAD

**Issue by drupby** [Niklan/Dru.io#139]
На всех страницах вопросов перед формой ответа 
"Обратите внимание! Вы являетесь автором вопроса. Данная форма может быть использована только если вы нашли решение самостоятельно и желаете поделиться им с остальными. Для этого напишите решение своего вопроса, а затем пометьте его как решение. При использовании "ответа" для дополнения своего вопроса воспользуйтесь комментарием или функцией редактирования вопроса, в противном случае, ваш ответ будет удалён."

**Comment by Niklan** [comment]
Ой я дурень, забыл условие написать. Ща пофикшу. Делал ночью)

**Comment by Niklan** [comment]
Спасибо, исправил.
