### ISSUE TITLE
Навигация по сообществу.

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#14]
Я тут на каждую возможную будущую возможность или раздел сообщества создал ишью. Список не маленький намечается 13 разделов, с текущими тремя и вовсе 16.

Очень остро встает вопрос, как это всё грамотно складывать в меню, чтобы не заблудиться никому, было удобно и не пугало никого сразу. Скорее всего придется разделить всё это на несколько категорий что-то типа: Материалы, Документация и обучение, Коммерция и т.д.

**Comment by drupby** [comment]
вот пример навигации по сообществу http://modx.ru/

**Comment by Niklan** [comment]
В принципе да, неплохо. А куда отнести, допустим "Мерпориятия"? А в целом понятная структура, ясно что куда отнести. Можно сделать по принципу жмем на "Новости и статьи" открывается, так сказать, направляющая страница. Где будут последние 10 новостей, статей, и ссылки на страницы со всем содержимым, ну а также в выпадающее запихнуть их. Никто не должен будет заблудиться.

**Comment by Tristamoff** [comment]
В данный момент навигация в сообществе никакая.Понятна она только автору. Или может ещё контента мало?

**Comment by Niklan** [comment]
#44 Оставим на редизайн. В принципе вопрос по-сути решён. У ModX хорошая навигация будем операция на неё.
