### ISSUE TITLE
Публикация по рейтингу

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#140]
Я сейчас в качестве теста поменял вывод главной, выводятся вопросы/публикации с рейтингом > -5. Есть предложение развить идею и депубликовать материалы с рейтингом >-10 . Будет такая общественная модерация, заодно всякий спам автоматом будет чистится (хотя его пока и нет особо).

Собственно, варианты что можно делать:
1. Не выводим посты с низким рейтингом в списках, выкидываем из индекса поиска, закрываем для поисковиков (это еще надо подумать как удобнее).
2. Просто депубликуем.

**Comment by Niklan** [comment]
1. metatags можно мешать на страницу "запрет для индексации", а он мета тег добавит запрещающий.
