### ISSUE TITLE
Автообновление блоков "Последние публикации" и "Последние вопросы" на главной

### ISSUE THREAD

**Issue by deadddie** [Niklan/Dru.io#144]
Интервал обновления, я думаю минут 3-5 должен быть.
https://www.drupal.org/project/views_autorefresh (если конечно эти блоки сделаны вьюсами)

**Comment by Niklan** [comment]
Как мне кажется, у нас не достаточно часто появляется новый контент, так что надобность нулевая.

**Comment by deadddie** [comment]
Дело же не в "надобности". Просто удобная фишечка.. Делов-то на копейку :)
Хм... ну может тогда продублировать ссылки из верхнего меню на "все вопросы", "все публикации" под блоками
