### ISSUE TITLE
"Решено" для своего ответа

### ISSUE THREAD

**Issue by semyondragunov** [Niklan/Dru.io#145]
Нету иконки для отметки вопроса решенным, если ты сам ответил на свой вопрос.

**Comment by adubovskoy** [comment]
Т.к. форма ответа была изменена, теперь можно разрешить помечать свой ответ. Включил опцию. Если будет кто злоупотреблять - посмотрим, будут ли его минусовать.

**Comment by semyondragunov** [comment]
@adubovskoy Да я даже знаю кто будет злоупотреблять))))

**Comment by adubovskoy** [comment]
да и пусть, он правда куча контента генерит. Как поиск нормально соберем, будет полезно. Коэффициент повышающий в рейтинге от этого небольшой, специально не нагонишь.

**Comment by fortis** [comment]
#49 теперь не актуально?

**Comment by adubovskoy** [comment]
Да, закрыл. Вакансий пока нет, потом поднимем.)
