### ISSUE TITLE
Беда-печаль..Все пропало...Сломалась страница event-ов. 

### ISSUE THREAD

**Issue by drupby** [Niklan/Dru.io#148]
На страницах мероприятий флаг выводится дважды и без стилей и формы комментов нет под "Добавить комментарий". Ну и на странице вывода мероприятий http://dru.io/events Saunacamp Helsinki 2015 выводится дважды.

**Comment by adubovskoy** [comment]
фичу кто-то выключал или ревертил. тип материала удален.

**Comment by adubovskoy** [comment]
выключил пока меню и модуль. все эксперименты на локальных копиях.

**Comment by drupby** [comment]
"фичу кто-то выключал или ревертил. тип материала удален." 
ну так фича не коммит - кто что менял неизвестно

**Comment by Niklan** [comment]
Эт. не я. Я давно на продакшн не лазил. И еще раз предлагаю всем или хоть кому-то со стороны потестить как работает дампер базы. Чтобы каждый у себя на локалке смог потыкаться и посмотреть что угодно а не на лайве.

**Comment by drupby** [comment]
"И еще раз предлагаю всем или хоть кому-то со стороны потестить как работает дампер базы."
давай дамп

**Comment by Niklan** [comment]
@drupby https://drive.google.com/file/d/0B1gk5NclOtkUUHp2Qm1nWlVIOGc/view?usp=sharing

**Comment by drupby** [comment]
@Niklan ты походу битый архив дампа выложил на гугл драйв, я в начале ловил ошибки при импорте бд, а потом попробывал его разархивировать и не распаковывается не через файловый менеджер, не через консоль, файл несколько раз скачивал заново - не помогает

**Comment by adubovskoy** [comment]
Вылечилось пересозданием типа материала.
