### ISSUE TITLE
Текст комментария к ответу не проходит через фильтры

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#15]
сабж. пример - http://community.drupalife.com/comment/reply/128/162

**Comment by Niklan** [comment]
Да, они отключены в комментах на ответы. Имеет смысл включить?

**Comment by xandeadx** [comment]
ну да, каша ведь получается

**Comment by Niklan** [comment]
Исправлено. Теперь форматы ввода действуют и в комментариях для Ответов, и Вопросов.
