### ISSUE TITLE
Сломались комменты

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#159]
Сабж, кто чего наломал сразу на продакшене?

**Comment by Niklan** [comment]
Слетели везде:
- Вопросы
- Ответы
- Публикации

Должно быть
![](http://i.imgur.com/9Wx3s3s.png)

Сейчас:
![](http://i.imgur.com/JI7NxwI.png)

**Comment by fortis** [comment]
@Niklan вернул посмотри визуально на сайте ок?

**Comment by fortis** [comment]
стиль аватара там разный в отображениях

**Comment by Niklan** [comment]
да там фиксы надо накатывать. Врапперам классы добавить обратно

**Comment by fortis** [comment]
это отдельный таск тут закрываем?
