### ISSUE TITLE
Логины всех пользователей

### ISSUE THREAD

**Issue by kala4ek** [Niklan/Dru.io#162]
По этому адресу (с посрщью перебора) можно получить логины всех пользователей: http://dru.io/user/autocomplete/kala4ek
Я думаю стоить заальтерить аксес на этот урл. Также по возможности закрыть прочие дефолтные страницы, например /node.

**Comment by SemanticsPRO** [comment]
пфф.
И профили юзеров закрыть.
И сайт в интернет не выкладывать

**Comment by fortis** [comment]
access callback => FALSE =)
зачем подбирать? можно спарсить интернет
да и проблемы по сути нет: https://www.drupal.org/search/user/a

**Comment by kala4ek** [comment]
Тогда вопросов нет :)
