### ISSUE TITLE
Непонятки (неполадки) с поиском

### ISSUE THREAD

**Issue by vistar** [Niklan/Dru.io#163]
На запрос http://dru.io/search?s=workbench ничего не выдаётся, хотя перед этим читал http://dru.io/question/1709 - не индексировалось ещё?

Потом: http://dru.io/search?s=%D1%85%D0%BE%D1%81%D1%82%D0%B8%D0%BD%D0%B3 - нет подсветки запроса в результатах, а главное, что результаты все в кучу лежат - некрасиво, неудобно

А ведь обычно в поиск посылаются дубли вопросов…

**Comment by adubovskoy** [comment]
1. надо комменты добавить в индекс.
2. при нахождении в комменте/ответе к вопросу, надо показывать результаты в формате заголовка ответа + подсвеченной области текста

**Comment by xandeadx** [comment]
Надо что-то с поиском делать, найти что-нибудь нереально

**Comment by xandeadx** [comment]
Для начало нужно:
- убрать из вывода всё кроме вопросов
- в индекс к вопросам добавить ответы и комментарии

**Comment by Niklan** [comment]
> убрать из вывода всё кроме вопросов
> Ни-ни, для этого жи есть фасеты. Если нужно что-то глубокое конкретно по вопросам. Надо отдельно для него запилить тогда. А общий пусть остается общим.
> Общим /search
> А по вопросам пожалуйста /search/questions или /search/answers

**Comment by fortis** [comment]
по мне так как раз понятнее если будут отдельные вкладки, а по умолчанию открыта первая по вопросам или чему-то еще, чем каша из всего когда мне нужно посмотреть только вопросы

**Comment by fortis** [comment]
фильтрация которая есть не понятна и не видна, я только сейчас узнал что она есть))))
это не поиск, а фильтрация, такое удобно с модулями, чтобы отбирать из кучи галочками, сокращая результаты, но с контентом это только мешает искать необходимое
