### ISSUE TITLE
Форму ответа спрятать за кнопкой

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#165]

**Comment by adubovskoy** [comment]
У кого есть возможность в ближайшие пару дней это запилить? По сути кнопку с slideDown всего-то.

**Comment by semyondragunov** [comment]
А что делать если сам нашёл ответ?

**Comment by adubovskoy** [comment]
Сам отвечаешь. Надо чтоб не путали ответ с комментом.

**Comment by adubovskoy** [comment]
Не нравятся кнопки http://www.awesomescreenshot.com/image/261937/b29861c0deae88a97fae91c414c88eeb . их надо как раньше, пометил себе, надо допилить.
