### ISSUE TITLE
Убрать shortlink

### ISSUE THREAD

**Issue by ghost** [Niklan/Dru.io#166]
Я советую убрать тег shortlink, т.к. он может привести к фильтру от поисковой системы Яндекс. На практике было все проверено, поэтому предлагаю просто убрать. Если будут вопросы, то более подробно смогу пояснить, пишите.

**Comment by fortis** [comment]
шортлинк по идее для соц сетей, твиттера и прочих, но действительно много плохих отзывов о нем, возьму на себя, изучу еще.

в коде имеем
<code>
<.link rel="shortlink" href="/node/1865" />
<.link rel="canonical" href="/question/1865" />
</code>
пока что и обычный урл достаточно короткий

**Comment by ghost** [comment]
опять-таки статистика не от "былды" основана на своем опыте и опыте других разрабов, которые делают сайты на drupal

**Comment by fortis** [comment]
убрано, пока имеем достаточно короткие URL для ретвитов, репостов и т.п.

**Comment by fortis** [comment]
#220
