### ISSUE TITLE
Убрать element-invisible

### ISSUE THREAD

**Issue by ghost** [Niklan/Dru.io#167]
В исходном коде встречается такая конструкция http://joxi.ru/12M7jQ7sdZLvrJ
</code></pre> она не семантична, лучше всего убрать, чтобы не путать поисковые системы.

**Comment by fortis** [comment]
эти элементы используются друпалом для скрин-ридеров, озвучивающих содержимое страницы слабовидящим людям. получается что это вполне семантическая конструкция, используют ее довольно часто

**Comment by fortis** [comment]
что есть у поисковых систем касательно скрин-ридеров? кажется аттрибуты у хтмл5 есть под это

**Comment by ghost** [comment]
Выпиливаю у всех проектов, тут нужно подумать конечно (на слабовидящих никогда не ориентировался). А выпиливал потому, что поисковая система скачивает разметку, часть выбрасывает, анализирует заголовки, вот тут и не понятно, почему это в h2 всякие "вы здесь", "страницы". Это противоречит логике формирования заголовков и у ПС от этого нарушается логика оценки страницы при ранжировании. Это особо думаю не критично в рамках данного проекта, т.к. еще до кучи факторов присутствует и по ним по сути все хорошо.

**Comment by fortis** [comment]
думаю решать правильно надо по-другому, поискать в schema.org как обозначать такие элементы без вреда индексатору. кажется через role="..."
применяемые для сео подходы не должны отсеивать посетителей))

**Comment by ghost** [comment]
как вариант да, лучше обойтись микроразметкой.

**Comment by fortis** [comment]
так как у element-hidden есть свое предназначение - для скринридеров - значит семантично. оставим. да и нет особой нужды в сео магии
