### ISSUE TITLE
Добавить поиск по заголовку при добавлении вопроса.

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#17]
Добавить AJAX поиск при вводе краткого вопроса, который будет выдавать 3-5 результатов с похожими вопросами, дабы сократить дальнейшие дубли вопросов.

**Comment by alexsco74** [comment]
Ok ob!

**Comment by fortis** [comment]
#autocomplete с колбеком к солру примерно таким:

<pre><code>
  $title = "Заголовок ноды";
  $server = search_api_server_load('apache_solr');
  $index = search_api_index_load('index');
  $options = array('parse mode' => 'direct');
  $query = new SearchApiQuery($index, $options);
  $query->keys($title);
  $query->fields(array('title'));
  $service = new SearchApiSolrService($server);
  $response = $service->search($query);
  if (!empty($response['results'])) {
  // ....
  }
</code></pre>

но для нормального автокомплита лучше сделать мультикор солра (там просто один конфиг поправить и по разным папкам разложить) и хранить нормальный индекс отдельно, а для автокамплита делать н-граммы с минимум 1 символ и индексировать только заголовки. либо альтернуть солрапи и ввести свой тип поля для которого прописать в xml индексацию по нграммам и тогда будет одно ядро

**Comment by Niklan** [comment]
Не, я хочу сделать иное.
Вводят заголовок, допустим "Обновление "
А он внизу допустим "Возможно на ваш вопрос уже отвечали" и до 5 ссылок на другие подходящие по заголовку вопросы.

**Comment by fortis** [comment]
suggestions =) ну это тот же самый автокамплит только больше кастомизированный.
либо вот такой автокамплит с анонсом и большей инфой чтобы понять тот это вопрос или нет http://www.iog3.com/322/so_tag-tagging-plugin-based-on-stackoverflows-tag-search/

**Comment by Niklan** [comment]
Типа вопрос и summary его?

**Comment by duozersk** [comment]
Я такое делал, через MLT фичу солра - создавал отдельный search listener у солра. Делал для сайта Computer Build, но его уже перепродали и закрыли. Исходники есть, можно поднять.
Отдельных ядер солра тут точно не надо - MLT сам всё там делает. И искать можно не только по заголовку, а вообще по всему введенному пользователем тексту - то есть солр выдаст айтемы, которые похожи на весь текст нового вопроса.
