### ISSUE TITLE
Оповещения на почту, в интерфейсе

### ISSUE THREAD

**Issue by vistar** [Niklan/Dru.io#170]
Об ответах на вопросы, комментарии.

Возможно и было, но не нашёл issue.

**Comment by adubovskoy** [comment]
В интерфейсе есть - трекер вверху, он не работал долгое время. Есть еще https://github.com/Niklan/Dru.io/issues/98 задачка.

**Comment by vistar** [comment]
А в трекере не заметил бейдж с количеством непрочитанного ;)

Но на почту оно сподручнее как-то.
А вот если pushbullet ещё бы. Но это я раскатал губу.
А так: https://github.com/settings/notifications

**Comment by adubovskoy** [comment]
вот есть мысль прикрутить pushbullet) Это ж Никита недавно написал - https://www.drupal.org/project/pushbullet . Прикрутить будет на раз-два.

**Comment by vistar** [comment]
Да, я же их (Никиту и модуль) имел ввиду ;) Но там получится переписать его, чтобы индивидуальные настройки оповещения делать?

**Comment by Niklan** [comment]
Его не потребуется переписывать для индивидуальных настроек. Всё там есть ;)
Если хочешь оповещения через pushbullet, берешь API ключик свой, а мы добавим поле в профиль куда каждый кто хочет вставит свой ключ. На него будут слаться пуш-уведомления. Всё уже продумано) Или же указывать не API ключ, а почту на которую зареган пушбулет аккаунт - тоже будет уходить. Я полностью их API реализовал.

**Comment by roman-yakimkin** [comment]
Скажите, а сейчас работают уведомления об ответах на вопросы через pushbullet ?
Я установил себе pushbullet, но на этом проекте не нахожу, куда вписать свой API ключ.

**Comment by Niklan** [comment]
Нет, пока pushbullet тут нет.
Да и ключ вводить не нужно, можно по email слать пуши на него ;)
