### ISSUE TITLE
Обновление комментария опускает его вниз.

### ISSUE THREAD

**Issue by tlito** [Niklan/Dru.io#171]
например в вопросе http://dru.io/question/1847
я обновил комментарий свой первый (исправил строчку кода) - и мой комментарий упал в самый низ. по-моему это не правильно, потерялась логика обсуждения

**Comment by adubovskoy** [comment]
Не смог продублировать в другом топике. А какой именно коммент? Пока непонятно

**Comment by tlito** [comment]
этот: "Аватар пользователя tlito tlito – 27.05.2015 - 15:19
спасибо, с вашим ответом я решил задачу таким кодом модуля commerce_line_item_enable_message...."
я его написал еще вчера, а седня изменил и время поменялось, и он опустился

**Comment by tlito** [comment]
вы не смогли повторить возможно потому что в друпал сложная функция обновления времени. если больше 50% текста изменено он меняет дату. хотя неточно но я такое замечал

**Comment by adubovskoy** [comment]
Это не так)
Закрываю, если будет повторное обращение еще, поднимем топик.

**Comment by tlito** [comment]
а закрыли значит проблема не обнаружена?
я могу помочь: вот адрес моего комментария:
http://dru.io/comment/reply/1849/1907
вот адрес следующего комментария по id: 
http://dru.io/comment/reply/1849/1908
но тот у которого id меньше отображается последним на странице вопроса:
http://dru.io/question/1847
значит проблема есть.

**Comment by fortis** [comment]
повторил, проблема не воспроизводится. закрываю
