### ISSUE TITLE
Поиск по названию расширения

### ISSUE THREAD

**Issue by semyondragunov** [Niklan/Dru.io#172]
Сделать либо на странице /project отдельно или сцепить с основным поиском.
Иногда ищешь модуль а помнишь только часть названия.

**Comment by adubovskoy** [comment]
Fixed

**Comment by Niklan** [comment]
Считаю что нужно в общий поиск добавить а оттуда убрать. Очень нелогично делить когда есть общий по всему сайту поиск но не ищущий модули. Там есть фасеты, всё что надо народ сам отфильтрует.

**Comment by fortis** [comment]
только не мешать в кучу результаты, статьи, например, выводить в области контента тизерами, а модули рекомендовать в блоке небольшим списком названий

**Comment by Niklan** [comment]
А почему бы и нет, они такие же информационные материалы как и публикации. Говорю же, для всего остального есть фасеты)

**Comment by adubovskoy** [comment]
Ок, уберем как будет готов общий поиск.
