### ISSUE TITLE
Было бы удобно и быстро видеть tracker с сортировкой по обновлениям

### ISSUE THREAD

**Issue by alexsco74** [Niklan/Dru.io#18]
Материалов и обсуждений в которых ты "лапу приложил" ?!

**Comment by Niklan** [comment]
RxB вызывался это сделать, закрепляю за ним.

**Comment by SemanticsPRO** [comment]
Да, я сделаю, правда придётся, видимо, дополнительный флаг вносить, но чего-нить придумаю

**Comment by xandeadx** [comment]
чем стандартный друпаловский не устраивает?

**Comment by SemanticsPRO** [comment]
Тем что он корректно вопросы и ответы не выведет.
Ответы на вопросы есть отдельная нода, надо либо через связь вывернутся, либо вносить дополнительную сущность.
Буду проверять

**Comment by alexsco74** [comment]
Оперативно, молодцы! Где вы время только "колдуете", завидую "белой" завистью.

**Comment by semyondragunov** [comment]
Может не в тот ишьюз, Но...
Будет возмоджно как тут на гите отписываться от обновлений? Ну и автоматом при ответе или создании вопроса подписывался на этот материал?
А что с комментами?

**Comment by Niklan** [comment]
#19 переезжаем.
