### ISSUE TITLE
Добавить трекер с оповещением.

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#19]
Необходимо добавить поддержку о новых комментариях и ответах на те материалы, которые подписался пользователь.

Оповещения сделать на почту, а также телефон, браузер, пк. Последние три по желанию.

**Comment by semyondragunov** [comment]
На сайте бы тоже как-нибудь обозначить.

**Comment by Niklan** [comment]
Ждем трекера от RxB

**Comment by Niklan** [comment]
Модуль для оповещений на телефоны\компы и прочую технику уже готов: https://github.com/Niklan/Pushbullet

**Comment by Niklan** [comment]
Для оповещений на устройства подготовлен [Pushbullet API](https://www.drupal.org/project/pushbullet).

**Comment by UksusoFF** [comment]
Сдается мне что почта все-таки в приоритете должна, при ее наличии можно все остальное доделать самостоятельно :)

**Comment by xandeadx** [comment]
А почта планируется?

**Comment by Niklan** [comment]
Первостепенно. На устройства будет по желанию, как альтернатива или добавочно. Сначала нужен трекер. Нам бы ответ @SemanticsPRO хоть какой)

**Comment by Niklan** [comment]
На деве @adubovskoy сделал трекер. Так что данный ишью будем считать закрытым. Если что, уже будем перерабатывать то что сделано. Скорее всего вылетит на продакшен вместе с темой, ибо подвязали уже.

**Comment by UksusoFF** [comment]
Скорее бы уже, люди вон на другие ресурсы уходят :) 
https://toster.ru/q/194605

**Comment by Niklan** [comment]
@UkusoFF да просто надеятся быстрее ответ получить. У меня сейчас завал, а тема готова на половину, как будет готово так сразу)

**Comment by UksusoFF** [comment]
Может быть хотя бы это подключить? :)
 https://www.drupal.org/project/comment_notify

**Comment by Niklan** [comment]
Трекер хз починили или нет и альтернативный хотели делать.

**Comment by UksusoFF** [comment]
Ну там в любом случае оповещения о комментах не отображаются

**Comment by adubovskoy** [comment]
Не отображаются.
коммент нотифи не подойдет - ответы то не комментарии. Да и комменты могут быть не к вопросу, а к ответу чужому, а автору вопроса нужно тоже их получать.

**Comment by UksusoFF** [comment]
Ну а https://www.drupal.org/project/notify ?

**Comment by SemanticsPRO** [comment]
В очередной холиварный вопрос, ну нафига делали нодами, а не комменты?
Так же поля же добавить можно.
Да, альтернативный на мне.

С уведомлялкой, думаю, можно намутить рулезы + мандрилл, 100% же апи для создания очереди есть

**Comment by adubovskoy** [comment]
> мандрилл, 100% же апи для создания очереди есть

Там даже проще, он все что получает через тот же drupal_mail (и соотв. через любой рулез), ставит в очередь. Ничего отдельно писать нельзя.

> В очередной холиварный вопрос, ну нафига делали нодами, а не комменты?

Может сконвертнем?) Правда переписывать придется много... прямо много. Проще текущую структуру в кастомный трекер.

**Comment by SemanticsPRO** [comment]
Саш, тут насчёт очереди, что нельзя сразу передавать на 100500 получателей письма, долго будет, нужно их буферизировать и по крону ему скидывать.

> Может сконвертнем?) Правда переписывать придется много... прямо много. Проще текущую структуру в кастомный трекер.
> ну тут у Никиты были какие-то странные доводы в пользу нод.
> Структуру в трекер-то запихнём, но чего в будущем костыльного возникнет - хз

**Comment by xandeadx** [comment]
Предлагаю сделать как на гитхабе:
1. Для нод "Вопрос" создать флаг "Подписаться"
2. После добавления вопроса/ответа/комментария автоматически ставить автору флаг
3. После добавления ответа/комментария к вопросу отправлять письма всем у кого есть флаг (можно сделать даже без кодинга)

Пользователь в любой момент может подписаться/отписаться - просто добавив/убрав флаг.
С очередями и кроном пока заморачиваться не имеет смысла - сейчас число писем крайне не велико.

**Comment by adubovskoy** [comment]
> Саш, тут насчёт очереди, что нельзя сразу передавать на 100500 получателей письма, долго 
> будет, нужно их буферизировать и по крону ему скидывать.

Так такого и не будет. Смотри, у тебя действие - это коммент в ветке, например. В большой ветке ответов у тебя человек 40 будет максимум. Вот 40 нотифи ушло в очередь мандрилла. А уж у него обычная queue по крону.

**Comment by Niklan** [comment]
@SemanticsPRO 
Затем что с ответом в виде ноды проще.

Как вопрос, так и ответ может иметь собственные комментарии, собственные настройки и т.д. и т.п. Меньше кастомных проверок, костылей и тому подобного.

**Comment by SemanticsPRO** [comment]
@Niklan я всё равно не понимаю смысла.
@adubovskoy ну ежели через очереди, то рулезом собираем, нафиг эти notify модули.

**Comment by Niklan** [comment]
Лучше бы кто потестил дампер базы. Не улетает ли там на лево чего лишнего? Он уже готов же. Так может больше подключится народу.

@SemanticsPRO 
Смотри кейс.
Вопрос - нода, ответы - комментарии.
Я хочу прокомментировать вопрос, уточнить его или что ещё. Как я это сделаю? Ответом? Так это форум какой-то выходит. Далее. Получается каждый может писать сколь угодно ответов (комментов 0 уровня), тут поедет первый костыль, ну или затчка для комментов. Затем надо контролировать флаги и рейт чтобы были тольку у 0 уровня и т.д и т.п. с нодой в данном плане всё намного проще. Я совершенно не вижу проблем для трекера. @xandeadx предложил хорошую идею, надо двигать в сторону подписки и отписки, а не принудительного трекера как на drupal.ru. И трекер будет сделать _в разы_ проще. В общем я поддержу идею @xandeadx она самая лучшая на данный момент, самая простая, и самая гибкая выходит. И плевать на нашу структуру, флаг отвечающему и комментирующему повесить вообще нехер делать.

**Comment by Niklan** [comment]
Собственно я за тест https://github.com/Niklan/Dru.io/tree/livetodevdb/sites/all/modules/custom/druio_livetodev
Надо бы выкатывать его, но я боюсь что чего-то пропустил.

**Comment by SemanticsPRO** [comment]
Принудительный трекер, это ты круто загнул.
Вообще, сложность там совершенно не в флагах, которые андед предложил, более того, они вообще из другой оперы.
У меня практически такая же система, с трекерными флагами, у андеда с почтовыми.

**Comment by Niklan** [comment]
Не, ну нам и на сайте нужно будет обновленные материалы на которые подписан юзер выводить. Заодно эта "подписка" может служить как закладка.

**Comment by SemanticsPRO** [comment]
я уже спрашивал в чятике, ответа не помню.
У нас редис есть на серванте?
Я хочу трекер через него промутить, концепт

**Comment by Niklan** [comment]
Нету. Если надо поставлю.

**Comment by Niklan** [comment]
Проще говорю, тестануть модуль для дампа базы. И каждый у себя на локалке что угодно сможет тестить. А потом, если всё ок, на сервак поставить всё необходимое не проблема.
