### ISSUE TITLE
Лишние кнопки

### ISSUE THREAD

**Issue by fortis** [Niklan/Dru.io#190]
Считаю в редакторе для ответов и комментариев перебор с кнопками и от того еще менее понятно как они работают

Считаю лишними:
заголовки
код в одну строку
список нумерованый
определение (что это?)
аббревиатура (что это?)
ПЕРЕВОД НА СЛЕДУЮЩУЮ СТРОКУ (лол)
таблица

эти кнопки нужны для постов, но там где пишут короткий текст, комментарий, они мешают

**Comment by fortis** [comment]
обсуждаем, если все ок уберу сам

**Comment by Niklan** [comment]
таблицы нужны. Я юзаю.

**Comment by fortis** [comment]
в ответах? покажи)

**Comment by Niklan** [comment]
Определения: http://www.w3schools.com/tags/tag_dl.asp
Абрревиатура: http://www.w3schools.com/tags/tag_abbr.asp

http://dru.io/question/1677 - таблицы в ответах

**Comment by Niklan** [comment]
Код в одну строку, определение, аббривиатуру можно убрать как по мне. А вот список, заголовки, таблицы - нужны. Имхо ведь еще и публикации есть где юзают.

**Comment by fortis** [comment]
убраны:
- код в одну строку
- аббревиатура
- определение

**Comment by fortis** [comment]
Дальше нужно разделить визуальный редактор для нод и для комментов и потом еще убрать лишнее
