### ISSUE TITLE
Переименовать пункт меню Расширения в Проекты или Модули

### ISSUE THREAD

**Issue by Chi-teck** [Niklan/Dru.io#191]
_Расширения_ - не друпальный термин.

**Comment by Niklan** [comment]
Там есть и темы, и дистрибутивы, и модули и даже ядро. Так что это явно не модули.

Проблема в том что "Проекты" не совсем очевидное значение. Люди не поймут что это такое. На том же drupal.org "Download & Extend". Как по мне так расширения уместнее всего. Именно так называется раздел модулей в Drupal 8.

Давайте посмотрим кто что еще думает.

**Comment by Chi-teck** [comment]
Ядро не может быть расширением ядра. ☺
Да и дистрибутивы не совсем расширения.

**Comment by Niklan** [comment]
Тут дело в том что "Проекты" совершенно не очевидный пункт меню. Люди могут подумать, и скорее всего подумают, что это сайты сделанные на друпал.

**Comment by Chi-teck** [comment]
Ну можно компоненты сделать. Хотя это тоже из джумлы. ☺

**Comment by fortis** [comment]
мне кажется лучше просто пункт в меню Скачать, где можно скачать все и модули и темы и ядро. Download & Extend собственно туда и ведет https://www.drupal.org/download 

и нужно это учесть когда будем главную доделывать оттуда должен быть вход сразу на модули, на темы и дистрибутивы - отдельно.

**Comment by Niklan** [comment]
@fortis тогда уж не "Скачать" а "Загрузки"

**Comment by fortis** [comment]
вопросы, публикации, загрузки... мне не нрав)

**Comment by fortis** [comment]
я бы и пункт этот отделил от контентных разделов, например прибить его вправо. например СКАЧАТЬ и рядом с пунктом кратко стату по количеству модулей, тем дистрибутивов
