### ISSUE TITLE
Добавить раздел Блоги

### ISSUE THREAD

**Issue by Chi-teck** [Niklan/Dru.io#192]
Транслировать там  RSS ленту с наиболее популярных русскоязычных друпал блогов.

**Comment by Niklan** [comment]
Думаю не имеет смысла, лучше делать #10

**Comment by Chi-teck** [comment]
Так ведь придется ручками ссылки на те же самые статьи добавлять. Лента удобней и работает в друпале из коробки. Можно наверно не всё подряд транслировать, а по какому-нибудь специальному тегу: `dru.io` или `планета друпал` как на д.орг.

**Comment by adubovskoy** [comment]
Лента не даст работать рейтингу. Пользователь делает репост или публикацию ссылки (и да -- это должно быть легко и удобно), если он постит мусор -- получает низкий рейтинг.

Либо думать как привязывать рейтинг к ленте и делать депубликацию поста / всей ленты после N минусов.

**Comment by Chi-teck** [comment]
Тут примерно так и сделано: http://drupal-bloggers.com/

**Comment by Chi-teck** [comment]
Пример, как это сделано у венгров.
https://www.drupal.hu/planet
