### ISSUE TITLE
Пагинация

### ISSUE THREAD

**Issue by deadddie** [Niklan/Dru.io#194]
Фактически нет CSS-оформления пагинации. Вообще не выдкляются ни hover-события, ни активные элементы.

**Comment by Niklan** [comment]
Не понял, и активный выделяется и при наведении.

**Comment by deadddie** [comment]
Действительно.. Но контраст у всех мониторов свой.. #f9f9f9 против #ffffff почти не различимы. У активных не помешало бы выделить и шрифт (не только фон).
Да и вообще с hover'ами и корректым выделением ссылок на сайте туговато. Очень много ссылок не подсвечивается (либо с мин. изменением цвета) при наведении курсора. Ресурс, по сути, текстовой, поэтому стоит обратить на это особое внимание.

**Comment by adubovskoy** [comment]
issue еще для старого дизайна.
