### ISSUE TITLE
Предложение по хедеру

### ISSUE THREAD

**Issue by deadddie** [Niklan/Dru.io#195]
Предлагаю такой хедер (меню).
1. Хедер - 4 равных блока.
2. Навигация (меню) - 5 равных блоков + иконки.

![dru-io-menu](https://cloud.githubusercontent.com/assets/10388841/8019658/e9dd5a98-0c61-11e5-94b6-8373858f4c98.jpg)

**Comment by fortis** [comment]
там будет больше разделов, иконки для главного меню не уверен что нужны,думаю лишнее. ими чаще сопровождают меню в каком-то контексте: операции с нодой и тп. да и слишком много иконок в шапке получается.

но сейча сменю не очень хорошо смотрится кажется прибитым к лого, давайте еще думать

**Comment by fortis** [comment]
самая верхняя строчка в предложеном варианте смотрится лучше чем сейчас, но мне кажется к ней тоже нужно подойти по-другому. зачем-то внешняя ссылка на гитхаб стоит между двух важных локальных пунктов трекер и профиль. 

трекер должен быть в близи профиля, даже думаю что он должен быть частью одной кнопки: с аватаркой, именем и ссылкой на трекер. при клике можно раскрывать в небольшой блок как в гмейле и там уже будет кнопка выхода и более подробная инфа о пользователе

**Comment by fortis** [comment]
если есть идеи пишите все - потом соберем во что-то цельное, шапку нужно переработать

**Comment by fortis** [comment]
редизайн в процессе, закрываю
