### ISSUE TITLE
Заменить блок "Последние вопросы" на "Похожие вопросы" на странице вопроса

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#197]
Блок "Последние вопросы" на странице вопроса достаточно бесполезная штука. Логичней будет иметь там похожие вопросы, как это сделано на stackoverflow.

**Comment by Niklan** [comment]
Поддерживаю

**Comment by adubovskoy** [comment]
Алгоритм? По модулю?

**Comment by duozersk** [comment]
У нас есть там солр? Если да, то можно по MLT

**Comment by Niklan** [comment]
@duozersk есть, удалённый.

**Comment by adubovskoy** [comment]
@duozersk возьмешься?) я не уверен что корректно смогу это сделать. Или ткните куда почитать. Или проще дам реквизиты доступа к нему.

**Comment by duozersk** [comment]
Может быть, но не сегодня... напишу как буду готов повозиться (там вроде стандартный блок должен быть для этого).
Сегодня у меня пока что приключения с отсутствующими цссками (надо генерить сассом) и ошибками в вариаблах - неправильно чистим переменные хибрида и мандрила - заведу ишьюсы.

**Comment by duozersk** [comment]
Да, нужно что-то поконфигурить
http://drupal.stackexchange.com/questions/38028/how-do-i-create-a-more-like-this-block
https://www.drupal.org/node/1250304#comment-4870278
https://www.drupal.org/node/1111852
