### ISSUE TITLE
Раздел: Мероприятия

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#2]
_Раздел планируется, тут обсуждается как реализовывать._

**Раздел:** Мероприятия.
**Статус:** Запланирован.
**Описание:**
Раздел в котором будут публиковаться информации о проходящих Drupal мероприятиях. Кемпы, конференции, кафе, обучающие лекции.

Возможно имеет смысл сделать что-то вроде мнимной\не мнимой регистрации на мероприятие. Или кнопки по принципу соц. сетей: Пойду, Возможно пойду.

**Comment by adubovskoy** [comment]
Давно была хотелка сделать удобный централизованный сервис по мероприятиям, для авторов этих самых мероприятий.
А именно:
- Чтобы был кросспостинг в твиттер с тегом, определяемым автором.
- Чтобы можно было подписаться обновление информации о мероприятии
- Чтобы участникам приходили напоминания о мероприятии почтой / смс (я спонсирую смс-гейт в первые года пол, потом может donate предусмотреть :) . Практика показывает что напоминания за 3-4 часа до мероприятия по смс сильно влияет на посещаемость.
- Чтобы можно было легко добавить в публичные календари (google cal. и т.п.)
- Чтобы потом можно было делать showcase/отчеты с презентациями, фото, видео.
- Чтобы посетители из определенного города могли подписываться на локальные мероприятия (и, возможно, галочка подписываться по дефолту включена).

**Comment by Niklan** [comment]
Отличные предложения.

Немного интересует уточнение следующего:

> Чтобы потом можно было делать showcase/отчеты с презентациями, фото, видео.

Это предполагается делать прямо в мероприятии, спец полями? Которые после мероприятия автором заполняются, или же каждый может свой ответ showcase с рейтингом создать, которые привяжутся?

Например в разделе видео было желание чтобы видео можно было связывать с конкретным мероприятием, т.е. он находится в своём разделе, а также легко вывести его в мероприятии в автоматическом режиме, причем сделать это может каждый, не имя доступа к ноде мероприятия.

**Comment by adubovskoy** [comment]
Да, наверное гибче будет это сделать отдельной сущностью а в мероприятии референс указывать.

**Comment by Niklan** [comment]
Так проще сделать сущность "Отзыв о мероприятии":
-  Описание
-  Фотографии
-  Рейтинг(и) (организация, доклады и т.д.)
-  Связь с мероприятием. (можно автоматизировать как с ответами. Сделав форму на странице мероприятия, при этом показывать только после даты заверешения, или через сутки после даты начала, если не указана дата окончания.)

**Comment by Niklan** [comment]
Тут что-то немного мне в голову пришло. В общем надо сразу предусмотреть что мероприятие может быть реальным и вирутальным. Мало ли сбор какой-то в хэнгаут, обучающией видеотренинг или ещё что.

**Comment by Niklan** [comment]
Ввиду предстоящего хакатона #85, где @adubovskoy намеревается сделать этот раздел, ну или хотя бы начать делать. Предлагаю нам обсудить структуру и что мы будем хранить в сущности "мероприятие".

Пишу своё мнение а дальше давайте все вместе додумывать.

Считаю что там должны быть такие данные:
-  Название (title)
-  Описание
-  Дата проведения, с возможность задать дату окончания. 
-  Место проведения (либо адрес строкой, а потом чрез API получать координаты и выводить карту) либо сразу добавить поле с картой.
-  Логотип мероприятия
-  Организаторы (надо или хватит описания?)
-  Поле для фотоотчета. Можно скрывать его до момента пока дата не достигнет по крайней мере даты начала.
-  Поле для видеоматериалов (референц на ноду Видео, которую тоже надо продумать для начала минимально чтобы референцы ставить) и все это через инлайн ентити сделать для удобства.

Также предлагаю добавить флаг "Пойду" и "Возможно пойду" чтобы примерно знать сколько народу ожидать.

Нужно ли для мероприятия отзывы или комменты? Думаю было бы не плохо.

**Comment by Niklan** [comment]
Моё примерное видение страницы мероприятий https://wireframe.cc/6Ae2j4

![_002](https://cloud.githubusercontent.com/assets/2356744/7250582/29b46ff6-e83d-11e4-913e-25ebf25721a3.png)

**Comment by Niklan** [comment]
Закрываю, так как раздел сделан. По доработкам давайте делать иные ишьюсы.

**Comment by adubovskoy** [comment]
reopen https://github.com/dru-io/Dru.io/issues/2#issuecomment-70081113 пусть висит

**Comment by adubovskoy** [comment]
Помечу на себя, надо добить в d8 версии.

**Comment by Niklan** [comment]
@adubovskoy ты это будешь делать ДО релиза на 8ке, или после?

Я хочу разделить Milestones на Drupal 8 — всё что касается конкретно переноса и до самого запуска. И сделать Release 8.x-1.1 и будем собирать туда что сделать в каких итерациях.

**Comment by adubovskoy** [comment]
думаю примерно на этапе сборки дизайна. вообще можно уже начинать, просто не знаю как со временем на эту неделю.
