### ISSUE TITLE
Возможность привязать аккаунт из социалок для уже зарегистрированного пользователя

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#20]
сейчас почему то такой возможности нет

**Comment by SemanticsPRO** [comment]
Ога, взял задачку

**Comment by Niklan** [comment]
Вроде как делается автоматически при совпадании email адресов. Встроенного функционала для подобного в Hybridauth не обнаружил. Видимо как-то самим придётся делать.

**Comment by SemanticsPRO** [comment]
Да есть такое, не сцыте, у мну время всё ж появилось

**Comment by duozersk** [comment]
Чего там искать? В стандартной поставке модуль добавляет вкладку HybridAuth к профилю пользователя - и там можно добавлять и удалять привязку соц аккаунтов.

**Comment by Niklan** [comment]
Тогда закрываем. @duozersk спасибо за разьяснение
