### ISSUE TITLE
Страница раздела Вопросы

### ISSUE THREAD

**Issue by fortis** [Niklan/Dru.io#203]
Предлагаю оформить табличкой раздел Вопросы, чтобы разгрузить страницу и сделать более легкой для чтения

http://dru.io/question
аватарка пользователя задавшего вопрос как мне кажется совсем там не нужна, важен сам вопрос, его можно сделать первой колонкой и самой большой по ширине.

в первую колонку - заголовок вопроса
во вторую колонку - название раздела
в третью - аватарки тех кто дал ответ (не коммент)
в четвертую - количество ответов
в пятую - теги
в шестую - дату

ориентироваться можно на http://try.discourse.org/ воспринимается легче, нужно чтобы читая сверху внизу можно было просмотреть только сами вопросы, не спотыкаясь о теги, и прочую попутную инфу - нужно просмотреть и зацепиться за вопрос в котором я могу помочь, а пузомеркам место в стороне, имхо

**Comment by adubovskoy** [comment]
а мне не очень нра. и по поводу таблички - нужно дивами делать, адаптивность иначе сложно будет крутить.

**Comment by Niklan** [comment]
Я тоже против таблички.

**Comment by adubovskoy** [comment]
reopen, если будут сторонники.

**Comment by fortis** [comment]
табличку я имел ввиду как форму представления, хоть дивами :)

что не нравится? как выглядит дискурс?

**Comment by fortis** [comment]
идея то в том чтобы сделать раздел лучше, можно по другому, на стеке тоже таблица и нет аватарок которые отвлекают

**Comment by Niklan** [comment]
> что не нравится? как выглядит дискурс?

Мне не нравится. Я видел более удачный для dru.io вариант. Сайт не помню, но помню оформление)
Потом накину покажу.

**Comment by Niklan** [comment]
Грубо набросал +-

И вопрос видно и начало вопроса. В общем тут есть что доработать, мне просто нравится такая концепция. Достаточно информативно выходит для тизера.

![g5949](https://cloud.githubusercontent.com/assets/2356744/8232454/6080845a-15e9-11e5-87f7-21cb901dad14.png)

**Comment by adubovskoy** [comment]
в реальности вопросы сильно разной длины, могут начинаться кодом или скриншотом. резать только текст, первые 300 символов - надо прогнать на реальном контексте, насколько осмысленными будут тизеры.

**Comment by drupby** [comment]
@Niklan "Достаточно информативно выходит для тизера."
Мне как то привычней список последних вопросов/публикаций/статей просматривать сверху вниз.

**Comment by fortis** [comment]
согласен, сверху вниз тоже удобнее. блоками на галерею смахивает, да и достаточно заголовков мне кажется - больше вместится, нужно просто осмысленно писать титлы

**Comment by fortis** [comment]
чем не нравится стэка вариант?
![](http://3xff.net/3jlnv19061252.jpg)
голоса, количество ответов, количество просмотров первыми стоят, это важнее чем аватарка спросившего

**Comment by Niklan** [comment]
@fortis стэк нравится, мне не нравится дискорс
