### ISSUE TITLE
textarea autoResize

### ISSUE THREAD

**Issue by UksusoFF** [Niklan/Dru.io#206]
Хочется такой фичи при написании вопросов, ибо маленькое окошко и лень его ресайзить каждый раз.
http://habrahabr.ru/post/114182/

**Comment by xandeadx** [comment]
Или просто увеличить высоту textarea. Сейчас оно раздражающе мало.

**Comment by fortis** [comment]
я тоже за просто увеличить

**Comment by UksusoFF** [comment]
Ну вот на гитхабе оно до какогото размера увеличивается, потом уже скролл появляется.

**Comment by Niklan** [comment]
+1 за просто увеличение размера. Растянуть - не составит труда никому.

**Comment by adubovskoy** [comment]
fixed.
