### ISSUE TITLE
Хлебные крошки на отдельной странице ответа

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#207]
Нужно настроить хлебные крошки на странице ответа, например - http://dru.io/comment/527

**Comment by Niklan** [comment]
По мне надо со страницы ответа редиректить на вопрос с якорем на ответ.  И крлы сделать типа /question/123/answer/456

**Comment by xandeadx** [comment]
можно и так

**Comment by isaenkov** [comment]
А то что хлебные крошки открываются на отдельной странице это баг или фитча?

**Comment by Niklan** [comment]
@isaenkov Больше считаем что баг, ибо тут есть ишьюс где предлагают это пофиксить. Так что да, баг.

**Comment by fortis** [comment]
крошки пофиксю в выходные)
