### ISSUE TITLE
Работа с изображениями при написании вопроса.

### ISSUE THREAD

**Issue by roman-yakimkin** [Niklan/Dru.io#209]
Добрый день.

Сейчас при добавлении в вопрос изображения приходится заливать его на специальный хостинг, а потом уже изображение в вопросе размещать через ссылку с того хостинга.

Скажите пожалуйста, планируется ли быстрая заливка картинок на этот же сайт при составлении своего вопроса ?

**Comment by fortis** [comment]
вопрос нужно ли хранить скриншоты, или написать модулек например с https://api.imgur.com/endpoints/image

**Comment by fortis** [comment]
я бы начал со стороннего хостинга картинок

**Comment by adubovskoy** [comment]
Хранить проще конечно. Но, например, 5000 вопросов со 100кб картинкой - получится уже ого. А цифра вполне реальная за несколько лет. Я за модулек)

**Comment by roman-yakimkin** [comment]
Написать модуль для работы с сторонним хранилищем - идея неплохая.
Только вот, если с тем проектом что-то случится, и все картинки потеряются, что тогда делать ?

**Comment by roman-yakimkin** [comment]
5000 вопросов и в каждом - 100кб картинка - это 500 мегабайт.
Не так уж и много для нынешнего времени. 
Даже 5 - 10 гигабайт для проекта - не так уж и много.
Недорогой VPS + бэкап-хостинг.

**Comment by adubovskoy** [comment]
черт, точно, я посчитал неправильно.

может ну его? пути разметить правильно /images/Y-m/uid/, например, и хранить локально.

**Comment by fortis** [comment]
скриншоты не весят 100кб))
хостинги картинок живут долго imageshack и imgur есть сколько я с друпалом знаком, скриншоты не несут черезвычайно важной информации, вся суть в вопросе и ответах

**Comment by roman-yakimkin** [comment]
Пусть даже в каждом вопросе скриншотов на мегабайт. 
Хотя скриншоты реально где-то в каждом четвертом (или пятом) вопросе.
Всё равно не так уж критично.

**Comment by drupby** [comment]
@fortis  "вопрос нужно ли хранить скриншоты, или написать модулек например с https://api.imgur.com/endpoints/image"
для использования api imageshack нужен минимум тариф $29.99, imgur тоже вроде требует оплаты, скриншоты встречаются в каждом пятом вопросе, вроде как не так и много места займет
если уж стороннее хранилище использовать, то Amazon S3 http://aws.amazon.com/ru/s3/pricing/ https://www.drupal.org/project/amazons3

**Comment by Niklan** [comment]
+1 за imgur, или покупать Amazon S3 для хранения "локально" (на cdn). Хранить с друпалом - не надо. Переносить сложнее, и прочие неприятные мелочи. Amazon S3 дешевый как хз что. Обьясните как там всё сделать я сделаю и заплачу. Тут вопрос в том что я на этом AMazon S3 дальше регистрации и активации не ушел. Там интерфейс черт ногу сломит.

**Comment by drupby** [comment]
есть еще нынче кроме амазона google cloud storage https://cloud.google.com/storage/ https://www.drupal.org/project/google_cloud_storage

**Comment by Niklan** [comment]
Не совсем ясно по ценам лучше/хуже? И вообще, где сервера то? На амазоне выбор есть а тут не вижу.

**Comment by fortis** [comment]
если бесплатного стороннего сервиса нет, то и нет смысла сейчас решать вопрос со сторонним платным хранилищем, проще картинки хранить у себя, места на ближайшее время точно хватит, амазон уже при необходимости рассматривать.

**Comment by fortis** [comment]
я такой непостоянный)))

**Comment by drupby** [comment]
"если бесплатного стороннего сервиса нет"
5Гб бесплатно на амазоне

нужен ли амазон? я пока смысла не вижу

**Comment by roman-yakimkin** [comment]
А если такой вариант для хранения ?
https://contabo.com/?show=vps

8 евро в месяц, 500 Гигабайт на диске, 6 ГБ ОЗУ.

По идее, хватит на десятилетия :)

**Comment by adubovskoy** [comment]
мы тут вроде в чатике приходим к мысли что будем локально там же где и сам сайт. А если будет напряжно хранить - у нас там уже 2 хостера на выбор которые готовы предоставить серваки)

**Comment by xandeadx** [comment]
храните локально, только папку пропишите отдельную, чтобы одним регекспом можно было сменить урлы всех картинок, если понадобится

**Comment by Niklan** [comment]
@xandeadx хорошая идея.
