### ISSUE TITLE
Дизайн главной

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#213]
Позже набросаем сюда идеи. 

Нужна главная, где эргономично будут видны (список в порядке убывания траффика):
- Вопросы
- Заказы (см #6 )
- Посты
- Мероприятия

**Comment by fortis** [comment]
- список новых модулей
- список уязвимостей

**Comment by Niklan** [comment]
Не ну а чо. Кнопки для загрузки ядра тоже не помешали бы

**Comment by fortis** [comment]
согласен надо

**Comment by xandeadx** [comment]
Можно добавить статистику:
- число вопросов / ответов / комментариев
- число пользователей
- самые рейтинговые юзеры
- самые часто вопрошаемые категории

**Comment by chelwolf** [comment]
У текущей главной есть некоторые проблемы на мой взгляд, излагаю идеи и их решения на скриншотах:
![1](https://cloud.githubusercontent.com/assets/13641759/9059825/8c174a6c-3acf-11e5-97ac-a652503d293a.jpg)
![2](https://cloud.githubusercontent.com/assets/13641759/9059823/8c16c286-3acf-11e5-9745-06de13f2d572.jpg)
![3](https://cloud.githubusercontent.com/assets/13641759/9059824/8c16cbc8-3acf-11e5-8410-920620d5312f.jpg)

**Comment by chelwolf** [comment]
Можно ещё добавить статистику - большая картинка с текстом занимает неоправданно много пространства. Возможно сделать вообще слайдер с различными презентационной информацией, туда же поместить календарь мероприятий сообщества, ниже предложен вариант со статистикой:
![default](https://cloud.githubusercontent.com/assets/13641759/9060205/6f48df78-3ad3-11e5-8477-fcd433e06e53.jpg)

**Comment by Niklan** [comment]
Это надо отдельной страницей делать, точно не на главной.

**Comment by adubovskoy** [comment]
про кнопки - ок, про иконки - да, хороший вариант) Статистика -- надо думать, либо отдельная страничка, либо поменьше.

**Comment by drupby** [comment]
Статистику сообщества только если в подвале разместить, ну и не такого громадного размера.

**Comment by Niklan** [comment]
Забрал, начал переработку темы, учту предложения.

**Comment by adubovskoy** [comment]
https://github.com/dru-io/Dru.io/issues/399 связан

**Comment by xandeadx** [comment]
У yiiframework неплохой дизайн - https://github.com/eshill/yiiframework.com/blob/master/png/Index.png
- Краткое описание
- Последние новости
- Книги
- Вопросы

**Comment by adubovskoy** [comment]
Никита вроде взялся для следующей итерации главной (на D8 уже) прорисовать, с учетом всех пожеланий и поведения народа по вебвизору. Но это январь только, вероятно.

**Comment by fortis** [comment]
имхо лучше заказать или подобрать готовый дизайн, у нас все-таки не очень хорошо получается)

**Comment by fortis** [comment]
лучше прототипированием заняться

**Comment by adubovskoy** [comment]
Ну, это лучше чем ничего)

**Comment by fortis** [comment]
как вариант ближе к запуску попробовать на конкурсной основе найти дизайнера

**Comment by xandeadx** [comment]
а платить кто будет?)

**Comment by fortis** [comment]
готовых psd много, тем более на техническую тематику, можно купить и адаптировать, там цены небольшие. я имею ввиду psd от фрилансеров дизайнеров, не тм и прочий шлак))
а платить.. ну домен мы как-то оплатили и продлили я и на диз не против скинуться

**Comment by Niklan** [comment]
Ну я сказал я попробую что-то накидать, учитывая что за это время все понаписали, пожелали. Я примерную картинку имею что хотят и просят. Но я не гарантирую что это лучше текущего будет и вообще получится :D
