### ISSUE TITLE
Добавить раздел "Code review"

### ISSUE THREAD

**Issue by malikin** [Niklan/Dru.io#215]
Я думаю, был бы уместен этот раздел на dru.io как часть концепции сообщества.

Многие новички как я, пишут код, и оценить его качество в рамках Drupal-way тяжело, и советы опытных камрадов были бы очень кстати.

Выглядеть раздел может точно также как и вопросы, не вижу особо что можно еще выдумать, но возможно у других есть идеи.

**Comment by holyorb2** [comment]
Можно обычную тему создать и выкласть туда свой модуль/код.
Делать для того раздел - нет смысла.

**Comment by malikin** [comment]
Дубль https://github.com/Niklan/Dru.io/issues/54
Пропустил. Удалите этот issue пожилуйста.

**Comment by adubovskoy** [comment]
Закрываю просто.
