### ISSUE TITLE
Развитие раздела Проектов

### ISSUE THREAD

**Issue by fortis** [Niklan/Dru.io#217]
на страницу каждого проекта, например: http://dru.io/project/browscap_block
я бы добавил вот таких ярлыков
![](http://3xff.net/glyaj26061148.jpg)
- стабильную версию, с ссылкой на нее
- кол-во загрузок с орга, с ссылкой на usage statistics
- кол-во открытых ишусов, с ссылкой на них

**Comment by fortis** [comment]
![](http://3xff.net/91z2y26061205.jpg)
команды должны быть на сером фоне с кнопкой для копирования в буфер

**Comment by Niklan** [comment]
Как ты такие плашки собираешься делать?

**Comment by fortis** [comment]
css'ом) пока я предложил всего три

**Comment by Niklan** [comment]
В смысле build status и прочее. Как ты их тестить то собрался?)

**Comment by fortis** [comment]
я не писал про build status

**Comment by fortis** [comment]
стабильную версию, с ссылкой на нее
кол-во загрузок с орга, с ссылкой на usage statistics
кол-во открытых ишусов, с ссылкой на них

**Comment by Niklan** [comment]
Проблема в том что для этого всего нету API. А парсить - уже не быстро и контролить придется. Для этого всего есть ссылка на орг по сути.

**Comment by fortis** [comment]
Там же OpenSearch, надо посмотреть как посчитать количество открытых issues, но можно и без них обойтись

Всю инфу можно брать из json ноды проекта, а не из xml, тут https://www.drupal.org/api-d7/node.json?field_project_machine_name=payment
- есть ссылка demo это simplytest можно тоже кнопкой делать
- есть количество загрузок  field_download_count
- есть скриншоты
- ссылка на документацию
- changelog
- организации спонсоры модуля
- есть описание его тоже можно брать из body

**Comment by fortis** [comment]
вообще я бы рассмотрел Проекты как отдельный инстал, вывести вопросы по модулю в отдельном сайте не проблема, а бутстрапить друпалу меньше, и кеш с парсингами отдельно будет жить своей жизнью. И в случае перехода основного портала на восьмерку или 10ку Проекты можно будет оставить на 7ке. Имея раздельные подсистемы с ними и в будущем проще выйдет я думаю

**Comment by Niklan** [comment]
Описание не нужно, а вот скрины хотели дергать. 

Стабильной версии нигде нет. 

Делить тоже думаю ненужно. Не такой уж и крупный раздел. Мы потом запаримся, все **\* положат на него.

**Comment by fortis** [comment]
так я и предлагаю сделать его больше, но отделив от основного чтоб не грузило, всю инфу можно парсить и кешировать но держать отдельно. 

и потом туда можно будет больше привязывать инфы, скринкасты к модулю, записи в других блогах с примерами работы с модулем и тп, это же самый посещаемый раздел может быть на сайте

**Comment by fortis** [comment]
цель то держать пользователей у себя и для русскоязычных делать более доступной инфу по модулям, и раздел значит нужно делать более полезным, а не просто каталогом ссылок на скачку

**Comment by fortis** [comment]
если новичек не знает английского, но видит что на страницах скачивания есть инструкции, задаваемые вопросы, записи из блогов - он будет заходить и скачивать тут всегда))

*можно не отделять
здесь хочу обсудить скорее развитие раздела

**Comment by Niklan** [comment]
Я категорически против разделение проектов. Я на 100% уверено - забьют на него все и разом. Всё надо делать вместе и смысла сильно расширять нету. Мы не drupal.org и цели выдать всё и сразу нету.

Видео и прочее мы и так можем выводить на странице, штук по 5 на каждый тип и дальше в писк на всё или ещё как. Для этого целый сайт делать - тупо. Тем более что видео раздел и прочее будет на основном. Загнется моментально всё это.

**Comment by Niklan** [comment]
А с развитием пока думаю надо притормозить. В принципе нам надо профили первостепенно сделать и заказы. Потом уже возвращаться. Пока он работает, свой минимум выполняет и хорошо. Ну и чтобы его расширять, те же скринкасты и т.д., надо для этого разделы сделать сначал а потом уже выводить в проектах.

**Comment by fortis** [comment]
Мы пилим то что интересно, мне интересно заняться проектами и обсудить их

**Comment by fortis** [comment]
и обсуждать нужно всем вместе, а не пресекать идеи. я вижу смысл в этом разделе для новичков и большую пользу

**Comment by fortis** [comment]
переформулирую отдельным ишьюсом тут закрываю
