### ISSUE TITLE
Пометка "решение" не только в ответе, но и в комментарии

### ISSUE THREAD

**Issue by roman-yakimkin** [Niklan/Dru.io#218]
Есть мысль - сделать, чтобы можно было помечать как "верный ответ" не только ответ, но и комментарий к нему.
А то в процессе разбора вопроса может возникать дискуссия в комментариях, в процессе которой выдается верный ответ.

**Comment by Niklan** [comment]
Не логично. Тогда проще самому его структурировать из дисскуссии ответ и написать в целом, автору вопроса и поменитть как решение. Иначе человек заходит и читает ветку 50+ комментов в ходе которой все же нашлось решение. Ведь по сути в такой дискуссии решение состоит из всех этапов обсуждения ведь код постепенно собирается в единое целое.

В общем как по мне, не нужно. Не видел такого нигде.
