### ISSUE TITLE
Специфика словаря

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#22]
Требуется переписать словарь с учетом след."синонимов":
друпал/drupal
обновление/обновить/обновился
... 
наращивайте список, поправим скопом.

**Comment by Niklan** [comment]
Раз солр не понимает транслитерацию, по самым популярным и ходовым транслитерациям в сообществе, думаю стоит сделать синонимы. Указываю в единственном числе, надеясь что склонения уже подхватит у синонимов.
-  views - вьюс
-  panels - панель
-  drush - драш

**Comment by SemanticsPRO** [comment]
pane - панель
Лучше так наверно

**Comment by Niklan** [comment]
api - апи
form - форма
alter- альтер
hook - хук

**Comment by fortis** [comment]
а почему solr не понимает транслитерацию? там же есть analyzer index/query http://wiki.apache.org/solr/AnalyzersTokenizersTokenFilters#solr.ASCIIFoldingFilterFactory
правда токенизеры только для fulltext работают, но это вроде только в помощь нам.

синонимы кажется через запятую лучше сразу писать чтоб проще было копипастить.

## 

хтмл, html
яваскрипт, javascript, js
drupal, друпал, дрюпал, друпл, дрюпл

**Comment by Niklan** [comment]
Я так понимаю ишью изжил себя. Никто этим не занимается, следовательно, закрывается до востребования.
