### ISSUE TITLE
Ошибка в консоли Uncaught TypeError: Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by karmazzin** [Niklan/Dru.io#221]
Проблема со скриптом select2, проблема и решение описано [здесь](http://stackoverflow.com/questions/29200171/select2-uncaught-typeerror-cannot-read-property-fn-of-undefined)

![image](https://cloud.githubusercontent.com/assets/2082480/8416780/a59df3ae-1eb0-11e5-9c2f-c658c17760cc.png)

**Comment by adubovskoy** [comment]
Валится, на странице добавления вопросов, сделал revert.

**Comment by karmazzin** [comment]
Вообще у плагина select2 есть свой файл со стилями, вероятно, проблемы из-за его отсутствия, но не стал добавлять т.к. его изначально не было.

**Comment by Niklan** [comment]
Ну у нас select2 по своему оформлен.

**Comment by fortis** [comment]
fixed, обновлено до 4.0.0

**Comment by fortis** [comment]
на странице добавления вопроса - множественный селектор, но внешний вид об этом не говорит - надо ткнуть сначала, чтобы понять. добавил и ему стрелочку dropdown
