### ISSUE TITLE
Дублируются мероприятия (воспроизводится локально)

### ISSUE THREAD

**Issue by karmazzin** [Niklan/Dru.io#223]
Возможно стоит включить удаление дубликатов в расширенных настроках вьюхи.

![image](https://cloud.githubusercontent.com/assets/2082480/8439885/789b1d74-1f77-11e5-9769-404e0f65db1b.png)

**Comment by adubovskoy** [comment]
Там стоит, на http://dru.io/events не наблюдается.

**Comment by karmazzin** [comment]
@adubovskoy, добро. Я просто развернулся из релиза v0.1, возможно уже было поправлено.
