### ISSUE TITLE
Причина удаления вопроса/ответа

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#226]
Неплоха бы при удалении вопроса/ответа иметь возможность указать причину. После этого либо слать автору письмо что его пост удалён по такой-то причине, либо выводить причину удаления вместо поста, чтобы автор видел и делал выводы.

P.S. как средство борьбы с комментами в виде ответов, раз уж не хотите отключать ответы для автора вопроса.

**Comment by drupby** [comment]
такое работает на stackexchange.com, но для этого нужны правила, можно взять за пример http://drupal.stackexchange.com/help

**Comment by Niklan** [comment]
Вообще идея неплохая. Надо придумать реализацию.

**Comment by adubovskoy** [comment]
Можно альтер формы подтверждения удаления сделать. Там select прописать с типовыми вариантами (или textfield, куда своими словами кратко) и просто через drupal_mail отправлять автору.

**Comment by Niklan** [comment]
Или трекер расширить чтобы туда можно было мессаджи слать и слать туда)

**Comment by adubovskoy** [comment]
кстати да, это ж сущность просто, ее создать легко. даже удобнее почты имхо.
