### ISSUE TITLE
Механизм рейтинга

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#227]
Посоветуйте насчет работы рейтинга пользователя. Пока идея следующая (в кастомном модуле): раз в день создавать очередь (queue + ultimate cron) на обсчет рейтинга пользователя. Значения пишем в поле профиля.

Сам подсчет: 
рейтинг = сумма голосов за все вопросы/ответы + кол-во ответов помеченных как "ответ" \* 2

**Comment by malikin** [comment]
Мне кажется, все очень здраво.

**Comment by Niklan** [comment]
Да вроде нормально.

Хотя мне кажется что рейтинг стак оверфлоу покруче сделан) Но поправитьв сегда сможем. У них там вообще жесть)

**Comment by adubovskoy** [comment]
готово, можно пользоваться для др.нужд.
