### ISSUE TITLE
Раздел: Работа

### ISSUE THREAD

**Issue by holyorb2** [Niklan/Dru.io#228]
Где раздел работа, вакансии, предложения и т.д.?

**Comment by adubovskoy** [comment]
https://github.com/Niklan/Dru.io/issues/6

**Comment by Niklan** [comment]
Я тоже так подумал сначала. Но потом уловил суть ишьюса.

В #6 у нас заказы фрилансерам. Здесь же предлагается поиск сотрудников (программистов) и студий программистами. Типа вакансии.

**Comment by fortis** [comment]
почему это должно отличаться от поиска исполнителя на проект/задачу?
