### ISSUE TITLE
"Бухгалтерские" вопросы

### ISSUE THREAD

**Issue by SemanticsPRO** [Niklan/Dru.io#23]
Подумалось тут.
Может стоит завести нечто для обсуждения легальной работы, финансовых вопросов и etc?

**Comment by Niklan** [comment]
Юр. раздел что ли? Думаешь будут обсуждать?

**Comment by semyondragunov** [comment]
Поясните плз, что из себя будет представлять раздел?

**Comment by xandeadx** [comment]
а подшивки раздела каждый месяц отправлять в налоговую :)

**Comment by semyondragunov** [comment]
to, xandeadx: )))))))) шпиёны, шпиёны)

А Вообще отставьте не программерскую/друпальную часть, специализированным форумам и сайтам)

**Comment by adubovskoy** [comment]
> А Вообще отставьте не программерскую/друпальную часть, специализированным форумам и сайтам)

солидарен
