### ISSUE TITLE
Добавить к вопросам поле "Файл"

### ISSUE THREAD

**Issue by dimmitri** [Niklan/Dru.io#230]
Хотел задать Вопрос на Dru.io и прикрепить 10-секундный файл с видео для лучшего понимания сути вопроса.
На drupal.org, да и на drupal.ru есть возможность прикреплять файлы.
На друпале делается за две минуты. Мелочь конечно, но мне кажется нужная. Может я и не прав.
Хотя конечно, даже, если ограничить файлы размером меньше мегабайта, наполняться будет очень быстро.
Вот такое предложение.

**Comment by fortis** [comment]
почему не на ютуб?

**Comment by dimmitri** [comment]
1) ради 10-сети секундного ролика без звука заливать на ютуб))) я даже не знаю...
2) может пользователям не только видео и картинки необходимо будет загрузить. .pdf или .ppt
3) это только предложение к рассмотрению, если никто не поддержит, я не умру)))

**Comment by adubovskoy** [comment]
Видео на серваке пока не будет, простите, потенциальная нагрузка. Либо вам самим придется оплачивать дроплет для этого, краудфандинг, все дела)

но. но. есть вариант с https://www.drupal.org/project/youtube_uploader .

**Comment by dimmitri** [comment]
Понятно. Это не конец света. Удачи в развитии проекта.

**Comment by Niklan** [comment]
10 секунд ролик можно и на imgur вроде как отгрузить.
Ща в моде webm, есть варианты куда залить)

**Comment by adubovskoy** [comment]
мы можем транслировать на ютуб через api сразу. аккаунт для druio сделать и там все хранить. ы?) Для мероприятий будет удобно)

**Comment by Niklan** [comment]
По мне так слишком специфичная задача хранить видео для вопросов. 
Не нужно такое поощрять. С мобилок и прочих вещей не посмотреть видео. Если давать такую возможность все будут траблы в видео постить и вообще писать не будут)

**Comment by Chi-teck** [comment]
Тикет был о том что добавить поле "файл" к вопросам. Такая возможность есть на _drupal.org_ и на _drupal.ru_ причем не только для нод, но и для комментариев. Видео это просто частный случай для примера. Да и не будет с ним никаких проблем если его просто отдавать как обычный файл для скачивания.

[drupal.ru](http://www.drupal.ru/)
**Максмальный размер файла:** 8 МБ
**Доступные расширения:** odt ods odg xcf svg jpg jpeg gif tiff png mng txt doc docx xls xlsx sxw sxc tex ps pdf rtf djvu ppt pptx pps odp tgz tar.gz bz2 tar.bz2 tbz2 zip rar psd po pot module info xpi diff install patch ogg spx.

[drupal.org](http://www.drupal.org/)
**Максмальный размер файла:** 50 МБ
**Доступные расширения:**  jpg jpeg gif png txt xls pdf ppt pps odt ods odp gz tgz patch diff zip test info po pot psd yml mov mp4 avi mkv.

**Comment by fortis** [comment]
+
поддерживаю орг расширения и размер

**Comment by adubovskoy** [comment]
Смотри, это вполне может дать нагрузку на storage. И будет 2 варианта:
1. Мы скидываемся на хостинг регулярно, т.к. монетизации нет. Тогда надо кошелечек завести публичный, куда надо будет перекинуть.
2. Мы переезжаем на радон или друпалхостинг или не важно куда, но на сайте явная реклама хостера за это.

**Comment by fortis** [comment]
от чего нагрузка то? видео потоковое же включать не будем, размер 50мб хоть mkv цепляйте но 50мб и только скачивание

**Comment by adubovskoy** [comment]
давай тогда дождемся еще мнений. И если включать, то осторожней, 10мб пока ограничение сделать.

**Comment by Chi-teck** [comment]
Проблема не в нагрузке, а в дополнительном дисковом пространстве которое потребуется от хостинга. 50 МБ действительно выглядит расточительно. Кстати, лимит может быть разным в зависимости от типа материала и комментария.

**Comment by adubovskoy** [comment]
я это и имел в виду. и посчитал кол-во желающих, пока тех кто "за" больше - ок, задача в todo листе, надо делать) 

Будет поле у вопросов/ответов, публикаций, мероприятий.

**Comment by fortis** [comment]
да и аттачи все равно будут нужны работодателям или на разовые проекты - прикрепить тз, макеты и прочее.

**Comment by Niklan** [comment]
Если делать загрузку с лимитом в 50МБ, надо задумываться о покупке гугл сторейджа или амазаона с3. Ибо на SSD хранить такие файлы как-то слишком жирно выходит и очень дорого.

**Comment by fortis** [comment]
у нас нет такой проблемы) и до нее нам далеко
