### ISSUE TITLE
Странные сообщения при авторизации

### ISSUE THREAD

**Issue by codev0** [Niklan/Dru.io#233]
Ввел неверено пароль, и тут http://gyazo.com/72bffb573c0bc2c10853f051e03525fb.

**Comment by fortis** [comment]
тоже самое при входе с сохраненным в браузере паролем, причем потом можно моментально сделать сабмит логина и пароля - пройдет. предлагаю выключить эту защиту она только вредит

**Comment by codev0** [comment]
можно попробовать через https://www.drupal.org/project/honeypot
