### ISSUE TITLE
markdown список не работает

### ISSUE THREAD

**Issue by Chi-teck** [Niklan/Dru.io#237]
Список

```
* Foo
* Bar
* Baz
```

Должен выглядеть так:
- Foo
- Bar
- Baz

**Comment by Niklan** [comment]
Там два пробела нужно.

**Comment by Chi-teck** [comment]
А зачем так?

**Comment by Niklan** [comment]
Спросите у автора markdown filter =)

**Comment by Niklan** [comment]
Вот он юзается: https://www.drupal.org/project/markdown

**Comment by Niklan** [comment]
Отсылка будет сюда скорее всего: http://daringfireball.net/projects/markdown/syntax#list

**Comment by Chi-teck** [comment]
Там не указно количество пробелов.

**Comment by fortis** [comment]
- один пробел
-  два пробела
-                                                                                                    СТОПРОБЕЛОВ!

**Comment by fortis** [comment]
😎

**Comment by Niklan** [comment]
Собственно это не наш косяк. Хакать модуль не вариант.

**Comment by Chi-teck** [comment]
> Собственно это не наш косяк.

Не наш, но у нас.

**Comment by Chi-teck** [comment]
Про два пробела никто не знает. Даже буэдитор.

**Comment by Chi-teck** [comment]
Проверил фильтр отдельно. Работает с одним пробелом. Может я чего то не правильно делал в прошлый раз? Предпросмотра на сайте нет чтобы проверить.

**Comment by Niklan** [comment]
В комментах потести где, потом потрем. Надо порыться в ишьсюах. Может это его траблы личные.

**Comment by fortis** [comment]
проверил, с одним пробелом работает
