### ISSUE TITLE
Добавить в вопрос поле Уровень сложности

### ISSUE THREAD

**Issue by tlito** [Niklan/Dru.io#239]
то есть например пользователь спрашивает Как настроить вьюс - некоторым будет достаточно пояснить какое поле настройки искать, а другим нужно пояснять куда кликать мышью - это зависит от уровня владения cms автором вопроса.
или вот пример http://dru.io/question/2641
в целом можно ответить на вопрос алгоритмом хука вьюс, а можно дать код этого хука - если автор не в состоянии написать хук по предложенному алгоритму.
поэтому будет иногда полезно отвечающим узнать уровень сложности, на который рассчитывает автор вопроса и степень владения автором cms

**Comment by Niklan** [comment]
Не нужно. В идеале всегда нужно давать развёрнутый ответ. Но когда дают ответ очень просто и не развёрнуто, скорее всего это посыл в гугл, ибо эта тема разжевана давно.

Понятие сложности у всех относительное. Это добавит лишь путанницы.
