### ISSUE TITLE
Модераторы

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#24]
Нужны наверно люди, которые будут:
- переносить ответы в комментарии ( http://community.drupalife.com/question/160 )
- править информацию о вопрос (заголовки, таксономию)
- создавать категории
- удалять спам и прочее

**Comment by Niklan** [comment]
Нужны, однозначно.

**Comment by xandeadx** [comment]
Могу править заголовки и проставлять таксономию

**Comment by Niklan** [comment]
Надо бы роль модератора сделать.

**Comment by Niklan** [comment]
Пф, нельзя несколько человек привязать :baby_chick: Сделаю сам тогда.

**Comment by Tristamoff** [comment]
Готов бороться со спамом.Я Chyvakoff.

**Comment by Niklan** [comment]
#42 Переходим сюда.
