### ISSUE TITLE
Page title

### ISSUE THREAD

**Issue by semyondragunov** [Niklan/Dru.io#241]
Открываем http://dru.io/question/2757 и дружно смотрим title **(не h1)**.

**Comment by Niklan** [comment]
```
<h1 id="page-title">"must have" набор модулей для начинающего осваивать Drupal.</h1>
```

???

**Comment by semyondragunov** [comment]
Сказал же не h1.

**Comment by semyondragunov** [comment]
![Title](http://storage4.static.itmages.com/i/15/0730/h_1438292071_2578210_a6a0e292ec.png)

**Comment by adubovskoy** [comment]
Кавычки, ага.
<title>&amp;quot;must have&amp;quot; набор модулей для начинающего осваивать Drupal. | Dru.io</title>
