### ISSUE TITLE
Опечатки в тексте.

### ISSUE THREAD

**Issue by RuZniki** [Niklan/Dru.io#242]
Встречаются очепятки, глаза режет. Нужен аналог orphus.
Пример: http://dru.io/post/2766

**Comment by drupby** [comment]
@RuZniki "глаза режит" - глаза реж**е**т

**Comment by fortis** [comment]
Позже отделим основной раздел публикаций от персональных записей, чтобы фильтровать материалы в основном разделе сайта, там орф ошибок не будет, а править персональные записи  каждого пользователя вряд ли возможно
