### ISSUE TITLE
HybridAuth: VK and GitHub - internal error 500

### ISSUE THREAD

**Issue by duozersk** [Niklan/Dru.io#245]
When I'm on the page /user/user_id/hybridauth and trying to add VK or GitHub identity - the popup shows up with internal error 500.
Facebook, Google and Twitter work fine.

**Comment by Niklan** [comment]
Facebook также
Гугл работает
Твиттер работает
GitHub нет

**Comment by duozersk** [comment]
Нужны логи сервера - на чем оно там валится

**Comment by duozersk** [comment]
Нет, логи уже не нужны - файлы провайдеров не скопированы при установке библиотеки.
Нужно скопировать файлы провайдеров VK и GitHub из additional-providers в hybridauth/Hybrid/Providers (в папке библиотеки) - это подробно описано в README.txt модуля

**Comment by duozersk** [comment]
Fixed in https://github.com/Niklan/Dru.io/pull/246

**Comment by Niklan** [comment]
@duozersk авторизация по google отвалилась

**Comment by Niklan** [comment]
```
400. That’s an error.

Error: redirect_uri_mismatch

Application: Project Default Service Account

```

**Comment by Niklan** [comment]
Стоп...

**Comment by Niklan** [comment]
Всё ок :)
