### ISSUE TITLE
Поставить модуль Google Analytics вместо вставки кода в шаблон

### ISSUE THREAD

**Issue by NL9** [Niklan/Dru.io#249]
Для лучшего отчета по ролям, учет поисковых запросов на сайте, отслеживания кликов по ссылкам, картинкам, отслеживание ошибок, сообщений (drupal_set_messages())

По желанию можно через https://www.drupal.org/project/ga_push настроить отслеживание регистрацией, добавления комментариев и т.п.

**Comment by Niklan** [comment]
ок
