### ISSUE TITLE
Запретить писать ответы создателю ноды и ограничить число ответов

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#25]
1. Нужно запретить создателю вопроса писать ответы. Для этого есть комментарии.
2. Запретить оставлять больше одного ответа. Для этого есть функция редактирования первого ответа и комментарии к ответу.

**Comment by Niklan** [comment]
Забрал, действительно полезно.

**Comment by Niklan** [comment]
Сделано.

**Comment by semyondragunov** [comment]
А как ответить самому если нашел решение? Писать в саму тему? Или как?

**Comment by xandeadx** [comment]
Что-то отвалился функционал — http://dru.io/question/1315

**Comment by semyondragunov** [comment]
https://github.com/Niklan/Dru.io/issues/88

**Comment by Niklan** [comment]
@xandeadx вот именно поэтому автору и не давали даже 1 ответа давать. Такие ответы надо сносить кароче без предупреждения. Чтобы сразу отвыкали)

**Comment by xandeadx** [comment]
Никто не пишет свои ответы, все пишут комменты в ответах - http://dru.io/question/1340
Давайте всё же запретим отвечать авторам. Ответ можно дописать в сам вопрос.

**Comment by semyondragunov** [comment]
@xandeadx пишут ответы, пишут. Только ещё путаются, что и куда писать, так как все привыкли к формату обычного форума, а тут....

**Comment by Niklan** [comment]
@xandeadx пусть, могут оставить ответ и пометить решением. Вдруг сами решат, такое часто бывает и повод будет.

А когда они юзают не по назначению, без угрызения совести удаляем. Текущего я снес. Над формой весит предупреждение, в котором ясно написано для чего использовать форму ответа автору вопроса и предупреждение об удалении. Так что всё ок. Они предупреждены.

**Comment by xandeadx** [comment]
Мне уже надоело удалять комментарии авторов из ответов. Никто не пишет туда свои же решения.
http://dru.io/question/1840

**Comment by adubovskoy** [comment]
ага, в чатике аналогичное предложение, 

> [21:17:19] Alan Bondarchuk: мне вот кажется нужно поменять отправку ответов и комментариев, 
> добавление ответа сделать большой зеленой кнопкой Я ВАМ СЕЙЧАС ДАМ ОТВЕТ
> [21:17:32] Alan Bondarchuk: а не текстовое поле, я зашел прочитал увидел поле и в нем задал вопрос
> [21:17:37] Alan Bondarchuk: а это поле для ответа блин
> [21:17:49] Alan Bondarchuk: чаще вопросы задают мне кажется чем ответы дают)
> [21:18:10] Alan Bondarchuk: и видя привычное поле оставляю в нем комментарий

https://github.com/Niklan/Dru.io/issues/165 сделал отдельную задачку.

**Comment by semyondragunov** [comment]
Сам раз 10 так путал ссылки: ответа и комментария.

**Comment by xandeadx** [comment]
Это продолжается http://dru.io/question/1902
А свои ответы по прежнему никто не пишет

**Comment by semyondragunov** [comment]
Свои ответы пишут, затем происходит - это https://github.com/Niklan/Dru.io/issues/145 Люди пужаются, что не могут пометить свой ответ правильным и удаляют его (вернее стирают, а модер потом удаляет). Но не все кстати, видел много вопросов, где автор сам написал ответ, но пометить не может.

**Comment by Niklan** [comment]
Надо не "Ответить на вопрос", а, например, "Написать решение".

**Comment by fortis** [comment]
или 
Предложить решение

**Comment by fortis** [comment]
а для автора топика кнопку переименовать в 
Я сам нашел решение

**Comment by Niklan** [comment]
@fortis всё гениальное - просто. 
Действительно, автору вопроса тупо сменить кнопку и всё!
