### ISSUE TITLE
Добавить микроразметку Событий

### ISSUE THREAD

**Issue by NL9** [Niklan/Dru.io#250]
https://developers.google.com/structured-data/rich-snippets/events?hl=ru
Для лучшего отображения в результатах поиска.
Потребуется написать небольшой модуль, для вывода разметки application/ld+json.

**Comment by Niklan** [comment]
Было

**Comment by drupby** [comment]
Было 2 ишью #80 #35 , потом их перенесли в #44

**Comment by Niklan** [comment]
Тогда оставляем.

**Comment by fortis** [comment]
возьму

**Comment by Niklan** [comment]
@fortis пока не делай. Тема на переработке. Всё слетит.

**Comment by adubovskoy** [comment]
@Niklan чем, это же с темой почти никак не связано, просто вывод в json данных из полей. Ты имхо тут перестраховываешься. В распределенном проекте каждый должен работать в удобное для себя время, иначе никак.

**Comment by fortis** [comment]
да тут не разметка а json inline

**Comment by Niklan** [comment]
@adubovskoy микроразметка schema.org идет на уровне аттрибутов. Аттрибуты у ds поле либо в коде, либов  админке. Я их меняю и переписываю. Каким бы методом их не сделали - все равно слетит. Или я чего-то не так понял?

**Comment by drupby** [comment]
@Niklan погугли  JSON-LD и все станет понятно.

**Comment by NL9** [comment]
В первом сообщении по ссылке есть пример кода.

Он зависит только от названия полей, они наверняка не будут меняться при разработке темы.

**Comment by Niklan** [comment]
А ну тогда ок. А я думал аттритубы описываются. Так даже проще если без них. А Яндекс поинмает?

**Comment by Niklan** [comment]
Блин, крутая штука, так-то. Это вообще норм если все описывать прямо в нем? И вопрос по Яндексу акутален. На счет гугла не сомневаюсь, а вот Яндекс хз.

**Comment by Niklan** [comment]
https://tech.yandex.ru/validator/ оу, норм, понимает.
Тогда нафига эта schema.org разметка прямо в коде если можно так просто?
Кто-то модуль с орга пробовал? Было бы круто аналог path_breadcrumbs для такой штуки, вообще бы шик был.

Но ведь не может быть так всё шикарно, какие-то минусы есть?

**Comment by NL9** [comment]
Яндекс понимает.

> Тогда нафига эта schema.org разметка прямо в коде если можно так просто?

Потому что этот способ новый, его только недавно гугл начал продвигать.

> Кто-то модуль с орга пробовал? Было бы круто аналог path_breadcrumbs для такой штуки, вообще бы шик был.

Есть https://www.drupal.org/project/structured_data и https://www.drupal.org/project/google_sitelinks_search_box, но они узкоспециализированные.

Нужно structured_data развивать, но превращать его не в аналог path_breadcrumbs, а в аналог metatag.
