### ISSUE TITLE
Убрать пункт "Главная" из main menu

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#252]
Есть же кликабельный логотип.

**Comment by adubovskoy** [comment]
Fixed

**Comment by adubovskoy** [comment]
У тебя, если мне память не изменяет, полный доступ к продакшну) Сам мог бы) Хотя ишью лучше все равно писать - чтоб все отслеживали кто что изменяет.

**Comment by xandeadx** [comment]
Вдруг оно там по чьей-то задумке. Я ишью не мониторю.

**Comment by Niklan** [comment]
Пишите сюда https://github.com/Niklan/Dru.io/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B9-2015 что изменилось вот и всё.
