### ISSUE TITLE
Ссылки на большие картинки

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#256]
Пример большой картинки с max-width - http://dru.io/question/3034
Картинка есть, но благодаря ресайзу трудно рассмотреть.
Можно либо на клиенте обходить картинки и оборачивать большие в ссылки, либо на сервере оборачивать все картинки в ссылки.

**Comment by fortis** [comment]
сделано, ужатые картинки (в контенте и комментах)  - оборачиваются лайбоксом на клиенте
