### ISSUE TITLE
Мультиязычность

### ISSUE THREAD

**Issue by tlito** [Niklan/Dru.io#257]
планируется ли на сайте русского сообщества Друпал поддержка мультиязычности?

**Comment by drupby** [comment]
Да нужно добавить белорусский язык. А то без нашай мовы не разумею ўсе пытанні. 
А если серьезно, то какие языки нужны на сайте русскоязычного сообщества drupal?

**Comment by Niklan** [comment]
Не будет. Зачем? Мы позиционируем сообещство как русскоязычное. Большинство, если не все, Белорусы, Украинцы и прочие страны СНГ понимают русский.
