### ISSUE TITLE
Голосуем за формат текста на сайте (Markdown vs HTML)

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#258]
Оставляйте свои предпочтения в комментах этого ишью. Через неделю посчитаем.

**Comment by Niklan** [comment]
Не понимаю зачем уже это. Ведь маркдаун прижился, всё приятно выглядит в коде. Клиенты (заказчики) и прочие не технари не будут разбираться с html, он тяжелее воспринимается, в нём легче накосячить, зачем он нужен?

Я считаю HTML лишь усложнит всё чем облегчит. Нет ни одного плюса же. Кому в кайф писать на HTML- пожалуйста, он же работает. Никто не заставляет насильно там маркдаун писать, html также пропускается.

Да и опыт уже крупных сайтов типа stackoverflow, github, bitbucket и прочих - маркдаун повсеместно или его аналоги, но никак не голый html

**Comment by adubovskoy** [comment]
Ну, голосование так и показало.) 30 за маркдаун проитив 6 за html сейчас.

**Comment by xandeadx** [comment]
Да там голосование без защиты от накруток, можно голосовать сколько угодно) Сейчас что-нибудь другое найду

**Comment by xandeadx** [comment]
HTML

**Comment by Niklan** [comment]
?

**Comment by Niklan** [comment]
HTML у нас в сообществе пропускается, тут то жестко маркдаун)

**Comment by adubovskoy** [comment]
можно тут в комментах)

**Comment by xandeadx** [comment]
да, лучше тут

**Comment by Niklan** [comment]
По сути мы обсуждаем убрать маркдаун с сайта или нет. Ибо HTML пашет.

**Comment by adubovskoy** [comment]
не, скорее что ставить дефолтом, я так понял.

я за markdown.

**Comment by Chi-teck** [comment]
HTML

**Comment by Niklan** [comment]
Markdown

**Comment by Niklan** [comment]
Всё же опрос тут в комментах тоже дело такое. Мы обсуждаем сейчас юзабилити для пользователей, а в голосовании тут примут участие кодеры.

**Comment by xandeadx** [comment]
> Ведь маркдаун прижился

За неимением альтернативы

> Клиенты (заказчики) и прочие не технари не будут разбираться с html

Все знают html, никто не знает markdown (даже я).

> Кому в кайф писать на HTML- пожалуйста, он же работает
> Никто не заставляет насильно там маркдаун писать

Редактор вставляет только markdown

> Да и опыт уже крупных сайтов типа stackoverflow, github, bitbucket и прочих - маркдаун повсеместно 

Это явно площадки не для "Клиенты (заказчики) и прочие не технари" о которых ты писал выше :)

**Comment by Niklan** [comment]
> Все знают html, никто не знает markdown (в том числе я).

Он понимается 1 раз попробовав, а для этого там еще BUEdtior стоит. Сомнительно что заказчики знают html) Это редкий случай.

> Редактор вставляет только markdown

Тогда для чего нам HTML если его вставляет редактор? Также и маркдаун вставлят редактор, но выглядит он чище и приятнее.

> Это явно площадки не для "Клиенты (заказчики) и прочие не технари" о которых ты писал выше :)

Это да, но почему бы и нет. Там такие же разрабы как и мы, и выбор пал на маркдаун.

**Comment by xandeadx** [comment]
видишь, даже ты не знаешь markdown, касячишь с цитатами :)

**Comment by Niklan** [comment]
Всего-то ентер забыл наставить :smile:

**Comment by semyondragunov** [comment]
За markdown + не обязательный HTML. (Всё как сейчас).

Сам сначала с непривычки плевался на markdown. Но как показала практика, проще выучить пару конструкций markdown'a, чем писать вереницы HTML.

Сам markdown можно и не знать в принципе, и жить нормально. Ведь blueditor нормально подставляет нужную разметку. И она намного меньше и компактнее, чем HTML, что несомненно плюс.

**Comment by semyondragunov** [comment]
Кстати. Если поставить чистый HTML и визуальный редактор. То у нас явно появится в сообщениях блондинка-стайл с цветными фонами, разными буквами и т.д.

**Comment by drupby** [comment]
+1 за HTML 
Markdown приемлим только для разметки redmy файлов (и прочих .md), для верстки статей и комментов нужен лишь чистый html

**Comment by sandrig** [comment]
Для данного сайта я за Markdown

**Comment by UksusoFF** [comment]
> Кстати. Если поставить чистый HTML и визуальный редактор. То у нас явно появится в сообщениях блондинка-стайл с цветными фонами, разными буквами и т.д.

Ой ладно, с грамотно настроеными фильтрами для CKEditor не будет никаких "блондинка-стайлов".

Я вообще за ббкоды :)

**Comment by i-amdroid** [comment]
Определенно MD. Можно сказать что это уже отраслевой стандарт.
Тем более что, как верно было подмечено, он позволяет вставлять HTML. Правда это могут не все знать, но это легко решается инфой о формате ввода. Короче в точности так, как сделано на stackoverflow.

**Comment by fortis** [comment]
для статей ckeditor
для вопросов, комментариев и ответов md

**Comment by shumod71** [comment]
HTML!

**Comment by Niklan** [comment]
На данынй момент:
- **MD**: 5
- **HTML**: 4

Не понятно как считать голос по типу фортиса и UksusoFF - он вообще за бб коды)

**Comment by Dsc0ne** [comment]
Markdown

**Comment by RedElephantDesign** [comment]
Присоединяюсь к голосованию.
Почему Mark?
1. Если не знаешь ни HTML, ни Mark, то проще освоить Mark.
2. Если знаешь HTML, то пиши на нем - он и так поддерживается фильтром.
Да и вообще, зачем там HTML городить? Есть кнопки на панели редактирования. Мне вообще их за глаза. А HTML слишком уж массивный для написания комментов.

Поэтому я за Mark. +++++
Считайте мой голос за 3 - со мной голосуют 2 дизайнера. Они за Mark тоже.)

**Comment by adubovskoy** [comment]
Ишью закрываю, по результатам голосования будет пока без изменений.
