### ISSUE TITLE
Сделать сортировку комментариев по дате создания

### ISSUE THREAD

**Issue by EvgeniyMukhamedjanov** [Niklan/Dru.io#259]
Сейчас сортируются по дате обновления, поэтому после редактирования комментарий "прыгает" в низ ветки, и смысл обсуждения теряется.

**Comment by xandeadx** [comment]
где-то был issue

**Comment by EvgeniyMukhamedjanov** [comment]
Я видел tlito что-то похожее писал. Но, почему-то, закрыли issue - не смогли воспроизвести. Видимо, не поняли там друг друга.

**Comment by Niklan** [comment]
Он писал об "ошибке" что там сортировка слетала. Комменты перемешивались из-за правок, а не предложение сменить сортировку)
