### ISSUE TITLE
Подсветка ссылок в комментариях

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#26]
В текущей настройке markdown ссылки автоматом не подсвечиваются. Постоянно когда даю ссылку куда-либо, ручками писать <> неудобно. Может markdowneditor включить для комментов?

**Comment by Niklan** [comment]
В смысле BUEditor включить в комментариях? Если да, то я за.

**Comment by adubovskoy** [comment]
да

**Comment by Niklan** [comment]
Готово.
