### ISSUE TITLE
Все ссылки в контенте выводить с target="_blank"

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#260]
Сабж.

**Comment by Niklan** [comment]
Хорошая идея.

**Comment by fortis** [comment]
- сделал

**Comment by xandeadx** [comment]
Теперь "Добавить комментарий" открывается в новом окне
удалить, изменить, ответить - тоже

**Comment by fortis** [comment]
странно вроде предусмотрел, спасибо поправлю

**Comment by fortis** [comment]
fixed

**Comment by xandeadx** [comment]
Ссылки на ники открываются в новом окне.
"Добавить комментарий" по прежнему открывается в новом окне.

**Comment by fortis** [comment]
++ ссылки на внешние ресурсы открывать в новой вкладке
