### ISSUE TITLE
Изменить типы содержимого на сайте.

### ISSUE THREAD

**Issue by Chi-teck** [Niklan/Dru.io#261]
### Исходные данные

В данный момент на сайте в основном используется только один тип содержимого - вопрос (Q&A формат). Есть еще публикации, но они предназначены только для статей.
### Проблема / мотивация

Q&A формат подразумевает создание четко сформулированного вопроса на который можно дать однозначный ответ. Для многих материалов на сайте этот формат не пригоден. Например, [Drupal VS Bitrix](http://dru.io/question/3427) абсолютно не подходит под Q&A формат, потому что вопрос слишком общий. На _stack exchange_ такие вопросы [закрываются](http://drupal.stackexchange.com/help/on-topic).
### Предлагаемое решение
1. Заменить вопросы на что то более общее (публикация или тема форума).
2. Заменить ответы на комментарии.
3. Убрать возможность принимать ответ (accept answer).

**Comment by fortis** [comment]
я бы вопросы оставил как есть, создав для обсуждений отдельный раздел, но не в виде форума на нодах, а сделал бы минимально простую сущность со свойствами и полем таксономии

**Comment by Niklan** [comment]
Я против данного изменения. Так как считаю что проблема далеко не в разделе.

> Например, Drupal VS Bitrix абсолютно не подходит под Q&A

Очень даже подходит. Тут проблема в том что вопрос поставлен некорректно. Прямо говоря, вопроса в заголовке нет. Хотя по сути из текста это самый настоящий вопрос, только задан он должен быть подобным образом: "Чем Drupal лучше/хуже Bitrix?". Суть останется та же, но восприниматься будет иначе.

Проблема кстати тащится почти с самого начала. У людей мало опыта работы с такими площадками, по всей видимости. Либо всякие ответы@mail научили их пользоваться такими сайтами как форумами, где нет никакой внятной модерации и в ответах творится хаос. Я давно за то чтобы при добавлении вопроса человек давал своё согласие что он понимает что он пишет и публикует, чтобы потом без обид удалять неверные вопросы.

Видно даже что в последнее время @xandeadx пишет чтобы вопросы писали внятные. Это еще с drupal.ru тянется. Напишут не пойми что, и сиди гадай чего хотел автор, если они и сами понимают в дальнейшем что спрашивали.

Я жду когда @adubovskoy доделает раздел заказов до хоть какого-то production-ready состояния, я переверстаю тему с нуля и заодно проработаю данный момент в вопросах. Я хорошо это помню.

Лучше, как мне кажется:
- Сделать страницу добавления вопроса по принципу StackOverflow, где четко написано что, зачем и почему, а также что автор создавая вопрос под этим всем подписывается и просто сносить без угрызений совести вопросы которые заданы неверно. Только тут надо будет в трекер чтобы писалось что материал удален и почему. Или просто сниматьс  публикации до тех пор пока не пофиксят свой вопрос.
- Найти штук 5 вопросов заданных грамотно и дать на них ссылки при добавлении как примерны правильно заданных вопросов. Так как старые вопросы мы тереть не будем уже, можно и собрать пару вопросов которые будут яркими примерами как делать НЕ нужно.

> Заменить вопросы на что то более общее (публикация или тема форума).

Публикации есть, там никаких ограничений нет, кроме как не задавать через них вопросы. Форум не нужен, или обозвать это "обсуждение". Будет как список вопросов идти с темами на обсуждение до тех пока автор не закроет тему самоятоетельно или не пройдет какой-то определенный срок. Как issues в данном случае. Это точно никак не относится к разделу вопросов.

> Заменить ответы на комментарии.
> Убрать возможность принимать ответ (accept answer).

Вся суть и идея вопросов и овтетов как функционала теряется, как и удобство использования. Хотят комментов - вон drupal.ru для этого есть. Форумы, комменты что угодно. Мы же от всего этого уходим к более современным вариантам.

**Comment by fortis** [comment]
но у нас сайт сообщества, а не только вопросов-ответов, обсуждения тоже нужны

**Comment by Niklan** [comment]
> но у нас сайт сообщества, а не только вопросов, обсуждения тоже нужны

^

>  Форум не нужен, или обозвать это "обсуждение". Будет как список вопросов идти с темами на обсуждение до тех пока автор не закроет тему самоятоетельно или не пройдет какой-то определенный срок. Как issues в данном случае. 

Т.е. сделать отдельный раздел. Где кто-то может поднять тему обсуждения, а в комментах общаться. При необходимости автор может закрыть и/или сделать чтобы автоматически закрывались после 30 дней простоя. Вывести это общим списком, разве что с категориями как у вопросов, и всё.

В общем это тема раздела для обсуждений. Но никак не изменения раздела вопросов. Он со своей задачей справляется.

**Comment by fortis** [comment]
зачем может понадобиться автоматически закрывать обсуждения? автору закрывать тоже мне кажется лишнее, каких только постов не бывает, это лучше уж на усмотрение сообщества оставлять с привлечением модератора по кнопке

**Comment by Niklan** [comment]
Чтобы не засорять общий список. И сделать сортировку по дате последней активности. Зачем там что-то давнее, можно будет через поиск найти что нужно. Ну это не суть уже.

Суть то в том что это надо отдельным разделом делать. :)

**Comment by fortis** [comment]
ну drupal vs bitrix вечная тема) 
мне было бы интересно попилить, подожду еще идей на этот счет

**Comment by Niklan** [comment]
Ну вот и идея по сути же.

Создать раздел "Обсуждения".
Обсуждение может иметь категории, например как у вопросов.
Все обсуждение в комментах, выводить общим списком с фасетной фильтрацией и всё. Вот и получится раздел для того что не катит на вопрос и в то же время на публикацию.

**Comment by fortis** [comment]
модерацию мы уже где-то тут обсуждали?

**Comment by adubovskoy** [comment]
Вопрос @Chi-teck, видимо, можно перефразировать: "а будет ли место для свободного общения без всяких рамок?". Есть мысли :)
1. Холивары типа "друпал / битрикс" часто провоцируют срач. Оно нам надо?
2. Полезны ли топики типа drupal vs битрикс? Да, есть хорошие ответы. Помогающие продавать, например. И они быстро отфильтрованы рейтингом и вверху. Значит - если делать "обсуждения", то делать и рейтинг к комментариям (https://github.com/Niklan/Dru.io/issues/243).
3. Не справится ли с той же задачкой (время от времени возникающих холиваров или просто "вечных вопросов" типа "как работать с заказчиком") какой-либо чатик типа slack? Там и ограничение истории есть.

**Comment by fortis** [comment]
@adubovskoy 
1. любое обсуждение может спровоцировать это, у нас должна быть культура общения, в отличии от друпалру
2. +
3. у нас ведь сайт сообщества, зачем уводить с него пользователей, которые может еще не готовы задавать конкретные технические вопросы, а только лишь присматриваются. 
По опыту скайп чатов: если ответ не получил сразу или не завязалась дискуссия то про свой вопрос можно забыть, его перекроют другие вопросы и обсуждения.

зачем на друио рамки стека? 
на дорг есть обсуждения, но даже тема Best CMS не скатывается в холивар https://www.drupal.org/node/749240
я вообще-то даже не нашел холиварных топиков (посмотрите может пропустил), думаю их просто нужно удалять без предупреждений

если люди не будут обсуждать здесь то они будут делать это на друпалру, без культуры общения, и он так и останется лицом сообщества. перекошеным)

https://www.drupal.org/forum-posting - к холиварам пункт 10 Ignore flames and rude tones. 
думаю нужно сделать перевод этих правил

**Comment by fortis** [comment]
но по пункту 2 не уверен, орг как-то обходится без рейтинга комментов, да и считаю что комментарии в обсуждениях не должны влиять на общий рейтинг пользователя в положительную сторону

**Comment by adubovskoy** [comment]
> да и считаю что комментарии в обсуждениях не должны влиять на общий рейтинг пользователя в 
> положительную сторону

В идеальном мире) Но - это дает возможность оскорблений в комментах (видел уже). Рейтинг  решит эту проблему автоматически.

**Comment by fortis** [comment]
ну тогда теряется смысл рейтинга основанного на помощи пользователям, если он будет расти от комментариев в дискуссиях, из солидарности других участников.  мне кажется ссылки "пожаловаться" будет достаточно

**Comment by Niklan** [comment]
Рейтингу от комментов можно уменьшить множитель. 1/10 ответа например. Хотя тоже идея не радует) Вот комментам в вопросах - можно. Там порой ответы вылетают)

**Comment by moelius** [comment]
Выдаю мысль.
1) Drupal vs Bitrix - бывает интерестно почитать кому нибудь?- ДА  (когда там есть действительно, что либо почитать)
2) Drupal vs Bitrix - бывает интерестно почитать кому нибудь?- НЕТ  (когда там написана ересь либо задвигается куда либо что либо)

Вопрос кому решать - users VS admins. Блин конечно юзерам. Но не всем, дабы избежать конкуренции фэйк трафика и т.д.
Вопрос как избежать наименьшего трафика на ересь и "продвинуть" полезный материал.
Предложние решения: один checkbox типо <strike>spam</strike>, not interesting, либо как то еще, который может поставить юзер с определенной ролью(кармой,рейтингом или что либо еще). Соответственно идет сортировка по рейтингу поста либо еще чего то. P/S тут должна быть конкретная формула без всяких либо если и т.д. Есть возможность поставить критический минимум при котором пост скроется совсем (Т.е. полный спам).
Сори про роли, кармы и т.д. просто первый issue, что открыл. Незнаю как устроено, но появилось немного времени, что бы помочь. Буду рад помочь если че=)

**Comment by moelius** [comment]
<blockquote>думаю их просто нужно удалять без предупреждений.</blockquote>

Нельзя удалять топики вообще. Кроме естественно запрещенных законодательством и т.д. Их нужно скатывать... Блин я тут подчитал ваши рассуждения про рейтинги и т.д. Если кто то считает, что без рейтинга можно сделать интересный трафик, то поверьте - ошибатесь.
Простая истина - свежее,адекватное,интерестное  вверх, старое,неадекватное,неинтерестное вниз. Без этого будет тот же drupal.ru - вск подряд.

**Comment by fortis** [comment]
интересный трафик в рамках русскоязычного сообщества друпал это какой?

**Comment by Niklan** [comment]
> Без этого будет тот же drupal.ru - вск подряд.

Если не удалять бред который очевидный бред, дубли, или нарушает правила раздела - вот тогда получится drupal.ru. Где ты гуглишь, а тебе 10 страниц с одними и теме же заголовками где все шлют в гугл который засран уже такими посылами в гугл.

**Comment by Chi-teck** [comment]
Ещё один вопрос который не вопрос. http://dru.io/question/3776

**Comment by fortis** [comment]
это должно быть в milestone d8

**Comment by Niklan** [comment]
Надо раздел обсуждений делать. Что-то типа лайт форума.

**Comment by adubovskoy** [comment]
или чатик. еще на кэмпе была рекомендация сделать на главной блок со ссылками на все известные региональные чатики (как на drupal.ua)

**Comment by Niklan** [comment]
Слаку бы нам, с разделами рыжных чатов типа Южный и т.д.
Все же скайп не очень удонбный. Чатй разрастаются, пользоваться становится нереально

**Comment by Niklan** [comment]
@Niklan test ответа через телеграм

**Comment by fortis** [comment]
у нас гиттер уже был и все сидели в скайпе, если заводить слак то нужно распускать скайп чаты, а никто на это не пойдет

**Comment by Niklan** [comment]
@fortis Гиттер не очень удобен. Слак поинтереснее. Понятно что из скайпа никто не уйдет. Но у нас в скайпе много точечных разедлов, но нету одного глобального для всех.

**Comment by fortis** [comment]
зачем кому-то региональные комнаты если есть скайп?

если объединять все сообщества в одном месте, ивенты, фото-отчеты с кафешек и других локальных мероприятий, тогда можно делать единый чат, тогда может и имеет смысл слак, но пока не дозрели до этого, дальше посмотрим

**Comment by Niklan** [comment]
@fortis Согласен что не дозрели. Просто надо думать. В принципе можно мини-форум сделать на сайте для общения. Какие-то разделы и свободное создание топика и комментарии как ответы. Т.е. для обсуждения каких-то более глобальных тем.

**Comment by Chi-teck** [comment]
> Согласен что не дозрели.

А что значит не дозрели? Создать чат займет пару минут. Комнаты не особо нужны (имхо). Нужен один глобальный чат. С правилами и модерацией. К примеру, из нескольких десятков [друпальных IRC каналов](https://www.drupal.org/irc), активность происходит только в трёх. В остальных новые сообщения могут отсутствовать неделями. Чтобы чат был стал популярным, его надо продвигать (ссылки с сайта, блок с трансляций, рассылки и т.д).

Пример друпал чата на гиттере: https://gitter.im/hechoendrupal/DrupalConsole

**Comment by adubovskoy** [comment]
> А что значит не дозрели? Создать чат займет пару минут. Комнаты не особо нужны (имхо). Нужен один глобальный чат. 

у нас просто он уже был недавно. И на gitter'е и на slack'е. Там было пусто. Народ не заходит в места, которые не надоедают нотификацией) Скайп только живее всех живых.

**Comment by Chi-teck** [comment]
> Там было пусто.

Про них мало кто знал.

**Comment by Chi-teck** [comment]
>  Комнаты не особо нужны

Всё таки могут быть полезными для каких то локальных мероприятий (кампы, спринты и т.д.).

**Comment by adubovskoy** [comment]
Что, пришла пора опять попробовать slack?) или, кстати, как вариант -- http://www.ryver.com/

**Comment by Niklan** [comment]
Я за слак, он крут, там можно и комнату для разработки, комнату-флудилку и т.д.

**Comment by adubovskoy** [comment]
почитай описание ryver) http://www.ryver.com/ryver-vs-slack/
слак чем хорош - он знаком уже всем

**Comment by Niklan** [comment]
Прикольно, можно попробовать

**Comment by fortis** [comment]
можно попробовать, есть инициатива по переводам ее можно туда перенести и распустить группу в скайпе, нужны какие то события что б затаскивать туда это верно

**Comment by Chi-teck** [comment]
У слака есть интеграция с Github, Jenkins и т.д. Если ryver тоже это поддерживает то можно попробовать.

**Comment by adubovskoy** [comment]
Обсуждение натолкнуло на мысль https://github.com/dru-io/Dru.io/issues/426 , привяжу ишью.

**Comment by adubovskoy** [comment]
https://gist.github.com/listochkin/c81c198a2b7b044a0dc5#%D0%9F%D0%BE%D1%87%D0%B5%D0%BC%D1%83-gitter

**Comment by adubovskoy** [comment]
Закрываю, пока тестим чат) https://gitter.im/dru-io/Drupal
