### ISSUE TITLE
Вопросы Tlito

### ISSUE THREAD

**Issue by dimmitri** [Niklan/Dru.io#269]
Участник Tlito, наверное, автор половины вопросов на сайте.
От силы 5% его вопросов полезные. Создает вопрос, через пять минут на него отвечает, либо на его вопросы вообще уже никто не отвечает.
Карма у него минусовая.
Можно создать отдельный раздел "Вопросы Tlito" либо исключить его вопросы из rss ленты хотя бы, он буквально везде уже(((
Мне его розовая аватарка скоро начнет сниться в кошмарах.

**Comment by fortis** [comment]
есть и адекватные вопросы, остальное минусуют
