### ISSUE TITLE
Ответы в комментариях

### ISSUE THREAD

**Issue by semyondragunov** [Niklan/Dru.io#27]
В ответах на вопросы можно оставлять коменты, и отвечать на них.

Идея: Выстроить дерево ответов, так как нифига непонятно, кто, что и кому сказал.
Так же уменьшить отступы и чуть изменить диз, чтобы они занимали меньше места.

**Comment by Niklan** [comment]
Дерево в комментариях ненужно. Моё мнение. Будет полнейшая каша и неразбериха.

**Comment by adubovskoy** [comment]
я думаю это можно просто отложить, потом как будут у нас многокилометровые ленты, склонить на dev-сервак, попробовать отступы и посмотреть нужно оно или нет. 
Сейчас не нужно имхо.

**Comment by semyondragunov** [comment]
Отложить можно, так как сейчас не критично. Но думаю станет критично скоро.

Если надо закройте тикет)

**Comment by Niklan** [comment]
Пока закрываю.
