### ISSUE TITLE
Привязывать к вопросу issue/patch

### ISSUE THREAD

**Issue by fortis** [Niklan/Dru.io#270]
если вопрос решен или есть частичные решения на орг то было бы неплохо давать ответ со ссылкой на issue или патч и чтобы они где-то на странице выводились списком все для тех кто зайдет в будущем

**Comment by fortis** [comment]
или без ответа - просто кнопку: добавить issue/patch и там в модальном ссылку вставить

**Comment by fortis** [comment]
#272

**Comment by adubovskoy** [comment]
Надо делать. Еще настроить, чтоб парсился заголовок, мета-теги и еще чтонть полезное и отображалось красиво.

Делать, думаю, правильнее в ответе - часто нужны сопроводительные пояснения к нему.
