### ISSUE TITLE
Что делать с whydrupal

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#274]
Появился топик http://www.drupal.ru/node/125473 . Ценности там уже особо никакой, кроме разве что домена. Надо?

**Comment by fortis** [comment]
я бы скорее пользовался им как методичкой к созданию промо странички, например можно взять какие-то ссылки на статьи хабра, чтобы не искать, награды дополнить к более свежим, инфа на странице с подборкой сайтов может быть интересна если ее дополнить еще и более актуальными сайтами и статистикой. 

а взять проект и возродить у нас сил не хватит, у нас задач намного вперед открыто тут, да и там больше авторское мнение в статьях, скорее как блог.

**Comment by Niklan** [comment]
Нам проще сделать это отдельной страницей с самой важной инфой просто dru.io/why или /whydrupal
А внизу ссылку на этот сайт, если им начнут заниматься.
