### ISSUE TITLE
Сортировка вопросов по дате добавления ответа/комментария

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#28]
сабж

**Comment by adubovskoy** [comment]
только если вид сортировки можно будет переключать (мне например по новым вопросам интересней). и хранить предпочтения пользователя - как ему по дефолту сортировать

**Comment by drupby** [comment]
А почему бы не вынести разную сортировку по вкладкам, как это сделано на тостере http://toster.ru/questions (новые, интересные, без ответа) или же на том же http://drupal.stackexchange.com/, на dropbucket http://dropbucket.org/ аналогично сделано,  хотя там и не вопросы публикуются, но суть та же.

**Comment by SemanticsPRO** [comment]
ага.
А я дублируюсь в #115

**Comment by greeneyesmi** [comment]
Людей и вопросов еще не так много, чтобы по вкладкам раскидывать, хотя идея хорошая.

**Comment by SemanticsPRO** [comment]
Миш, а по-моему, уже вопросов достаточное количество

**Comment by greeneyesmi** [comment]
Ну может быть. Я сам обычно по таким вкладкам не хожу, ленту читаю, но с точки зрения интерфейса это смотрится.

**Comment by greeneyesmi** [comment]
если добавлять вкладку интересные, то или по колличеству комментов считать или дать это на право админа, как в жж, там кто то сидит отбором материалов занимается и добавляет его в категорию живой журнал и они выводятся даже с другим оформлением. смотрится красиво.

**Comment by xandeadx** [comment]
Если не поднимать вопросы, то они умирают буквально за пару дней. Это я считаю неправильно.

**Comment by xandeadx** [comment]
Можно держать вверху списка вопросы без ответов, заданные в течении дня (можно даже как-нибудь их выделить), а дальше по дате ответа/комментария.

**Comment by greeneyesmi** [comment]
можно такие категории по сортировке
![exa](https://cloud.githubusercontent.com/assets/4700845/7215956/9627dd20-e5f5-11e4-9a8c-165ab1f7174b.jpg)

**Comment by Niklan** [comment]
Добавить вьюхи question/unanswered question/answered и вверху у вьюхи просто сделать ссылки в виде табов. Делов то)

**Comment by xandeadx** [comment]
Up.

Ввиду сложной структуры можно добавить вопросу новое поле - "дата последнего действия" и сортировать по нему. Поле обновлять после добавления ответа/комментария.

**Comment by Niklan** [comment]
> Поле обновлять после добавления ответа/комментария.

Почему тогда просто не задействовать $node->updated? Прямо как на stackoerflow. Там собственная правка тоже опять в топ кидает.

**Comment by xandeadx** [comment]
можно так
