### ISSUE TITLE
Выводить число новых ответов/комментариев

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#29]
В списке вопросов у каждого вопроса выводить число новых ответов/комментариев с даты последнего просмотра вопроса

**Comment by Megawing** [comment]
Поясните пжта смысл комментариев к вопросу и к ответу? Не мешают ли они и нужны ли вообще? Есть же вопрос и список ответов к нему и все - насколько я понял такая задумка.

**Comment by xandeadx** [comment]
Это по поводу моего предложения или просто офтоп?

**Comment by adubovskoy** [comment]
оффтоп.
2megawing: они хорошо структурируют вопрос. http://community.drupalife.com/question/165 - пример. Есть разные ответы в разную сторону тянущие дискуссии. Комментарии к ним - уточняют конкретное направление. Будь все в общей ленте - путались бы. А так - будет понятно что обсуждаем. И лучшие ответы и их ветки комментариев будут вверху.

**Comment by Niklan** [comment]
@Megawing порой часть ответа может прозвучать в комментариях. Не редкий случай на сайтах с подобным структурированием (stackoverflow), когда ты находишь ответ, но прямо чего-то не хватает, или еррор мелкий, непонимание, то такие моменты уточняют в комментариях ответа.

P.s. для упоминания автора в комменте на гитхабе можно использовать @ - тогда ему придёт оповещение об ответе.

**Comment by Niklan** [comment]
#19 перекатываемся туда. Всё в одно.
