### ISSUE TITLE
Двухфакторная аутентификация

### ISSUE THREAD

**Issue by RuZniki** [Niklan/Dru.io#292]
Для улучшения безопасности.
Предлагаю использовать контриб модули. 
https://www.drupal.org/project/ga_login
https://www.drupal.org/project/mobile_codes

**Comment by Niklan** [comment]
Что нам защищать то там?

**Comment by RuZniki** [comment]
Аккаунты пользователей.

**Comment by fortis** [comment]
если и делать то опционально, не думаю что так уж много людей будут этим пользоваться.
ведь не удобно, я этим готов пользоваться в операциях с деньгами, и с почтой, а тут комменты и ответы только

**Comment by RuZniki** [comment]
https://www.drupal.org/project/ga_login так и работает. Если пользователь включил tfa, то он сможет авторизоваться только если укажет временный код.

**Comment by fortis** [comment]
вот Николаю принудительно и включим))) и капчу двухфакторную)))

**Comment by fortis** [comment]
можно оставить но приоритет низкий, задач уж очень много
