### ISSUE TITLE
Увеличить кнопки создания материалов

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#295]
Добавить заказ, вопрос, etc, справа вверху. Некоторые не находят.

**Comment by Niklan** [comment]
для кода сделать максимульную ширину 100% и добавить скрол по горизонтали.
Добавить ссылки изменить, удалить, ответить в комменты на вопросы и их ответы.

**Comment by tlito** [comment]
сделать код "вкладочным", чтоб 500 строк кода отображались тока 20 чтобы не крутить и высвечивались все по клику... ну и чтобы длина кода была видна.

**Comment by adubovskoy** [comment]
https://github.com/dru-io/Dru.io/issues/438
