### ISSUE TITLE
Замечания к апдейту, доработки по заказам

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#296]

**Comment by drupby** [comment]
OK, перенесу с dru.io
"А заказчик после выполнения заказа может отметить исполнителя, добавить ему отзыв или поставить оценку?"

На странице "заказы" (/oders) еще бы и статус заказа выводить, ну и фильтры бы в процессе добавить по статусу и бюджету

если статус у заказа отменен, то его можно и не выводить в списке заказов

ну и неплохо бы на странице профиля видеть заказы (можно только чтобы видны были свои заказы в своем профиле)

**Comment by adubovskoy** [comment]
> На странице "заказы" (/oders) еще бы и статус заказа выводить, ну и фильтры бы в процессе 
> добавить по статусу и бюджету

Ок. Фильтры - да.

> ну и неплохо бы на странице профиля видеть заказы

Об этом даже не подумали сначала. Да, хорошая мысль, можно посмотреть кто заказчик по истории.

> "А заказчик после выполнения заказа может отметить исполнителя, добавить ему отзыв или 
> поставить оценку?"

Пока нет. И это очень скользкий вопрос. Надо думать.

**Comment by roman-yakimkin** [comment]
Несколько замечаний.
1. На форме заказа хорошо бы убрать абзац "формат текста", либо русифицировать его, либо поставить по умолчанию какие-нибудь bb-коды, или визуальный редактор. А то у заказчика от этих "англоязычностей" может испортиться настроение.
2. Поле для приложенных файлов назвать не "техническое задание", а как-нибудь более нейтрально. Там ведь может быть не только ТЗ, но более общие файлы. Например, скриншоты того, что не работает.
3. Добавить возможность задавать сроки выполнения.
4. Может быть, в поле бюджет можно валютой выбирать не только рубли, но и  задавать другую валюту (через combobox). Например, кому-то удобнее указывать цену в долларах или еще как.
5. Может быть, как-то задавать тип заказчика для расчетов. Например, один - фрилансер - физлицо, другой - имеет ИП и может работать по безналу, третий - работает через ООО и т.д.

**Comment by drupby** [comment]
По поводу избыточности формы заказа тоже согласен, выбор статуса заказа убрать в select вместо чекбоксов, 
в textarea описание rows="20" (нужно не больше 10)
подсказки по форматированию в двойном экземпляре занимают по  пол экрана (особенно для  Markdown)

**Comment by fortis** [comment]
жму отозваться и ничего не дает ввести, просто добавляет меня.

**Comment by fortis** [comment]
нужна возможность сделать предложение, иначе как заказчик будет выбирать кандидата, не общаться же с каждым, и не по стене из аватарок и циферок. 

он должен почитать и выбрать несколько понравившихся исходя из их писем и рейтинга. на сайт визитку в друпал ру личку заваливают от 20 и больше предложений, если адекватный заказ и пост

**Comment by fortis** [comment]
надо темизировать поле репутация и везде выводить к нему подсказку (иконка вопросика при наведении хинт) где подробно расписать за что дана эта репутация, то есть просто текст о том что это баллы за ответы на вопросы и комментарии.
сейчас это не баллы за выполнение заказов и это важно понимать

**Comment by fortis** [comment]
лично я вижу это с минимумом фишечек, и больше с живым общением.

не надо заказчику показывать ип или ооо (не гарантирует качество), не надо уводить его от оценки конкретного исполнителя в сторону всяких параметров на которые всеравно нельзя опираться в выборе и показывать намекая что они важны для этого. 

рейтинг может быть можно, но с разъяснением за что он его получил

также не надо отдельное поле с бюджетом, чтоб его не заполняли с потолка, потому что в момент отклика маловероятна правдивая оценка.

есть заказчики не в теме, посмотрят циферки и решат что все ок, 
- "это же сайт российского сообщества, ладно отдам деньги антону егорову с рейтингом 9999+" =))

**Comment by fortis** [comment]
и если заказчик будет ориентироваться только на стоимость в откликах, а не на результат общения с потенциальными исполнителями, то могут быть топики с мелочевкой только чтоб собрать отклики - вдруг кто за 500р предложит сделать, обсуждать же не нужно, посмотрел и ок. 

а заказчик пусть сам бюджет указывает если хочет

**Comment by drupby** [comment]
У всех вопросов заголовок "Создание материала Ответ" (на странице вопроса)

**Comment by tlito** [comment]
где есть заказы, всегда будут споры. так что с этой опцией вам надо арбитраж на сайте делать.
пресейв денег для защиты исполнителя. или эти заказы - чисто демонстрационная часть а договоры по контактам?

**Comment by fortis** [comment]
споров не будет, обсуждение подразумевается личное, функционал биржи не предусматривался, сообщество не выступает посредником между заказчиком и исполнителем

**Comment by malikin** [comment]
Неудобно стало выбирать версию и категорию.
![druio](https://cloud.githubusercontent.com/assets/5649312/10185758/415b7cc6-6754-11e5-9a62-c6246be84037.png)

**Comment by xandeadx** [comment]
Без аваторов в комментариях они стали сливаться друг с другом:

![screen_2015-09-30_142243](https://cloud.githubusercontent.com/assets/845389/10191676/cca85f22-677e-11e5-90d1-deb58fcb9817.png)

**Comment by RuZniki** [comment]
На странице вопроса, нет версии Drupal и модулей.

**Comment by vistar** [comment]
В списке вопросов нету фильтра по "Без ответа".

**Comment by drupby** [comment]
У меня в мозиле (41, ubuntu) страница  /orders выглядит
![image](https://cloud.githubusercontent.com/assets/3697814/10194654/a2c37228-6792-11e5-9cbd-20451fae8e11.png)
то же самое и на /events и /post
![image](https://cloud.githubusercontent.com/assets/3697814/10194878/a60adbfa-6793-11e5-827e-dbaa616a4797.png)

**Comment by fortis** [comment]
если зайти в раздел заказы сейчас то он пустой там ничего нет и кнопка добавить заказ не видна, ее надо влево и какое-то сообщение с инструкцией как размещать заказ и что потом будет, как это все устроено. для тех кто не в теме

**Comment by tlito** [comment]
дизайн без картинок тяжело воспринимается. авки надо вернуть или добавить картинки рубрик вопросов для каждого вопроса. стэковерфлов стиль мне не нравится. количество ответов и оценки  в строку лучше  ибо это не так интересно как авка или картинки тем.
и футер слишком большой и мрачный и не нужен он. и плавающие кнопки не добавляйте если думаете. максимум плавающий чат как на тлито

**Comment by fortis** [comment]
по дизайну предлагать нужно макетом =) исходники можем дать, хотя в issues они были

**Comment by drupby** [comment]
В css имеется 

```
a:hover {
  color: #27adff;
}
```

то же бы самое и для a:visited

**Comment by Niklan** [comment]
Многое нафиксил, там для мобилок, сайдбары и вообще минимал вью на лисе.
Там по коммитам если что видно)

**Comment by Niklan** [comment]
Случайно закрыл)

**Comment by dgastudio** [comment]
разрешите высказать свое IMHO, как человеку который долгое время сидит на премиум аккоунтах на фриланс биржах (http://c2n.me/3pihZnw)
1. отметить флажком, это не ответ. 
2. вытекая из этого, нужно внедрить систему комментариев (private comments), для того чтобы я мог ОТВЕТИТЬ человеку, а не отметиться в его топике. Сейчас отвечает 2-3 человека, что будет когда ответов будет 50+? 
3. вытекая из этого, мне НЕ ИНТЕРЕСНО светить свои контактные данные в профиле. Я уже сталкивался с воровстом портфолио и фальшывими аккоунтами.

**Comment by adubovskoy** [comment]
Опущу пока вопрос про личные сообщения - нет мыслей.

> Сейчас отвечает 2-3 человека, что будет когда ответов будет 50+?

Я генерил у себя локально много ответов. Просто будут вверху ребята с рейтингом. Это решит проблему "как перебрать всех", визуально очевидно

> вытекая из этого, мне НЕ ИНТЕРЕСНО светить свои контактные данные в профиле. Я уже сталкивался с воровстом портфолио и фальшывими аккоунтами.

Фальшивые аккаунты тут не заведешь (опять же из-за рейтинга). А вот про светить данные -- да. Надо галочку наверно сделать "показывать только заказчикам при ответе" в профиле. Сделаем отдельный таск? Кто возьмется?

**Comment by dgastudio** [comment]
разгребусь с проектами, сделаю. все 3 пункта. думаю к концу следующей недели
