### ISSUE TITLE
Увеличить скорость работы сайта

### ISSUE THREAD

**Issue by tlito** [Niklan/Dru.io#297]
например github у меня быстрее листает страницы, чем dru.io, быстрее редактируется.
а вот самый быстрый сайт на мой взгляд webtoolkit.eu
конечно, динамика сайта еще не велика, но меня сильно утомляет ожидание открытия страниц.
да и прокрутка страниц тоже, сократите подсказки, сделайте форму задания вопроса компактнее, а комментарии встроенными или подгружаемыми без перелистывания

**Comment by fortis** [comment]
не нашел ни одной страницы которая грузилась бы со всеми ресурсами стилями, картинками, скриптами больше 2х секунд, в среднем 1.5с, под администратором

**Comment by fortis** [comment]
если есть возможность покажите примеры долгих страниц

**Comment by tlito** [comment]
нет примеров, есть субъективное впечатление

**Comment by fortis** [comment]
скприты и стили минимизированы, скрипты перенесены в подвал, визуально страницы быстрее отображаются без скачков, 

медленные нашел, нода мероприятия до попадания в кеш грузится очень долго больше 4-6с, не кешированные вопросы кажется тоже. в остальном все быстро. 

todo:
+expires
+profiler

**Comment by Niklan** [comment]
>  github у меня быстрее листает страницы, чем dru.io

Вы сравнили сервера гитхаба и dru.io конечно же) Со стороны друпала тут всё ок.

>  быстрее редактируется.

Тут многое на аяксе, когда у нас для этого отгружается страница.

> да и прокрутка страниц тоже, сократите подсказки, сделайте форму задания вопроса компактнее, а комментарии встроенными или подгружаемыми без перелистывания

Это не ускорит сайт.
