### ISSUE TITLE
Ник автора выводить в начале его сообщения

### ISSUE THREAD

**Issue by EvgeniyMukhamedjanov** [Niklan/Dru.io#298]
Спасибо за обновление, все супер!
Предлагаю ник автора выводить в начале сообщения. Под сообщениями имею в виду вопросы, комментарии, ответы.

Когда автор снизу - не получается удобно читать обсуждение в комментариях сверху-вниз: при чтении нового сообщения приходится глазами искать его конец и смотреть кто автор. Особенно когда один человек оставляет два комментария подряд: при последовательном чтении не сразу "въезжаешь" что второй коммент - это не ответный комментарий кого-то другого. В качестве примера - любой вопрос с обсуждением в комментах.
Хуже, когда сообщение длиннее экрана. Приходится скроллить до конца коммента, где указан автор. Пример: http://dru.io/question/3799. Сначала я принял ответ drupby как ответ самого автора вопроса и долго не мог понять, так в чем же проблема.

**Comment by drupby** [comment]
А все потому что ориентировались явно на stackexchange, а не на тот же тостер https://toster.ru/q/251312

**Comment by fortis** [comment]
++1 не видно автора а интересно всегда кто пишет

**Comment by Niklan** [comment]
tlito everywhre :dancer:

**Comment by EvgeniyMukhamedjanov** [comment]
> tlito everywhre :dancer:

)))))

if ($tlito) захардкодьте

**Comment by tlito** [comment]
авка нужна для быстрого считывания уже прочитанных вопросов на странице dru.io/question
теперь усложнилось чтение новых вопросов, потому что авки не подсказывают что уже читал а что нет - вот это неудобно. для вашего проекта с начальной почещаемостью и активностью желательно оставить авки чтобы быстрее видеть появление нового вопроса без чтения текста а просто глянув на авку.
авку проще запомнить последнего вопроса чем буквы

**Comment by EvgeniyMukhamedjanov** [comment]
@tlito Поддерживаю. С аватарками и удобнее и смотреть приятнее.
Но рейтинг и ответ тоже убирать не надо. Сразу видно есть ли новые ответы.

**Comment by tlito** [comment]
теперь когда привык цифры ответов и рейтинга помогают взгляду ориентироваться среди новых вопросов. так что авка уже не так нужна, хотя желательна.
зато большие кнопки вверху слишком много места занимают. уже если без авок, то тогда и кнопки надо уменьшить и заголовок сжать
