### ISSUE TITLE
Страница 403 (404)

### ISSUE THREAD

**Issue by drupby** [Niklan/Dru.io#299]
Сейчас для 403 ответа применяется шаблон

```
<section class="content">
  <h3 class="code">403</h3>
  <h4 class="status">Access denied</h4>
  <a href="<?php print $front_page; ?>" class="home"><?php print t('Home'); ?></a>
</section>
```

Выглядит так
![image](https://cloud.githubusercontent.com/assets/3697814/10193969/caa3d85e-678e-11e5-8c15-80f75e0c4012.png)
Туда бы форму входа пользователя, если он не залогинен и навигацию по сайту

Для 404 тоже бы навигацию и форму поиска

**Comment by Niklan** [comment]
Походу классы в препроцессе забыл.

**Comment by drupby** [comment]
Просто если не авторизованный юзер перейдет по кнопке добавить заказ/вопрос/публикацию, то у него не имеется возможности войти/зарегистрироваться

**Comment by drupby** [comment]
Пока у анонимных пользователей при переходе к форме добавления заказов будет выводиться такая страница, много заказов ждать не приходиться

**Comment by Niklan** [comment]
Страницы поправил. На 403 вывел 2 кнопки (авторизация, регистрация)
![image](https://cloud.githubusercontent.com/assets/2356744/10264500/aa545e62-6a26-11e5-855b-3f73add31a7f.png)

**Comment by drupby** [comment]
Пример более "дружелюбного" оформления для 403 http://spark.ru/admin - в данном примере редирект на страницу регистрации и авторизации с параметром destination в случае друпала

**Comment by fortis** [comment]
спарк нравится да, нужно так

**Comment by fortis** [comment]
я возьму остально по теме допилено или еще в процессе?

**Comment by Niklan** [comment]
А что еще по теме. Чтобы темплейты работали правильно я починил. Оформление уже можешь делать какое хочешь.

Темплейты: https://github.com/Niklan/Dru.io/tree/master/sites/all/themes/druio_theme/templates/pages

Их стили:
https://github.com/Niklan/Dru.io/blob/master/sites/all/themes/druio_theme/styles/scss/theme/_status-pages.scss
