### ISSUE TITLE
Раздел: Выставка сайтов

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#3]
_Раздел планируется, тут обсуждается как реализовывать._

**Раздел:** Выставка сайтов.
**Статус:** Запланирован.
**Описание:**
Раздел где каждый желающий может добавить сайт созданный на друпале на оценку окружающим.

**Comment by Samodelkin777** [comment]
Тут можно подумать сразу над привязанным голосованием: Дизайн, Юзабилити, Скорость отдачи и т.д.

**Comment by adubovskoy** [comment]
А чем http://drupalogy.ru/ не угодил? Может просто линк на него?

**Comment by Niklan** [comment]
> А чем http://drupalogy.ru/ не угодил? Может просто линк на него?

Устраивая такое у себя, мы можем позволить пользователям делать свой профиль с портфолио. А также рейтинг его работ учитывать в общем рейтинге пользователя.

И новичкам получается неудобно. Чтобы добавлять свои проекты надо регаться уже на другом сайте.

Также можно к проекту добавить поле связи с проектами друпала. А в проекте выводить случайные сайты из портфолио, где использовались данные проекты. Ну и на странице сайтов фильтровать по конкретному проекту, чтобы посмотреть сайты. Например если хотят посмотреть Panels в действии где-то. Или Panels + Display Suite + Search API.

Можно также мелкую инфу парсить и выводить, ТИц, PR и т.д.

Получается что мы сохраняем экосистему сообщества и всё логически связываем, увеличиваем кол-во полезной и интересной информации.

**Comment by semyondragunov** [comment]
Да, регаться на другом сайте, не очень хочеться.

Ещё советую сделать, автоскрин сайта, как на anseo и в вебмастерках гугла и яши. И причем иногда их обновлять, так как сайты тоже время от времени обновляются.

З.Ы.: На  http://drupalogy.ru/ неадекватные оценки.

**Comment by adubovskoy** [comment]
Я вообще не вижу реальной практической пользы от выставки сайтов в виде "просто каталог". Имеет смысл? Для оценки? Это будет выливаться в "нравится, не нравится", для того чтобы был фактический анализ - нужна вводная информация, это уже кейс.

Имхо лучше чтобы был только формат кейсов - вот сайт, вот рецепты и решения, вот модули и т.п.
Т.е. хочешь повесить сайт показать и начать обсуждение -- дай полезную информацию.

Возможно еще прикрепление к профилю в виде портфолио, но не сводить это в неких единый для сайта каталог и не тратить на это глобальный пункт меню.

**Comment by semyondragunov** [comment]
Да, всё верно.
И правильный вопрос будет: "Или кейс или каталог сайтов?".

Я за кейсы.

**Comment by Niklan** [comment]
Тогда стоит это скорее не "Каталог сайтов" а "Сайты сделанные на Drupal", или около того обозвать.

Просто была идея, парсить в порфтолио сайтов с ТИЦ и свистопердлеки сделать, типа общиц ТИЦ сайтов в нашем каталоге, страниц в индексе сайтов на друпале и т.д. и т.п. Никому не нужны, но потенциальным заказчиком это понравится лол. Хотя это лишь больные фантазии моего мозга.

**Comment by adubovskoy** [comment]
Тогда тут подмена задачи.
Задачу "показать заказчикам друпал и крупные сайты" решает промо-страничка про друпал и несколько (всего несколько, зато оч крутых) примеров сделанных сайтов (drupal.com не устану приводить в пример - нужен просто блок "Работают на Drupal" :)

**Comment by Niklan** [comment]
Да с drupal.com всё ясно, сделаем промо-страничку как drupal.com. Хоть 1 в 1 но на русском, не проблема. Я сверстаю, кто-то переведёт, всё будет в общем.

Что делать с каталогом\выставкой сайтов. Кейсы не будет писать никто, у нас не такое крупное сообщество как drupal.org, даже для их сообщества новые кейсы появляются на так часто. 

Либо мы будем жестко модерировать, и пускать реальные кейсы, с нестандартными проектами, не накликанными в админке, но таких кейсов пару штук в год накопится, либо пускать всех, тогда смысла от кейсов нету и это обычный каталог.

Имхо, каталог какой-то нужен, именно русских сайтов. Мне не раз говорили что не смогли найти примеров сайтов на друпале. Не знаю как они гуглят, но видимо drupalogy не всплывает. Можно вообще рейтинг исключить из каталога.

В общем и целом, на данный момент раздел пока мутный.

**Comment by semyondragunov** [comment]
to, Niklan: А если он разраб а не SEOшник, то откуда тиц? Ну и так далее, по накатаной. Не считаю нужным.

Если будут кейсы, то самые крутые можно привязать ссылками на промо-страницу с фразами мол "Оно пашет на друпал"))).

**Comment by adubovskoy** [comment]
Тогда может пока просто закрыть ишью выставки и кейсов, непонятная и неприоритетная задача, непонятно как делать. Если в постах появится несколько обзоров сайтов (это ж в принципе блоговый формат) - будем думать про кейсы.

**Comment by semyondragunov** [comment]
Наврятли они сами там появяться. Надо б на самом сайте и спросить!

**Comment by Niklan** [comment]
Хорошо, давайте пока данный ишью закроем, если появится идея для реализации, открывайте из закрытых, дабы не терять нить почему отказались ранее.
