### ISSUE TITLE
Ползет верстка меню

### ISSUE THREAD

**Issue by UksusoFF** [Niklan/Dru.io#301]
На мобильном браузере Dolphin менюшка всегда отображается так и ее не возможно скрыть.

![screenshot_2015-09-30-22-41-33](https://cloud.githubusercontent.com/assets/1931442/10203000/b5646d2e-67c4-11e5-920b-2abecdbb7ee5.png)

**Comment by Niklan** [comment]
Строка в js отвечающая за это: https://github.com/Niklan/Dru.io/blob/master/sites/all/themes/druio_theme/js/script.js#L76
Тут сдвиг всего содержимого: https://github.com/Niklan/Dru.io/blob/master/sites/all/themes/druio_theme/styles/scss/theme/_theme.scss#L1319-L1327

Почему-то отсоветует сдвиг для сайдбара. Если кто хочет, можете поправить, там по сути в css все решается на тех строках что скинул.

**Comment by RuZniki** [comment]
![a2543628e05dffa990514d563934f9679835c0e8a7e65a6d887be88c3cca0152](https://cloud.githubusercontent.com/assets/1125080/10220429/117ae58a-6850-11e5-8365-41c7d1221a13.jpg)
У меня в другом браузере такая же беда с меню, плюс фильтры налезают на контент. Я хочу исправить, не знаю как к себе issue прикрепить.

**Comment by UksusoFF** [comment]
Вот еще на мобильном Firefox последней версии пропали галочки "Лучший ответ".

![screenshot_2015-10-02-20-53-50](https://cloud.githubusercontent.com/assets/1931442/10253521/e5fdf76c-694e-11e5-87b2-4f40539a512e.png)

**Comment by Niklan** [comment]
Починил и флаг, и меню, и сайдбар
