### ISSUE TITLE
В ответах и комментариях разные имена

### ISSUE THREAD

**Issue by EvgeniyMukhamedjanov** [Niklan/Dru.io#303]
Захожу через фейсбук.
Когда пишу комментарий - имя "Евгений". (http://dru.io/question/3811)
Когда пишу вопрос или ответ - имя "Evgeniy Muhamedjanov" (http://dru.io/question/3823)
В профиле - "Evgeniy Muhamedjanov".
Надо либо к одному виду все привести либо дать возможность задавать имя.

**Comment by Niklan** [comment]
> Надо либо к одному виду все привести либо дать возможность задавать имя.

Такое вроде имеется при регистрации первоначальной и присоединении. Хотя да, странно почему так пляшет. Берет же из $user->name

**Comment by EvgeniyMukhamedjanov** [comment]
Раньше, помню, в ответах, вопросах, комментариях было "Евгений" - имя, которое указал при первом входе, но на странице профиля всегда было "Evgeniy Muhamedjanov". Это, видимо имя, которое фейсбук возвращает.
А сейчас и вне профиля разные имена пошли.

**Comment by Niklan** [comment]
Исправлено в апдейте с комментами
