### ISSUE TITLE
К чему вообще минусование?

### ISSUE THREAD

**Issue by vistar** [Niklan/Dru.io#304]
Предлагаю избавиться от минусов, оставить только возможность увеличения.
Ни к чему хорошему не приводит наличие и возможность залепить кому-то минус, кмк.

**Comment by EvgeniyMukhamedjanov** [comment]
Частично поддерживаю. Считаю, что если человек дал ответ, пытался помочь, рейтинг ответа не должен отпускаться ниже нуля. Пусть более точные ответы плюсуются и выйдут в топ.

Но минус нужен, чтобы пользователь мог понизить рейтинг заплюсованного ответа,  если считает его неверным.

**Comment by Niklan** [comment]
> Считаю, что если человек дал ответ, пытался помочь, рейтинг ответа не должен отпускаться ниже нуля.

А если человек бред пишет? Т.е. сейчас хоть есть мотивация не писать бред в ответах, если её не будет, все будут от балды на угад давать советы и в этом будет сложнее разбираться.

Также минус используется для сортировки ответов. Если ниже 0 не будет опускаться, получается реально адекватные ответы будут идти в перемешку с бредом?

Минусы хорошая мотивация подумать перед тем чтобы написать и что написать. У нас так яро не минусуют.

**Comment by fortis** [comment]
думаю что нам нужно ввести ограничение на право минусовать. чтобы это могли делать только люди с каким-то минимальным рейтингом, на стеке примерно так же. тогда не будет минусов от балды

**Comment by fortis** [comment]
например с рейтом от 20, это примерно тот порог когда человек уже достаточно помог другим и знает что не так уж просто дать хороший ответ или задать правильно вопрос

**Comment by fortis** [comment]
ну и вполне можно ввести ограничение на плюсы, уже сложилась аудитория с рейтингом, которая вытянет других на право плюсовать-минусовать, адекватных)

**Comment by Niklan** [comment]
@fortis хорошая идея. С плюсами тоже, кстати, и стаке такое ограничение вроде имеется, на минусы точно.

**Comment by fortis** [comment]
если будем вводить то одновременно с этим функционалом надо объявить амнистию заминусованым и обнулить им рейт иначе они долго будут оттуда выбираться из-за минусов от балды :) хотя надо посмотреть

**Comment by EvgeniyMukhamedjanov** [comment]
> объявить амнистию заминусованым

А что, есть заминусованные ребята кроме tlito? :-)

**Comment by Chi-teck** [comment]
На некоторых сайтах за то чтобы поставить минус надо потратить свои плюсы (рейтинг).

**Comment by vistar** [comment]
На том же тостере минусов нет, и живут.

> А если человек бред пишет? Т.е. сейчас хоть есть мотивация не писать бред в ответах, если её не будет, все будут от балды на угад давать советы и в этом будет сложнее разбираться.

Пусть автор вопроса сам решает, чей бред лучше.

Та стеке и минусовать и плюсовать можно после определённого количества репутации.

Цель dru.io какая? Сделать копию стека или тостера или ещё чего-то? Или сделать нечто своё, и показать всем как мы можем дружно себе площадку напилить?

Так же нужно ограничение на количество минусов в единицу времени тогда уж. Да и много их ещё нужно в таком случае, лучше вообще убрать минусы. А через некоторое время ответы с низким рейтингом затенять.

Я считаю, что минусы не идут на пользу сообществу. Тот же стек - это не узкое сообщество. У нас может быть такое: кто-то на кого-то обиделся и пошёл минусовать товарища.

**Comment by tlito** [comment]
минусы это хорошо. осталось только понять кто так активно меня заминусовал и понять причину. я например не понял о чем говорят минусы (для профиля тлито)

**Comment by fortis** [comment]
@tlito посмотрел вопросы, и комментарии. думаю скорее дело в вопросах, к примеру правильно сформулированный вопрос http://dru.io/question/3658 получил ответы и без минусов.

и вот такой http://dru.io/question/3570 - трудно на него ответить потому что недостаточно информации и вряд ли кто-то будет специально скачивать тему что бы помочь, следовало бы привести хотя бы скриншоты того что есть и как надо сделать, ответы у вас с плюсами в основном

**Comment by fortis** [comment]
к тому же часть вопросов довольно простые и сопровождаются ссылкой на ваш блог, например http://dru.io/question/3264
думаю это может не нравиться другим участникам так как похоже больше на пиар своего ресурса

**Comment by fortis** [comment]
если вопрос простой то пишите решения которые пробовали и что не получилось, тогда будет больше желания помочь

**Comment by Niklan** [comment]
> вопрос http://dru.io/question/3658 получил ответы и без минусов.

Тоже ответил, для себя чтобы не забыть потом и если гуглить буду :)

**Comment by UksusoFF** [comment]
> минусы это хорошо. осталось только понять кто так активно меня заминусовал и понять причину. я например не понял о чем говорят минусы (для профиля тлито)

Потому что половина ваших вопросов - поток сознания, который кроме вас никто не может понять.
Потому что ответы ваши порой very bad practice.

https://github.com/Niklan/Dru.io/issues/297 тому пример, как вообще компактность формы влияет на "скорость работы сайта"?

**Comment by orion76** [comment]
ИМХО минусы нужны, возможно надо просто доработать "формулу" учета оценок.
Я правильно понимаю, что все оценки вопроса-ответа идут в "карму" пользователя?
В разрезе одного вопроса-ответа, я думаю, кол-во положительных-отрицательных оценок важно.
А нужно ли оно в карме пользователя?
Может просто за положительную оценку +1, за отрицательную соответственно -1?

**Comment by UksusoFF** [comment]
Я тут заметил что вопросы tlito с тостера вообще выпиливают.
Может есть смысл вопросы сильно ушедшие в минус 10 например удалять? Или скрывать?

**Comment by fortis** [comment]
я пока смотрю на них как на то, что вполне может пригодиться новичкам, у них как раз по началу очень много вопросов, а потом все сходит больше в самостоятельные решения, я бы понаблюдал пока. 

если вопрос стандартный и есть куда ткнуть то надо давать ссылки на поиск, если вопрос не ясен то сразу писать что ничего не понятно, дальше автор сам пусть решает нужен ему ответ и будет ли он уточнять

собственно минусы как раз накидывают когда вопрос не ясен, лучше было бы если б написали, введем порог голосования и правила распишем

**Comment by EvgeniyMukhamedjanov** [comment]
> думаю что нам нужно ввести ограничение на право минусовать. чтобы это могли делать только люди с каким-то минимальным рейтингом

Тоже поддерживаю. Хорошая идея. Получил плюс за ответ, потом минус за тот же ответ. Стал подозревать, что другой ответивший "влепил" минус, чтобы оказаться выше моего ответа. Стало интересно - неужели такое может быть. Не поленился: скачал базу, проверил. :-) Теория подтвердилась. Заодно нашел еще минусик в другом ответе. Причем, минусовали явно не за низкое качество моих ответов.

**Comment by fortis** [comment]
++ чистить флаги в дампе))

**Comment by EvgeniyMukhamedjanov** [comment]
> ++ чистить флаги в дампе))

:-))) 
Зачем? Надо же как-то выявлять минусовщиков. Хотя, как сказал Никлан, особо не минусуют. На 100 ответов нашел три минуса
Зато приятно было узнать, что получал плюсики от уважаемых гуру друпала. :-)

**Comment by orion76** [comment]
Вообще-то да... Ставить минус просто за вопрос, имхо не правильно.
Логично минус ставить за некое умышленное действие, например нарушение правил ресурса, с указанием - что нарушено.
А ставить "новичку" минус, из-за того что он пока не "в теме", мягко говоря, странно.

Ставить минус за ответ, наверное правильно..
Ответ - это уже более "умышленное" действие..

Но всеже я за разделение рейтингов.. 
Смешивание теплого с мягким не точно отражает действительность..

**Comment by Niklan** [comment]
> А ставить "новичку" минус, из-за того что он пока не "в теме", мягко говоря, странно.

Если вопрос задан корректно, новичку либо дают ссылки на решение, либо ответ. Никто не минусует практически за простые вопросы. Это как минимум глупо. А вот если вопрос уже повторяющийся, когда уже давали на это ответ, то да, за то что не поискал могут и минусов налепить.

Надо, как говорилось, ввести минимальный порог для использования рейтинга и сделать страницу добавления вопроса кастомной, с пояснениями как правильно задавать и как не надо, не забыв указать ссылки на примеры по каждому разделу (правильно и не правильно) и накатить поиск по вопросам при вводе вопроса в заголовок. Глядишь это сильно поможет.

Считаю что минусы у вопроса убирать тоже не стоит. Иначе безнаказанность заставит задавать вопрос на каждый чих, они засрут всю ленту, или задолбают модераторов сносить это всё. Поэтому прежде чем задавать вопрос подумают и попробуют найти.

tlito же минисуют не за нубские вопросы, а за то что он их задает в большинстве своём совершенно некорректно. Вообще не ясно порой чего он хочет спросить, вот и лепят минусы. Или порой откровенно глупые вопросы, которые по сути к друпалу то и отношения не имеют или заданы не верено.

**Comment by UksusoFF** [comment]
> tlito же минисуют не за нубские вопросы, а за то что он их задает в большинстве своём совершенно некорректно.

И за то что дает ответы не соответсвующие действиетльности, с полной уверенностью что он прав.

**Comment by Niklan** [comment]
Ну так тут ничего не спасет. Для того и минусы. Никого же также не минусуют

**Comment by adubovskoy** [comment]
И в целом это все работает -- посмотрите, качество контента и общения на голову выше друпалру.

**Comment by Niklan** [comment]
Ишью изжило себя, закрываю.

Выводы сделаны, дальнейшее обсуждениее более конкретное будет в ишьюсе #315
