### ISSUE TITLE
Письма от комунити

### ISSUE THREAD

**Issue by SemanticsPRO** [Niklan/Dru.io#306]
Внешний вид писем от сервиса - ужасен.
Во-первых, оттуда надо убрать drupalife, я считаю.
Во-вторых, запилить переносы строк, а лушче - хтмл формат
![testo dru io - 8278231 gmail com - gmail 2015-10-01 21-02-38](https://cloud.githubusercontent.com/assets/1708410/10229252/d3d33fd6-687f-11e5-9926-81ba9f4788d1.png)

**Comment by Niklan** [comment]
Теперь уходят от no-reply@dru.io

Немного приоформил.
![image](https://cloud.githubusercontent.com/assets/2356744/10264238/6812a7ae-6a1f-11e5-84fa-5165ef84e971.png)
