### ISSUE TITLE
За что бы взяться?

### ISSUE THREAD

**Issue by orion76** [Niklan/Dru.io#309]
Может я сходу не нашел.. Тогда извиняюсь..
Где можно посмотреть, какие работы в данный момент ведуться по развитию dru.io, какие работы планируются и т.п.
Хотелось бы тоже приобщиться, но чтоб не в холостую, а с пользой..

Вроде уже 21 форк, а что там твориться?
Может нет смысла что-то свое "мутить" ,а помочь кому?

Короче без координации никуда-)

**Comment by Niklan** [comment]
21 форк в по факту активно мало кто пилит.

Смотришь ишьсы. Если нету Assignee, пиши что забрал - пили. Если есть, но уже прошло нмого времени, спроси делаются ли работы и тот кто забрал скажет пилить или нет.
