### ISSUE TITLE
Изменение комментария переписывает дату

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#31]
Итого - http://community.drupalife.com/question/246#comment-245 . 
Т.е. написал коммент, получил ответный коммент, решил в своем комменте ссылку сделать кликабельной -> получил свой коммент ниже чем ответ.

**Comment by Niklan** [comment]
Не смог его воспроизвести.  Отредактировал - дата осталась прежней.

**Comment by fortis** [comment]
тоже не удалось воспроизвести
но отвечал сам себе

**Comment by Niklan** [comment]
Ошибка так и не всплыла. Закрываю, если повторится, переоткроем.
