### ISSUE TITLE
Редактирование страницы профиля

### ISSUE THREAD

**Issue by UksusoFF** [Niklan/Dru.io#311]
Имхо лучше убрать подсказки и сделать как в форме ответа.
Плюс зачем тут выводить рейтинг? Я что могу его редактировать?

![default](https://cloud.githubusercontent.com/assets/1931442/10268500/a7039688-6acb-11e5-9614-e2a427fd04b7.png)

**Comment by UksusoFF** [comment]
А тулбар? :)

**Comment by Niklan** [comment]
Не понял вопроса.

**Comment by UksusoFF** [comment]
Я о BUEditor для вставки разметки, его там нет :)

**Comment by fortis** [comment]
нужен пусть парни верстают)))

**Comment by UksusoFF** [comment]
Вот тут кстати еще вылазиет, может есть смысл поалтерить все формы, а не каждую по отдельности?
http://dru.io/comment/reply/3858#comment-form

**Comment by Niklan** [comment]
Так кидайте где нашли. За всем сразу не уследить
