### ISSUE TITLE
word-break заголовкам

### ISSUE THREAD

**Issue by fortis** [Niklan/Dru.io#312]
<code>    word-break: break-all;</code>
![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_41174/489h1SZREL5EfGdZvT341oyeWJhTmT/q1jae05101424.png?Expires=1444130711&Signature=biMzq9kSLjwDiLG0Iug8d50aKZtwfxmq5vKCRyYF5XUnzDe7MNPFmKR0TPtbIZqK-yOB~heN~K-NkCSKTlu5y0m4HNPt4nXPrOLReuwopf~QmksO2JmMqa~VN7rDCcu9UVifsBCuRjQMPgvTuiv3vn99ZJW2NNsnCiN2Dby4LG8XRrl85dmTJKAGon7uHLWaQ7LrDILMD0T4k69hVV2eLGHWtlloYSRqfuwEdoN9B77KOKdg3sQ~PSpqP5x1hUO4UFwrDkvqRXVhrxXW5pqKhSj7PGs57VSuNTY9B6Q5Gcc4Ei9aUy0VOrJZHOhYqCPPPXemyNNi6i0Avx7mdfyE3w__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by Niklan** [comment]
да, тоже собирался чинить этот бред. Особенно он заметен на мобилках. И сиду по всему таких заголовков после rc1 у Drupal 8 будет много :smile:
