### ISSUE TITLE
links на странице ответа на комментарий

### ISSUE THREAD

**Issue by drupby** [Niklan/Dru.io#314]
links на странице ответа на комментарий (пример http://dru.io/comment/reply/3943/4507) не совсем inline
![image](https://cloud.githubusercontent.com/assets/3697814/10317082/5cdc4b08-6c6b-11e5-931a-19e9cd980dc1.png)

**Comment by Niklan** [comment]
Сделал оформление комментов для ответов и вопросов как просили "Как на тостере".
Как руки доберутся, поправлю всё и подальше, если никто не сделает до меня.
