### ISSUE TITLE
Поставить ограничение на использование рейтинга

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#315]
#304 - к такому решению мы пришли обсуждая минусы на сайте.

Возможность голосования необходимо ограничить минимальным рейтингом. Пул пользователей с рейтингом уже имеется, так что вполне безопасно и безболезненно можно ввести.

Какие преимущества:
- Ставить +/- смогут только те, у кого рейтинг достинг N отметки. Для всех у кого рейтинг, доступ к голосванию будет заблокирован. Но больше никаких ограничений.
- Это предотвратит массовое создание аккаунтов и скручивание рейтинга в плюс или минус. Чтобы таким заниматься, придется реально помогать пользователям. Будет очень затратно по времени и не оправдано. 
- Предполагается что юзер, достигший рейтинга N уже проявил себя как полезный для сообщества человек и минусовать необдуманно не будет, также как и специально поднимать кому-то рейтинг.

Из обсуждения пришли к решению что оптимальным значением для N на данном этапе развития сообщества будет 20.

Ишью оставляю на обсуждение этого числа N, а также, стоит ли запрещать людям не достигшим рейтинга N блокировать возможность давать положительный рейтинг? Т.е. блокировать минусование будем 100%, а вот плюсование?

Как по мне, тоже стоит, чтобы рейтинги себе не накручивали и не было проще достичь того самого рейтинга в 20.

**Comment by UksusoFF** [comment]
> Т.е. блокировать минусование будем 100%, а вот плюсование?

Конечно.

**Comment by drupby** [comment]
Значит нужно правила писать и ссылку на них выводить, чтобы потом не возникало вопросов.
А ограничивать нужно и в up и в down.

**Comment by Niklan** [comment]
Сделал ограничение. Люди с рейтингом < 20 не смогут голосовать. Будет выдаваться сообщение об этом.

Если кто знает как можно улучшить этот запрет или найдете ошибки, переоткрывайте или ишьюс новый делайте. В идеале бы как-то Ajax запросу Rate отдавать Message
