### ISSUE TITLE
Верстка блоков в профиле пользователя

### ISSUE THREAD

**Issue by UksusoFF** [Niklan/Dru.io#316]
Хорошо бы их переносить и делать на всю ширину.

![screenshot_2015-10-06-19-17-59](https://cloud.githubusercontent.com/assets/1931442/10317734/f46e96be-6c76-11e5-804c-e2b05b017628.png)

**Comment by Niklan** [comment]
Честно говоря я не понимаю как они туда выводятся.
Я вижу 2 поля в отображении, я вижу 2 вьюса, но я не понимаю как они связаны. Поле не с кодом, вообще не ясно :) Подожем пока @adubovskoy расскажет как оно там подключено и я переделаю.

**Comment by drupby** [comment]
На данный момент вьюхи выводятся с помощью ds, нужно просто для group-left и group-right определить медиа запросами ширину при которой они будут в одну колонку.

**Comment by Niklan** [comment]
То что DS там понятно. 2 кастомных поля созданные в админке. Но как они связаны с вьюсами это тоже вопрос. А вообще надо взяться и перепелить страницу профиля.

**Comment by adubovskoy** [comment]
Это просто dynamic field у DS. Просто group-left/right, правильно написали. помечу на себя.

**Comment by Niklan** [comment]
@adubovskoy это то да. Но где ты указывешь в динамическом поле какие вьюсы тянуть?

**Comment by adubovskoy** [comment]
в настройках отображения есть.

**Comment by adubovskoy** [comment]
https://qsnapnet.com/snaps/zv5q8bd6lbbotj4

**Comment by Niklan** [comment]
:cool:  :+1:
