### ISSUE TITLE
Ссылка-якорь на комментарий не везде

### ISSUE THREAD

**Issue by vistar** [Niklan/Dru.io#318]
Не хватает её, чтобы сразу на комментарий давать ссылку.
Как на d.org: http://i.imgur.com/q1A8PFO.png

**Comment by Niklan** [comment]
Есть
![image](https://cloud.githubusercontent.com/assets/2356744/10370157/1fe3e610-6df7-11e5-952a-7a5734d9844e.png)

**Comment by vistar** [comment]
Хорошо, дополню: не везде.

В публикациях нет, на ответ тоже нет. В комментах к ответу эту ссылку выделить надо как-то - а то не сразу понятно.
