### ISSUE TITLE
Оповещение о комментариях

### ISSUE THREAD

**Issue by vistar** [Niklan/Dru.io#319]
В трекере не было - оказалось мне оставили комментарий к ответу.

В профиле тоже не отображаются. Возможно стоит сделать, чтобы владелец профиля только видел.

**Comment by drupby** [comment]
Оповещения на email нужны - можно задействовать mandrill

**Comment by Niklan** [comment]
mandrill уже зайдействован. Надо как-то помечать что человек хочет получать комменты. Стоит ли такую пометку делать глобально?

**Comment by drupby** [comment]
Так тут два варианта - либо в профиле выбирать либо непосредственно в вопросе

**Comment by Niklan** [comment]
Я тоже ко второму больше скланаюсь. Сделать флаг "подписка" и высылать в таком случае.

**Comment by drupby** [comment]
Флаг будет относится к вопросу, письма слать при добавлении ответов и комментов к ним?

**Comment by Niklan** [comment]
Да, почему бы и нет. Отследить не сложно.

**Comment by vistar** [comment]
Почему только почту? Вы обсуждением ушли в сторону #170 забыли, забили?

Этот issue конкретно про то, что комментов нет нигде следа - ни в профиле, ни в трекере.

**Comment by Niklan** [comment]
Никто не забыл. Для этого и надо сделать флаг "подписка".

Далее в профиле сделать вариант оповещения на выбор, чтобы можно было дополнять. Очевидно просто что первым делом появится оповещение на почту. Потом я могу сходу сделать на pushbullet. А дальше уже по требованию.

**Comment by tlito** [comment]
после удаления моей публикации на английском у меня в трекере остались оповещения которые  не прочитал - комментарии под этой статьёй - но прочитать невозможно, и трекер все время со значком новых уведомлений.

**Comment by fortis** [comment]
фейл)) надо вьюху подправить да

**Comment by fortis** [comment]
подписаться на оповещения можно ссылкой Follow как на орге, не обязательно участвовать чтобы интересоваться тредом

**Comment by drupby** [comment]
@tlito "после удаления моей публикации на английском" - вот смысла в той публикации я так и не понял, зачем?

**Comment by tlito** [comment]
я учусь писать на английском. а сайту возможно будут отдавать предпочтение и зарубежные друпалеры

**Comment by drupby** [comment]
@tlito в случае с dru.io (вроде как - русскоязычное сообщество Drupal) лучше делай переводы англоязычных статей - тебя только поблагодарят, ну и улучшишь в любом случае свой скилл в английском.
