### ISSUE TITLE
Информация в профиле (Соц.профиль)

### ISSUE THREAD

**Issue by fortis** [Niklan/Dru.io#32]
Что если дать возможность подключать к аккаунту ссылки на 
- Facebook
- Vkontakte
- Twitter
- Github
- другие

Кроме того выводить такую информацию (поштучно подключается по желанию):
- активность на гитхабе (колличество коммитов, дата последнего коммита)
- активность на друпал орг (коммиты, мейнтейнерство)

как менее значимые можно рассмотреть:
- возможность подключать отзывы FL.ru (количество хороших-плохих и ссылку на страницу отзывов)
- BL Webmoney и наличие претензий/отзывов (BL 75 - 50/1)

**Comment by UksusoFF** [comment]
Еще материалы и вопросы пользователя не помешали бы. Как минимум хотя бы свои чтобы видно было.

**Comment by Niklan** [comment]
Да, будут, в трекере. А общие может тоже будут, как было предложено в #64

**Comment by Niklan** [comment]
Эту задачу по сути уже растащили на множество других. Профиль базово сделан. Теперь дело за **конкретным** улучшением.
