### ISSUE TITLE
Выводить список пользователей оценивших пост

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#322]
Предлагаю по наведению (или по клику) на текущий рейтинг вопроса/ответа выводить список оценивших юзеров

**Comment by fortis** [comment]
и домашний адрес)

**Comment by Niklan** [comment]
Просто список всех кто жал, или только плюсы? Зачем это? Отслеживать что ли кого-то?) Или просто для "любопытства" любого

**Comment by xandeadx** [comment]
Всех. Видеть кто за, кто против

**Comment by drupby** [comment]
@xandeadx "Всех. Видеть кто за, кто против" - приведи пример сайта с подобной реализацией
Есть бд в открытом доступе, кто захочет сможет посмотреть.

**Comment by Niklan** [comment]
Мне честно говоря идейка не очень нравится, но я и не против неё.

Просто есть подозрения если будем выводить кто кого минусует/плюсует начнется взаимное плюсовение/минусование.

**Comment by drupby** [comment]
Да просто ограничить голосование пользователям с raiting < X

**Comment by Niklan** [comment]
Уже #315 

По теме. Давайте подождем еще мнений. Я нейтрально отношусь к ней. 1 точно ЗА, @drupby я тоже не понял, нейтрально?

**Comment by xandeadx** [comment]
@drupby вконтакте, фейсбук, дискус

**Comment by xandeadx** [comment]
> Просто есть подозрения если будем выводить кто кого минусует/плюсует начнется взаимное плюсовение/минусование.

сделать хотя бы для модеров, чтобы неадекватов вычислять

**Comment by drupby** [comment]
Для модераторов можно сделать вьюху-страницу с выводом вопросов и ответов и юзеров проголосовавших связями подтягивать
А вообще первоочередно сделать " просто ограничить голосование пользователям с raiting < X" #315

**Comment by Niklan** [comment]
@drupby #315 уже сделан и на продакшене. См. ласт коммит :)

**Comment by fortis** [comment]
"за" если для модеров

**Comment by ttenz** [comment]
думаю здесь нужно исходить от причины почему человек захотел посмотреть кто оценил его пост/публикацию, обычно причина определит кто враг, кто друг. поэтому лично против данной инициативы. думаю достаточно будет знать, что если и заминусовали, то люди с определенным N весом.

**Comment by grebennikovf** [comment]
Мне ка

**Comment by uxpromo** [comment]
"за" если для модеров.
Иначе можно наткнуться на неуловимых мстителей, вовлекающих всех вокруг в "сливание кармы". 
Например: заходит человек XXX, задаёт откровенно тупой вопрос. Пользователь YYY ставит минус. XXX  видит, что его минусанули и искрене обижается, находя посты YYY и расставляя всем подряд минусы

**Comment by tlito** [comment]
это сложно. проще в чате спросить. сделайте чат и не надо нагружать страницы вопросов.

**Comment by Niklan** [comment]
Что сложного то, 1 запросом дернуть id юзеров и вывести их имена?

**Comment by tlito** [comment]
у вас сайт уже нагружен и работает медленно. сравните скорость перелистывания stihi.ru
у вас раза в 4 медленнее

**Comment by Niklan** [comment]
И чем 1 запрос, который выолнится за 0.1ms увеличит нагрузку на сайт? 
Тормозит он далеко не из-за этого, а из-за того что сервак нагружен другими сайтами и он не мощный. 

То что вы привели в пример, скорее всего отдает статику, если мы включим boost, у  нас все будет работать точно также. Под анонимом у нас точно также шустро пашет.

Это все равно если бы я вам сказал:

> у вас сайт (stihi.ru) уже нагружен и работает медленно. сравните скорость перелистывания google.ru

Понимаете к чему я такую аналогию привел? :smile: 

В данном случае этот запрос не сыграет НИКАКОЙ роли на скорости, тем более, сказали же, показывать модераторам. У юзера ничего происходить не будет.
