### ISSUE TITLE
Трекер

### ISSUE THREAD

**Issue by vistar** [Niklan/Dru.io#323]
Не понятно, почему из трекера удаляются старые извещения?
Почему нельзя их все оставлять, как историю, а удалять по желанию?

**Comment by Niklan** [comment]
Потому что он для оповещений а не для складирования по принципу drupal.ru. см. трекер github.

Где вы поучаствовали есть в вашем профиле.

**Comment by vistar** [comment]
Тогда переименуйте - не трекер, а извещатель.
Потому что трекер, это именно отслеживание.

Но мне удобнее, именно трекер - когда вся история хранится. Да д.ру немного логичнее в этом плане, давайте совмещать как-то, несовмещаемое.

**Comment by drupby** [comment]
> Потому что он для оповещений а не для складирования по принципу drupal.ru. см. трекер github.

На гитхабе это notifications, хотя на хабре аналогично трекер, только в боковой панели
![image](https://cloud.githubusercontent.com/assets/3697814/10514679/dffc7966-7357-11e5-8294-e6af3455a594.png)

**Comment by SemanticsPRO** [comment]
+
Я тоже за трекер со старыми материалами.
Во-первых, все привыкли.
Во-вторых, что мне делать если я хочу к просмотренному вопросу/публикации вернуться?

**Comment by fortis** [comment]
ПЛЮС ++++ за норм трекер

а оповещения это почта и пушбулет

**Comment by vistar** [comment]
> Где вы поучаствовали есть в вашем профиле.

Оповещения о комментариях не нашёл ни в профиле ни в трекере.

**Comment by malikin** [comment]
Имхо нужен трекер где можно отследить обновлённые материалы. Для меня идеал linux.org.ru. есть и уведомления и трекер.

**Comment by SemanticsPRO** [comment]
@SoraTM можешь скринов наделать и парочку комментариев по их логике дать?

**Comment by malikin** [comment]
Так логика простая:
1. Кнопка "Трекер" - просто показаны все обновленные материалы с новыми комментариями, т.е. даже столетняя тема может вылезть если новый комментарий кто-то оставил
2. Кнопка "Уведомления" - появляются ответы в ваших темах или ответы на ваш коммент в других темах.
![default](https://cloud.githubusercontent.com/assets/5649312/11028991/c6cc9562-86d4-11e5-95a4-6b470e29055b.png)
![default](https://cloud.githubusercontent.com/assets/5649312/11028990/c6cc56b0-86d4-11e5-954e-fc95bf0d28a3.png)
