### ISSUE TITLE
Как переносить изменения в базу?

### ISSUE THREAD

**Issue by vistar** [Niklan/Dru.io#324]
Понятно, что Д7 не рассчитан для этого, но!
Фичами, экпортами, мануалами как я это сделал?

В инструкции ни слова про это :8ball:

**Comment by Niklan** [comment]
С этим у нас жопа. Переносим руками. 

Что именно хочется перенести? Можно конечно фичу сделать и положить в /sites/all/modules/features (не следовать фичи events которая). Назвать druio_feature_NAME и собственно прислать с пул реквестом.

Возможно я утащу на дев, посмотрю что делает, и если не критично и быстро проделаю на продакшене руками чтобы откинуть фичу. А вообще это походу единственный выход в нашем случае если нет доступа к админке. Поэтому и надо на 8-ку будет переезжать, иначе дальше нам поддерживать все на фичах и/или переносить руками - просто задолбает и все бросят.

**Comment by vistar** [comment]
Этот бы отразить в инструкции ;)

**Comment by Niklan** [comment]
У нас нету никаких по этому поводу правил. Вы задались вопросом, я высказал своё личное мнение. Я думаю самое оптимальное, по причине что других в принципе нет. Но мы решили в своё время что с фичами легче тоже не станет.

**Comment by Niklan** [comment]
Так как ответ по сути дан, думаю ишьюс себя исчерпал. Думаю переезд на 8-ку решит многие из данных проблем, сильно заморачиваться под 7-ку уже с этим просто не имеет смысла, у нас нет в планах засиживаться на ней.
