### ISSUE TITLE
WSOD http://dru.io/

### ISSUE THREAD

**Issue by ttenz** [Niklan/Dru.io#325]
WSOD http://dru.io/

**Comment by Niklan** [comment]
Unsupported operand type. От флага идет. До компа должность вечером. Кто может, почините)

**Comment by Niklan** [comment]
Как файл закинуть с телефона?

**Comment by ttenz** [comment]
https://play.google.com/store/apps/details?id=com.sonelli.juicessh

**Comment by Niklan** [comment]
Стоит. Но надо еще найти откуда лезет. У меня возможности порыться нет да еще и с телефона

**Comment by Niklan** [comment]
Последние коммиты для флага надо смотреть и отлавливать

**Comment by Niklan** [comment]
Вроде поднял

**Comment by ttenz** [comment]
всё ОК

**Comment by ttenz** [comment]
опять повторилось

**Comment by Niklan** [comment]
сделал `drush up`
