### ISSUE TITLE
Проблема с авторизацией.

### ISSUE THREAD

**Issue by Grayw0lf** [Niklan/Dru.io#327]
Спустя какое то время нет возможности войти на сайт хотя имя пользователя и пароль верны, пишет "Извините, это имя пользователя или пароль неверны". Если раньше можно было зайти через восстановление пароля (на почту приходила ссылка для входа), то теперь приходит пустое сообщение (скрин сообщения прикреплен). 
![post](https://cloud.githubusercontent.com/assets/14905056/10412414/66ad1048-6f8d-11e5-921c-0f19eac0b5b6.jpg)

ОС Win7 pro 64-bit, браузер firefox 41.0.1

**Comment by fortis** [comment]
привет, регулярно так? выходишь и заходишь сразу? автозаполнение логина пароля используется? 

попробуй воспроизвести и отпишись в какое время делал я по логам посмотрю, сейчас не осталось ничего - расширил количество записей лога для хранения

**Comment by Grayw0lf** [comment]
Так происходит как только зарегистрировался, т е фактически со времени создания сайта. Вначале было что не мог зайти на следующий день, последние наверное пару недель, может месяц уже через день. Использую автозаполнение, но также не могу войти когда вбиваю и юзера и пароль ручками. Через соц сети не входил и не планирую. Входил 11 октября 1:38, если что посмотри по ip киров.
Похоже вопрос снимается, было заполнение что в качестве юзера стояла почта а мне надо было вбивать ник, как то порой не замечаю, друп позволяет входить и по почте поэтому не обратил внимание. Вероятно раньше можно было входить используя почтовый адрес. Но все таки на почту не приходит ссылка для входа на сайт при восстановлении пароля, (скрин в начальном топике).
Все таки проверю через какое время меня выбросит если буду заходить хотя бы раз в день.

**Comment by fortis** [comment]
ок проверим, спасибо

**Comment by Grayw0lf** [comment]
Еще добавлю.
Теперь, т е где то в 1:46 - 1:47 вышел и зашел только на второй раз, первый раз не пустило с сообщением что то про капчу (где то есть такой ишью).

**Comment by fortis** [comment]
да это есть когда быстро либо автокамплитом входишь, поправим
