### ISSUE TITLE
WSOD

### ISSUE THREAD

**Issue by ttenz** [Niklan/Dru.io#329]
c раннего утра WSOD

**Comment by Niklan** [comment]
Да ппц, хоть бы кто поднял :)

**Comment by Niklan** [comment]
У кого есть доступы (а таких не мало) слейте и задебажте чо за херня происходит. Орет на флаги.

**Comment by Niklan** [comment]
https://www.drupal.org/node/2347297 - это ишьюс с проблемой как у нас.
https://www.drupal.org/node/1925922

**Comment by Niklan** [comment]
В общем dev весия флага не помогла. Надо дебажить. У меня нет ни возможности, ни времени сейчас это сделать. Так что пусть лежит пока кто-нибудь другой не доберется или у меня время не появится. Все походу отдыхают :)

**Comment by ttenz** [comment]
всё наладилось

**Comment by ttenz** [comment]
опять

**Comment by UksusoFF** [comment]
А что бекапы не далаются ежедневно? (:

**Comment by Niklan** [comment]
Делаются.но зачем открывать когда там ошибка в коде

**Comment by ttenz** [comment]
done
