### ISSUE TITLE
Внешний вид комметариев

### ISSUE THREAD

**Issue by fortis** [Niklan/Dru.io#33]
Имхо, но кажется плохо читаются комменты, ответы совсем мелкие, а цитаты в них крупные, если почитать тему с большим количеством комментов, например http://community.drupalife.com/question/165 то бросается в глаза коммент хулигана (крупный), при этом на гитхабе визуально все просто и понятно https://github.com/Niklan/DrupalCommunity/issues/29 так давайте и возьмем форму редактирования коммента и внешний вид комментов как на гитхабе. Могу сделать

**Comment by Niklan** [comment]
Считаю вид комментариев надо приводить к stackoverflow. В вопросах однозначно. В остальных можно как на гитхабе. Могу переоформить.
Также надо комментам в ответах и вопросах слева отступа добавить.

**Comment by fortis** [comment]
а чем вид как в стеке лучше для вопросов чем вид гитхаба? он мне кажется более лаконичен.
лучше один стиль обсуждений иметь.

я разницу вижу только в том что в вопросах акцент сделан на голосовании за ответ, две стрелки и число поместятся под аватарку в самый небольшой коммент (как твой выше трехстрочный), как еще лучше это оформить можно придумать потом, а пока готовое взять например

**Comment by adubovskoy** [comment]
Гитхаб для обсуждений (удобно обсуждать, нет доминирующего поста), стек - для коллекционирования базы готовых ответов (удобно читать, есть доминирующая реплика -- ответ и сопуствующие -- комментарии(уточнения по сути) к ответу).
Соглашусь с Никитой, в вопросах надо как в стеке.

Цель раздела в итоге - чтоб пользователь пришел с поисковика и за максимально короткое время увидел решение своего ответа. stackoverflow на это направлен.

**Comment by fortis** [comment]
теперь понятно, не рейтинговые ответы свернуты до минимума, но и с таким подходом есть что переверстать, на этом поддомене кстати красивее стек http://aviation.stackexchange.com/questions/11766/can-a-large-passenger-aircraft-recover-from-a-stall

**Comment by semyondragunov** [comment]
https://github.com/Niklan/DrupalCommunity/issues/27

**Comment by Niklan** [comment]
Ты предлагаешь дерево комментариев, а тут непосредственно оформление. Массивное или минималистичное строчкой.

**Comment by semyondragunov** [comment]
Вообще-то я там тоже предлагал убрать уменьшить отступы в комментах, а то всё большое. Тупо теряешься.

**Comment by xandeadx** [comment]
Когда под ответами много комментариев, то сами ответы теряются, пример - http://community.drupalife.com/question/282
Можно сделать как на тостере - по умолчанию скрывать коментарии.
Или например скрывать за js ссылкой всё после 3-го комментария.
В первую очередь юзеров попавших из поисковика будет интересовать ответы.

**Comment by Niklan** [comment]
Ага, мы тут подобное обсуждали #36 

Пожалуй ишьюс текущий закрываю, в том более активно обсуждение пошло.
