### ISSUE TITLE
При оценке "против" - вводить текст, почему против

### ISSUE THREAD

**Issue by roman-yakimkin** [Niklan/Dru.io#331]
Добрый день.
Такая вот мысль - чтобы при оценке "против" оценивающий был обязан ввести в поле текст, почему он против. Чтобы не было всяких голословных "заминусовок" только потому, что человек ранее успел нахватать "минусов".

**Comment by Niklan** [comment]
Считаю бесполезным. Слишком раздражающая функция будет, никто вводить не будет.

Мы частично решили данный вопрос сделав порог в 20. Т.е. те у кого рейтинг меньше 20 не может пользоваться рейтингом на сайте. Следовательно к такому рейтингу человек все же понимать должен за что минусовать и плюсовать.

**Comment by ttenz** [comment]
почему минус поставил можно написать в комментах, такая возможность уже есть.
