### ISSUE TITLE
Непорядок с контактными данными

### ISSUE THREAD

**Issue by vistar** [Niklan/Dru.io#333]
На странице заказа указано: Для того чтобы отозваться на заявку, вам необходимо указать личные контактные данные в своём профиле. Добавить контактную информацию.

На странице редактирования профиля: Вы можете указать контактные данные, которые будут видны всем пользователем при просмотре вашего профиля.

А не есть ли это нарушение закона о ПД?

Возможно стоит разделить контакты на публичные и для заказов?

**Comment by Niklan** [comment]
> А не есть ли это нарушение закона о ПД?

Нет. Предельно ясно указано что будут доступны всем (мы предупреждали), и это поле не обязательное, никто не заставляет. Но проблему я понимаю.

Считаю что не поле для контактов надо делать дополнительное, а добавить поле к флагу, где можно написать заказчику коротко по заказу и свои контакты на данны конкретный заказ. Что-то типа оставить комментарий еще к заказу, но лично для клиента, без возможности ответа, только для прочтения. Типа как коммерческое предложение. Вот и всё ;) Сразу двух зайцев убьем.

**Comment by fortis** [comment]
связываю с #334 - частично решает проблему публичных данных
