### ISSUE TITLE
Заказы. Приватный отклик, закрытое обсуждение

### ISSUE THREAD

**Issue by fortis** [Niklan/Dru.io#334]
## Приватный отклик

необходимо добавить опцию (checkbox), чтобы после публикации сам отклик был виден только заказчику, а для посетителей выводить общий счетчик откликнувшихся. 

большинство предпочитает откликаться на заказ приватно (через личку, почту, и тп) а не публично в комментариях.
## Обсуждение

обсуждение сделать в виде комментариев к отклику, эти комментарии всегда будут видны только клиенту и потенциальному исполнителю: 
- клиент видит все комментарии
- фрилансер видит только свои комментарии и ответы клиента

**Comment by adubovskoy** [comment]
А он и сейчас приватный, не? Только модераторы всех видят.

**Comment by Niklan** [comment]
Да так и есть, просто Алан администратор и видит всех :)

**Comment by Niklan** [comment]
На счет комментов - это то что я предлагал, с полем для своего сообщения заказчику?

**Comment by fortis** [comment]
то есть обычные пользователи не видят список откликнувшихся?))

**Comment by Niklan** [comment]
Разумеется. Видят только кол-во

**Comment by fortis** [comment]
да но чтобы они могли нормальную дискуссию вести, чтобы и заказчик мог отвечать там, чтобы это было в одном месте для него на одной странице со всеми другими

**Comment by Niklan** [comment]
Я категорически против, честно говоря. Обсуждать там ничего не надо, по одной простой причине - база в открытом доступе. Пусть исполнитель пишет своё предложение и они контактируют удобным для них способом. Мы вроде и не предполагали общение внутри сообщества по заказам. Только как связующее звено.

Да и как ты комменты то прикрутишь к флагу? На 8-ке запросто, а на 7-ке увы и ах, нам придется создавать ноду для их личного общения. Как минимум, такое надо тянуть до 8ки, ибо сейчас это выльется в не очень хорошие решения.

**Comment by fortis** [comment]
заказчику нужно обсуждать, он не всегда может сходу дать все подробности, так же как и исполнитель. а с базой уже давно пора решать по-другому, при дампе одним запросом заменять текстовые поля на рыбу, хеши на пустые, имена пользователей на рандом

**Comment by Niklan** [comment]
Так пусть обсуждают любым удобным для этого способом. Считаю что такую дисскусию не нужно переводить на сайт. Да и пользоваться врядли кто таким способом будет. Обсудят как связаться удобнее да и всё :)

**Comment by fortis** [comment]
хотя возможно это и не плохо, если нужно будет связаться и обсудить лично с каждым... но базу все-равно нужно чистить

**Comment by fortis** [comment]
won't fix )))

**Comment by Niklan** [comment]
:smile:
