### ISSUE TITLE
Подписка на заказы

### ISSUE THREAD

**Issue by SemanticsPRO** [Niklan/Dru.io#335]
Сабж.
Во-первых, RSS, что решится доп.дисплеем вьюхи.
Во-вторых, на мыло.
Шо скажет олл?

**Comment by adubovskoy** [comment]
rss только за.
про почту: есть вопрос. будет 1000 подписчиков в итоге, каждый раз это море почты всем скопом высылать? может лучше твиттер или еще что?

**Comment by Niklan** [comment]
pushbullet ;)

**Comment by fortis** [comment]
rss +
почта лучше тем что там все уведомления как правило, и комментарии будут смотреть и заказы, и обычно все связанное с заказами и работой как раз на почту и получают, тут твиттеры и другие каналы не очень удобны.

пушбулет не самое приоритетное считаю, тот же rss по сути

**Comment by fortis** [comment]
а почту высылает у нас мандрил все равно, не справится?
как вариант в разделе заказов сделать блок с кнопкой подписаться, чтобы почта шла не всем пользователям а тем кто заинетерсован в заказах

**Comment by Nikit** [comment]
Запушил orders rss, имхо мыло не нужно, кому надо могут оттуда гнать на мыло http://mailchimp.com/features/rss-to-email/
