### ISSUE TITLE
Тулбар для всех

### ISSUE THREAD

**Issue by SemanticsPRO** [Niklan/Dru.io#336]
Имею довольно хорошие результаты по использованию тулбара ака admin_menu для всех в коммьюнитях.
Удобная вещь, когда скроллить не надо, а у тебя под боком есть ссылки на личку, трекер и прочие там "Мои вопросы".

Готов внедрить выслушав олла.

**Comment by Niklan** [comment]
Так у нас итак все на видном месте сейчас же ) Да и адутория не как на фермере :smile: :feelsgood:

**Comment by adubovskoy** [comment]
Админ меню сложно темизируется и полон костылей. Уж лучше самим ручками если есть потребность (нужен мокап/дизайн).

**Comment by SemanticsPRO** [comment]
> Так у нас итак все на видном месте сейчас же ) Да и адутория не как на фермере

А на хабре аудитория как на фермере?
Мне не нравится твоя категоричность по любым вопросам.

**Comment by fortis** [comment]
ну как дефолтный тулбар по мне так лишнее, внешний вид и нагруженность пунктами отталкивает. 
но сама идея панельки, хз может быть... 
надо и правда набросать что там будет полезного.

**Comment by SemanticsPRO** [comment]
Да самое элементарное и полезное, это затолкать туда ленты/трекеры разных типов контента.
Может даже с цифирью сколько новых, по типу как в модуле, название которого я забыл
![menu_node_count-example](https://cloud.githubusercontent.com/assets/1708410/10512639/9d2c91aa-734a-11e5-9a7a-68ec128e030c.png)

**Comment by fortis** [comment]
начать можно с примеров других сайтов, кидайте скрины

**Comment by fortis** [comment]
у тостера мне нравится, но оно там смотрится органично из-за дизайна у нас пока не понятно как вписывать

и еще одно преимущество панельки туда реально можно выводить уведомления

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_41174/WJbj0oQwXnlKVSJ5ZgPorCxoU4q9Wb/4em0715101442.png?Expires=1444995807&Signature=GyQhRHpey~DYivhGSCKwq0D89mxUrUNyBrxJnKoGsduVpzqbNhklG30btH1lKSchYu5lziEt7Xe6P-VdNeMD9pImA0uDeb6RQXZm06k~pJKU6KuiFSioQ6jRUJKfegIjg4H5vo9wZdV946Cwd1ifIzVrb7Ks1kfFqS4b42SNzXGqmUNrZSzixbGqlOORUFXwvaQgRcTDb9jAM41aRqWRMwFSRPlzQEd1cSxs6inUg~5wNaxNM5k5GGINqb3CHKh7Ocn2vQXWXIlqRsYZRHc41qQHwho3qh2lOZH3Rqp7GxJ1nuOiyW2H2X6S4LkSOywFAo2zAZ01g5lQMOvzamU8pg__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by drupby** [comment]
> у тостера мне нравится, но оно там смотрится органично из-за дизайна у нас пока не понятно как >вписывать

правый сайдбар есть, добавить еще и слева и выводить только для авторизованных

**Comment by drupby** [comment]
> Может даже с цифирью сколько новых, по типу как в модуле, название которого я забыл

возможно https://www.drupal.org/project/menu_badges

**Comment by drupby** [comment]
Или как на хабре
![image](https://cloud.githubusercontent.com/assets/3697814/10514452/72773332-7356-11e5-8385-aed91a33651a.png)
![image](https://cloud.githubusercontent.com/assets/3697814/10514459/7b593bbc-7356-11e5-94d2-87579a766453.png)

**Comment by tlito** [comment]
админ меню - очень тормознутое, потому что тяжелый js.
я думаю убрать джс со своего сайта, надоело. как на дру.ио оптимально.

**Comment by SemanticsPRO** [comment]
Я искренне не понимаю почему все пристали к админ меню, реализовать можно чем угодно, давайте о полезности, реализации или ещё чему

**Comment by tlito** [comment]
можно просто сделать плавающий блок с админскими значками, но без js. у меня на сайте например кнопка вверх плавает и всегда видна.

**Comment by drupby** [comment]
>  можно просто сделать плавающий блок с админскими значками, но без js

Javascript вешает сервер?

**Comment by adubovskoy** [comment]
> Я искренне не понимаю почему все пристали к админ меню, реализовать можно чем угодно, давайте о полезности, реализации или ещё чему

покажи на какомнть dev пример как можно. Пока непонятно просто, мысли как это сделать "малой кровью" приводят к тому что "сейчас удобнее".

**Comment by fortis** [comment]
я за панельку как на хабре чтоб разворачивалась при клике на иконки, а уж думать как красивее потом можно, сейчас важнее функционал и его удобство. кровь потом прольем)))

**Comment by tlito** [comment]
и скорость для авторизованных тоже важна. такая панель добавит скорости при работе с сайтом.
