### ISSUE TITLE
Список пользователей или раздел "Люди" с фильтром

### ISSUE THREAD

**Issue by uxpromo** [Niklan/Dru.io#337]
Приветствую. 
**Небольшая предыстория, для понимания проблемы:**
Dru io развивается и много людей уже регулярно там бывают. 
Я живу в небольшом городе Великий Новгород и, как оказалось, найти в моём городе людей, интересующихся и работающих с Drupal - непростая задача. С удовольствием бы поучаствовал в организации локального друпал-кафе или просто как-то поддержал существование местной дру-тусовки, которой нет (либо она очень секретная :) ). 

**Суть ишью:**
Добавить раздел "люди" и поле "город" в профиль, иметь возможность фильтровать пользователей по городу и видеть контактные данные.

**Comment by Niklan** [comment]
Был такой вроде. Если не закрыт, надо найти и связать. Там обсуждение даже было.

**Comment by uxpromo** [comment]
Найти похожий ишью не смог, но искал не глобально...

**Comment by Niklan** [comment]
#5 примерно тот о том же

**Comment by tlito** [comment]
это позволит новичкам искать поддержку в своем городе, а заказчикам - исполнителей.
страницу профиля тогда участники будут оформлять как порфтолио - грузить скрины и делать ссылки. это если к этим страницам действительно будет внимание заказчиков через сайт.
хотя бы поиск по городам нужен.

**Comment by ttenz** [comment]
хорошая идея, заказчики больше доверяют спецам во плоти.
