### ISSUE TITLE
Убрать рейтинг вопроса

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#338]
Как показывает практика у вопросов либо нулевой рейтинг либо отрицательный. Предлагаю убрать рейтинг из списка вопросов.

**Comment by fortis** [comment]
на стеке такая же картина, чем он мешает?

**Comment by xandeadx** [comment]
лишняя информация

**Comment by fortis** [comment]
если вопрос с минусами то я туда не буду заходить чтобы ответить, можно будет сортировать в поисковой выдаче по релевантности, наличию ответа и по рейтингу, и минуса идут в карму, пока вроде все сходится глядя по профилям - в минус ушли за вопросы в виде домашнего задания - "решите за меня", или вообще без подробностей

**Comment by Niklan** [comment]
Считаю что убирать не стоит. Отличный мотиватор писать вопросы осмысленно, и погуглить перед тем как задавать.

**Comment by tlito** [comment]
да. с приходом новых пользователей рейтинг будет поднматься, на стеке много вопросов с высоким рейтингом

**Comment by ttenz** [comment]
соглашусь с xandeadx, новички будут боятся потом вопросы задавать. а в гугле можно найти практически всё, смысл тогда ответов/вопросов?

**Comment by tlito** [comment]
зачем новичкам рейтинг?
рейтинг имеет значение если человек присутствует. если он будет решать вопрос: спросить и получить отрицательные оценки, но имет вероятный ответ - или уйти и не найти ответ - то он выберет первый вариант.

**Comment by adubovskoy** [comment]
еще рейтинг это способ автоматизировать модерацию. Накликали минусов на треш-рекламе ручной, она депубликовалась (сейчас нет, но будет необходимость если спамеры набегут, 5 мин делов). А какие-то сложные действия/выборки - это писать долго. Не на d7, думаю.
