### ISSUE TITLE
Сжать заголовок до 30px

### ISSUE THREAD

**Issue by tlito** [Niklan/Dru.io#339]
слишком высокий заголовок. мне нравится как на linuxforum.ru
1. верстать по макету
![maket_druio](https://cloud.githubusercontent.com/assets/11997227/10574880/c6335a64-7626-11e5-8ba6-f460553ce2f7.png)
1. убрать поиск на отдельную страницу, так как я, например, через гугл ищу по сайту
2. кнопка выход не нужна, её вынести на личную страницу
3. убрать крошки или сдвинуть их в правую колонку
4. ничего не добавлять вверх в колонке вопросов

слово Друпал на всех страницах часто используется, поэтому нет смысла пояснять в логотипе цель сайта, сайт-то уже всем знаком.

github в подвал.

**Comment by adubovskoy** [comment]
Не получили комментариев/подтверждения, закрываем. Либо требуется более тщательная прорисовка для reopen (дизайн выглядит хуже чем то что сейчас).
