### ISSUE TITLE
Подсветка кода

### ISSUE THREAD

**Issue by fortis** [Niklan/Dru.io#34]
**Поправьте если пропустил и уже есть какое-то решение**, предлагаю использовать Codemirror, нравится тем что есть хоткеи и удобные аддоны. 
Подключу его к bueditor кнопкой и повешу на подсветку кода в тексте. Взял себе

**Comment by Niklan** [comment]
Прикольная штука Codemirror, но как её вставлять посередине текста? Придется добавлять поле для ввода кода, а затем токены типа [code:1] чтобы из первого поля код подставлял.

**Comment by fortis** [comment]
мне кажется лучше по кнопке буедитора открывать попап и писать код отдельно от текста и по кнопке вставлять в позицию курсора
![](http://3xff.net/6kyok20011455.png)

**Comment by Niklan** [comment]
Хорошая идея. И еще надо дать выбора языка, так как текущий скрипт от мазиллы нифига не детекстит, ему надо классы добавлять типа language-XXX, где XXX-язык

**Comment by fortis** [comment]
http://codemirror.net/mode/index.html
думаю для минимума достаточно будет
- CSS 
- PHP 
- SQL 
- XML/HTML 
- YAML 
- diff  

LESS Sass SCSS на потом если появится необходимость, чтобы не раздувать список

**Comment by Niklan** [comment]
А теперь решить надо кто это сделает. Я BUEditor из просьб влепил, не юзал, поэтому незнаю. Могу попробовать добавить кнопку, но не уверен) Просто если есть кто точно знает как шустро сделать, лучше скинуть, а так сами пороемся)

**Comment by fortis** [comment]
я делаю, назначил же себе)

**Comment by Niklan** [comment]
Ну ты назначил даже когда не решено было что делать, а так ок. Ждём эпика)

**Comment by Niklan** [comment]
Нашел еще вот такой: http://ace.c9.io/ Он тут на гитхабе используется.

**Comment by fortis** [comment]
нравится да, изучу

**Comment by fortis** [comment]
с чайком накидал базу
![](http://3xff.net/q0sin25011925.png)

нужно подобрать иконку для кнопочки, где ты их брал?

**Comment by Niklan** [comment]
А я тут значит тебе в скайп это пишу) Иконки шли в комплекте. Если надо, могу отрисовать, какие-нибудь, или из fontello в img векторный перегнать.

**Comment by fortis** [comment]
с фонтелло возьму подгоню под те что есть, на выходных закончу с этим

**Comment by Niklan** [comment]
Я могу иконки в PNG экспортировать в нужном цвете или SVG

**Comment by drupby** [comment]
Судя по ответу на вопрос http://dru.io/question/448 появилась подсветка кода, но как ее использовать?
Нашел в редакторе кнопку insert code, но она не имеет кнопок внутри формы добавления кода.

**Comment by Niklan** [comment]
@drupby она и была)

http://dru.io/post/3 тут всё описано

> Код с подсветкой синтаксиса
> 
> Для этого достаточно к тройной тильде дописать language-xxx где xxx — название языка разметки. Доступные варианты:
> 
> markup (html и прочее)
> php
> css
> js
> git
> bash
> Пример:
> 
> ```
> ~~~language-php
> ```
