### ISSUE TITLE
Быстрый поиск неотвеченных вопросов

### ISSUE THREAD

**Issue by tlito** [Niklan/Dru.io#340]
Допустим, новый пользователь хочет получить опыт или рейтинг.
Как тогда найти старые неотвеченные вопросы?
Ещё в дополнение к этом можно сделать что-то типа
"мои нерешенные вопросы" - то есть чтобы видеть пользовтелю что он еще не решил и что уже не задавать...

**Comment by tlito** [comment]
а еще можно делать публикации с тем что было решено и как это было решено. типа как обзор новых вопросов и новых решений за пол-месяца или месяц. типа чарт

**Comment by greeneyesmi** [comment]
Вот ты неугомонный)) Сдался тебе этот рейтинг?)

**Comment by adubovskoy** [comment]
Нет необходимости. Список вопросов есть в профиле (и автору очевидно какие нерешенные), а список общих есть в /question, и там видно какие нерешенные.
