### ISSUE TITLE
Теги вопроса в node full mode

### ISSUE THREAD

**Issue by semyondragunov** [Niklan/Dru.io#341]
Нету тегов (версия дру, теги, модули) в вопросе.

**Comment by xandeadx** [comment]
up

**Comment by adubovskoy** [comment]
Еще бы дать возможность модераторам(или тем у кого рейтинг выше) их добавлять к постам. Для упрощения поиска -- так и библиотека полезностей появится.

**Comment by Niklan** [comment]
Тегов у нас нет.
Есть версия друпал, категория вопроса, связь с проектами

**Comment by xandeadx** [comment]
и это тоже не выводится

**Comment by Niklan** [comment]
Это да

**Comment by isaenkov** [comment]
Up
Да, хотелось бы увидеть теги **Версии друпал** и **Связанные проекты** в полном виде вопроса, а то бывает не удобно ориентироваться о какой версии друпала идет речь.

**Comment by als-studio** [comment]
UP
В связи с появлением большого количества вопросов по D8 все более актуально :)

**Comment by adubovskoy** [comment]
Я доберусь к выходным. Если кто раньше сможет - берите ишью.
