### ISSUE TITLE
Перевести сайт на Drupal 8

### ISSUE THREAD

**Issue by Chi-teck** [Niklan/Dru.io#342]
### Исходные данные

Drupal 8 дотянул наконец до RC версии. Стабильный релиз ожидается в течении следующих нескольких недель.
### Мотивация

Drupal 8 явно круче чем Drupal 7.  😀
### Первоначальные задачи
1. Составить таблицу всех используемых на сайте contributed модулей и их наличия для Drupal 8.
2. Создать 8.x ветку в гите.
3. Создать тестовое окружение для D8 версии сайта.

**Comment by fortis** [comment]
сложный вопрос, с одной стороны если не заняться этим в ближайшее время то можно об этом забыть, через год сайт обрастет функционалом и это будет слишком большой проблемой, чтобы заниматься этим в свободное время с чайком))

с другой стороны помощи в работе над сообществом может стать еще меньше, потому что другим участникам нужно будет изучать много нового.

**Comment by fortis** [comment]
идея мне нравится, я бы дистрибутивом это оформил.
и если начинать то нужно стопорить текущие разработки и бросать все силы на запуск новой версии. заодно нужно пересмотреть структуру проекта перед миграцией

**Comment by fortis** [comment]
Flag - нет, нужно искать альтернативу или свое небольшое решение
Rate - нет, нужно искать альтернативу или свое небольшое решение
Search API - нет, можно по самим слать запросы в солр

DS - есть 8.x хотя думаю нам хватит функционала ядра
HybridAuth - нет, не обязателен
Mandrill - нет, не обязателен
Markdown - нет, не обязателен
Rules - нет, не обязателен

Остальной функционал либо есть в ядре д8, либо не критичен. 
Кастомы обновим, там кажется не много кода

**Comment by adubovskoy** [comment]
Очень за. И Никита тоже вроде очень ждет) С деплоем проще будет. Я за то чтобы уже потихоньку начинать писать миграции, делать отдельную ветку и пересобирать. D7 версию заморозить (делать мелкие хотфиксы, верстку, мелочи, не планировать что-то огромное на старой версии).

**Comment by Niklan** [comment]
Я пока с 8-кой разбираюсь. В плане кода если я уже освоился. То в плане верстки там пока надо еще порыться. Почти не верстал.

**Comment by afi13** [comment]
Search API есть же для восьмерки уже
https://www.drupal.org/project/search_api
https://www.drupal.org/project/search_api_solr

**Comment by Niklan** [comment]
rate api и флага нет, остальное есть.

**Comment by Niklan** [comment]
Добавил метку обозначающую миграцию. Все ишьюсы, которые будем делать в процессе или после мигарции на 8-ку, давайте помечать им. Чтобы не делать понапрасну их на 7ке.

**Comment by fortis** [comment]
есть https://www.drupal.org/project/votingapi
и https://www.drupal.org/project/like_and_dislike
rate просто виджет можно и потом доставить

**Comment by Niklan** [comment]
В принципе можно что-то быстренько еще на неделе пофиксить на 7-ке. Собрать список изменений, делать релиз v0.3 и замораживать 7-ку. И тыкаться неспеша в 8ке. На 7-ке только хотфиксы накатывать и незначительные правки. Основа есть, она работает, за пару месяцев ничего не случится)
