### ISSUE TITLE
Добавить оценку заказчиков

### ISSUE THREAD

**Issue by ttenz** [Niklan/Dru.io#343]
Добавить оценку/отзывы/рейтинг заказчиков для фильтрации недобросовестных, неадекватных заказчиков, видный только разработчикам (или кто подрядился).

**Comment by adubovskoy** [comment]
На upwork и многих биржах есть, и в целом это работает. Наиболее актуальным это станет когда будет больше заказов/откликнувшихся. Пока я например не смогу сделать выборку есть ли постоянные заказчики -- непонятно.

**Comment by fortis** [comment]
для биржи это конечно нужно, а нам биржа зачем?) 
просто с этим будет довольно хлопотно, а заказы итак будут размещать, потому что есть скопление специалистов. эти рейтинги на известных ресурсах постоянно терпят изменения. и чтобы рейтинг был настоящий, за реальный заказ, нашему ресурсу нужно быть посредником

**Comment by ttenz** [comment]
раздел заказов - это уже микробиржа.
- как различать адекватов от неадекватов, мошенников, халявщиков? имхо рейтинг нужен и здесь он к месту. оценивать должен исполнитель, по критериям: точность задания, своевременная оплата и т.п.

**Comment by fortis** [comment]
возможность фейковых заказов и отзывов убивает саму идею рейтинга фрилансеров.
как отличать неадекватных фрилансеров которые минусуют заказчиков? вспомним друпалру и оскорбления заказчиков в комментах

**Comment by ttenz** [comment]
так здесь есть порог адекватности (20), если адекватно оценивают ответы/вопросы, то почему неадекватно будут оценивать заказчиков? там оскорбления, здесь рейтинг, почти одно и тоже. Человек с февраля ищет исполнителя. почему? а стоит на него время тратить?

**Comment by fortis** [comment]
это порог адекватности лишь для вопросов-ответов, там где это не имеет большого значения. можно набрать карму на вопросах и ответах и нахамить заказчику и оставить плохой отзыв или просто чтоб другие не брались. при всех этих НО не вижу смысла в этом вообще, будет только вводить в заблуждение других специалистов. 

исключительно мое личное мнение)

**Comment by ttenz** [comment]
нет ничего нового под небом. умный учится на чужих ошибках.
думаю, что лучше об этом подумать заранее (биржи не дураки делали), чтобы правильно спроектировать на 8.

**Comment by adubovskoy** [comment]
Ок, отложим до d8
