### ISSUE TITLE
убрать минусование за вопросы

### ISSUE THREAD

**Issue by ttenz** [Niklan/Dru.io#344]
За что минусуем http://dru.io/question/4238?

так они вообще перестанут писать.

**Comment by fortis** [comment]
пора за минусы наказывать))) нормальный вопрос, видимо порог все еще низкий =)

**Comment by ttenz** [comment]
интересно, тот кто заминусовал, какой у них рейтинг?

**Comment by vistar** [comment]
В общем пока видится так:
Борьба за лидерство в заказах началась - одни минусуют других, чтобы либо обогнать в рейтинге, либо опустить их.

Надо разделить рейтинги в заказах и вопросах - это две разные сущности, кмк.

**Comment by adubovskoy** [comment]
tlito могут минусовать просто из-за плохой истории. у него очень много вопросов, зачастую не очень хорошо оформленных. Когда это 1 раз - ок, но множество - раздражает многих. У остальных вроде нет такого минусования "без причины".

**Comment by ttenz** [comment]
причина, то всегда найдется. остальные, по-умней. они просто перестали задавать вопросы. вроде хотели новичков на ресурс привлекать? имхо, вообще убрать рейт с вопросов, за вопрос не судят, но... сделать флаг, когда это спам и т.п.

**Comment by Niklan** [comment]
Да всё нормально с рейтингами. Минусуют откровенно глупые вопросы или неверно составленные где не ясно чего хочет автор, или где он хочет чтобы за него все сделали. У тлито даже не все в подряд минусуют.

**Comment by ttenz** [comment]
> тлито даже не все в подряд минусуют

п.ч. добрые люди плюсуют)

**Comment by tlito** [comment]
да, вопросы часто тяжело читать - впустую время тратить.
тогда можно сделать песочницу - место в котором могут появляться вопросы слабоищущих или ленивых.
для тех кто минусовал автора больше 20 раз показывать кнопку: не отображать сообщения этого юзера: вопросы, ответы, комментарии

**Comment by Niklan** [comment]
#358 - решаем проблему не отключением функционала, а его улучшением. Рейтинг на данный момент себя проявил вполне положительно.
