### ISSUE TITLE
Возвращаюсь к вопросу ввода причин минусования

### ISSUE THREAD

**Issue by roman-yakimkin** [Niklan/Dru.io#346]
Хочу вернуться к тому, чтобы предложить вводить причину минусования. 
Причем, чтобы минусующий был ОБЯЗАН ввести эту причину. Причем, не на уровне "бред", а понятно и развернуто.
Вот, например, ветка - http://dru.io/question/4242
Непонятно за что мой ответ заминусован. 
Хотя несколько раз деактивация, снос и перезаливка модуля помогали решить проблему, когда до переноса на новый хостинг какой-то модуль работал, а вот после переноса не работает.

**Comment by adubovskoy** [comment]
Потому что ответ странный (хотя я не минусовал). Файлы удалять зачем?)) 
Смотрите: вы можете давать ответы в нескольких форматах:
а) вам нужно сделать то-то и то-то, потому что вот тут так работает, вот ссылка на issue/код, можете вот тут посмотреть логи.
б) есть шаманство, я его не понимаю, было похожее - попробуйте, может сработает.

вариант б несомненно рискует получить минусы.
