### ISSUE TITLE
Автоматика по блокированию

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#350]
Предлагаю настроить rules, дабы коллективный разум заменял модераторов.

А именно:
1. Посты, набравшие -5 рейтинг - убираются с главной. (сейчас для постов уже есть)
2. Посты, набравшие -10 рейтинг - депубликуются вообще.
3. Пользователи, набравшие -50 - блокируются.

Профит: 
1. Если вдруг будет ручной спам, посетители его уберут (а при повторении - и вместе с пользователем-спамером).
2. Снять "моральный груз" с модераторов, когда непонятно что делать с какими-то ответами, постами, насколько они соответствуют правилам/тематике и т.п.

**Comment by koddr** [comment]
Полностью поддерживаю. Но я бы снизил порог бана юзеров до -30.

Поясню. Есть у нас пользователь [tlito](http://dru.io/u/tlito), который постоянно в минусе находится. Собственно, это логично — то ли у него русский не родной, то ли специально так пишет, что глазам и мозгу постоянно бо-бо с его комментов/ответов. Короче, как бы его не минусовали — он постоянно болтается между -27...-36 (видимо ботовод, себя отлайкивает постоянно). Следовательно, он ещё долго (никогда) не будет забанен, если сделать бан при -50, а жаль.

> Просто tlito, лично мне, сильно напоминает Inferno с drupal.ru, с чьим появлением, я считаю, d.ru и стал таким УГ, какой он есть сейчас... Не допустим такого на dru.io!

Другой вариант: сделать при достижении -30 запрет на ответы/комментарии в чужих вопросах. Пусть в своих вопросах минусованный что хочет, то и делает, а чужие не портит.

**Comment by adubovskoy** [comment]
> (видимо ботовод, себя отлайкивает постоянно)

так уже нельзя, плюсовать/минусовать могут только те у кого рейтинг больше 20. Ботов не заведешь.

ждем еще комментариев, по деталям математики или в целом.

**Comment by drupby** [comment]
> 1. Посты, набравшие -5 рейтинг - убираются с главной. (сейчас для постов уже есть)

http://dru.io/question/4340 c -6 есть и на главной и на /question

**Comment by Niklan** [comment]
Так убираются посты а не вопросы. По поводу вопросов пока только предложение от Александра)

Меня лишь момент блокировки немного напрягает. Как-то жестко, не?)

**Comment by tlito** [comment]
на стековерфлов довольно продуманная политика. при достижении ранга там выдают привилегии. тут тоже надо какие-то привилегии. для постояльцев сделать область в которую не смогут писать заминусованные. а заминусованным сделать отдельную стенку

**Comment by tlito** [comment]
если честно то большинство вопросов я пишу для себя. так что действительно пусть будет место которое будут видеть только те кто хочет.

**Comment by adubovskoy** [comment]
> Меня лишь момент блокировки немного напрягает. Как-то жестко, не?)

давайте увеличим до психологической "нормы". Например до 80. Если кто-то систематически набрал 80 минусов -- то надо бы, а?) Тут как раз и идея в том чтобы не кто-то из модераторов выключал профиль, а мнение всех.

**Comment by koddr** [comment]
> если честно то большинство вопросов я пишу для себя

Для этого есть личный блог или около того — http://tlito.ru, например.

Если вы не понимаете смысла (прикола, замысла, идеи, etc) в ресурсах, типа Dru.io, то перечитывайте чаще вот этот абзац с главной страницы:

> Dru.io — место, где вы можете _задать интересующие вас вопросы_ по Drupal, _пообщаться_ с профессиональными разработчиками, _получить бесплатную поддержку_, _узнать самую свежую информацию_ и стать частью нашего дружного сообщества.

На счёт этого:

> Как-то жестко, не?)

Могу парировать: «а не жестоко из отличного профильного ресурса по Drupal, который уже более-менее оброс адекватной аудиторией (которая даёт обдуманные и хорошо читаемые ответы на, почти, любые вопросы) — делать УГ, типа drupal.ru?».

Самый простой вариант научить заминусованных — банить на создание ответов/комментариев к чужим вопросам/ответам. Как на StackOverflow, например, пока не наберёшь +50 репутации — комментировать нельзя, лайкать/дислайкать — тоже.

Хотя Никиту понять можно. Зачем рубить сук, на который можно потом отлично присесть. Это я про постоянное генерирование НЧ/СЧ контента (простых вопросов, обычно такие возникают у всех новичков === нескончаемый трафик из поисковиков), который может дать высокие позиции сайту и, в ближайшем будущем, сделать рекламу на сайте — золотой жилой.

Вообще, я бы ввёл «личные баны», то есть мне, например, не нравится как пишет товарисч tlito. Захожу в настройки профиля и указываю его логин (ID) в «чёрном списке». С моей стороны: я не вижу его вопросы, с его стороны — нет возможности комментировать/отвечать на мои вопросы. Если так уж хочется написать ответ на мой вопрос, то всегда в профиле указан e-mail — ни чьи права не ущемляются :)

**Comment by fortis** [comment]
согласен по всем пунктам, по мне -50 для бана не мало

**Comment by fortis** [comment]
но я б лучше хуком, а то разрастаются эти рулзы у нас и медленнее они значительно, а пользователей дофига

**Comment by tlito** [comment]
для ввода санкций нужно более продуманную политику и правила, чтобы ссылаться на эти правила и выдавать предупреждения

**Comment by fortis** [comment]
а вопросы "для себя" можно будет размещать в личных блогах, персональные черные списки мне кажется лишнее

**Comment by koddr** [comment]
> а вопросы "для себя" можно будет размещать в личных блогах, персональные черные списки мне кажется лишнее

Это вы tlito расскажите, ага.

**Comment by fortis** [comment]
зачем? если продолжать размещать вопросы для себя со ссылкой на свой блог можно навлечь минусы и улететь в автобан

**Comment by Niklan** [comment]
Я не против бана, я как-то не очень за рейтинг -30 для бана. Как сказал Александр, это "психологический барьер" и в данном случае, для меня, он мелкий, я считаю. -30 словить очень просто я думаю.

**Comment by koddr** [comment]
> Как сказал Александр, это "психологический барьер" и в данном случае, для меня, он мелкий...

Так чем меньше этот самый `психологический барьер` — тем лучше контент будет на проекте.

То есть, я правильно понял, что человек, который словил до -80 (к примеру), нормальный участник Dru.io сообщества? То есть, если у него будет и -78 и -65 — он всё равно будет «адекватным» для проекта? Типа «оступился 80 раз, с кем не бывает»?!

ИМХО, строже надо быть, иначе можно превратиться в drupal.ru №2. Пишешь хрень непонятную и не на русском языке (tlito) — уж извини-подвинься, без ответов/комментариев/лайков/дислайков в чужих вопросах/публикациях. Свои — создавай/комментируй/отвечай. Прекрасный пример — Хабр.

> -30 словить очень просто я думаю.

Если человек адекватный, то он и -10 не получит никогда. Да, может кто-то специально минусовать каждый вопрос/ответ человека, чтобы он в бан слетел — но в остальных случаях — минусы более чем заслужены и по делу выставлены. Тем более, что минусовать/плюсовать могут только те, у кого +20 (адекватные люди, которые доказали это).

Так что тут скорее вопрос: кто нам на Dru.io нужен (такие как tlito или такие как xandeadx) и что это будет за ресурс (Ответы@Mail.ru или StackOverflow)?

**Comment by fortis** [comment]
пока нет никаких причин ужесточать правила, достаточно того что планка есть, каким будет ресурс зависит не от плюсиков-минусов

> То есть, если у него будет и -78 и -65 — он всё равно будет «адекватным» для проекта?

очевидно да, так же как если из -65 он выйдет на +10 он все еще будет полноценным участником сообщества

**Comment by fortis** [comment]
> Так что тут скорее вопрос: кто нам на Dru.io нужен (такие как tlito или такие как xandeadx)

нам? сообществу? 
тут все плохо, сообществу нужны все, и новички в том числе, для того опытные специалисты и отвечают на вопросы, чтобы помогать и поднимать общий уровень. А уж правила поведения на ресурсе отработаем.

**Comment by adubovskoy** [comment]
Пока нет правил, было решено не блокировать пользователя. Но депубликация материалов при -10 есть.

**Comment by fortis** [comment]
![](http://cs10177.vk.me/u166350354/-6/x_4d6e83b2.jpg)

**Comment by adubovskoy** [comment]
Есть новая мысль. 
Что если автоблокирование не использовать, а сделать другой механизм.

Если у пользователя -30 и выше - то 2 минуса на посте его депубликуют. Не 10, а 2. Если у пользователя -50 - то 1 минус депубликует.

**Comment by koddr** [comment]
> Если у пользователя -30 и выше - то 2 минуса на посте его депубликуют. Не 10, а 2. Если у пользователя -50 - то 1 минус депубликует.

Полностью согласен.

**Comment by Niklan** [comment]
Хорошее предложение

**Comment by fortis** [comment]
👍

**Comment by tlito** [comment]
для минусованных вообще кнопки опубликовать не должно быть

**Comment by drupby** [comment]
> для минусованных вообще кнопки опубликовать не должно быть

В числе первых вроде должен был поддержать это предложение, так нет же.

**Comment by fortis** [comment]
согласен с тлито, кнопку лучше вообще убрать, кредит доверия исчерпан к этому моменту и восполнять его лучше ответами на вопросы, чем раньше пользователь начнет это делать тем быстрее выйдет из минусов, а так он может спокойно постить материалы даже с отрицательным рейтом

**Comment by Niklan** [comment]
@fortis вот это уже не есть гуд. Новичек по глупости своей может улететь в минус. Как он поможет другим?

Мне такой подход не нравится, ибо это аналог Full Project REview с Drupal.org.
Когда чтобы получить права на публикацию своих проектов на org, тебе предлагают проверить чужие заявки на предмет ошибок в коде, и т.д. Но как ты будешь проверять при том что тебя самого еще не проверили? Ты сам не знаешь какие ошибки допустил, тебя еще пальцем никто не потыкал, но чтобы тебе потыкали на твои ошибки, ты сначала должен потыкать на ошибки других. Вообще какая-то ахинея, я считаю. То же самое и тут будет. Он еще больше со своих ответов в минус улетит чем с глупых вопросов. Это как у многих профессий с вакансиями. Везде требуются люди с опытом, но где им получать его если везде нужен опыт, а без опыта не берут. В итоге все в проигрыше.

Лучше депубликовать вопросы раньше у тех у кого меньше рейтинг, нежели потом чистить ответы от откровенного хлама. Если пойти по пути как и drupal.org, ответы превратятся в помойку. Лучше на уровне вопрсов разруливать, чем выискивать ответы повсюду.

**Comment by adubovskoy** [comment]
Да, убрав кнопку публикации мы, может, потенциально уберем какой-то хороший контент.
Проблема в чем - участник с низким рейтингом с высокой вероятностью опубликует какой-нибудь спам/флейм. Эту проблему можно решить именно быстрой депубликацией (снизив порок). А если это будет что-нибудь стоящее - человек будет потихоньку выбираться из минуса.

хотя.... давайте пока сделаем быструю депубликацию и будем смотреть дальше... вдруг будут примеры которые позволят и на публикацию пересмотреть точку зрения. из практики исходить в общем.

**Comment by tlito** [comment]
у вас такого опыта не было.  это очень оптимистичные ожидания

**Comment by tlito** [comment]
в таких случаях надо расширять поле деятельности. например создать категорию Песочница. кстати мне нужны категории: безопасность, Магазин, оптимизация, новости, обзоры модулей, новичкам. а то сплошной блог без рубрик это для небольших сайтов

**Comment by Niklan** [comment]
Нам не нужна песочница. Депубликация и так сделает дело, а лишний порог входа не нужен совершенно, это лишь отпугнет. "Песочницами" рукой подать до закрытости ака хабр.

Что касается категорий. Это для публикаций не нужно. Это вообще у нас такой тип материала где что-то опубликовать можно, без какой-то точной направленности типа "блоги". 

Для "блогов" у нас планируется раздел #10 , вот там стоит предложить ввод категорий, ибо там это будет полезно.

В общем я всецело поддерживаю вариант @adubovskoy о скорой депубликации для заминусованых, нежели отключения публикаций вообще.

Только вместо двух надо три - для депубликации при рейтинге -30
И 2 вместо 1 при депубликации при рейтинге -50+.
1 слишком мало. Неприязнь другого человека или еще чего может стать причиной депубликации. Да банально, случайно нажал и всё, материал уже отсутствует. И кто и как его вернет?

**Comment by koddr** [comment]
> И кто и как его вернет?

Хорошие манеры, соблюдение правил русского языка и, пожалуй, дельные вопросы/ответы, после прочтения которых — не жалеешь о том, что не можешь поставить сразу -10, чтобы больше никто не видел этого «преступления против dru.io сообщества».

**Comment by Niklan** [comment]
Я про то, что слишком низкий порог тоже не дело.
Допустим зная что у тлито меньше -50 рейтинг, и депубликация при одном минусе - этот минус может влепить просто тот, кому "надоел" тлито или лично не понравился вопрос. Надо хотя бы 2, чтобы не единолично вышибали из вопросов.

**Comment by fortis** [comment]
я бы сделал -1 и только при наличии проблем если будут желающие - делать -2, предвзятая неприязнь при -50 - скорее надуманное явление, она уже вполне обоснованная и конечно придется постараться и раскаяться, может быть не с первого раза :) заслуженно
мы для того и вводили порог адекватности

**Comment by fortis** [comment]
хотя проблема пока не столь существенная 2 или 3 или 1, тлито пока у нас в единственном числе, консилиум собрали, польза всеравно от решения будет, а скорректировать его придется думаю в любом случае, будут еще меняться эти пороги, такая участь систем с рейтингом, придется часто подкручивать

**Comment by Niklan** [comment]
Решение мне нравится. Возьму на себя тогда задачу, если никто не хочет в ближайшее время делать. @adubovskoy ты будешь делать или мне сделать?

**Comment by adubovskoy** [comment]
бери если раньше успеешь.) я не знаю что у меня в ближайшие дни, сомневаюсь что до выходных возьму.

**Comment by adubovskoy** [comment]
Там собстно пару проверок добавить, сам каркас в https://github.com/Niklan/Dru.io/blob/master/sites/all/modules/custom/druio_rating/druio_rating.module#L106

**Comment by Niklan** [comment]
Реализовал.
-9 при обычном рейтинге до -30
-3 при рейтинге от -30 до -50
-2 при рейтинге меньше -50

**Comment by adubovskoy** [comment]
забыли залить на продакшн, залил.
