### ISSUE TITLE
Удаление комментариев

### ISSUE THREAD

**Issue by boatsman-spb** [Niklan/Dru.io#352]
Ребята, для начала яростно плюсую за dru.io. Всем сенкъю вери мач!) 
Однако, бывает, что вопрос задан так, что не сразу поймешь что надо Кемску волость), поэтому начинаешь уточнять в комментах, а потом - раз и догоняешь масштаб трагедии и коммент твой оказывается просто бессмысленным. Как для тебя, так и в целом. 
Так вот, к чему я рефлексирую - ясно-понятно, что раз ты решился на ответ, то все - баста карапузики, кончилися танцы)
Но вот комменты хотелось бы иметь возможность удалять.

**Comment by fortis** [comment]
пока не понятно в чем проблема и почему нужно удалять даже если не так понял вопрос

**Comment by multpix** [comment]
может просто добавить ~~зачеркнутый~~ и редактировать комментарий, или добавлять новый.
считаю что удалять ничего не нужно - это живые диалоги, они могут быть интересны третьему лицу.
это ж и источник идей, и ход мысли.
