### ISSUE TITLE
Как угадать допустимый размер загружаемых картинок?

### ISSUE THREAD

**Issue by vistar** [Niklan/Dru.io#353]
Скачать сборку себе и поискать?
Или написать оповещение об этом?

3 раза пытался залить картинку в коммент, выводится неадекватное Too large, и ни слова о допустимых размерах.

**Comment by tlito** [comment]
делайте jpg'ом до 200кб

**Comment by fortis** [comment]
Request Entity Too Large ?

**Comment by vistar** [comment]
В редакторе нажимаю на кнопу загрузить изображение, выбираю over 500 kiB картинку. Пробую over 300 kiB. В общем ребус разгадал не сразу, сколько же там before size.

"Too large file size" - лень было набирать, так как выпадало сообщение в Хроме из которого скопировать нельзя было.
