### ISSUE TITLE
Шрифт кода нечитаем

### ISSUE THREAD

**Issue by vistar** [Niklan/Dru.io#357]
Например: http://dru.io/question/4320#comment-5073
У меня (Хром 46 в линукс): http://i.imgur.com/8xYZ6Oz.png

**Comment by adubovskoy** [comment]
У меня норм. Надо туда добавить для pre code еще одно семейство которое гарантированно у всех есть. Но не вперед, а с низким приоритетом

**Comment by Niklan** [comment]
У меня тоже норм под линуксом.

Menlo,Monaco,Consolas,"Courier New",monospace - куда еще ниже. Вроде monospace самый низкий для кода.

**Comment by vistar** [comment]
Ну вот у меня:

``` css
.hljs-keyword {
  font-weight: bold;
}
```

ужасно смотрится.

Цепляется шрифт Monaco - системный. А у вас какой?
В ФФ хорошо всё, а вот Хромиум генерит его ужасно.

В ФФ ещё этот блок в одну строку со горизонтальным скроллом.
