### ISSUE TITLE
Улучшения для новичков в сообществе

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#358]
В скайп-чате родились идеи:
1. Пояснительный текст перед заданным вопросом у тех, у кого рейтинг ниже 20 или для первых N вопросов, по типу stackoverflow
2. Сделать тур по аналогии http://drupal.stackexchange.com/tour
3. Сделать доп.мотивацию для помощи новичкам, а именно: сделать метку "new" для новых пользователей (допустим показывается на первых 5 вопросах пользователя) и ответ на этот вопрос дает рейтинг с повышенным коэффициентом.
4. Не учитывать в рейтинге пользователя минусы за первые 5 вопросов.

**Comment by drupby** [comment]
Вслед за туром нужно сделать и help http://drupal.stackexchange.com/help с пояснениями и правилами, как и какие вопросы можно задавать и по каким причинам вопросы могут быть удалены, то же самое и про ответы и комментарии. Только help в отличии от drupal.stackexchange лучше бы вместить на одну страницу

**Comment by Niklan** [comment]
Добавил рекомендации при добавлении вопроса пользователями, чей ретинг ниже того, который требуется для использования рейтинга. На данный момент 20.

**Comment by Niklan** [comment]
Ещё сделал #17

**Comment by Niklan** [comment]
![image](https://cloud.githubusercontent.com/assets/2356744/11262971/8b3e3642-8ea7-11e5-9ad3-eb9e3fb5e3b7.png)
Когда жмешь на кнопку "Добавить ответ" на askubuntu. Отличное решение, и более заметное чем просто сообщение над формой.
