### ISSUE TITLE
/question: при нажатии ^ около ответа (стрелка вверх), перебрасывает наверх, оповещения нет

### ISSUE THREAD

**Issue by petrovnn** [Niklan/Dru.io#359]
Должно говорить что-то вроде "у вас недостаточно кармы чтобы голосовать за ответы"

**Comment by Niklan** [comment]
Должно писать...
https://github.com/Niklan/Dru.io/blob/master/sites/all/modules/custom/druio/druio.module#L341

**Comment by petrovnn** [comment]
При нажатии на стрелки у самих вопросов, действительно пишет. А при нажатии на стрелки у ответов на вопросы - не пишет, а просто перебрасывает вверх
