### ISSUE TITLE
Улучшение комментариев для ответов

### ISSUE THREAD

**Issue by semyondragunov** [Niklan/Dru.io#36]
На друру, можно выделить часть текста, жмякнуть кнопку и получишь цитату в окне редактора текста внизу. Это мне нравилось, это очень удобно. Предлагаю сделать тоже самое.
Вы скажете, а редактора нет при комментах: ну дак пусть выделит жмякает и едитор появится, в модалке можно, а можно и развернуть под ответом/вопросом. И вообще путсь едитор при комментах появляеться всегда, без перезагрузки.

Зачем? Я вот лично всегда пытаюсь убрать перезагрузки страниц, если это не вредит SEO. Так как:
1) Нагрузка на сервер ниже. Следствие... хотя кому я тут объсняю, не маленькие!)
2) Дэто круто и удобно!

З.Ы:
Новый предгалаемый функционал:
Отставить кнопку "Ответить", но придать ей функцию: открываем модалку с редактором и вприсываем в начало ник для коммента. К примеру как делается тут на гите с помощью @. Но привязка @Юзер будет не к пользорвателю, а к комментарию по пермалинку.

**Comment by SemanticsPRO** [comment]
ajax comments подтянуть только если.
Цитирование "как на д.ру" у меня есть в двух вариантах, непосредственно как на д.ру и для модуля quote

**Comment by fortis** [comment]
пока ж еще не решили будут ответы на комменты деревом или нет, если будут то с цитатами выйдет фигня

**Comment by semyondragunov** [comment]
Деревом в любом случае будет ИМХО, только позже.
Ну тогда редактор для комментов в модалку пихать чо...

**Comment by Niklan** [comment]
Не нужно дерево комментов в ответах, ну вообще ненужно. Вы представьте нить, куда она потянется? Проще приучить обращаться по имени\нику, чем такие огороды раздувать вправо, а если в ответе код? Он же утпо нечитаем будет. 100% ненужно в ответах делать комментарии древовидными.

**Comment by semyondragunov** [comment]
@Niklan Ну идея здравая. Тогда отставить кнопку "Ответить", но придать ей функцию: открываем модалку с редактором и вприсываем в начало ник для коммента. К примеру как я сделал в этом сообщении. Но привязка @Niklan будет не к пользорвателю, а к комментарию по пермалинку.

**Comment by xandeadx** [comment]
> Не нужно дерево комментов в ответах

+1. категорически не нужно

**Comment by fortis** [comment]
В вопросах-ответах ссылка скорее всего нужна только для комментариев первого уровня, там ведь не дискуссии, обсуждение одного из вариантов решения проблемы

**Comment by semyondragunov** [comment]
@fortis И что, что обсуждения, то есть я буду писатьв пустоту и непонятно кому. Видишь щас же понятно что тебе написал. Это применимо только к комментариям.

**Comment by Niklan** [comment]
Так значит надо приучить обращаться по имени\нику.

**Comment by fortis** [comment]
символ @ есть у всех на клавиатуре))

**Comment by semyondragunov** [comment]
@Niklan Да!!!! Я к этому и веду, и чтобы упростить это, сделать данный функционал.

**Comment by fortis** [comment]
@Niklan @Niklan 
@EmperorSAM 
у меня вот получается ^^

**Comment by semyondragunov** [comment]
Давайте уже вердикт и позакрывает кило ишьюзов сразу.

**Comment by fortis** [comment]
я бы вообще не делал цитирования оно засоряет комменты только

**Comment by semyondragunov** [comment]
@fortis Я думаю сначала надо попробовать просто добавить мною предлагаемый функционал. И посмотреть чем будут чаще пользоваться к комментах, цитатой или обращением по нику. ИМХО чаще будут 2м.

**Comment by Niklan** [comment]
Во вариант придумал.
![вариант](http://i.imgur.com/jFvgtsR.png)
Значит так. Отображаем небольшую кнопочку "N ответ(-а, -ов)". При нажатии показываются все комментарии к ответу, при повторном закрываются. Ну и стрелочка будет менять вид, типа внизу вверх. 

Плюсы:
-  Изначально страница пустая, сплошные ответы;
-  Экономия места;
-  Можно отображать в более крупном формате, а не мелком, включая аватарки и т.д.

Минусы:
-  Возможно будут не догадываться нажать, а иногда часть ответа в комментарии может быть. Хотя это уже, скорее, проблемы тех кто не догадается по такой видной кнопке жмакнуть.

**Comment by semyondragunov** [comment]
Надо добавить в эту кнопку (Новых N Коментов или тупо цифру). Идея норм ИМХО.
А что по поводу редактора и коментов то?

**Comment by fortis** [comment]
аватарка не в тему как-то рядом со стрелками. 

зачем придумываешь, возьми как есть, все уже придумано и эффективно используется. сейчас на стеке видя ответ я пробегаюсь по мелким комментам чтобы заранее увидеть возможные проблемы, особенно если вариантов решения мало и они проблемные - прятать их не надо совсем.

**Comment by semyondragunov** [comment]
@Niklan Хорошая идея, надо так сделать. + Предыдущий мой коммент (или вариант подсветить кнопку классом-цветом если есть новые комменты на ответ).

А чо по поводу ответа на комент то (см. шапку ишьюза (ЗЫ))?

Решение принято? Или обсуждаем дальше?

**Comment by Niklan** [comment]
#44 перекат. Оставим на новый дизайн.
