### ISSUE TITLE
Сделать промо страничку /drupal-8.0

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#364]
Простенькую страничку + небольшое промо на главной.

Страничку по примеру: https://www.drupal.org/drupal-8.0 пока с небольшим кол-вом инфы, далее если что дополнимю

**Comment by fortis** [comment]
на орге локализацию ввели, кажется скоро там промо страничка на русском будем

**Comment by Niklan** [comment]
Там всегда были локализации для мажорных релизов.

**Comment by Niklan** [comment]
https://www.drupal.org/drupal-7.0/ru

**Comment by Niklan** [comment]
Сначала сделаем аналог, потом если что перепишем. или переделаем. Хуже точно нам не станет

**Comment by adubovskoy** [comment]
С главной вопрос.

Может один из этих?
![ok23](https://cloud.githubusercontent.com/assets/297623/11154577/472fbb38-8a51-11e5-803a-b396362da028.png)
![ok24](https://cloud.githubusercontent.com/assets/297623/11154581/4a66d200-8a51-11e5-911f-5bb47fd6e9b3.png)

**Comment by Niklan** [comment]
2ой вариант нравится больше
