### ISSUE TITLE
"Ответить" - убрать в обсуждениях

### ISSUE THREAD

**Issue by fortis** [Niklan/Dru.io#37]
ссылка не нужна (нет дерева) и ведет на отдельную страницу. нужна только в вопросах-ответах

**Comment by semyondragunov** [comment]
Да, тупо переименовать в "добавить коммент".
А по поводу отдельной страницы: https://github.com/Niklan/DrupalCommunity/issues/36

**Comment by fortis** [comment]
как тут по символу @ можно выводить список имен для вставки в редактор и этого должно быть достаточно

**Comment by semyondragunov** [comment]
Зыкрывай ишью, всё равно все спроты тут: https://github.com/Niklan/DrupalCommunity/issues/36
