### ISSUE TITLE
А как вставлять картинку справа-слева?

### ISSUE THREAD

**Issue by tlito** [Niklan/Dru.io#374]
не дает эффекта:
`<img src="http://dru.io/sites/default/files/user-images/2015-11/686/drupal-media.png" style="float:right;margin-left:1.5%;">`

**Comment by fortis** [comment]
думаю что пока нет такой возможности и фильтры режут аттрибуты. форматирование пока в низком приоритете, но возьмем на заметку спасибо

**Comment by Chi-teck** [comment]
В восьмерке вроде это поддерживается.

**Comment by EvgeniyMukhamedjanov** [comment]
Попробуйте атрибут align для картинки. Насколько я знаю, атрибут style фильтруется, т.к. туда можно вписать яваскрипт.

**Comment by tlito** [comment]
спасибо получилось пример http://dru.io/post/4586

**Comment by fortis** [comment]
круто) мы то и не знали)
