### ISSUE TITLE
Материалам на главной требуется премодерация

### ISSUE THREAD

**Issue by fortis** [Niklan/Dru.io#379]
нужно редактировать

**Comment by adubovskoy** [comment]
Заменим людей человекоподобными роботами! (с).

Давайте алгоритм лучше придумаем для публикаций.

На главной:
1. в информационных блоках (где только заголовки) публикуется вообще все, кроме того где рейтинг меньше -5.
2. в promoted публикуется все, у чего рейтинг (кол-во участников для мероприятия) выше +5, а также то что выделено вручную как "опубликовано на главной" (важные события типа новостей по кэмпам).

**Comment by fortis** [comment]
то что публикуется само тоже может требовать редактирования, материал может быть полезным и интересным но с заголовком: Пацаны я нашел как заставить эту хрень работать

**Comment by fortis** [comment]
хотя наверно надумал, начать точно можно с твоим вариантом, и уже если будет необходимо подумать над чем-то типа #380
