### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by UksusoFF** [Niklan/Dru.io#38]
То что RSS есть это хорошо!
http://community.drupalife.com/post/16
Но почему его нет в head?
link rel="alternate" type="application/rss+xml" title="DrupalCommunity: Вопросы" href="http://community.drupalife.com/rss/questions"

**Comment by Niklan** [comment]
Да потому что он выведен через одно место, вот и нету) Надо добавить.

**Comment by als-studio** [comment]
Поддерживаю. Тоже не нашел в заголовках, удивился.

**Comment by UksusoFF** [comment]
Посты в RSS после обновления кривые, не содержат текста, только единички, нолики и аватарка не нужная ![rss](https://cloud.githubusercontent.com/assets/1931442/7040756/7e9486b4-dde3-11e4-9284-6dfb4d079c91.png)

**Comment by Niklan** [comment]
Починил

**Comment by UksusoFF** [comment]
Хорошо! Осталось добавить в head (:
