### ISSUE TITLE
Оформление системных сообщений drupal

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#383]
Как-то полетели. Выглядят не верно. Нет отступа. нет рамки. Хотя фон и цвет текста остались прежними.

**Comment by adubovskoy** [comment]
Пока мы все тут... ) 
http://druio.examplesite.ru/question/4575 - посмотри, вроде нормально. правок не было, просто вывел примеры. https://qsnapnet.com/snaps/po3i6ex3n3gfd2t

**Comment by adubovskoy** [comment]
Закрывать ишью?

**Comment by Niklan** [comment]
Да, они исправились после того как я пул сделал с какими-то правками. Вроде по друпал 8
