### ISSUE TITLE
Продажа услуг

### ISSUE THREAD

**Issue by tlito** [Niklan/Dru.io#384]
если сайт сообщества будет удовлетворять интересам заказчиков, то можно продумать эту составляющую: демонстрация, продажа услуг и продвижение участников. на данный момент только рейтинг помогает это понять.
также необходимо:
1. в профиль добавить "предлагаемые услуги", чтобы участники могли заявить о своих услугах, а заказчики в дальнейшем лучше изучать профили
2. инфо для заказчиков как пользоваться страницей Заказов. желательно сео-ориентированная презентация или текст
3. для участников продумать поощрения в виде рекламы их услуг: слайд на главной или на странице "Услуги разработчиков", поднятие в "Рейтинге разработчиков" - для тех, кто вносит вклад, делает коммиты или набирает рейтинг
4. Рейтинг разработчиков - предлагаю сделать раздел Примеры выполненных проектов или Галерея Друпал-сайтов, куда разработчики могли бы добавлять свои проекты и скриншоты, а другие голосовали бы. тогда на основе голосов производить расчёт рейтинга. те, кто открыто публикуют свои работы (а проверить принадлежность можно как на яндкексе - загрузкой спец файла с хэшэм) - так вот - тем разработчикам больше вероятность быть в топе. А кто не показывает свои сайты - тот не в рейтинге.
5. главная должна включать раздел для заказчиков: Рейтинг ,Галерея сайтов, Услуги 

В целом: если подключить бизнес-составляющую, намного живее будет сайт, и участие на нём будет лучше восприниматься его обитателями. дайте людям такую возможность наполнить сайт полезной информацией для заказчиков.

**Comment by adubovskoy** [comment]
Закрыто до момента переноса на d8 и обсуждения #6 .

Поле с услугами/специализацией в профиле - да, имеет смысл. Остальное требует обсуждения. Отложим до d8.
