### ISSUE TITLE
Список заявок на заказ

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#386]
Считаю что стоит его немного переработать, а точнее доработать.

Именно данную часть с использованием рейтинга нам выставляют как главный недостаток сообщества. Типа кто тут давно, у того рейтинг выше, тот выше в заказах и рубит "всю капусту". Хоть у нас такого и нет, но это первые впечатления.

Я думаю будет вполне справедливо сделать сортировку по умолчанию по дате флага. Т.е. кто первый нажал - тот выше всех. Это честно, не предвзято, и самый нейтральный вариант.

При этом вверху списка предоставить инструменты фильтрации данного списка. По сути дата заявки просто будет сортировкой по умолчанию, также дать возможно сортировать по рейтингу. Тогда я думаю негатива будет меньше.

Также дать пометку, что высокий рейтинг - не значит что человек знает больше тех, у кого он меньше. Это я думаю и так всем ясно. Банальный пример @drupby @adubovskoy имеют рейтинг меньше чем у меня, хотя они знают намного больше меня. Что и является показателем того, что высокий рейтинг, не всегда означает больше знаний - это лишь показатель активности, не более.

Это явно снизит кол-во негатива и будет как-то легче восприниматься новичками.

**Comment by adubovskoy** [comment]
Ок, давай.

> хотя они знают намного больше меня

это ты загнул) у меня по d8 вот например пока ни одной статьи) учусь у тебя как с очередями d8 работать.

**Comment by Niklan** [comment]
@adubovskoy зато я 0 в верстке на д8 и остальном что не задел в постах. И буду учиться с твоих докладов)  Я уж про д7 молчу.
