### ISSUE TITLE
Выработать инструкции и практику по использованию Configuration Manager

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#388]
Перед тем как бросаться за реализацию функционала на 8-ке, нам стоит попробовать и разобраться с конфигурациями, их применением и написать инструкции что да как. Надо задействовать их по-максимуму, чтобы любой желающий мог без доступа к базе делать правки.

**Comment by Chi-teck** [comment]
С конфируграцией Drupal 8 работать намного проще чем с фичами. По сути достаточно знать всего две драш комманды.

``` bash
# Получаем актуальный код из удаленного репозитория
git pull origin 8.x-1.x

# Импортирум кофигурацию в базу.
drush cim

# Редактируем что то в файлах или в админке.
...

# Экспортируем конфигурацию в файлы.
drush cex

# Коммитим.
git commit -am"Some new feature."

# Отправляем правки в удаленный репозиторий.
git push origin 8.x-1.x
```

**Comment by Niklan** [comment]
@Chi-teck прямо блеск. :tada: Большое спасибо ;)
