### ISSUE TITLE
Защита аккаунтов

### ISSUE THREAD

**Issue by tlito** [Niklan/Dru.io#389]
вход на сайт должен  быть защищен
1. использованием логина, отличного от ника (или как удобно пользователям)
2. использованием емайла в качестве логина (без возможности использования ника в качестве логина, как на тостере)

тогда имена участников не обязательно будут информацией для входа, это может ограничитьь активность злоумышленников.

**Comment by adubovskoy** [comment]
не является уязвимостью. также почта зачастую дублируется в открытом профиле.

по повышению безопасности можно покопать, но там скорее вопрос полноценного аудита нужен.
закрываю, переоткройте если есть еще мнения.
