### ISSUE TITLE
Ссылка на данный репозитарий в сообществе.

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#39]
Считаю что нам необходимо сделать на видном месте ссылку/баннер на данный репозитарий или ишьюсы напрямую, чтобы каждый мог увидеть и при желании поучаствовать с нами в дискуссиях.

**Comment by semyondragunov** [comment]
В шапку, гит иконкой.

**Comment by UksusoFF** [comment]
Или в основную менюшку

**Comment by Niklan** [comment]
Готово с новой темой.
