### ISSUE TITLE
Фильтрация на странице заказов.

### ISSUE THREAD

**Issue by bsyomov** [Niklan/Dru.io#390]
На странице заказов, вместо списка последних вопросов, куда разумнее, смотрелась бы фильтрация по статусу заказа. И возможно, по каким-нибудь другим критериям: 
Например добавить тип заказа (доработка, разработка, вёрстка, etc.). 
Наличию или размеру бюджета.
Когда заказов станет больше, это может сильно помочь ориентироваться.

Также, было бы здорово отмечать, например цветом фона, статус заказа в списке, примерно также, как это сделано с вопросами имеющими решение.

**Comment by adubovskoy** [comment]
да. Боюсь это уже после миграции на d8. Но доработка/улучшение раздела заказов будет приоритетной сразу после миграции.

**Comment by fortis** [comment]
можно еще показывать когда последний раз заказчик просматривал свой заказ, чтобы косвенно можно было определить какие уже не актуальны

**Comment by Niklan** [comment]
Обе идеи нравятся. Только ЗА, но как сказал Александр, тут скорее всего уже после миграции
