### ISSUE TITLE
Решить как делать ответы в 8-ке

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#391]
Что имеем в 8-ке. Наконец-то! мы можем цеплять комменты к чему угодно- это поле.

Можем создать тип комментариев - Ответ или оставить как есть: Ответ - нода.

Возможные плюсы и проблемы:
- Комментарии легче (на много ли?)
- Нода гибче
- Комментарии нельзя депубилковать, они только удаляются. Либо придется мириться, либо костылить полями - что уже сводит на нет идею с комментами, проще с нодой в таком случае, ибо она гибче выйдет, а учитывая что разницы там почти никакой в сущностях, то и не факт что тяжелее окажется.

disquss

**Comment by Niklan** [comment]
- ноды будет проще мигрировать из 7-ки

**Comment by adubovskoy** [comment]
Всякие готовые нотификации в контрибе будут писаться для комментов.

**Comment by adubovskoy** [comment]
Можно поле сделать у коммента, с правами закрытыми, "депубликован", например
и по нему фильтровать.

**Comment by drupby** [comment]
А как быть с комментами к ответам тогда? Если ответы будут комментами.

**Comment by Niklan** [comment]
Там разные типы комментариев можно делать. К полю-комментарию ответ, добавить поле-комментарий обычный. Ага, вот такое вот.

Я все же буду за ноды, еще в голову пришло. А вдруг мы захотим убирать дубликаты. Например с нодой просто - мы можем ответ привязывать сразу к нескольким вопросам (одинаковым, конечно), а вот комменты уже нет.

**Comment by Niklan** [comment]
> Можно поле сделать у коммента, с правами закрытыми, "депубликован", например
> и по нему фильтровать.

И о чем я говорил, уже какие-то "костыли" попрут с комментов. Я считаю нода гибче, но надо обсудить

**Comment by adubovskoy** [comment]
Референсы по похожим вопросам/ответам это конечно аргумент, да. Основное нарекание наверное только в том что трекер придется пилить целиком самим.... ну, почему бы и нет.

**Comment by fortis** [comment]
я за комментарии, трекера у нас до сих пор нет и это большая проблема плюс раз в 8ке комменты стали гибче то и контрибы под них могут еще появиться потом, а с нашими нодами ничего не прикрутишь

а с дубликатами мы не будем бороться да и не за чем, потому что они всегда будут возникать, и бывает так, что ответ похожий, но с дополнениями, тут лучше в поиск посылать. 

так что я за ядро и уведомления с трекером из коробки

**Comment by drupby** [comment]
Так трекер из коробки все равно не будет учитывать комменты к ответам.

**Comment by fortis** [comment]
комментарии не нужно депубликовать их надо удалять, этих сущностей будет больше всего в базе да и незачем хранить их в ущерб производительности.

да и по скорости я не уверен что ноды не так уж и плохо, у нас действительно медленно открываются вопросы которые не попали еще в entitycache

**Comment by fortis** [comment]
@drupby трекер учитывает комменты к вопросу, ответ и комментарии к нему там тоже будут

**Comment by drupby** [comment]
@fortis где ты такой трекер из коробки в восьмерке видел?

**Comment by fortis** [comment]
трекер в смысле функционал, нода-вопрос и количество новых комментариев к ней + уведомления на почту чем не подойдут? следи за вопросом и комментариями к нему, как на друру: оставил комент и получаешь потом все уведомления, можешь галочку поставить и отписаться

**Comment by drupby** [comment]
> дак нода-вопрос и количество новых комментариев к ней 

А как же комментарии к ответам-комментариям? Будут видны получается только новые ответы.

**Comment by fortis** [comment]
если мы все делаем комментариями то комментарий к ответу это... ответ на ответ = тоже комментарий и будет учитываться как новый комментарий к ноде, нет?

**Comment by Niklan** [comment]
Нет. Этот комментарий будет к комментарии у учитываться в нем же а не ноде

**Comment by drupby** [comment]
Во-первых в восьмерке из коробки отсутствует вьюха с трекером - надо делать свою. А во-вторых коммент прикрепленный к комменту не относится напрямую к ноде.

**Comment by Niklan** [comment]
Именно мы хоть как свой делать будем. Не сразу так позже. Так что это не аргумент

**Comment by Niklan** [comment]
Трекер*

С телефона нельзя править

**Comment by fortis** [comment]
да не может быть у любого комментария есть ссылка на ноду (сущность) http://take.ms/fJGFv
это было бы странно если б модуль комментариев не видел (не считал) новые комментарии если они с иерархией

**Comment by fortis** [comment]
я отредактировал выше, сейчас ноды с вопросами реально тяжелые пока не попадут в entitycache и пока открываются tlito успевает досчитать до 12, это так)

**Comment by drupby** [comment]
Хотя в восьмерке все же есть модуль Activity Tracker

**Comment by drupby** [comment]
Получается, если делать комментами, то нужно добавлять к ноде-вопросу два поля с комментами:   первое - для комментов самого вопроса, второе - для ответов.

**Comment by Niklan** [comment]
> Получается, если делать комментами, то нужно добавлять к ноде-вопросу два поля с комментами: первое - для комментов самого вопроса, второе - для ответов.

Да, о чём я и говорю. Мы добавляем ноду - Вопрос, ноде Вопрос мы добавляем поле-комментарий типа "Ответ" к комментарию типу Ответ мы добавлем поле обычных комментов.

Может не будет велосипедить, пойдем путем как сейчас на нодах? Он уже проверен и гибче комментов. Учитывая во что превратились комменты в 8ке, мы явно не получим скорости в работе от перехода на них. А вот дополнительные доработки получим.

**Comment by fortis** [comment]
давай проверим на пустой 8ке и посмотрим как оно будет с активити трекером

**Comment by drupby** [comment]
> давай проверим на пустой 8ке и посмотрим как оно будет с активити трекером

Здесь согласен, нужно протестировать и если будет работать с трекером, то останутся только вопросы с миграцией - пока однозначного принятия решения этого вопроса нету.

**Comment by Niklan** [comment]
Миграция на потом - сначала воссоздадим структуру. Потом будем миграции писать.

**Comment by Niklan** [comment]
Вопрос вроде как решен. Ещё раз недавно обсудили в чатике, у вопросов и ответов будет два типа комментариев: комментарий — ответ и самый обычный.
