### ISSUE TITLE
Не могу отключить HybridAuth

### ISSUE THREAD

**Issue by anton-staroverov** [Niklan/Dru.io#392]
Зарегистрировался через Twitter и теперь не могу изменить свое имя в профиле.

Отключить HybridAuth тоже не могу, так как он просит добавить другой сервис HybridAuth.

Вопрос: как полностью отключить HybridAuth и сделать обычный аккаунт со старым добрым email-ом и именем?

**Comment by adubovskoy** [comment]
fixed

**Comment by adubovskoy** [comment]
Теперь вам на http://dru.io/user/1492/edit доступно редактирование имени

**Comment by adubovskoy** [comment]
Единственное что, придется пройти процедуру восстановления пароля на почту.
