### ISSUE TITLE
Говорят плывет верстка главной в IE11

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#395]
Проверьте пожалуйста, накидайте мне скриншотов.

**Comment by Niklan** [comment]
> 2015, почти 2016
> 
> Internet Explorer

IE скоро вообще (по моему в феврале 2016) прекратиться поддерживаться. Смысл заморачиваться?

**Comment by fortis** [comment]
там речь о старых  <= 10

**Comment by Niklan** [comment]
Темболее, зачем нам проект костылями обвешивать для каких-то убогих браузеров которыми никто не пользуется.

![IE SUCK](http://i.imgur.com/fxsrzyM.png?1)

Посмотрите насколько ничтожна доля IE у нас.

**Comment by adubovskoy** [comment]
Нет, именно в 11м (последнем) плохо. Это надо чинить. Но собстно починил. Но надо посмотреть как в страрых теперь (10м например), не могу сейчас посмотреть.

**Comment by Niklan** [comment]
А чо это за flex такой на #main? Я такого вроде не делал. К слову, там у нас есть миксины для флексов которые и фолбеки делают и все параметры проставляют принудительно, такой бы фикс был бы не нужен если бы его юзали.

**Comment by drupby** [comment]
У меня на виртуалке в ie 11 вот так http://i.imgur.com/BVN0VR7.png?1

**Comment by Niklan** [comment]
https://github.com/Niklan/Dru.io/blob/master/sites/all/themes/druio_theme/styles/scss/base/_mixin.scss#L158

**Comment by fortis** [comment]
никит сайт должен везде адекватно работать мы ж для людей сделали и есть те кто и с ие 11 зайдет

**Comment by adubovskoy** [comment]
> У меня на виртуалке в ie 11 вот так http://imgur.com/BVN0VR7

а сейчас тестни. я переделал.

> А чо это за flex такой на #main?

sticky footer. Миксины кажись с ie11 не очень умеют. но там фикс буквально 2 символа)

**Comment by fortis** [comment]
заказчики вообще могут с ие 8 приходить кто им запретит

**Comment by Niklan** [comment]
Миксин бы сработал, на который я линканул. Он бы как раз сделал то что ты пофиксил)

**Comment by drupby** [comment]
сейчас уже лучше http://i.imgur.com/HigKE7Q.png

**Comment by adubovskoy** [comment]
> сейчас уже лучше http://i.imgur.com/HigKE7Q.png 

иконки вверху плывут. но это не из-за flex уже.

**Comment by Niklan** [comment]
Видимо из-за transform

надо префиксы добавить

**upd**
не, там без трансформа

**Comment by adubovskoy** [comment]
добавишь? ты под win же вроде, мне на ощупь будет совсем туго

**Comment by Niklan** [comment]
Нет, я под netrunner :)

**Comment by drupby** [comment]
может ie не понимает line-height: 2.5rem; ?
который прописан для #header .pane .content .top .header-links .link.tracker:before, #header .pane .content .top .header-links .link.github:before

**Comment by Niklan** [comment]
Сомнительно, тогда бы всё плавало вообще. У нас везде rem

**Comment by adubovskoy** [comment]
> может ie не понимает line-height: 2.5rem; ?

а тестни http://druio.examplesite.ru/ , там px сейчас, посмотрим.

**Comment by drupby** [comment]
http://i.imgur.com/fk9JNJ4.png

**Comment by adubovskoy** [comment]
ага, есть. нормально. поиск я не трогал.

**Comment by adubovskoy** [comment]
мне не нравится строгое значение в px, но видимо пока так.

**Comment by adubovskoy** [comment]
поиск не починился. скрин с wp телефона
https://scontent-frt3-1.xx.fbcdn.net/hphotos-xal1/v/t34.0-12/12311974_1080931951919999_1806937837_n.jpg?oh=773110beba0f5f3aadbf0c37cc929591&oe=565D22C3

**Comment by drupby** [comment]
для #header .pane .content .top .search-form:before нужно тоже в px прописать

**Comment by adubovskoy** [comment]
http://druio.examplesite.ru/ так норм?

**Comment by drupby** [comment]
так нормально

**Comment by drupby** [comment]
как вариант можно для line-height прописать два значения: первое в пикселях, а второе в rem

```
line-height: 37px;
line-height: 2.5rem;
```

**Comment by Niklan** [comment]
Да, так правильнее, у нас так @include font-size() работает

**Comment by Niklan** [comment]
![bug](http://i.imgur.com/VUtksmp.jpg?1)

Нахимичили что-то.
height у `#header .pane .content .top .search-form .search-input` должен быть 40px а не 37, и такой же line-height у иконки.

**Comment by adubovskoy** [comment]
а у меня на 40 плывет меню нижнее.

**Comment by Niklan** [comment]
Chrome Версия 46.0.2490.86 m, Windows 10 Pro
Надо просто проверить еще кому-то тогда

**Comment by drupby** [comment]
да, инпуту нужно выставить height: 40px;
тогда уже нужно и ссылкам (вместе с иконками в :before) #header .pane .content .top .header-links .link выставить   line-height: 40px чтобы они были в линию с placeholder у инпута

**Comment by Niklan** [comment]
Подтверждаю. На линуксе тоже нужно 40

**Comment by Niklan** [comment]
Причем ссылкам с иконками - тоже

**Comment by adubovskoy** [comment]
пока оформил pr на откат изменений. https://github.com/dru-io/Dru.io/pull/400 .

**Comment by Niklan** [comment]
Надо у менюшки тоже поправить "Трекер, GitHub". Тоже отступ остался, также нужно 40px.
