### ISSUE TITLE
D8 Заказы: Словарь "статус заказа" мигрировать в поле

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#396]
Есть мнение что там где привязан функционал (у нас в зависимости от статуса заказа зависит темизация, как минимум), это нужно хранить не в термине таксономии, а в поле (список, текст). И код читабельнее, без tid == 47 и констант и в конфигурациях хранится. То что сейчас сделано на быструю руку и работает, но в d8 версии хочется переделать.

**Comment by adubovskoy** [comment]
собственно сам и виноват первоначально. оке, попишу миграции теперь.

**Comment by als-studio** [comment]
Кажется, имеет смысл привязать к #419

**Comment by Niklan** [comment]
Done
