### ISSUE TITLE
Проблема при входе на сайт

### ISSUE THREAD

**Issue by roman-yakimkin** [Niklan/Dru.io#397]
Добрый день.

Не получается просто выполнить вход на сайт.
Через "Забыли пароль" вхожу по одноразовой ссылке. 
Далее меняю пароль.
При входе по новому паролю пишет, что 
"Обнаружена атака в виде подбора captcha"
"Вы ввели неправильный ответ на контрольный вопрос"

Хотя никакой капчи я не вижу, и никакой ответ на вопрос я не вводил.

И приходится входить через Facebook, это работает.

**Comment by adubovskoy** [comment]
Изменили настройки капчи, проверьте еще раз пожалуйста.

**Comment by roman-yakimkin** [comment]
Проверил.
На капче трудно разобрать, что нужно вводить.
И нет возможность загрузить новое изображение.

Ну а после того, как ввел данные, высветилось сообщение, что неверное имя пользователя или пароль. Хотя e-mail пользователя совпадает, пароль я сам сегодня новый вводил.

**Comment by adubovskoy** [comment]
Поправил перевод.  Это неверная капча значит . И упростил ее на 1 символ.

**Comment by roman-yakimkin** [comment]
Получилось.
Но в капче все-таки некоторые буквы сложно распознать в плане - прописные они или строчные. Например, "P".

**Comment by Niklan** [comment]
Может reCaptacha от Google поставим. Сейчас вообще какая?

**Comment by roman-yakimkin** [comment]
А mollom не хотите подключить ?
Или он для данной задачи не годится ?

**Comment by adubovskoy** [comment]
mollom имхо не универсален и в неанглоязычном контексте не очень корректно себя иногда ведет.
Но в целом я посмотрел логи, проблем со входом у народа вроде сейчас нет, закрываю пока.

**Comment by UksusoFF** [comment]
Зачем вообще капча на логине?

**Comment by adubovskoy** [comment]
боты пришли умные однажды. пришлось повесить.

**Comment by UksusoFF** [comment]
Вообще все юзабилити ломает. Менеджеры паролей не используешь теперь.
И все же какой смысл ставить именно на логин? Оставить на регистрацию и все. Если уж они на реге прошли, то и на логине пройдут.

**Comment by adubovskoy** [comment]
На вход поставил hidden captcha. Проверь не спотыкаются ли на ней твои менеджеры паролей. А я помониторю что там с ботами будет.

**Comment by adubovskoy** [comment]
> И все же какой смысл ставить именно на логин? Оставить на регистрацию и все. Если уж они на реге прошли, то и на логине пройдут.

там был вопрос что имена вполне релевантные были, как и почта. т.е. я не мог вычленить кто живой пользователь кто бот и прибить ботов. это когда они уже зарегились скопом.

**Comment by UksusoFF** [comment]
Да, все ок.

**Comment by UksusoFF** [comment]
Опять вылезла :(

**Comment by adubovskoy** [comment]
А какая? Там гугловская капча должна быть (галочка). И это норм по юзабилити по идее.

**Comment by UksusoFF** [comment]
Ну да. Только кейс с менеджерами паролей все равно сломан. Ибо он заполняет логин и пасс и пытается сабмит формы сделать.

**Comment by adubovskoy** [comment]
Ок, уберем и закроем как будет решена https://github.com/dru-io/Dru.io/issues/423 .

**Comment by fortis** [comment]
по 423: 
есть боты которые зарегались и вошли 2 недели назад и ранее. выходит текущая капча не помогает, возможно стоит оставить спамбот для проверки емейла по базе стопфорумспам при регистрации (пока выключено) ну и посмотреть что у нас с капчами, может что-то недокрутили, но сначала нужно избавиться от того что мешает нормальным пользователям (автозаполнение сломано)

**Comment by fortis** [comment]
при копировании и вставке вручную в поля тоже сообщение красное появляется "Обнаружена атака ввиде подбора CAPTCHA"
