### ISSUE TITLE
В promoted материалах оставить 1 на главной

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#399]
Долго скролить к последним вопросам. А именно там обновление инфы частое.
Останется 1 пост про кэмп.

**Comment by fortis** [comment]
верхушка с картинкой занимает всю высоту экрана на ноуте и чтобы хоть что-нибудь увидеть нужно скролить, бесполезный блок и текст http://take.ms/o4XYD

по мне лучше его убрать чем материалы которые сообщество продвинуло на главную

**Comment by adubovskoy** [comment]
Уберем для залогиненных?

**Comment by adubovskoy** [comment]
Но и сократить promoted тоже имхо нужно.

**Comment by adubovskoy** [comment]
<img src="https://qas-shared-assets.s3.amazonaws.com/snaps/zv7nz9jdtj8257b"/>

Вот так будет залогинненным

**Comment by fortis** [comment]
но их всего-лишь 3 )))

**Comment by adubovskoy** [comment]
У меня типовой кейс захода:
1. Заход на главную
2. Скролл
3. Клик на вопрос.

зачем скролл?

**Comment by adubovskoy** [comment]
Или давай оставим 3 но опустим ниже обновляемого контента

**Comment by Niklan** [comment]
Убирать плашку с картинкой не нужно, по крайней мере для гостей.

Думаю 3ех вполне достаточно чтобы висели в топе. Остальные есть ниже в общем списке.

**Comment by adubovskoy** [comment]
> Убирать плашку с картинкой не нужно, по крайней мере для гостей. 

так речь именно о зарегенных. Анонимам как сейчас, авторизованным плашку убирать.

**Comment by fortis** [comment]
а что в ней хорошего? у нас есть промо страничка, чтобы рассказать о друпал, даже анонимам этот блок нужен один раз, потом его просто игнорят

**Comment by fortis** [comment]
ладно бы еще только второй абзац, хотя по мне итак понятно куда я попал и что тут можно делать, мышкой все кликать умеют.

"Добро пожаловать на Dru.io. Русскоязычное Drupal сообщество" - у нас в логотипе есть уже это.

первый абзац - вода, друпал можно заменить на wordpress, joomla, bitrix. 

у нас внизу страницы про друпал есть блок со ссылкой на полноценную страницу и в самом низу ему и место, а обновления контента должны быть видны сразу, выше

мне кажется лучше анониму показать интересные новости или вопросы которые задают другие, чем на всю высоту экрана рассказывать о том, что у нас тут есть новости, люди и вообще-то можно задать вопрос)))

**Comment by fortis** [comment]
> > У меня типовой кейс захода:
> > 1. Заход на главную
> > 2. Скролл
> > 3. Клик на вопрос.
> > зачем скролл?

а ты не читаешь статьи, а отвечаешь на вопросы, но кто-то вообще не смотрит чужие вопросы, кому-то интересны обсуждения и статьи, пока их мало, но лента материалов есть.

по мне оптимально было бы иметь ленту публикаций, мероприятий, с выводом трех тизеров и ниже списком заголовков, а в сайдбаре вопросы

**Comment by adubovskoy** [comment]
> кому-то интересны обсуждения и статьи, пока их мало, но лента материалов есть.

давай просто статистику вебвизора посмотрим и будем ориентироваться на большинство?) завтра займусь.

**Comment by fortis** [comment]
что покажет вебвизор на плохой странице где надо скролить?) мне кажется только то что большинству не нравится скролить и все ссылки недостаточно востребованы))

**Comment by adubovskoy** [comment]
что статьи в таком объеме не нужны. не?)
вообще тема редизайна главной назревает. Давайте попробую на своей dev-копии, покажу потом что вышло. Общая цель:
- убрать шапку для анонимов
- вывести другие типы материалов на главную (мероприятия + заказы)
- упростить доступ к последним вопросам.

**Comment by fortis** [comment]
попробуй с сайдбаром, у нас текст размазан в ширину так, что картинки приходится в анонсы ставить

**Comment by multpix** [comment]
Для авторизованных, по заходу на главную, может быть редирект на свой (настраиваемый) дашборд.

Такое решение с орга - вполне удачное.

**Comment by adubovskoy** [comment]
> Для авторизованных, по заходу на главную, может быть редирект на свой (настраиваемый) дашборд.

это вообще идеальное решение. вопрос трудозатрат, скорее всего такое надо делать уже после переезда на d8.

**Comment by Niklan** [comment]
http://webvisor.com/inpage/click_map?url=http%253A%252F%252Fdru.io%252F&id=33842429

А вы гляньте. Эти самые популярные особо никому и не интересны выходит. Народ всё равно скролит до последних публикаций. Смысл тогда какой? Может оно и не надо вовсе? Может лучше ближайшие мероприятия выводить и последние заказы, также в два столбца с минимизированым тизером

**Comment by Niklan** [comment]
![image](https://cloud.githubusercontent.com/assets/2356744/11530094/7dbe40e0-9913-11e5-90e3-8622435e59dc.png)
![image](https://cloud.githubusercontent.com/assets/2356744/11530100/89215ce2-9913-11e5-81b9-8514eedd5d5c.png)

**Comment by Niklan** [comment]
Также из скринов видно, что заказы реально интересуют больше людей чем "популярное содержимое". Я вообще предлагаю пункт заказов в таком случае поставить сразу после "Вопросы".

**Comment by adubovskoy** [comment]
И блок на главной. Я начал вчера, не доделал. http://druio.examplesite.ru . И мероприятия вывести 4ми. Может на выходных покажу.

**Comment by Niklan** [comment]
Хотел идеей поделиться, а глянув на тестовый сайт @adubovskoy увидел там тоже самое.

Суть в том, что коль уж мы поставили метрику — надо ей пользоваться, не для красоты же. Полезная штука там имеется для нашего сайта — карта кликов, о чем я выше упоминал.

Так вот, эти блоки: Последние вопрос, Последние заказы и Последние публикации стоит расположить в порядке слева-направо, сверху-вниз, учитывая это "карту". Там самым востребованным, разумеется, является "Последние вопросы", заказов хоть и нет, но очевидно они также выйдут в топ, ибо публикации у нас крайне редкие, поэтому их надо во второй ряд, оставив рядом с вопросами заказы. Впрочем как не тсовом сайте по ссылке выше.

**Comment by adubovskoy** [comment]
Уже в продакшне. Исправления если будут - открываем отдельные ишью.
