### ISSUE TITLE
Раздел: Каталог Друпал-студий

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#4]
_Раздел планируется, тут обсуждается как реализовывать._

**Раздел:** Друпал-студии.
**Статус:** Запланирован.
**Описание:**
В данном разделе можно будет добавлять компании, которые предоставляют услуги по разработке на Друпал. Скорее всего потребуется жесткая проверка добавляемых сайтов, читаем как ручная. 

Пока не совсем понятно, нужен такой раздел или нет. Планируем, если есть _против_, высказываемся.

**Comment by adubovskoy** [comment]
Как представитель студии скажу -- уже надоело писать о себе во всяких каталогах студий)
Лучше сделать donate, не важно от кого, в стиле "community member", и показывать список тех кто помог ресурсу деньгами. И сделать список тех кто помог не деньгами, как тут https://github.com/Niklan/DrupalCommunity/issues/5#issuecomment-70079084 описано.

**Comment by Niklan** [comment]
Т.е. я правильно понимаю. Делаем рейтинг пользователей в сообществе. Но их будет два:
1.  Он же основной, рейтинг по рейтингу основанному на сообществе, как помог и т.д. и т.п.
2.  Те кто пожертвовал, кто больше, тот выше.

Следовательно Каталог друпал студий и каталог фрилансеров мерджится в один этот рейтинг.

**Comment by adubovskoy** [comment]
угу. Можно без "кто больше тот выше", а несколько градаций и внутри них без сортировки. Это наверное надо уточнять голосованием, у меня нет понимания какой вариант лучше.

**Comment by xandeadx** [comment]
у нас студий то - раз два и обчёлся

**Comment by Niklan** [comment]
Тоже верно. Но как я вижу, рейтинг пользователей смело объединит в себе каталог фрилансеров и компаний. Добавить эти разделы можно будет всегда, а рейтинг пользователей хоть как бы пригодился.

**Comment by semyondragunov** [comment]
Может компании сделать как ноду с референсем на юзера? Аля Гитхаб и т.д.
И тут уже думать:
1) Пока юзер не достигнет определенного уровня фиг ему а не добавить компанию в сообщество...
2) ХЗ
