### ISSUE TITLE
Добавить метку "Готов оплатить время" к типу Вопросы

### ISSUE THREAD

**Issue by AkPeter** [Niklan/Dru.io#40]
Думаю полезная фича, зачастую вопрос так или иначе не решаем без реальной помощи спеца, а труд должен оплачиваться. У самого подобных вопросов уже копится порядочно, но без ТЗ пока не пишу их...

**Comment by Niklan** [comment]
Будет раздел заказов, думаю это будет как раз его цель. Вопрос-ответ это раздел для решение каких-то мелких недопониманий или просто чтобы направили на правильны путь, а не решения всего за того кто задал вопрос. Считаю что если мы сделаем такую галочку + появится раздел заказов, народ не будет понимать разницы.

Если только что-то хитрое сделать. По типу как на staoverflow. Допустим за решение вопроса автор устанавливает гонорар, допустим 500р. После того как он помечает лучший ответ, его автор получает гонорар. Это стимул писать развернутые ответы, причем качественные, а у автора есть реальный шанс получить быстрое решение и простимулировавть отвечающих.

**Comment by SemanticsPRO** [comment]
А я за.
Заказы заказами, а решения решениями.
Неоднократно сталкивался с заказчиками, которые готовы были оплатить какие-то мелочи, но ставили условием публикацию решения

**Comment by Niklan** [comment]
[Тут](http://www.drupal.ru/node/115018?page=1#comment-634238) @adubovskoy доступно объяснил почему не нужно это. Темболее на данном этапе.
