### ISSUE TITLE
Пагинация для малых экранов лезет

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#403]
https://i.imgur.com/dSeAXp8.png

**Comment by sashagar** [comment]
Хотел вместо пейджера поставить https://www.drupal.org/project/views_load_more. Не работает ajax в теме.
Переключил на бартик там ajax работает.
Значит дело в теме.

**Comment by Niklan** [comment]
Думаю нам не нужно views_load_more. Не совсем очевидная штука и ссылку не дать на страницу, что бывает очень полезно. Надо просто убирать часть кнопок на мобилке и всё

**Comment by sashagar** [comment]
А тогда такой вариант. Создать 2 пейджера один в виде кнопок. Второй в виде селекта с выпадающими значениями. И для определенной ширины экрана показывать тот или иной пейджер.
