### ISSUE TITLE
Формулировки заголовков

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#406]
Issue родился из этого обсуждения. https://twitter.com/xandeadx/status/674473236839710720 .

Есть мнение что у нас можно сделать заголовки лучше)

Я правда не очень понял, вот например: http://dru.io/question/5011 . Как должен звучать идеализированный вопрос?

**Comment by drupby** [comment]
> "вот например: http://dru.io/question/5011 . Как должен звучать идеализированный вопрос?"

На заголовки типа: "Срочно нужна помощь", "HELP!!!" и тд нужно реагировать и  они могут неизбежно появиться, но в данном примере по ссылке заголовок вроде понятен и  вопрос задан вполне ясно.

**Comment by Niklan** [comment]
В правилах при добавлении вроде есть про это. Сносить безжалостно такие вопросы вот и всё.

**Comment by evgeniypiter** [comment]
правила никто не читает, слишком дофига текста имхо. надо сократить и визуально подать, чтобы внимание зацепилось.

**Comment by xandeadx** [comment]
> но в данном примере по ссылке заголовок вроде понятен и вопрос задан вполне ясно

это я его исправил

**Comment by adubovskoy** [comment]
https://github.com/DrupalRu/drupal.ru/issues/177 тут есть на эту тему мысль. Валидировать заголовок на "help, sos, срочно, помощь, азазаза")

**Comment by Niklan** [comment]
Нет, лучше сносить не думая и всё.

Вопросов может быть уйма, какова вероятность что "sos", "срочно" не является частью вопроса? А мы будет фильтровать.

Допустим вопрос "Как добавить статус "срочно" для help desk" — сразу под два "запрещенных слова" и в итоге вопрос уже будет задан исковеркано.

В общем стоп-слова явно не выход из ситуации. Проще удалить. Предупреждены теперь все — никакой обиды быть не должно, там прямо написано, что некорректные вопросы будут удаляться. А если быстро не удяляются модерами — их потопят минусы. Вот и всё. У нас уже два варианта как повилять на это. Стоп-слова совершенно не изменят ситуацию. Надо думать что-то более действенное.

**Comment by xandeadx** [comment]
Я в отдельной теме уже предлагал такой вариант:
1. Пользователь пишет вопрос без понятного заголовка
2. Модератор снимает с публикации вопрос и пишет в поле причину
3. Пользователь заходит на сайт и видит вместо вопроса причину снятия с публикации (как на тостере)
4. Пользователь исправляет заголовок
5. Модератору приходит уведомление
6. Модератор публикует вопрос

**Comment by Niklan** [comment]
Хорошая идея

**Comment by adubovskoy** [comment]
++

**Comment by xandeadx** [comment]
@drupby зачем удаляешь мои замечания?

**Comment by adubovskoy** [comment]
где?

**Comment by drupby** [comment]
@xandeadx я комментарии просто подчистил о замечаниях о неправильно составленных заголовках - автор топика увидел, зачем оставлять навсегда и плодить такие комменты?

**Comment by xandeadx** [comment]
@drupby как ты узнал что он увидел?

**Comment by drupby** [comment]
@xandeadx за полдня должен был увидеть, а вообще такие комменты должен видеть только автор топика и в идеале соответственно они должны посылаться оповещением на почту или private message - в самом вопросе эта информация лишняя для посетителей сайта.

**Comment by Niklan** [comment]
@drupby не нужно убирать. Пусть будут. Другие тоже увидят. Хорошие и правильные замечания же.
