### ISSUE TITLE
Проблемы с формой редактирования вопроса из-за ajax

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#409]
После добавления ajax поиска схожих вопросов в форме редактирования вопроса всплыли несколько проблем:
1. Если изменить заголовок и попытаться отправить форму с помощью мышки, то после потери фокуса в форму добавиться новый элемент и кнопка прыгнет вниз. Т.е. с первой попытки попасть в "Сохранить" очень тяжело.
2. Если всё же успеешь попасть мышкой в "сохранить", то заголовок не изменится, так как title в этот момент будет disable.
3. Невозможно засабмитить форму интером.

Предлагаю удалить ajax из формы редактирования, он там бесполезен, так как вопрос уже задан.

**Comment by Niklan** [comment]
+
