### ISSUE TITLE
Публичные правила

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#41]
Вопрос архитектурный и идеологический. Следует ли делать публичную систему правил. Задумался после того как опубликовал рекламу - http://community.drupalife.com/question/269 . 

Два подхода - 
1. Правила нужны, должны следить модераторы. в формате drupal.ru это не работало.
2. Правила не нужны. Нужен просто умный рейтинг. Тот кто набрал много минусов не публикуется, пост с многими минусами сворачивается и сразу не виден, и т.п. Модераторы могут ускорить этот процесс (допустим сделать сразу "-10" к рейтингу), если увидят явный треш в виде мата и т.п.

я за второй подход.

**Comment by Niklan** [comment]
Да, нужно саморегулирование. Пусть само сообщество решает, что есть хорошо, а что плохо. Порой реклама может оказаться очень полезной, так что чтобы всех под одну гребенку не закидывать, надо дать возможность решать каждому лично.

Но я считаю нам нужны правила для материалов на сайте, и тут более-менее четкие. Например, по вопросам, написать для чего он, что тут можно спрашивать а что нельзя, чтобы, например, там не всплывали предложения по улучшению сообщества, оно не для этого. Т.е. запретить использование вопросов только для того чтобы привлечь внимане к своей проблеме и т.д. и такеи сразу удалять. Еще, допустим, чтобы не указывали сразу все версии друпала. Допустим у человека проблема на 7 друпале, а он пометит и 8 и 6, что введет других в заблуждение.

**Comment by drupby** [comment]
Правила нужны в любом случае для публикации(снятия с публикации) вопросов и ответов, как пример для изучения можно взять http://drupal.stackexchange.com/help, только у них сделан каждый пункт на отдельной странице и на странице help выведены ссылки на все пункты, можно все правила оформить на одной странице в виде вопрос/ответ.

**Comment by fortis** [comment]
тоже считаю что одно другому не мешает)

**Comment by adubovskoy** [comment]
http://community.drupalife.com/question/282

Отписался Никите в скайпе, немного подумал и формализовал мысли для топика.

История вопроса - был опубликован очень плохо оформленный вопрос. Набрал минусов. Потом начался срач. А у нас же одна из задач -- избежать любого негатива и любых возможных оскорблений. Саму возможность убрать - новые люди на ресурсе не должны найти такие вот топики или комментарии. Нужен позитивный фон и полезная информация. Да, будут люди которым хочется "посраться", да, мне тоже иногда хочется) Надо найти стратегию, как этого избежать. Мысли:
1. Народ срется в комментариях. Комментарии нельзя рейтингом корректировать - а очень хотелось бы в данном случае. Вообще, по текущей структуре конфликтное место это как раз комментарии, а не ответы. Нужны механизмы рейтингов там, чтобы стимулировать этичное поведение.
2. Сам факт что народ персонализированно срется - плохо. Может, добить рейтинги для того чтобы это прятать, в таком контексте:
   если вопрос набирает N минусов, он депубликуется а автору уходит сообщение о том что он депубликован и что частые причины это: "недостаточно раскрыт вопрос, нарушение правил, оскорбления, реклама" и т.п. со ссылкой на правила и рекоменлации. Ведь "плохие пользователи" тоже бывают. И их можно прятать и давать рекомендации как обучиться задавать вопросы правильно.
   Если кто-то написал вопрос некорректно, вместо того чтобы его потом всем давать читать и хранить - депубликуем по рейтингу, даем рекомендацию автору как опубликовать новый вопрос таким образом, чтобы он остался.
   Аналогичным образом с комментариями - много минусов -- скрываем (может, и ответы на него, надо думать).

p.s. очень крутая ссылка на help от стека. http://drupal.stackexchange.com/help/on-topic - собственно, вопрос набрал изначально минусы, т.к. не выполнил этих требований.

**Comment by drupby** [comment]
@adubovskoy я так понимаю речь идет о вопросе http://community.drupalife.com/question/282, который нахватал минусов. Ты предлагаешь такие вопросы депубликовать. А суть вопроса в том, что человек просто взял не тот модуль, ему просто нужно было дать ссылку на модуль для Drupal 7. Ему же начали объяснять неведомо что, да и еще и хулиган постарался подогреть ситуацию. Это я к тому, что случается все и оценивать вопрос автоматически по минусам не всегда правильно.

**Comment by Niklan** [comment]
@drupby но если смотреть независимо со стороны. Вопрос был сам щелчком для всплеска негатива. Вопрос был поставлен совершенно некорректно и не являлся вопросом. А именно, человек написал название модуля и то что он не смог с ним разобраться. При этом он совершенно не описал суть проблем, ибо "у меня не получилось" это не оправдание. В данном конкретном случае, если же ты даже не знаешь как подойти к вопросу, можно бы было задать вопрос следующего характера: "Где можно найти документацию по следующему модулю, на официальной странице нет ничего" и такой вопрос воспринялся намного легче. Ведь все мы знаем что есть модули совершенно без документации, я порой сам попадаю в такие ситуации, и сиди гадай что делать. Ладно если модуль маленький, можно по коду найти где настройки и как работает, но ведь не всегда код маленький и не каждый его может прочитать и осмыслить. Ведь затем вопрос был перефразирован именно на этот лад и получил ответ.

**Comment by fortis** [comment]
Мне кажется не все в состоянии с первого раза задать вопрос правильно =) Возможно тут стоило вмешаться модератору и объяснить что нужно развернуто объяснить, лучше со скриншотами и объяснить что именно не работает и какие ошибки существуют (и где их посмотреть), это может быть шаблонным ответом, который часто будет пригождаться. Может быть даже закрывать комментарии пока автор не внесет изменения, чтобы не разводить срачь

**Comment by Niklan** [comment]
Правила видимо не будем делать. Будем делать "вводные". Эту проблему по сути перекрывает #358. Вместо правил, которые никто не читает, давайте делать для новичков вводные тексты и дополнять формы чтобы было проще по конкретному разделу. Как это было сделано в последних коммитах и #358 в частности.
