### ISSUE TITLE
Не видно больше 10 комментариев под самим вопросом.

### ISSUE THREAD

**Issue by isaenkov** [Niklan/Dru.io#411]
Если коментов под самим вопросом больше 10, то не появлется пагинация, т.е. видно только первые 10 коментариев, остальных не видно.
Для примера, здесь (http://dru.io/question/5122) я оставил уже два коментария, а их не видно.

**Comment by adubovskoy** [comment]
Ошибка была в http://dru.io/admin/structure/views/view/comments/edit/comments_to_question . Исправлено, спасибо!
