### ISSUE TITLE
Выводить число непрочитанных материалов в меню

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#414]
Сабж. Как нибудь так:

![untitled-1](https://cloud.githubusercontent.com/assets/845389/11907550/d1bc09aa-a5e5-11e5-85b4-ae2f68ec5686.png)

Повысит время проведённое на сайте.

**Comment by Niklan** [comment]
+

**Comment by drupby** [comment]
Как вариант реализуется модулем https://www.drupal.org/project/menu_badges

**Comment by Niklan** [comment]
Ой там своё то написать раз-два)
