### ISSUE TITLE
Предложение по расширению проекта в сторону обсуждения организационных вопросов

### ISSUE THREAD

**Issue by roman-yakimkin** [Niklan/Dru.io#415]
Добрый день.
Возникла такая мысль. Если, конечно, этот проект изначально не задумывался только как проект для программистов, то, может быть, его стоит как-то расширить в направлении освещения и обсуждения организационных вопросов.
Например, обсуждать нюансы взаимодействия с клиентами, вопросы по организации веб-студий, всякие юридические, бухгалтерские вопросы и т.д.
Тем более, в сайтостроении на Drupal есть прослойка сайтостроителей, которые как раз программированием не владеют. Они знают верстку, фотошоп, сео, знают, для чего какой модуль, для программных работ, где модулями не обойдешься, привлекают программистов. И в случае расширения проекта в сторону обсуждения оргвопросов такие люди тоже могли бы поучаствовать в дискуссиях, чем-то полезным поделиться и т.д. 
Для рейтингования, думаю, было бы неплохо для таких вопросов иметь отдельный рейтинг (назовем его "организационный"). 
Ну а вопросы разделять на технические (которые сейчас) и организационные.
За ответы на технические вопросы баллы в копилку технического рейтинга, за ответы на организационные вопросы - баллы в копилку организационного.

**Comment by Chi-teck** [comment]
https://github.com/dru-io/Dru.io/issues/261
