### ISSUE TITLE
Vagrant сборка для разработки

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#416]
Общий смысл - моментальное получение полной среды разработки. С gulp/sass и т.п. Сделать на базе того же vlad или vdd. Чтобы новый разработчик (не важно, под win он, mac или linux) мог запустить vagrant, у него автоматом бы развернулась свежая база и все окружение. Чтоб "вхождение" занимало 20  минут (и то в основном на загрузку).

Предложено уже дважды, @duozersk и @fortis

**Comment by Niklan** [comment]
+

**Comment by fortis** [comment]
имхо докер в разы проще новичку

**Comment by fortis** [comment]
у меня есть https://hub.docker.com/r/fortis/drupal-dockerized/ 
но хочу еще допилить и проверить на виндовс и линуксе, и потом уже можно будет форкнуть конкретно под dru.io

**Comment by adubovskoy** [comment]
в принципе не важно что именно, если принцип "20 минут и простой набор действий для полноценного окружения" выполняется
