### ISSUE TITLE
Роль: Модератор

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#42]
#24 - Есть предложение сделать модераторов. Создаю отдельный ишью чтобы решить, какие права будем давать роли модератор.

Для начала:
-  Правка\редактирование любого материала на сайте (Вопросы\Публикации). Проекты пока думаю не надо давать редактировать, они живут своей жизню и полностью автоматизированы.

Нужно ли дать возможность удаления? И что еще можно выдать?

Будем ли помечать модераторов на сайте? Какой-нибудь плашкой к нику, типа "Модератор"?

**Comment by drupby** [comment]
Право на удаление не нужно, вместо него же можно просто снимать с публикации

**Comment by fortis** [comment]
Может и не нужно модераторов светить? Чтобы не обсуждали лишний раз действия администрации, лишние это холивары. Модератор какого-нибудь Заїку забанит а потом скажут что он исходники скачал)))

**Comment by adubovskoy** [comment]
кстати да. обезличенная реакция "прилетело нло и ...", хабр в этом деле молодцы - прямого негатива там не к кому проявить) и приучили всех в комментариях быть вежливыми и понятными.

**Comment by Niklan** [comment]
@adubovskoy у этого есть и обратная сторона медали. Там почти всегда невозможно читать комментарии. Редко там здравый встречается, в основном жоползитво и подхалимство, читать просто тошно такое. Все подлизываются друг к другу, боятся даже пошутить, ибо заминусуют. Они там как в концлагере.

**Comment by adubovskoy** [comment]
Я забанен на хабре, мне можно не пояснять)
Но в целом, например холиварная статья http://habrahabr.ru/post/246905/ , вполне адекватные и интересные комменты. Читать даже интересней статьи. Там одно дело -- просто неудачный коммент или неверный, набирает -1/-3, а если кто-то начал цапаться - там стороны резко схатят -20 и исчезнут.

невозможно читать в платных хабах. Там сидят сотрудники и накликивают отзывы.

**Comment by Niklan** [comment]
Там таких здравых обсуждений наверное 1 на 100 материалов. Печально что такое крупное сообщество ведет себя как непойми кто, зато "ИЛИТА" :smile:

**Comment by adubovskoy** [comment]
Не, если взять любой технический пост -- там все в порядке внутри. Просто специфика - они ж ориентированы на получение денежки и по сути являются СМИ, генерирующими переводы рейтинговых материалов. Когда материал оказывается написанным технарем и когда там есть что обсудить - подключаются присутствующие на ресурсе технари и все ок.

**Comment by semyondragunov** [comment]
Не советую светить модераторов. Пусть как фсб, тихо и бесшумно...))) А то их драконить начнут, и подлизываться.
Неугодные комменты/ответы/материалы в анпаблик и минусуем провидившегося через эти же комменты(-3)/ответы(-7)/материалы(-15)
Оценки привел в пример.

**Comment by SemanticsPRO** [comment]
С другой стороны, всем понятно кто модераторы

**Comment by SemanticsPRO** [comment]
@adubovskoy касательно хабра, думаю, что это один из самых неудачных примеров общественной модерации.
Особенно вспомни, что было раньше. Сплошной кармадроч

**Comment by semyondragunov** [comment]
@SemanticsPRO Это нам понятно, но по мере развития проекта, будут приходить новые люди!

**Comment by Niklan** [comment]
Тут вообще палка о двух концах. Показывать лучше не надо, но все итак будут знать кто модератор а кто нет.

**Comment by fortis** [comment]
Но не будут знать кто потер комент или забанил очередного неадеквата, это же и цель?

**Comment by drupby** [comment]
вот и первая работа для модераторов http://community.drupalife.com/post/349

**Comment by Niklan** [comment]
@drupby =)

**Comment by Niklan** [comment]
Создал роль moderator. В отличии от обычных юзеров имеет:
-  Возможность править (только править) любые вопросы и ответы. (Надо ли дать на публикации?).
-  Удалять\добавлять\редактировать таксономию категорий.
-  Пользоваться панелью инструментов.

Попутно создал раздел для категорий. Позже подцепим к вопросам и выведем.

**Comment by Niklan** [comment]
Выдал для начала права xandeadx. Кому ещё будем выдавать? По желанию или отберем сами?

**Comment by Tristamoff** [comment]
Можно мне тоже права модератора? http://community.drupalife.com/user/115

**Comment by Niklan** [comment]
@Tristamoff выдал.

**Comment by Tristamoff** [comment]
Вижу. Только я например не могу снять с публикации материал.

**Comment by Niklan** [comment]
@Tristamoff теперь можно

**Comment by drupby** [comment]
Если нигде не будет выводится упоминание роли модератора, то добавь мне эту роль.

**Comment by Niklan** [comment]
@drupby готово

**Comment by Tristamoff** [comment]
@Niklan ,да, щас всё норм,спс.

**Comment by drupby** [comment]
публикации нет возможности править/снимать с публикации? опять спам http://community.drupalife.com/post/353

**Comment by Niklan** [comment]
Есть же права на снятие с публикаций

**Comment by Tristamoff** [comment]
Не на все контент тайпы

**Comment by Niklan** [comment]
Пф, там это одно единственное правило на все разом "Управление содержимым"

**Comment by drupby** [comment]
@Niklan для типа материала "Публикация" не доступно редактирование

**Comment by Niklan** [comment]
@drupby да, для неё выключал, видать понадобится, поэтому включил.

**Comment by drupby** [comment]
@Niklan теперь ямогу давать ответы от имени любого пользователя (в том числе и админа), смотри пример http://community.drupalife.com/question/350

**Comment by Niklan** [comment]
@drupby надо бы настроить модерацию. Я честно говоря не в теме, раньше модерирование просили с такими возможностями, так что первое что приходит в голову костыли, делать в форме кнопку для модеров а это скрывать. Если кто знает как гибко настроить  отпишитесь)

**Comment by drupby** [comment]
Сильной проблемы в том я не вижу, не думаю, что модераторы будут этим как то злоупотреблять

**Comment by Niklan** [comment]
Так вот и я также думаю, выдаем то уже тем кто не первый год с друпалом. Запреты всегда можно поставить)

**Comment by drupby** [comment]
Можно сделать альтер формы и поставить access false этой вкладке как вариант

**Comment by drupby** [comment]
С помощью permissions вроде как нельзя сделать ограничение

**Comment by webremake** [comment]
https://www.drupal.org/project/vppr - права только на редактирование и добавление терминов в определенных словарях
https://www.drupal.org/project/override_node_options  - права только на снятие с публикации

**Comment by Niklan** [comment]
Вроде как основная суть "Роль - Модератор" решена, ишью закрываю. По улучшениям, думаю, следует создавать ишьюсы с улучшением.
