### ISSUE TITLE
Документация по Drupal на русском языке

### ISSUE THREAD

**Issue by levmyshkin** [Niklan/Dru.io#422]
Здравствуйте, я по поводу руководства друпал на русском языке на сайте drupal.org. На  DrupalSib Camp была идея сделать общими усилиями руководство и сделать инициативу на
drupal.org, чтобы разместить на русском языке статьи.
Нам нужна площадка для совместной работы, если есть желание то можно сделать такую
площадку на dru.io .Пока я начал делать мануал у себя на сайте, но если есть желание работать совместно, то я могу продолжить уже на dru.io.
http://drupalbook.ru/drupal/videokurs-razrabotka-saytov-na-cms-drupal-8

**Comment by fortis** [comment]
Идея сделать видеоматериал?

**Comment by levmyshkin** [comment]
Да и видео тоже, я делал по 7ому друпалу:
https://www.youtube.com/channel/UCkzEoCBcOFx2HK0_IDxSMZQ

Но основная идея все же в том чтобы перевести документацию с drupal.org на русский язык и опубликовать ее там же на drupal.org. Для этого уже есть функционал на drupal.org, нужно только скооперироваться, подготовить документации и с готовой документацией создавать инициативу.

**Comment by fortis** [comment]
добавил в скайп, обсудить в чате будет продуктивнее

**Comment by andypost** [comment]
Нам даже подсказывают, куда для начала копать https://www.drupal.org/node/363896#comment-10687502

**Comment by fortis** [comment]
#9
