### ISSUE TITLE
Вычистить спам-ботов

### ISSUE THREAD

**Issue by fortis** [Niklan/Dru.io#423]
около 500 пользователей которые никогда не входили, можно чекнуть с spambot и остальное руками добить

**Comment by fortis** [comment]
заблокировано порядка 500 пользователей, проверил вручную все ок, позже пересмотрю и удалю аккаунты. 

проблема:  есть боты которые зарегались и вошли 2 недели назад и ранее. выходит текущая капча не помогает, возможно стоит оставить спамбот для проверки емейла по базе стопфорумспам при регистрации (пока выключено)

**Comment by webremake** [comment]
Очень хорошо помогает от регистрации ботов https://www.drupal.org/project/google_recaptcha
На одном из сайтов было по 30 - 50 регистраций в день. После установки модуля уже три недели ни один бот не зарегистрировался. И авто заполнение не ломается с этим модулем (по крайней мере в хроме, в других браузерах не проверял).

**Comment by adubovskoy** [comment]
уже стоит)

**Comment by adubovskoy** [comment]
удалил пользователей с совокупностью признаков: со статусом заблокировано, которые 2 года не заходили и у которых нет материалов.
