### ISSUE TITLE
Ссылки на новые статьи

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#426]
**Вводная**: есть большое кол-во ресурсов по друпалу, которые почитываю. Прямо "вау" статей там не так много, но бывают. Хочется быстрее такой контент находить и читать в одном месте. 
**Как решаю сейчас**: да как все, твиттер, дайджест, некоторые блоги.
**Как можно сделать**: на dru.io тип материала "ссылка на публикацию". Там собственно линк (с nofollow) и краткий пояснительный текст что там (или что понравилось). Рейтинг будет. 
**Что не решено:** хочется видеть там именно свежие статьи/заметки. Не записи из блогов годичной давности, а свеженькое (не обязательно на русском кстати, англ. также). Как проверять на новизну? Сделать описание внятное и дальше самоорганизуется рейтингом?
**Почему не сделать твит-ленту?** - модерации не будет, рейтингов, не будет привязки к профилю на dru.io, сортировки по рейтингу не будет (для дайджеста может быть интересно).
**Вторичные бонусы:** будет неплохое подспорье для дайджеста, а также туда можно будет кидать новости по крупным русскоязычным статьям, тому же дайджесту и т.п.

**Comment by fortis** [comment]
этому нужно хорошее видное место на главной

**Comment by andypost** [comment]
можно просто шоткатсервис сделать и его содержимое выводить

**Comment by fortis** [comment]
репостить в твиттер и другие соц сети хорошие материалы стоит, в момент когда материал наберет 10 баллов можно программно делать репост в нашем аккаунте. назревает порт vkxp на 8ку, бекпорт я уже делал на 6ку =) вк может в твиттер сам слать так что достаточно только с ним связать, про фб подумать надо

**Comment by adubovskoy** [comment]
tnx, сделал https://github.com/dru-io/Dru.io/issues/427 дабы отдельно вести.

**Comment by vistar** [comment]
**Как решаю сейчас:** rss + feedly

**Comment by Niklan** [comment]
А в чём разница от: https://github.com/dru-io/Dru.io/issues/10 ?

**Comment by fortis** [comment]
там видимо это тип материала для того чтобы пользователи публиковали, тут функционал который сам такие материалы делает

**Comment by Chi-teck** [comment]
Статьи русские?

**Comment by adubovskoy** [comment]
> А в чём разница от: #10 ?

ни в чем, дубль. сорри, не увидел вовремя. этот закрываем. дальше в #10

**Comment by adubovskoy** [comment]
> Статьи русские?

не только. Но если английские - то больше шансов что читателям не понравится. Надо будет оч привередливо выбирать

**Comment by fortis** [comment]
имхо их (англ) нужно выносить из общей ленты, в сайдбар например и делать более кратким списком
