### ISSUE TITLE
Предпросмотр материалов перед публикацией

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#431]
Пожелание из коммента http://dru.io/question/5327 . В целом разумно. 
Там нет никаких подводных камней почему сейчас нет? На dev-копии просмотрел, вроде все ок. Если не будет возражений, скоро включу.

**Comment by Niklan** [comment]
@adubovskoy Там вроде оформление в превью едет?

**Comment by adubovskoy** [comment]
У вопросов не едет, остальное еще не тестил. Отступы может кое-где подправить, но там мелочи.
