### ISSUE TITLE
Возможность написать текст при отклике на заказ

### ISSUE THREAD

**Issue by icanall10** [Niklan/Dru.io#432]
Почти каждый клиент пишет "Оставляйте ваши предложения, указывайте цену" и подобное.
Был даже случай, когда у заказчика не были указаны контакты, чтобы это самое предложение написать. 
Нужно либо поле для ввода текста, либо поля для ввода цены и срока.
Чтобы это не превращалось в срач, как на д.ру (насколько я понимаю, именно по этой причине это не было сделано изначально), можно просто не показывать текст предложений остальным пользователям.

**Comment by adubovskoy** [comment]
Пока показываются контактные данные из профиля.
Коротенькую заметку в стиле "Почему я подойду для этого проекта" имхо не помешает, да.
Пометил пока на D8. Если кто возьмется сделать раньше - было бы неплохо.

**Comment by fortis** [comment]
нужно раньше, до д8 пол года прикидываем, а заказы идут

**Comment by fortis** [comment]
я вроде посвободнее сейчас, попробую

**Comment by als-studio** [comment]
+1 в поддержку возможности оставлять комментарий при отзыве на заказ.
Конкретный пример: есть заказ http://dru.io/order/5523, контакты заказчик не оставил. То есть единственный способ связаться - нажать "отозваться". При этом просит "Сразу присылайте, пожалуйста, примеры своих интернет-магазинов на drupal."

**Comment by adubovskoy** [comment]
Можно полем к флагу сделать http://dru.io/admin/structure/flags/manage/ready2work/fields .

**Comment by webremake** [comment]
Очень нужная функция. Свежий пример - заказ http://dru.io/order/5759.
У меня в портфеле есть сайт на commerce с тем функционалом, который нужен заказчику - сделать возможность добавлять товары зарегистрированным пользователям в свой собственный магазин .
Как мне об этом сказать заказчику и дать ссылку? Ни контактов заказчика ни ссылки на его профиль в заказе нет.
