### ISSUE TITLE
Возможность отмечать (или скрывать) заказы, по которым найден исполнитель

### ISSUE THREAD

**Issue by als-studio** [Niklan/Dru.io#433]
Сейчас на http://dru.io/orders много старых заказов, некоторые висят по 3 месяца. Это вызывает некоторое неудобство - не понятно, на какие заказы реагировать, а на какие уже поздно.
Мне кажется, старые заказы нужно каким-то образом помечать, как неактивные, либо вовсе скрывать.
На мой взгляд, самый лучший вариант- скажем, через 10 дней отправлять на email автору ноды ссылку для "освежения" заказа. Если автор не кликнул по ссылке в течение 2 дней, автоматически менять статус заказа на "архивный".

**Comment by adubovskoy** [comment]
Поддерживаю.
