### ISSUE TITLE
Создание блога по Друпал

### ISSUE THREAD

**Issue by dmitrysusloparov** [Niklan/Dru.io#434]
Ребята, привет!

Я работаю на компанию Vardot (https://www.vardot.com/), которая сотрудничает с Acquia, занимается разработкой сайтов, пишет общедоступные модули и спонсирует Друпал на Ближем Востоке. Мы хотим сделать на базе сайта блог (он уже есть, но не очень хороший), где будем писать течнические и не очень тексты и ищем людей, которым бы было интересно делать это. Я предложил участие некоторым из вас лично, но в итоге мы сошлись на идее, что правильнее всего будет запостить объявление здесь. Так вот, если кто-то из вас заинтересуется, пишите мне на d.susloparov@vardot.com! Вознаграждение гарантируется :) 
ПС: важное уточнение - сайт и блог на английском языке, поэтому и писать придется на английском. Мы со своей стороны будем это вычитывать и исправлять ошибки. Буду рад сотрудничеству, так что если у кого-то возникнут любые идеи (не только по блогу), мы готовы их обсуждать! 

Всем хорошей недели!

**Comment by adubovskoy** [comment]
Привет)
Ишью они по доработкам самого сайта dru.io. Все разработчики ваше ишью увидели, но чтобы рабочему процессу оно не мешало и не было в ленте, я его закрою.
Вы можете продублировать объявление на http://dru.io/orders , там и аудитория больше и висеть активным будет на главной долго.
