### ISSUE TITLE
Добавление в список категорий понятий, связанных с Drupal 8

### ISSUE THREAD

**Issue by roman-yakimkin** [Niklan/Dru.io#436]
Добрый день.
Небольшое пожелание - добавить в список категорий понятия, связанные с Drupal 8.
Помню, когда задавал вопросы по Drupal 8, не смог подвести их под нужную категорию.

**Comment by adubovskoy** [comment]
А можно набросок вариантов?

**Comment by roman-yakimkin** [comment]
Попробую ...

Рутинг
Контроллеры
Шаблоны twig
Плагины
Система конфигурирования (yaml)

Я с D8 практически не работал, может быть, здесь поучаствуют те, кто имеет более-менее опыт работы ...

**Comment by adubovskoy** [comment]
Да, давайте набьем небольшой список и внесем термины.

**Comment by Niklan** [comment]
Routing или Routing API
Plugin API (уже есть).
Controllers
Config API
Services (Не в смысле услуги а именно Services объектов).

> Шаблоны twig

У нас для этого есть Theming. Это его часть.

У нас также есть Import, и в 8-ке есть Migration API, не ясно. Отделять, переименовывать или не трогать. С одной стороны они пересекаются но импорт далеко не всегда мигерйт апи, фидсы, кастом, вообще вливание данных каким-либо способом. Но и мигрейт апи по сути стоит четко отделять.

Лучше всего новые категории **ввести ещё на Drupal 7** версии. Так как их спокойно подхватят миграции, а также будет полезно прямо здесь и сейчас, так как они актуальны на данный момент и нужны.
