### ISSUE TITLE
Правила/описания для разделов

### ISSUE THREAD

**Issue by SemanticsPRO** [Niklan/Dru.io#437]
Господа, преведствую.

В общем, хочу накидать публикаций, но:
1. Нет правил для публикаций, непонятно, можно урлы, нельзя, что вообще разрешено, что нет.
2. Непонятно насчёт уникальности теста в публикациях
3. Непонятно вообще для чего раздел. Ссылки на свои блоги/статьи, для полноценных статей и т.п.

Ваши мысли? Накопирайтить правила готов

**Comment by adubovskoy** [comment]
В общем, хочу накидать публикаций, но:
1. Нет правил для публикаций, непонятно, можно урлы, нельзя, что вообще разрешено, что нет.
урлы можно, они все равно парсятся с nofollow.
1. Непонятно насчёт уникальности теста в публикациях
   мне тоже непонятно, тут вопрос к сеошникам.
2. Непонятно вообще для чего раздел. Ссылки на свои блоги/статьи, для полноценных статей
   для полноценных статей. Для ссылок скоро будет https://github.com/dru-io/Dru.io/issues/10
