### ISSUE TITLE
Неполный список вопросов

### ISSUE THREAD

**Issue by roman-yakimkin** [Niklan/Dru.io#439]
Добрый день.
Задавал на днях вопросы, сегодня смотрю, их почему-то в списке нет
http://dru.io/question

Хотя на моей личной странице они остались ?

Вы провели какую-то модернизацию сайта, чтобы список вопросов каким-то образом фильтровался ?

**Comment by adubovskoy** [comment]
Нет, это баг. Что-то с индексом солра, ребилд запустил.
