### ISSUE TITLE
Вариант нового дизайна (оформления)

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#44]
Текущий дизайн в сообществе делался на коленке абы как для галочки. Разумеется, рано или поздно нам придётся его менять. Я люблю, отдыхая от кодинга рисовать в Inkscape, по крайней мере учиться и пробовать. И набросал свой новый вариант. Если задумка понравится, можно будет развить и довести до ума, нет, так нет, что-нибудь другое сделаю с таким оформлением)

Для наглядности отрисовал страницу вопроса, так как она сейчас является самой информационной. Заодно и отобразил своё видение того как должны выглядить ответы и комментарии к ним, которые активно бсуждались недавно тут: #36 и #33 
![Пример](http://i.imgur.com/jj1HQwI.png)

**Comment by semyondragunov** [comment]
Фишку со звездой-избранным непонял. ИМХО лучше всю страницу в избранное. Или если ты имел ввиду, как пометка ответа для себя в контексте данного вопроса то я хз прям. Надо ли...

Не отобразил отображение новых комментарием (не трекер), прямо в кнопке "3 комментария". Можно допустим ей цвет поменять если там есть новые.

По дизу, норм, мне нравиться. Попробуй ещё тоже самое, но в светлых друпально-синих тонах. Ну так, для наглядности.

**Comment by xandeadx** [comment]
Давит тёмный бэкраунд вокруг. Частопосещаемые сайты имхо должны быть беленькие.

**Comment by adubovskoy** [comment]
![687474703a2f2f692e696d6775722e636f6d2f6a6a31485177492e706e67-1](https://cloud.githubusercontent.com/assets/297623/5843264/62ac2b36-a1bc-11e4-9583-b6d224b3d46c.png)

светлый читается попроще. это просто осветление, над общими акцентами не думал, просто демка фона.

**Comment by EmperorSAM** [comment]
Во, уже намного лучше, но всё таки я за текущий диз...

**Comment by semyondragunov** [comment]
Этот вариант лучше. Плюс, то что компактнее шапка. Но, я за текущий диз. Просто доработать.

**Comment by fortis** [comment]
+1 за вариант @adubovskoy

**Comment by fortis** [comment]
думаю может быть норм если сделать по высоте первую строку меньше, и синюю строчку сделать меньше в высоту чем сейчас, но больше по высоте чем первая и фон ей задать как у строки поиска то есть светлее/темнее чем первая строка.

**типа такого** http://themeforest.net/category/ecommerce

![](http://3xff.net/tec8s21012304.png)

**Comment by fortis** [comment]
и может быть также вытянув на весь экран, а у контента убрав границы. пока что макет смахивает на блог

**Comment by Niklan** [comment]
Я чтобы прояснить ещё раз напишу. Я не настаиваю на предложенном мною варианте. Я так, просто кинул, на обсуждение.

Завтра залью сюда SVG, чтобы было проще каждому показать вживую вариант.

P.s. я считаю что надо оставить рамки, растянутые сайты на больших мониторах очень скудно воспринимаются. Фон всё же делает их поуютнее, а как сейчас, допустим, создает ощущение пустоты.

**Comment by fortis** [comment]
я как раз не предлагаю растягивать контент, только шапку. посмотри ссылку http://themeforest.net/category/ecommerce

**Comment by Niklan** [comment]
Вот SVG

Дизайн:
http://community.drupalife.com/sites/default/files/DrupalCommunity.svg
Фон:
http://community.drupalife.com/sites/default/files/DLcommunitybg.svg

У фона надо менять левый верхний квадрат, это будет менять отображение у всех. Ориентироваться на центральный. Экспортируется только "страница" (т.е. центр) так получится литая картинка для css repeat.

**Comment by hulygun** [comment]
+1 @fortis за шапку... обрезанная по контенту не смотрится...

**Comment by fortis** [comment]
Еще
аватарку + ссылкупрофиль сделать кликабельными и по нажатии выводить всплывашку аля гмейл, туда потом стата пойдет

![](http://3xff.net/u61wp30012343.png)

**Comment by hulygun** [comment]
А потом ваще запилить DruioOS )))))
Стоп... стата?

> туда потом стата пойдет

Только не карма((( хнык-хнык )))))))

**Comment by fortis** [comment]
ну вопрос-ответ же плюсуют зачем-то)) должна быть стата, возможно отдельная по вопросам-ответам, не общий рейтинг. общий рейтинг ничего не скажет

**Comment by semyondragunov** [comment]
@fortis Вот микро-трекер так же бы запихать. Как тут на гите.

**Comment by hulygun** [comment]
В общем... ОЙ ВСЁ!

**Comment by drupby** [comment]
@hulygun
``Стоп... стата?

туда потом стата пойдет
Только не карма((( хнык-хнык )))))))``
отвергая обосновывай

**Comment by Niklan** [comment]
Так как особых возражений нету, альтернативных вариантов тоже, а текущий вариант вообще ужасен. Потихоньку приступаю пилить тему. Она будет в репозитарии рядом с текущей валяться.

**Comment by RedElephantDesign** [comment]
Есть возражения. Если решения по теме окончательного не принято, то мы готовы предложить свой вариант в течение 1-2 недель. Немного загружены работой, но очень хотим помочь развитию сообщества. Никита, у нас есть столько времени, что предоставить новый макет? Предложенный в самом начале вариант немного не подходит для лица Drupal сообщества. На наш взгляд сегодняшняя тема более подходящая, чем предложенная. Думаю нужно идти по пути flat-дизайна. Отбросить все лишнее, чтобы был простой и функциональный дизайн с использованием animate jquery. В синий фон вставить картинку, менять ее периодически, чтобы сайт обновлялся немного в плане дизайна. Тогда это привлечет новых пользователей. Вообщем мы за простоту.

**Comment by RedElephantDesign** [comment]
Немного подумали над темой как она есть сейчас на сайте. Предложение такое: в header периоически загружать какую-то новость. Если не понятно, то смотрите картинку ниже (лучше открыть на полный экран). То есть в фоне новость и справа краткое описание события. Так можно выводить архиважные мероприятия локальные или международные - решать главреду.
В остальном думаю можно все оставить как есть. Дизайн простой и понятный, обладает большим потенциалом к развитию. Можно много еще чего накрутить будет позже, постепенно.
А фоновые новости придадут жизни, будут обновлять общий вид сайта. Каждую неделю новая картинка и новость. Остальные элементы flat. 
![web-maket](https://cloud.githubusercontent.com/assets/10986896/6183482/bc7602fa-b390-11e4-8e25-7f4bb5ddc39e.png)

**Comment by Niklan** [comment]
Хм, интересно. Пока создание темы идёт очень не спешно и далеко не ушло. Пусть другие тоже выскажут своё мнение. 

Тему всё равно, даже в случае небольшого редизайна придётся полностью переделать. Ибо сейчас там бардак полнейший, ибо делалось абы как, а потом и правилось так же.

P.s. иконки стоит использовать какие-нубидь векторные аля FontAwesome, ибо картинкам в текущих реалиях их просто нету смысла вставлять, на ретинах это будет ужасно смотреться.

**Comment by RedElephantDesign** [comment]
@Niklan а svg вставить можно? В редакторах графических можно в svg все загнать, там вам и код будет. Про особенности ретины не имею опыта, но масштабируемая графика должна идти хорошо.

**Comment by RedElephantDesign** [comment]
@Niklan если svg пойдет, то мы можем вам все иконки и логотип там сделать. Только пока нет опыта встраивания в html, но разберемся я думаю.

**Comment by Niklan** [comment]
@RedElephantDesign svg пойдёт, его и в шрифты конвертировать дело пары минут.
В HTML можно прямо svg и ставить, его все понимают.

**Comment by Niklan** [comment]
Хочу ещё заметить, что новый вариант дизайна более "уютный" что ли. В том смысле что там есть фон и границы. Такие пустые как сейчас создают впечатление пустоты. Может имеет смысл также в новом варианте пилить такие анонсы на главной. Просто сейчас же отрисованы только вопросы, а главной вообще нет.

Люди, ну-ка подключайтесь к обсуждению)

**Comment by RedElephantDesign** [comment]
Сейчас взглянул на новый дизайн еще раз (тот что с фоном) - уже больше понравился. Понравилось расположение элементов. Элегантно все стоит на своих местах. Но с фоном надо что-то сделать. Немного серьезность весь проект может потерять (на мой взгляд), если фон гороховый будет. Попробуем что-то предложить в качестве альтернативы. Не обязательно получится лучше, но уже можно будет выбирать и обсуждать.

**Comment by RedElephantDesign** [comment]
Думаю надо навигационную панель с нового дизайна взять, а главную страницу (структуру) так и оставить с фоновыми новостями.

**Comment by Niklan** [comment]
"Гороховый фон" содержит в себе элементы сайта. Т.е. логотип друпала, значок помощи, значек вопросов и ответов, новостей, мероприятий. Т.е. по сути хоть как-то отсылается, другого не придумал, а больше и не предлагали) Я не дизайнер, на досуге рисовал, поэтому получилось как получилось.

**Comment by RedElephantDesign** [comment]
Мы постараемся что-то для альтернативы дать. Если лучше в итоге не придумаем в этой ветке, то оставим "горох". Он хороший, имеет право быть) 
Не обязательно, чтобы он ссылся на возможности и тематику сайта, главное чтобы дизайн был функционален. Как говорят: "если вы не заметили дизайн, значит он сделан хорошо".))))

**Comment by fortis** [comment]
полностью согласен, горох ^^ ни к чему, это отчасти и придает сайту вид бложика

**Comment by Niklan** [comment]
Переехал на лайв.

**Comment by dgastudio** [comment]
как по мне, идеал форума = https://geekbrains.ru/topics

в идеале, сделать frontend и backend разными.

по сути, то что является frontend можно сделать на оcнове http://themeforest.net/category/site-templates/admin-templates

**Comment by adubovskoy** [comment]
В целом да, сейчас http://dru.io/question уже приближено . 

> в идеале, сделать frontend и backend разными.

не совсем понятно. раскройте идею)
