### ISSUE TITLE
Убрать Drupal8 из меню, добавить Чат

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#440]
на https://gitter.im/dru-io/Drupal , предложение @xandeadx

**Comment by Niklan** [comment]
@adubovskoy Чат лучше к гитхабу и трекеру.  Ему там самое место, в основном слишком жирно.

**Comment by Niklan** [comment]
Я уже писал в гиттере. И ссылка должна вести не на чат гиттер на кастомную страницу /chat

Там будут какие-то простенькие правила, зачем чат, для кого чат и почему туда стоит зайти и т.д. А ниже айферймом реалтайм чат.
