### ISSUE TITLE
Снижение порога рейтинга для голосования

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#445]
Вопрос поднят в чате.

Есть предложения снизить с 20 до 10 рейтинг пользователя, после чего он сможет голосовать сам.

**Comment by Niklan** [comment]
+, пока пул с пользователями 20+ мало, до 20 по сути нереально добраться.

**Comment by adubovskoy** [comment]
сделал табличку для анализа http://druio.examplesite.ru/users

**Comment by Niklan** [comment]
@adubovskoy Думаю как миниму 2 страницы надо чтобы были с 20+.
