### ISSUE TITLE
Сообщение о невозможности голосовать за ответ

### ISSUE THREAD

**Issue by als-studio** [Niklan/Dru.io#446]
Про голосовалку еще один непонятный момент. Допустим, я не знаю, что голосовалка зависит от рейтинга. Захожу на страницу вопроса, кликаю "плюсик" на одном из ответов - страница перезагружается, однако никакого сообщения или изменения рейтинга не видно.
Т.е. нужно вывести сообщение о том, что человек не может пока голосовать (желательно со ссылкой на страницу, где написано, что такое рейтинг и как его можно увеличить).

**Comment by Niklan** [comment]
@als-studio Сообщение должно быть, в коде есть. Но не первый раз уже об этом пишут, надо тестить.
