### ISSUE TITLE
Объединение с drupal.ru

### ISSUE THREAD

**Issue by anton-staroverov** [Niklan/Dru.io#449]
На тему http://www.drupal.ru/node/126549.

Проект drupal.ru уже реанимируется, в связи с чем возникает закономерный вопрос — почему бы не объединить усилия и не сделать один супер-сайт о Drupal на русском?

Цели проектов общие, аудитория общая, контент тоже во многом пересекается. Слоган dru.io звучит как "русскоязычное сообщество Drupal". Домен drupal.ru как никакой другой лучше всего подходит под эти слова.

Почему бы не зарыть топоры войны и не попробовать объединить усилия? Вместе мы сможем больше!

**Comment by Niklan** [comment]
Уже обсуждалось. Совершенно разные проекты. Dru.io точно вливаться в drupal.ru не будет. И возможность вливания drupal.ru в dru.io также обсуждалось. Только как архив на поддомене.

> Проект drupal.ru уже реанимируется

Пока что ничего не ясно. Обновление на 7-ку и пару фиксов верстки это не реанимация. Пока это больше похоже на начало конца.

> Цели проектов общие

Общая цель - да, но подходы совершенно разные.

> аудитория общая

Не совсем. ЦА - да, но контингент совершенно разный.

> Слоган dru.io звучит как "русскоязычное сообщество Drupal". Домен drupal.ru как никакой другой лучше всего подходит под эти слова.

Домен друпал.ру подходит для _русского сообщества_ а не _русскоязычного_. То что его стали позиционировать как русскоязычное, это собственно их дело, данный проект же с самого начала так позиционировался и мы идём этой дорогой. По поводу этого на drupal.ru не так давно даже срач был, как его позиционировать и там как обычно...

> Почему бы не сложить топоры войны и не попробовать объединить усилия? Вместе мы сможем больше.

Уже не раз тут обсуждалось, обсуждалось локально, где только не поднималось это обсуждение. Проекты совершенно разные, разное устройство, разные подходы, разное видение, то каким должно быть сообщество, разная аудитория.

Я уже высказывал своё мнение. Лучше будет если оба проекта будут гнуть свою линию. Вопрос об "объединении" имеет место быть только когда один из проектов окончательно загнется. 

Элементарно стоит посмотреть на подход drupal.ru. Полный отказ от Views, 1 материал - на все задачи, который обвешивается костылями чтобы для каждой задачи была своя галочка, негативное отношение к рейтингам. У нас же наоборот, мы стараемся использовать существующие решения, а не кастомим всё в подряд, мы наоборот считаем что рейтинг удачная идея и пока видим лишь положительные результаты. У нас для каждой задачи свой тип материала заточеный под свою задачу.

Да элементарно подход к разработке совершенно разный. Просто сравните. Например для меня, 1000 коммитов из ничего - дикость, в них не разобраться будет уже через год, когда их станет тысяч 50. Отказ от 8ки, когда у нас в ветке уже идет портирование проекта на новую версию Drupal.

Конкуренция пойдет нам всем на пользу. Но пока что мы даже не конкуренты, это совершенно два разных ресурса.

**Comment by adubovskoy** [comment]
> почему бы не объединить усилия и не сделать один супер-сайт о Drupal на русском?

было бы неплохо) Но есть несколько но, основные тут перечислены http://dru.io/post/4637 .

Если сократить:
1. Это будет возможным только если drupal.ru будет открытым. Сейчас только Егор имеет права принимать-не-принимать пулреквесты. У нас много человек этим занимаются и пулят в продакшн) Зачастую без внимания Никиты (представляю моменты когда он после отсутствия заглядывает - а уже другая главная на ресурсе :)). И это работает быстрее. Егор отличный специалист, мы все его любим и уважаем его вклад, но в системе где все проходит через 1 бутылочное горлышко.... гхм, я не хочу пока делать на это ставку. Чтобы не повторять эту систему мы сделали так чтобы весь код и ежедневный дамп базы был доступен всем, чтобы все активные котрибьюторы имели доступ пушить обновления. 
2. Также необходимо сосредоточиться на культуре. Мы довольно просто сделали так, чтобы не было троллинга на ресурсе. Все по делу. Заказчикам отвечают специалисты, нет никаких "публичных обсуждений заказчика", что имхо норма для бизнес-ориентированного ресурса. Не хочется забирать из drupal.ru эту часть проекта. А там пока так себе с борьбой с троллями... Это идейная позиция Егора, он не видит ничего катастрофичного в этом. В тех топиках где мы хватаемся за голову и кричим "да как это вообще может быть, это же окно подачи друпала бизнесу" (типа http://www.drupal.ru/node/125624, http://www.drupal.ru/node/125246), и текущие модераторы drupal.ru считают эти топики "условно нормальными", не требующими удаления и коррекции.
3. Продолжение п.1 наверное. Очень хочется закончить с миграцией на d8, кое-что начато, но все еще впереди. Конфигурации позволят намного быстрее мигрировать обновления. А еще серьезный самопис хочется делать уже на D8, чтобы дольше это все жило. Drupal.ru в лице Егора же очень смотрит в сторону backdrop, не пишет на D8 сам и выражает явную нелюбовь как к новой архитектуре там и появлению d8 вообще. Это тоже причина почему не хочется мне лично туда вкладываться -- хочется "перспектив на будущее" подальше, чем на 1-2 года. D7 не будет жить долго, уже через 2-3 года начнутся проблемы с поиском тех, кто сможет это поддерживать...

Т.е. тут идейные разногласия. Мы хотим делать красивое, презентабельное, статусное представление Drupal и в IT сообществе, и для конечного заказчика/бизнеса. Считаем это одним из важнейших критериев. Как только эти разногласия будут решены -- вот тогда можно будет поднимать вопрос объединения. Тикет повисит, может есть какие-то вопросы, чуть позже закрою.
