### ISSUE TITLE
Title в вопросах

### ISSUE THREAD

**Issue by semyondragunov** [Niklan/Dru.io#45]
Вообще не по SEO...

**Comment by Niklan** [comment]
Баг только у юзеров, боты не видят так что по SEO) А так да, надо бы фиксануть

**Comment by hulygun** [comment]
Кстати, да.  Когда нет своих ответов, то стандартный тайтл создания ноды типа "Ответ"

**Comment by Niklan** [comment]
#44 оставим данное на редизайн.
