### ISSUE TITLE
Нужен ли promoted регион

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#451]
https://qsnapnet.com/snaps/0ovudc7wy8ir7ld

Собственно, есть мысль откатить эти изменения и оставить как раньше только блок публикаций.

Почему:
Контент там редко меняется. Соответственно на втором рефреше эта инфа уже не интересна. Чаще всего меняются вопросы и вакансии - они самые интересные при рефреше главной и должны быть вверху.

Аргументы против: "вузальное разнообразие" главной. Но имхо это идет в ущерб функциональности.

**Comment by fortis** [comment]
заголовков очень много и их просматривать не удобно, там даже даты публикации нет и отметок что из этого новое или обновилось (коменты)

промотед это отобранный контент который рекомендуют прочитать, убирать бы не хотелось, но вниз сместить стоит

**Comment by sandrig** [comment]
Убирать нельзя, т.к. будет в ущерб, лучше да, спустить вниз

**Comment by Niklan** [comment]
Оформление надо однозначно менять. Заголовков хватит, не дуамю что такие сдоровые тизеры там уместны.

**Comment by fortis** [comment]
имхо сплошные заголовки это для раздела форума или вопросов хорошо, но на главную же со всех разделов вывод и там должен быть отобранный контент, а у нас просто по 10 штук из каждого в виде заголовков

**Comment by Niklan** [comment]
@fortis Тоже верно. Надо искать баланс. Как минимум надо его в колонку закинуть. На всю шириную как-то диковато смотрится

**Comment by fortis** [comment]
не нужно придумывать и изобретать) надо взять за пример один из ресурсов и делать как там

**Comment by Niklan** [comment]
@fortis Найти бы эти примеры)
