### ISSUE TITLE
Закладки + Добавить в закладки или функционал - Подписаться

### ISSUE THREAD

**Issue by the69** [Niklan/Dru.io#452]
Всем добрый день, может быть стоит подумать о реализации функционала "Закладки" или "Подписаться"?

Допустим пользователь нашел ответ на вопрос который будет ему полезен через какое-то время. Чтобы не потерять этот ответ было бы удобно добавить вопрос к себе в закладки. Ну или появился интересующий пользователя вопрос пока еще без ответа, но он хотел бы посмотреть на ответы которые появятся позже...

Здорово, если бы внутри самих закладок была бы разбивка по категориям типа: Form API (7), Theming (3), Field API (1) и т.п. Значительно бы облегчило поиск при большом количестве закладок у пользователя.

Что скажите?

**Comment by the69** [comment]
Нашел похожие Issue 
https://github.com/dru-io/Dru.io/issues/253
https://github.com/dru-io/Dru.io/issues/169
https://github.com/dru-io/Dru.io/issues/98

**Comment by adubovskoy** [comment]
делать надо.)
