### ISSUE TITLE
Некорректные ссылки в RSS ленте раздела «Заказы»

### ISSUE THREAD

**Issue by kovtunos** [Niklan/Dru.io#454]
Заметил некорректное формирование ссылок в заголовках RSS ленты раздела «Заказы». 
http://dru.io/rss/orders

`http://dru.io/<a href="/node/XXX">Заголовок</a>`

При переходе, естественно, получаем 404.

**Comment by fortis** [comment]
поправил, проверьте

**Comment by kovtunos** [comment]
Теперь все нормально.
