### ISSUE TITLE
Уведомления на email об откликах на заказ

### ISSUE THREAD

**Issue by vkapas** [Niklan/Dru.io#455]
Похоже, сейчас нет возможности получать на почту отклики на созданный заказ, как это делается на фриланс-биржах.

Сам недавно создавал заказ, и получил отклик, а узнал о нём случайно и только через несколько дней, уже после того, как исполнитель сам на меня вышел и даже успел сделать проект. Честно говоря, при создании заказа даже и не подумал, что придётся постоянно проверять — а не откликнулся ли кто.

Поэтому было бы здорово добавить такую подписку.

**Comment by Niklan** [comment]
@vkapas Согласен

**Comment by RuZniki** [comment]
Не нашел где хранятся настройки полей.
Планирую создать новое поле (Получать уведомление о новых откликах на почту) и новый рулс, который будет отправлять уведомление заказчику.

Описание поля:
- Получать уведомление о новых откликах на почту
- field_order_notify_email
- Логическое
- Одиночный флаг вкл./выкл.
- вкл по-умолчанию.

**Comment by RuZniki** [comment]
**Тема**: Получен новый отзыв.
**Текст**: На ваш заказ [flagged-node:url] получен новый отзыв.

Экспорт фичи
```
{ "rules_order_owner_notify" : {
    "LABEL" : "Order owner notify",
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "TAGS" : [ "flag", "order" ],
    "REQUIRES" : [ "rules", "flag" ],
    "ON" : { "flag_flagged_ready2work" : [] },
    "IF" : [
      { "entity_is_of_bundle" : {
          "entity" : [ "flagged-node" ],
          "type" : "node",
          "bundle" : { "value" : { "order" : "order" } }
        }
      },
      { "entity_has_field" : { "entity" : [ "flagged-node" ], "field" : "field_order_notify_email" } },
      { "data_is" : { "data" : [ "flagged-node:field-order-notify-email" ], "value" : "1" } }
    ],
    "DO" : [
      { "mail" : {
          "to" : [ "flagged-node:author:mail" ],
          "subject" : "\u041f\u043e\u043b\u0443\u0447\u0435\u043d \u043d\u043e\u0432\u044b\u0439 \u043e\u0442\u0437\u044b\u0432.",
          "message" : "\u041d\u0430 \u0432\u0430\u0448 \u0437\u0430\u043a\u0430\u0437 [flagged-node:url] \u043f\u043e\u043b\u0443\u0447\u0435\u043d \u043d\u043e\u0432\u044b\u0439 \u043e\u0442\u0437\u044b\u0432.",
          "language" : [ "" ]
        }
      }
    ]
  }
}
```
