### ISSUE TITLE
Запилить раздел "Вакансии" и перенести существующие вакансии туда

### ISSUE THREAD

**Issue by petrovnn** [Niklan/Dru.io#456]
Заметил что в разделе Заказы публикуются вакансии.

Тут надо либо делать раздел "Вакансии", либо переименовать раздел "Заказы" в "Работа".

Что скажете?

Например сейчас на странице "Заказы" самих заказов только 4, и 6 вакансий.

**Comment by Niklan** [comment]
@petrovnn Думаю по вакансиям нужна отдельная страница и материал чтобы не мешать их

**Comment by fortis** [comment]
я скорее за отдельный раздел работы, вакансии могут быть долго открыты, а заказы часто мелкое и быстро уходящее

**Comment by petrovnn** [comment]
Как вариант можно поставить галочку "Это вакансия", и показывать их на странице вакансий. Это самое простое технически решение, тем более что поля "Заказа" мало чем отличаются от полей "Вакансии"

**Comment by Niklan** [comment]
@petrovnn не стоит мешать вакансии и заказы. Пока вот так, но если решать это, то вакансии нужно отделять в свой раздел. Как фортис написал, есть проблемы и ньансы. А это лишь вершина айсберга. Разные задачи.

**Comment by Chi-teck** [comment]
По факту, сейчас в этом разделе находятся и заказы и вакансии.
