### ISSUE TITLE
Отправка почты

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#457]
Собственно почта раньше шла через Mandrill, его закрыли. Переключил пока на стандартный метод отправки который у нас в спам уходил частенько, хотя может сейчас поменьше будет.

В общем вопрос такой. Переходим на SMTP и шлем через яндекс (ограничение 500 писем сутки), либо на sparkpost.com или аналогичные.

**Comment by fortis** [comment]
я б оставил родной и прописал spf и dkim и по итогам уже решать

**Comment by fortis** [comment]
посмотрю что там в настройках домена

**Comment by Niklan** [comment]
@fortis Ок. И напиши как spf dkim для своего домена ставить

**Comment by Niklan** [comment]
@Niklan Ну в смысле что в DNS прописывать)

**Comment by fortis** [comment]
к до у меня нет доступа, но настроить dkim и spf с яндексом проще, 500 писем в день считаю нам пока более чем достаточно 

https://yandex.ru/support/pdd/set-mail/spf.xml
https://yandex.ru/support/pdd/set-mail/dkim.xml

@Niklan настрой ты

**Comment by Niklan** [comment]
@fortis Ну так получается через Яндекс слать будем?

**Comment by fortis** [comment]
да, это сейчас проще всего и в лимиты мы впишемся, скинь в скайп скрины потом того что получится по записям

**Comment by Niklan** [comment]
Проблема решена.
