### ISSUE TITLE
Личные сообщения

### ISSUE THREAD

**Issue by isaenkov** [Niklan/Dru.io#459]
Хотелось бы увидеть функционал **_Личного сообщения_**, порой хочется задать вопрос кому-то из участников лично.

**Comment by fortis** [comment]
общаться можно в https://gitter.im/dru-io/Drupal
если автор считает нужным то в профиле скорее всего укажет способы связи

**Comment by fortis** [comment]
не все хотят чтобы им задавали вопросы :)

**Comment by isaenkov** [comment]
А если автора нет в гиттере? :-)

**Comment by Niklan** [comment]
@isaenkov В профиле есть возможность указать данные для связи. Если человек их не указывает, возможно он не желает чтобы с ним связывались, по той же причине он может отсутствовать в gitter.

**Comment by isaenkov** [comment]
Ясно, спасибо.
