### ISSUE TITLE
Навигация в разделе "Вопрос-Ответ"

### ISSUE THREAD

**Issue by hulygun** [Niklan/Dru.io#46]
Когда комментов к ответам становится больше 1 страницы смотрится ужасно, юзабилити ваще нулевое

**Comment by drupby** [comment]
подтверждаю, даже когда комментов просто много, то смотрится просто  ужасно   http://community.drupalife.com/question/296

**Comment by Niklan** [comment]
#89 - дубль, но там оживленно пошло общение. Поэтому закрою этот.
