### ISSUE TITLE
Текст http://dru.io/drupal-8.0 утарел.

### ISSUE THREAD

**Issue by bardachev** [Niklan/Dru.io#460]
Особенно первое предложение.

**Comment by Niklan** [comment]
Ок, верно. Надо ещё страницу drupal-8.1 сделать. Есть желающие?) Там тупо всё на темплейтах.
https://github.com/dru-io/Dru.io/blob/master/sites/all/modules/custom/druio_pages/theme/drupal-8-0.tpl.php

**Comment by Niklan** [comment]
Думаю ишью больше не актуально с релизом промосайта эти страницы просто не нужны.
