### ISSUE TITLE
Невозможность отказаться от выбора версии Drupal при добавлении вопроса

### ISSUE THREAD

**Issue by roman-yakimkin** [Niklan/Dru.io#469]
Добрый день.

При добавлении данного поста (http://dru.io/question/7557) поначалу выбрал версию Drupal, но потом решил, что пост ни к какой версии не относится. Но, к сожалению, возможности отказаться от выбора версии Drupal нет - список с версиями не содержит пустого элемента.

Возможно ли это устранить ?

**Comment by Niklan** [comment]
Ну андеад правильно подметил. Там вопросы непосредственно по Drupal, а не по проекту. Обсуждение проекта ведется здесь. Если уж хочется обсуждения - можно написать публикацию и вынести обсуждение в комментарии к ней. Так делалось на начальных этапах, вполне жизнеспособное решение для обсуждения проекта.

**Comment by roman-yakimkin** [comment]
Думаю, мой вышеуказанный топик на публикацию явно не тянет, это просто рацпредложение. Поэтому не хочу засорять список публикаций.

**Comment by Niklan** [comment]
Ну это я так обозвал, по факту же, там и публикации в 1 предложение имеются. Вот например такой публикации: http://dru.io/post/104

У нас по сути реально GitHub - место где каждый может задвинуть идею, ещё что-то, вынести на обсуждение. Просто тут сидят и мониторят те кто может это сделать и кто реально в этом всё заинтересован. 

То что вы предложили в вопросу (добавить поле для LinkedIN) даже на обсуждение то особо можно не выносить. LinkedIN, сеть в тематику ресурса - она не развлекательная, ссылка была бы полезной. Т.е. можно вообще не особо опасаясь это в реквесты делать и надо это будет сделать.

Просто сейчас тут уже вопрос в другом, это скорее надо делать в прототипе на 8-ке, нежели внедрять в 7-ку, так как основные работы по 7-ке мы заморозили, чтобы начинать потихоньку писать миграции на 8-ку. @adubovskoy сейчас изучает вопрос миграции и будем выявлять проблемы, писать свои. И там же можно будет и добавить поле для Linked IN сразу. Темболее что в 8-ке это внедрить можно вообще через пару yml файликов.

**Comment by Niklan** [comment]
Такое теперь возможно в 8 ветке.
