### ISSUE TITLE
Загрузка файлов

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#47]
Мой One Click Upload теперь работает на HTML5 File API (пока только версия для BUEditor), можно поставить на сайт. Забирать через git:

```
git clone --branch 7.x-2.x http://git.drupal.org/project/ocupload.git
```

**Comment by SemanticsPRO** [comment]
Спасибки

**Comment by Niklan** [comment]
Сделать бы по принцупу гитхаба. Вниз перетаскивать.

**Comment by Niklan** [comment]
Кстати, считаю что при использовании модулей в сообществе необходимо предпочтение отдавать модулям тех кто в сообществе тусует. Дабы при переходе на 8-ку помочь портануть, сообща с автором будет намного легче, в добавок просто банально поможем кодом или еще чем.

**Comment by SemanticsPRO** [comment]
Пусть выйдет ещё

**Comment by xandeadx** [comment]
можно на кнопку для BUEditor прямо перетаскивать, будет работать

**Comment by fortis** [comment]
да пока хоть как есть прикрутить, а потом ветку отдельную сделаем и добавим дргандроп

**Comment by SemanticsPRO** [comment]
таки шо? Никто не сделал?

**Comment by Niklan** [comment]
@SemanticsPRO , неа, а нужно бы. Если по палочком ложит, да хотябы файлы трекаются, вообще отлично. Надо только поле будет добавить в вопрос для "прицепки" файлов и скрыть от виду.

**Comment by xandeadx** [comment]
Добавил в One Click Upload возможность атачить файлы к полям. Только виджет поля нужно будет скрыть.

**Comment by xandeadx** [comment]
Модуль теперь поддерживает заливку файлов в любое место (дропбокс и т.д.), главное чтобы был реализован соответствующий стрим-врапер. Так что пора ставить)

**Comment by adubovskoy** [comment]
тестируйте настройки.

**Comment by xandeadx** [comment]
надо только шаблоны на markdown переделать, ну или от markdown отказаться, как решили ранее ;)

**Comment by adubovskoy** [comment]
может будем считать что это "markdown way"?) "if this is important to you, you can simply use regular HTML <img> tags." (c) http://daringfireball.net/projects/markdown/syntax#img

Хакать модуль не хочется. Делать опцию в модуле для маркдауна, ну, тоже накладно.

**Comment by Niklan** [comment]
Отказывать от маркдауна?) Не, он хорошо себя показывает.

**Comment by Niklan** [comment]
Какое ограничение сейчас у нас на файл загружаемый через one click upload?

**Comment by xandeadx** [comment]
У модуля ограничений нет, у файлов зависит от шаблона:
картинки - 300 кб ( http://dru.io/admin/config/content/ocupload/edit/1 )
файлы - без ограничений ( http://dru.io/admin/config/content/ocupload/edit/2 )
видео - без ограничений ( http://dru.io/admin/config/content/ocupload/edit/3 )

**Comment by xandeadx** [comment]
> Хакать модуль не хочется. Делать опцию в модуле для маркдауна, ну, тоже накладно.

какой модуль хакать?

**Comment by Niklan** [comment]
Влепил на файлы и видео 5 МБ. Если что расширим, чтобы не злоупотребляли.

**Comment by adubovskoy** [comment]
> > какой модуль хакать?

а разметку он откуда берет?

> > Влепил на файлы и видео 5 МБ. Если что расширим, чтобы не злоупотребляли.

там права только для админов на файлы/видео. Наверное пусть так и будет)

**Comment by xandeadx** [comment]
> а разметку он откуда берет?

Кто "он"? Шаблоны модуля One Click Upload настраиваются в админке.

**Comment by adubovskoy** [comment]
аа. точно. а так тестируй)
