### ISSUE TITLE
Проблемы со спамом

### ISSUE THREAD

**Issue by roman-yakimkin** [Niklan/Dru.io#470]
Добрый вечер.
Парни, что-то спамить стали проект довольно сурово в последнее время.
Может быть, имеет смысл mollom подключить ?
Или он не поможет ?

**Comment by adubovskoy** [comment]
mollom не поможет. он похуже чем google captcha, которая стоит. Тут вопрос - выбирать между удобством (галочка на логине, это все-таки удобно) и надежностью.
