### ISSUE TITLE
Предложение по устранению спама.

### ISSUE THREAD

**Issue by roman-yakimkin** [Niklan/Dru.io#471]
Хочу внести предложение по устранению спама.

А именно, добавить на странице спамовой сущности ссылку с надписью "Это спам", которая бы показывалась определенным пользователям (например, с определенной ролью, с определенным рейтингом, не ниже, чем какой-то, и т.д.). 
И по нажатию на ссылку происходило бы какое-то действие, например, удаление данной сущности с её автором.  Может быть, как-то завязать это на Mollon API.
В общем, предлагаю рассмотреть этот вариант.

**Comment by alexd73** [comment]
У меня spambot+honeypot убрали на 99.99% левые регистрации и, как следствие, спам.
