### ISSUE TITLE
Не работает авторизация через ВКонтакте

### ISSUE THREAD

**Issue by UksusoFF** [Niklan/Dru.io#475]
![image](https://cloud.githubusercontent.com/assets/1931442/22617702/df40a6ae-eae4-11e6-828b-cc67076f9143.png)

**Comment by fortis** [comment]
и не только вк, гибриду или пхп плохо

**Comment by Niklan** [comment]
У меня пока нет возможности в выходные что-то сделать.

Вот что в логах: `Hybrid_Exception: Endpoint: Error while trying to init Hybrid_Auth: You cannot access this page directly. в функции Hybrid_Endpoint->authInit() (строка 217 в файле /home/community/web/dru.io/public_html/sites/all/libraries/hybridauth/hybridauth/Hybrid/Endpoint.php).`

P.s. обновлений нет.

**Comment by adubovskoy** [comment]
https://github.com/hybridauth/hybridauth/issues/771

**Comment by adubovskoy** [comment]
Похоже проблема у вендора. Отключил пока иконку входа через вконтакте, остальные работают корректно.
