### ISSUE TITLE
JS attach error

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#476]
![screen_2017-03-11_011615](https://cloud.githubusercontent.com/assets/297623/23822939/58c1fb10-0668-11e7-844d-1087ae8923c3.png)

На страницах вопросов, http://dru.io/question/8054 .

**Comment by roman-yakimkin** [comment]
Да, а при попытке нажатия кнопки "ответить на вопрос" ничего не происходит.
