### ISSUE TITLE
HTTPS->HTTP редирект

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#477]

**Comment by SemanticsPRO** [comment]
Помощь нужна?
Почему с https редирект на обычную версию?

**Comment by Niklan** [comment]
Не понимаю зОчем. Давайте я HTTPS включу и редирект на него жесткий? Что выдумывать то.

**UPD**
Я раньше HTTPS не ставил так как была проблема с конфигами nginx, у меня уже наверное год так все пашет без проблем и автоматически продлевается LetsEncrypt. Я считаю что надо делать HTTPS.

**Comment by SemanticsPRO** [comment]
Никит, перевод сайта на https, чтобы позиции не потерять, немного отличается от просто включил и забыл.
Я могу осуществить, крупные сайты я уже переводил.

**Comment by Niklan** [comment]
Так я могу включить HTTPS но не делать жестокого редиректа. Пропишем там где надо уже на новые сайтмапы роботсы и постепенно зафорсим.

Нам что терять то. Весь трафик прямой или рефералы.

**Comment by Niklan** [comment]
А нет, чекнул с поиска прут больше всего. Ну плавно сделаем. Подключу SSL дальше скажешь что делать или сам сделаешь.

**Comment by Niklan** [comment]
У нас уже примерно с того времени работет https и http паралельно. Думаю пора форсить уже https?
