### ISSUE TITLE
Ошибка при добавлении вопроса.

### ISSUE THREAD

**Issue by roman-yakimkin** [Niklan/Dru.io#478]
Добрый день.

Пытаюсь задать вопрос. При попытке сохранения обнуляет значение поля "Вопрос", а потом пишет, что поле "Вопрос" обязательно для заполнения.

Это ошибка или какие-то новые особенности проекта ?

**Comment by Niklan** [comment]
@roman-yakimkin Можно скрин и как воспроизвести, просто задать вопрос и всё?

**Comment by roman-yakimkin** [comment]
Знаете, несколько раз такое было.
Потом написал в поле заголовка "123" и вопрос записался. 
Ну и после этого также изменил заголовок на нужный.

**Comment by Niklan** [comment]
Вообще это очень странное поведение. Я сейчас обновлю ядро и модули и локально попробую вопросы позадавать.

**Comment by Niklan** [comment]
К сожалению, ошибку я не смог воспроизвести. В следующий раз когда повторится, пожалуйста, запишите время (чтобы примерно по логам посмотреть), и какие теги были выбраны, проекты и версия ядра, есть подозрение на это. Там просто особо и багать нечему.
