### ISSUE TITLE
Категории для вопросов

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#48]
Что решили с категориями? Вопросы создаются, пока их не много, можно быстро протегать ноды

**Comment by Niklan** [comment]
Таксономию создал. Сейчас базовыми заполню.
Я не знаю как бы права модерам дать на редактирование таксономии. Там сразу же дается доступ к редактированию полей и т.д и т.п. Вообще фигня какая-то.

**Comment by Niklan** [comment]
Создал пока такие. Сейчас добавлю поле и выведу их.
![_014](https://cloud.githubusercontent.com/assets/2356744/5920598/9b84432e-a65f-11e4-87a8-aa76d0bd7303.png)

**Comment by xandeadx** [comment]
спасибо

**Comment by Niklan** [comment]
Добавил поле, добавил в индекс, добавил фасетный блок

**Comment by Niklan** [comment]
Пока не понимаю куда их вывести в тизере. Четвертым столбцом - поплывут проекты если их более двух. Ибо названия длинные. Да и категорий может быть несколько.

Если только сразу второй строкой уже пустить.

**Comment by xandeadx** [comment]
![screen_20150127_184008](https://cloud.githubusercontent.com/assets/845389/5921288/f29008e4-a653-11e4-9824-abe8cc39f8dc.png)
как пример

**Comment by xandeadx** [comment]
Можно сделать ссылки как текст - серые, маленькие и без подчёркивания. А то они слишком много внимания забирают.

**Comment by fortis** [comment]
теги лучше под заголовком разместить, без иконок чтобы не отвлекали. зайдя в вопрос и прочитав заголовок (а иногда сам вопрос может быть и в виде заголовка) мы смотрим тут же на теги чтобы понять какая версия, так же и с вакансиями, сейчас нужно пррлистать до конца текста чтобы узнать

**Comment by fortis** [comment]
как то так
![](http://3xff.net/mjhuh27011854.png)

**Comment by Niklan** [comment]
Это кто-то из модеров добавил категорию "вирус"?)) Если юзеры могут добавлять, то видимо придётся альтерить автокомплит поле

**Comment by drupby** [comment]
@Niklan скорее всего любой пользователь может при добавлении материала добавить тег

**Comment by xandeadx** [comment]
А можно их сделать select-ом? На память их трудно вводить

**Comment by xandeadx** [comment]
кстати в списке вопросов категории выводить не обязательно, это не такая важная информация

**Comment by Niklan** [comment]
Категерии добавлены. Ишью больше не актуально.
