### ISSUE TITLE
Документация как разворачивать Dru.io на Drupal 8

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#480]
Подготовить переход на composer + документацию по разворачиванию для контрибьюторов

**Comment by Niklan** [comment]
Репо обновлен, смерджен с репо @politsin и все оттуда вычещено, только кастом + composer.json

**Comment by Niklan** [comment]
Поправил заголовок так как всё на композере уже.

Там лежит внутри профайл `config_installer`, который, к слову, надо убрать из репо, .gitignore его не покрыл. Он в зависимости композера и может установить абсолютно чистую версию сайта, с полноценным функционалом но без контента. Считаю его надо оставлять, особенно, пока базы 8-ки не появится в свободном доступе. Это удобно по многим причинам. Во-первых, это чистый сайт. Делай что хочешь и пробуй что хочешь. По сути любой желающий может создать на нашей кодовой базе своё сообщество, где никаких следов от нас в плане контента, юзеров и т.д. не будет вообще. По мере наращения базы, голая инсталяция будет шустрее для разработки каких-то мелких вещей, и возможно, ещё куча других плюсов. В принципе его можно из `required` перенести в `suggest`, чтобы он не ставился но был как напоминание. Если кто-то против его в required.

**Comment by Niklan** [comment]
config_installer удалил из репо и в игнор добавил `profiles/contrib/*`

**Comment by Niklan** [comment]
[Написал](https://github.com/dru-io/Dru.io/blob/8.x-migrations/README.md) в ветке миграций черновой вариант. Дальше уже дорабатывать будем по необходимости.
