### ISSUE TITLE
Разделение проектов на гитхабе

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#481]
Есть мнение что для активной разработки проще будет:
1. текущий dru.io репо переименовать в d7.dru.io
2. сделать новый dru.io репо, где будет только d8, issue связанные с d8 и т.п.

Т.к. сейчас master и d8 ветки текущего репозитория не имеют общего родителя, выглядит неудобно.

вопрос дискуссионный, с другой стороны issue и история тоже важны. как удобней? или потом просто ветку 8.x переименовать в master и сделать основной, тоже вариант.

**Comment by Niklan** [comment]
С одной стороны да, надо бы их отдельять но с другой стороны тут история и контрибуция. Ядро также пилят в куче веток и ничего :) Это одна из их задач.

Как по мне, так лучше просто закрыть все старые ишьюсы массово, и открывать только те что касаются 8-ки так как на 7-ке я так понял мы проект уже заморозили. Я сам хотел это вчера предложить. Те ишьюсы уже никто разбирать не будет, а если кому-то надо будет, переоткроют, или создадут заново. Большинство из них касается 7-ки, а те что касаются 8-ки под milestone и их мало, их просто оставить как есть. А затем просто сделать 8.x ветку по умолчанию, так что даже переименовывать ничего не нужно, просто в настройках сменим. А master ветку надо и вовсе переименовать в 7.x и удалить сам master. Он не нужен по сути, и если оставить их оба, то в дальнейшем ещё и путать начать может.

В общем моё мнение, если коротко, оставлять тут, 8.x ветку делать главной, master переименовываем в 7.x, сам мастер удаляем, ишьюсы все что не касаются 8-ки напрямую закрываем.

**Comment by adubovskoy** [comment]
ok
