### ISSUE TITLE
Тема для Drupal 8

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#482]
Верстку беру на себя.

Что касается макета и дизайна, на данный момент всё остается как и ранее. Тем не менее нам вызвались нарисовать дизайн в КлипСайт @andlevashov, так что если что, то тут будем обсуждать и макет для 8-ки.

**Comment by andlevashov** [comment]
Реализация дизайна с учетом пожеланий "Нам так нравился старый ламповый Друпал.ру"
![dru-io-2 9](https://user-images.githubusercontent.com/15849842/29467514-e2ef3cf0-8451-11e7-9fc9-18d34f6d57e1.jpg)

**Comment by Niklan** [comment]
Думаю поиск надо позаметнее как-то, в целом круто!

**Comment by enemis** [comment]
Синий цвет верните. Выглядит если честно как дешевый темплейт монстр.

**Comment by enemis** [comment]
Лента на главной :-1:  Сделайте календарь, важные ссылки только не лента это мрак

**Comment by Niklan** [comment]
> Лента на главной 👎 Сделайте календарь, важные ссылки только не лента это мрак

А вы знаете, что-то в этом есть. Если побродить по крупным сообществам, не только разработчиков, у многих видно что главная служит путеводителем. Да, там обычно есть пару последних новостей в легкой доступности, а все остальное что-то типа ссылок, но оформленых понятно и крупно. Типа как с кратким описанием раздела и т.д.

**Comment by adubovskoy** [comment]
Цвета вполне нормальные, хотя имхо вопрос не принципиальный. Все равно это будет пяток scss-переменных, легко можно менять, хоть раз в неделю. Если @andlevashov и клипсайт не найдут время на цвета - будет psd исходник и каждый может поиграться предложить варианты. Понравится - решается сменой 5 строчек в коде.

По мелочам:
1. Кол-во тегов вопросов, не продумано если их будет много
2. Заказы - некоторые из них "0 руб" или когда не хотят указывать сумму (когда ищут в штат часто)
3. Кол-во показов вопросов. Не уверен что нужно, доп.нагрузка на счетчики. Можно попробовать, но потенциально этот квадрат на выпиливание (хотя это легко вроде сделать будет)
4. Промо-материал. Картинка. Картинки то нет в публикациях сейчас. И тут варианты:
- делать поле картинки всем
- делать поле картинки модераторам, которые вручную туда что-то ставят.
- вообще этот блок - это не материал, а отдельный тип блока, где картинка, описание, ссылка.

С этим промо-материалом (сайты друпалеров на схеме) больше всего вопросов. Еще несколько тезисов:
- Он скучный. Ну обычно там что-то, что редко меняется. А оно мелькает перед глазами - на 10е посещение уже ненавидишь этот блок, и скроллишь. 
- Надо подумать как отображается если нет для него контента - без этого блока.
- Может подумать что разместить вместо него? Аналог drupal planet. Заголовки блогов, еще чтонть.

В целом считаю все в том направлении, хороший вариант дизайна

**Comment by adubovskoy** [comment]
>Лента на главной

А почему нет? Ради вопросов и заходят. Авторизованным сразу ленту надо показывать.

Да! Кстати, совсем забыл. Кнопочки добавить вопрос, добавить пост/заказ надо, гденть рядом с заголовком соответствующим

**Comment by Niklan** [comment]
> Промо-материал. Картинка. Картинки то нет в публикациях сейчас. И тут варианты:
Добавить поле "Промо-картинка", и если пользователь не заполнил, а материал метит на главную, заполнять за него, если что сам дольет что хочет.

**Comment by vistar** [comment]
Тоже по цветам возражение - в духе одного дизайнера, если глянуть его работы :)
Не друпальные какие-то.

Попробую своего дизайнера подключить.

**Comment by andlevashov** [comment]
Версия главной для анонима без промо-новости, но с путеводителем.

![dru-io-2 13-ano](https://user-images.githubusercontent.com/15849842/29524416-cfb5b49c-86a0-11e7-9324-fa99d1d921e8.jpg)

**Comment by andlevashov** [comment]
Версия главной для авторизованного пользователя:

![dru-io-2 13-auth](https://user-images.githubusercontent.com/15849842/29524510-102ee584-86a1-11e7-901c-d7fc4e6d06e1.jpg)

**Comment by andlevashov** [comment]
Мы пока останавливаемся - до полноценного набора правок/голосования/принятия решения

**Comment by Niklan** [comment]
Мне нравится. Хотя версия для авторизованых смотрится пустовато.

А то что цвет желтый, так мы это, как и было написано, эту идею подняли с воспоминания старого дизайна drupal.ru. В целом не критично, но желтый отлично вписывается.

**Comment by adubovskoy** [comment]
И мне нравится.

Предлагаю следующий вариант: у нас еще уйдет наверное пара недель на миграции/каркас, перед самой версткой.

@andlevashov - выложите исходники гденть. Если кто-то предложить вариант с другой расцветкой или изменениями - будем обсуждать/выбирать. Если нет - примем текущий вариант и концепт (т.к. он сильно лучше текущего).

**Comment by andlevashov** [comment]
Мои комментарии по некоторым моментам:

1) Цвет - изначальная задумка (старый д.ру) + сейчас вокруг ВСЁ СИНЕЕ (d.org, FB, VK. Twitter, тысячи их!)
2) Пустая главная для авторизованных - взяли с текущей главной dru.io - готовы выслушать предложения, что там могло бы быть. Если не будет вариантов - предложим "полушапку".
3) Лента на главной - её сейчас заменить нечем - пару событий в год не спасают.

**Comment by enemis** [comment]
1. Не могу отрицать что синий везде. Но желтый объективно ( после черных экранов шторма) глаза режет, по крайней мере мне. 
2 ленту замените путеводителем по разделам в духе старого Д.ру. с разделами\категориями\тегами. Может облако тегов хз.

**Comment by vistar** [comment]
Так что - голосование будет? Или решаем в пару человек?

И исходник дизайна есть тут, чтобы "поиграться шрифтами/цветами"?

**Comment by Niklan** [comment]
@vistar на данный момент выслушиваются пожелания и правки будут вноситься. А потом уже и поголосуем. За это время может больше народу подключится.

Пока что до верстки ещё далеко, поэтому всё очень свободно.

**Comment by andlevashov** [comment]
> Так что - голосование будет? Или решаем в пару человек?

@vistar - Виталий, решать в пару человек - плохой путь, конечно надо голосовать, но я бы хотел, чтобы была какая-то аргументация отстаиваемой позиции. Пока я вижу только два пункта для голосования: желтый/синий и лента/не лента.

> Но желтый объективно ( после черных экранов шторма) глаза режет, по крайней мере мне.

@enemis - Андрей, смотри, какя штука - при переключении с "выворотки" (белым по черному) на обычный макет (черным по белому) по глазам бьет именно белый. Вспомогательные цвета тут роли не играют.

> ленту замените путеводителем по разделам в духе старого Д.ру

Во второй версии заменили промопост на мини-путеводитель

**Comment by andlevashov** [comment]
> И исходник дизайна есть тут, чтобы "поиграться шрифтами/цветами"?

@vistar - наведем порядок и выложим )

**Comment by vistar** [comment]
@andlevashov, лады. А то конкурса на дизайн не было объявлено (или пропустил?). Мы тоже хотели поучаствовать в сотворчестве. Может покритикуем хоть :)

**Comment by andlevashov** [comment]
@vistar - тут исключительно наша инициатива. В чате началось обсуждение переезда на д8, и мы просто между делом сказали, мол, а давайте мы, нам ответили - а давайте )

**Comment by Niklan** [comment]
@vistar всё это произошло спонтанно в чате разработчиков.

- Можно ради прикола сделать дизайн как на drupal.ru раньше желтый был, лишь осовременив.
- А давайте

И @andlevashov предложил что они нарисуют. Никто ничего пока ещё не принял. Это единственный на данный момент вариант, он лучше текущего, так что выбирать пока даже не из чего в общем-то. Если можете что-то своё предложить, пожалуйста, а если особых претензий нет, можно и то что предложил @andlevashov доработать всеми силами, критикой и пожеланиями.

**Comment by enemis** [comment]
@andlevashov Набросал улучшения на мой взгляд. Больше наверно проблема не в цвете. А очень слабый контраст сайта. Подумайте допустим о солнечном дне и грязном экране(мой случай) текст 'последний ответ' реально виден очень плохо. 
![Image](http://pix.toile-libre.org/upload/original/1503435318.jpg)

**Comment by Niklan** [comment]
@enemis заливка цветов у ответов считаю нужно оставить как в текущем варианте. Данное поле заливается в случае если на вопрос дан ответ с решением.

**Comment by andlevashov** [comment]
По поводу пустоватости версии для авторизованных - вариант с шапкой: 

![dru-io-2 19](https://user-images.githubusercontent.com/15849842/29708695-a25dee86-899a-11e7-847a-8ebe21dfdc44.jpg)

и вариант с полушапкой:

![dru-io-2 20](https://user-images.githubusercontent.com/15849842/29708714-bc2395d2-899a-11e7-91a9-7bf10cb18195.jpg)

**Comment by adubovskoy** [comment]
++ за полушапку.

**Comment by Niklan** [comment]
Тоже нравится полушапка.

**Comment by andlevashov** [comment]
Выкладывем исходники. Далее мы приостанавливаемся до решения сообщества, максимум что делаем - участвуем в обсуждениях и голосованиях

https://yadi.sk/d/8mesiVIA3MKZUj

**Comment by Niklan** [comment]
https://github.com/dru-io/Dru.io/projects/4#card-7471192 тест линковки на карточки
