### ISSUE TITLE
Общий Telegram-канал

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#485]
https://web.telegram.org/#/im?p=@niklannet как хороший прототип)

Сделать канал, раздать права на публикацию (именно нотифи-канал, чата там не будет).

Что публиковать:
- Вопросы/посты/заказы с dru.io
- Всякие полезняшки из мира drupal, ссылки (не обязательно на русском, что сочтем полезным)
- Объявления о кафе (всем организаторы кафе дать права)
- все что сочтут нужным)

Ботика написать, который о новых версиях или модулях будет писать, еще что..

**Comment by Niklan** [comment]
Канал есть, права выдам разрабам и голосованием тем кто попросит
https://t.me/druio

Думаю развивать его нужно после 8-ки, если кто хочет раньше заняться, то пожалуйста.

**Comment by adubovskoy** [comment]
В ручном режиме публикаций можно и раньше . Через недельку попробую что-то начать.
