### ISSUE TITLE
Вопрос решен или вакансия не актуальна

### ISSUE THREAD

**Issue by fortis** [Niklan/Dru.io#49]
Метку для вакансий и вопросов которая будет показывать что вопрос решен или вакансия не актуальна

**Comment by fortis** [comment]
Метку для вакансий и вопросов которая будет показывать что вопрос решен или вакансия не актуальна

**Comment by Niklan** [comment]
Обратил внимание. На stackoverflow для таких моментов автор может сам оставить ответ и пометить его решением.

**Comment by UksusoFF** [comment]
Как отметить решенным вопрос если ответ в комментах к вопросу? 
Тут вот например http://dru.io/question/399

**Comment by Niklan** [comment]
На данный момент никак. Скорее дадим возможность авторам также давать ответ как на stackoverflow, для них видимо придётся к форме добавить дополнительную надпись, чтобы понимали зачем форма.

**Comment by Niklan** [comment]
Давайте оживим ишью. Может всё же самое правильное решение дать возможность автору вопроса дать ответ на свой же вопрос? Это актуально, и даже на stackoverflow частенько человек сам находит ответ на свой вопрос. Почему бы его не оформить оветом и пометить как решение если оно таковым и является. Возможно это даже выльется в то, что кто-то специально будет публиковать вопрос-проблему и сам давать на него ответ. Хуже от этого не станет, это уже точно.

**Comment by fortis** [comment]
отвлекусь: может быть решенным вопросам стоит ставить префикс в заголовок [РЕШЕНО]? мне кажется в поисковой выдаче такие топики будут привлекать внимание

**Comment by fortis** [comment]
чтобы автор помечал свой вопрос решенным его нужно как то к этому подтолкнуть, может быть присылать разок письмо: Ваш вопрос просмотрели N человек, оставлено X ответов, и K комментариев. Перейдите по ссылке если вы получили подходящий ответ ССЫЛКА.
При переходе по ссылке попадает к форме комментирования с кнопкой Пометить решенным. может оставить комментарий, а может просто нажать и отметить решенным.

**Comment by fortis** [comment]
Решенные вопросы должны оставаться комментируемыми, но возможно при добавлении комментария к такому вопросу или ответу на него стоит предложить создать отдельную тему. Чтобы к ответам не задавали другие вопросы которые косвенно связаны, но требуют дополнения решения и напрямую к топику не относятся

**Comment by UksusoFF** [comment]
http://dru.io/question/564 а самого себя нельзя отметить до сих пор?)

**Comment by drupby** [comment]
"а самого себя нельзя отметить до сих пор?)"
автор вопроса не может пометить свой вопрос лучшим/решенным 
вот пример вопроса http://dru.io/question/2252,  где пришлось пометить вопрос решенным вместо отметки автора [решено]

**Comment by adubovskoy** [comment]
да уберите там проверку ктонть из кода да сделайте пулреквест) уже можно, с момента оформления задачки стиль форморчки поменялся, сейчас путать не будут.
