### ISSUE TITLE
Раздел: Каталог фрилансеров

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#5]
_Раздел планируется, тут обсуждается как реализовывать._

**Раздел:** Фрилансеры.
**Статус:** Запланирован.
**Описание:**
Любой желающий пользователь сможет добавлять себя в каталог фрилансеров, с указанием прейскуранта, описанием и т.д. Самый подходящий ориентир профиля-фрилансера — Freelansim.

**Comment by Samodelkin777** [comment]
Я бы не спешил с этим разделом, много других ресурсов. Будет иметь смысл когда наберется народ, когда будет рейтинг. Что-бы можно было понять человек опытен или нет, как он помогает народу, пишет статьи и т.д. На мой взгляд в этом будет плюс перед другими площадками. Главное не допускать студии т.к. в них не факт кто именно выполняет работу.

**Comment by Niklan** [comment]
Поэтому для студий отдельный проект, чтобы ни те, ни другие друг другу не мешали. А раздел да, на ранних этапах попросту не нужен. Но все что запланировано и не будет сделано завтра. Постепенно, по мере необходимости. Даже текущий опрос показывает, что каталог фрилансеров и студий сейчас менее необходимый функционал.

**Comment by adubovskoy** [comment]
Искусственные ограничения приведут к тому что студии будут представлены и как фрилансеры, и как студии) Везде так, "рецепта от" еще не придумали.

Лучше действительно, просто сделать листинг "лучшие специалисты", где показывать пользователей набравших за счет ответов высокий рейтинг -- фактически это и будет хорошим и полезным каталогом для заказчика.

**Comment by semyondragunov** [comment]
Подниму тему... Так как думаю, она уже начинает быть актуальной.
Предлагаю объединить данный функционал с https://github.com/Niklan/Dru.io/issues/4
Как это будет выглядеть:
Вариант 1) Мембер может нажать кнопку у себя в настройках. И появиться в разделе каталога фрилансеров. Если он от фирмы, то сделать галочку, которая выведет доп. поля для фирмы. В таком случае будет видно что этот человек от этой фирмы.
Вариант 2) Создать фрилансера как сущность. Она может быть как фрилансером, так и компанией. В таком случае в одну компанию могут быть привлечены несколько юзеров (по референсу).

**Comment by adubovskoy** [comment]
Есть мысль сделать просто в профиле пользователя поля для описания и сделать ранжирование по рейтингу.

**Comment by Niklan** [comment]
Ну можно еще сделать как на брейинстроадже. Чтобы юзер мог своё портфолио оформить в дальнейшем, какие-то базовые прайсы указать по-необходимости, описание.

**Comment by semyondragunov** [comment]
@Niklan Ну моём варианте это тоже предусматривалось. Забыл указать.

**Comment by holyorb2** [comment]
> Есть мысль сделать просто в профиле пользователя поля для описания и сделать ранжирование по рейтингу.

Поддерживаю.
Сделать профиль с указанием всех регалий и активностей. А раздел фрилансеров это каталог профилей. Отдельно можно сделать список состояний юзера:
- не указано
- занят
- ищу работу 8 часов в день
- ищу подработку
- ищу заказы

И по этому списку выводить список тех кто ищет работу.
