### ISSUE TITLE
Баг или фича? Разное количество ответов в тизере и в самом вопросе.

### ISSUE THREAD

**Issue by drupby** [Niklan/Dru.io#50]
Вот вопрос http://community.drupalife.com/question/363 - на самой странице один ответ, на странице http://community.drupalife.com/question у этого вопроса два ответа.

**Comment by Niklan** [comment]
"Это не баг - это фича". А на самом деле глянуть надо да. Хотя думал кэш.

**Comment by drupby** [comment]
@Niklan какой кеш для авторизованных пользователей? У тебя вьюхи кешируются?

**Comment by Niklan** [comment]
А я под гостем залипаю часто)

**Comment by drupby** [comment]
@Niklan боишься, что мини-хостинг ляжет под нагрузкой залогиненного админа?

**Comment by Niklan** [comment]
да) а вообще тулбар всегда бесил и админ меню.

**Comment by xandeadx** [comment]
там мой неопубликованный ответ. его не видно просто

**Comment by drupby** [comment]
я так понимаю количество ответов определяется в функции dlcommunity_question_answers_count() https://github.com/Niklan/DrupalCommunity/blob/master/sites/all/modules/dlcommunity/dlcommunity.module#L150 ?

**Comment by Niklan** [comment]
@drupby да

**Comment by drupby** [comment]
я бы заменил такой функцией к примеру, чтобы в подсчете не участвовали неопубликованные ответы

``` php
function dlcommunity_question_answers_count($nid) {
  $answers = db_select('field_data_field_answer_question_reference', 'er');
  $answers->addExpression(1);
  $answers->join('node', 'n', 'n.nid = er.entity_id');
  $answers->condition('n.status', 1);
  $answers->condition('er.entity_type', 'node');
  $answers->condition('er.bundle', 'answer');
  $answers->condition('er.field_answer_question_reference_target_id', $nid);
  $result = $answers->execute()->rowCount();

  return $result;
}
```

надеюсь твой мини-хостинг от лишнего джоина не ляжет :arrow_down:

**Comment by Niklan** [comment]
А зачем тут addExpression?

**Comment by drupby** [comment]
@Niklan можно вместо него добавить какое-нибудь поле (поля) методами fields(), addField()

**Comment by SemanticsPRO** [comment]
Господа, в код не вникал, но не лучше было бы туда втулить непосредственно count(*), чем считать возвращённое мускулем количество строк? Это же приведёт к скану таблицы

**Comment by drupby** [comment]
@SemanticsPRO я предлагал как вариант, вот тоже самое с count

``` php
function dlcommunity_question_answers_count($nid) {
  $answers = db_select('field_data_field_answer_question_reference', 'er');
  $answers->addExpression('COUNT(*)');
  $answers->join('node', 'n', 'n.nid = er.entity_id');
  $answers->condition('n.status', 1);
  $answers->condition('er.entity_type', 'node');
  $answers->condition('er.bundle', 'answer');
  $answers->condition('er.field_answer_question_reference_target_id', $nid);
  $result = $answers->execute()->fetchField();

  return $result;
}
```

**Comment by Niklan** [comment]
@drupby Взял код, всё отлично, спасибо. Вопрос только. Скажи свой email чтобы авторство коммита было за тобой. Если не хочешь светить скинь её на hello@niklan.net

**Comment by xandeadx** [comment]
пусть пушреквестит, взрослый уже

**Comment by drupby** [comment]
@xandeadx изначально так и хотел, но потом просто предложил вариант, совсем даже не протестированный

**Comment by Niklan** [comment]
Ну я его потестил, он уже на продакшене стоит. Так что можешь и пул реквест сделать. Мне все равно, минут через 20 закоммичу)

**Comment by drupby** [comment]
@Niklan сделал pull request

**Comment by Niklan** [comment]
@drupby готово, ещё раз спасибо.
