### ISSUE TITLE
Раздел "Расширения"

### ISSUE THREAD

**Issue by imyaro** [Niklan/Dru.io#500]
привет
Простенький вопрос:
Зачем нужен раздел расширения?
Проблемы, которые я увидел:

- Описания на русском нет
- Некоторые модуля выглядят, как минимум, неприятно. Пример: http://dru.io/project/static
- Невозможно добавить какой-либо модуль в список. Хотя бы с премодерацией.

Кажется, от раздела надо избавляться или же переделывать его полностью

**Comment by Niklan** [comment]
> Невозможно добавить какой-либо модуль в список. Хотя бы с премодерацией.

В процессе добавления вопроса вроде же можно.

**Comment by imyaro** [comment]
не очевидно :(
да и вопрос я задавать не хочу особо

**Comment by Niklan** [comment]
Не обязательно его задавать. Просто там есть возможность добавить проект, и он появится сразу без добавления вопроса. В чем смысл добавлять проект просто так? На данный момент в этом нет смысла поэтому и standalone формы нет. Возможно подумаем в 8-ке над разделом получше.
