### ISSUE TITLE
Рейтинг в Drupal 8

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#501]
Собственно в 7-ке у нас используется [Voting API](https://www.drupal.org/project/votingapi). На 8-ке он походу заброшен, последний коммит был 16 июня 2016 года.

Что же будем делать:

- Берем Voting API и если что патчим и высылаем патчи пока там не появится меинтейнер.
- Пишем свой простой аналог под задачу.
- Ищем аналоги, может где-то уже пилится?

Надо мигрировать рейтинг, а мигрировать его некуда.

**Comment by adubovskoy** [comment]
Первый вариант ок, он может в процессе перерасти во второй (свое), и имхо ничего плохого в этом не будет. По ситуации.

Аналогов не знаю.

**Comment by Niklan** [comment]
Окей, ставлю Voting API. Будем набивать шишки и помогать патчами если что.
