### ISSUE TITLE
Утечка памяти при импорте переводов

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#511]
После импорта переводов drupal происходит утечка памяти в браузере, как FireFox, так и Chrome.

Мне нужно чтобы хоть кто-то подтвердил или опроверг данный баг. Именно с профилем config installer, так как в других утечка отсутствует. Если проявляется, я сделаю баг репорт и попробуем пропатчить.

**Comment by adubovskoy** [comment]
Есть такое. Он начинает сыпать отладочную информацию. Через консоль ставится корректно (поправил инструкции чтобы легко было поставить через консоль)

**Comment by Niklan** [comment]
> Он начинает сыпать отладочную информацию.

А где ты это увидел? У меня консоль пустая, страница тоже.

**Comment by Niklan** [comment]
https://www.drupal.org/project/config_installer/issues/2953585 может поможет или направит автор проекта.
