### ISSUE TITLE
Проблемы при развёртывании локальной копии

### ISSUE THREAD

**Issue by ivnish** [Niklan/Dru.io#518]
1) Не применяется патч к snippet_manager

![Screenshot at 2019-03-18 20-55-41](https://user-images.githubusercontent.com/29428813/54543867-3d269d00-49c0-11e9-97b5-13e200c6dd06.png)

2) Невозможно установить друио через drush

![Screenshot at 2019-03-18 20-56-39](https://user-images.githubusercontent.com/29428813/54543979-6cd5a500-49c0-11e9-96c7-b6edc4716c72.png)

3) Ну и собственно валится и импорт конфигов

![Screenshot at 2019-03-18 21-01-40](https://user-images.githubusercontent.com/29428813/54544293-19178b80-49c1-11e9-8539-8d166c1240cd.png)

4) Через drush cim тоде не получается

![Screenshot at 2019-03-18 21-30-09](https://user-images.githubusercontent.com/29428813/54546232-0ef78c00-49c5-11e9-8698-0caa6764240b.png)

Локальная среда: docker + docker4drupal

**Comment by Niklan** [comment]
Патч для сниппет менеджера больше не нужен. Все чо я раньше патчил тебе не требуется. 

Первым делом надо обновить ядро и все модули до актуальной версии, там много было исправление у configuration_installer.

**Comment by ivnish** [comment]
Проблема решается использованием

https://gitlab.com/drupal.ru/dev_docker/tree/8.x
