### ISSUE TITLE
Раздел: Code Review

### ISSUE THREAD

**Issue by fortis** [Niklan/Dru.io#54]
что-то вроде http://codereview.stackexchange.com/
нужно продумать

**Comment by fortis** [comment]
идея: пользователь публикует код с подсветкой и форматированием, 
участники сообщества могут комментировать код, допустим, нажав кнопку **Review** будет появляться возможность комментировать каждую строку в топике, по кнопке **Отправить** к ноде добавляется обычный комментарий в котором выводятся строчки исходного кода и комментарии к ним.

или так: по кнопке **Review** форма добавления комментария к ноде заполняется кодом из топика где каждую строку можно прокомментировать, закончив ревью пользователь публикует комментарий, не прокомментированные строки можно скрывать или делать серыми

можно добавить голосование за лучшее ревью как в вопрос-ответ

**Comment by Niklan** [comment]
Круто но как реализовывать такое будем? Даже на примере такого нет. Зато есть тут, на гитхабе)
Мне кажется и просто копипаст кода хватит

**Comment by hulygun** [comment]
С точки зрения идеалогии друпала... через филд коллекшн + дабл филд, но предвкушаю монструозность решения. Либо реализовать отдельной сущностью хотя бы через 2 внешних ключа... Ну и соответственно оптимизированный db_query

**Comment by fortis** [comment]
сам могу, мне интересно, но я с ангуляром js интерфейсик фигачить буду =) 
бекенд примочки тут кажется и не понадобятся

**Comment by hulygun** [comment]
Да там даже ангуляра не нужно...

**Comment by hulygun** [comment]
На js обыкновенный построчный парсер, динамические инпуты и бек-энд для обработки. Как по мне тут главный вопрос именно этих "интерфейсиков")))))

**Comment by fortis** [comment]
да, но с ангуляром интерфейсики легче делать))
в общем я б взялся но мне интересен ангуляр

**Comment by hulygun** [comment]
Мне тоже импанирует ангуляр, но в таком случае желательно весь возможный функционал перенести на него... а тут уже REST делать нужно... писать сервисы для ресурсов...
Кстати, как раз сейчас провожу эксперементы с ngMaterial ))))

**Comment by fortis** [comment]
ну, зачем же весь, подключать его можно исключительно в этом разделе, на странице ноды из cdn по кнопке Review подгружать и инициализировать ангуляр. ну и может где еще пригодится, я сейчас доделываю виджет для тегов разделенных по категориям с suggestions + solr, потом покажу может и в сообществе пригодится, там тоже с ангуляркой. 
а рест думаю тут не обязателен, было б мобильное приложение, но код ревью с мобильника точно никто не будет делать))) просто аякс колбек с json в ответе

**Comment by hulygun** [comment]
Ты сейчас предлагаешь на танке за хлебом съездить. Использовать готовый асинхронный js фреймворк только для 1 плюшки? Я не отговариваю, но для меня твои слова звучат немного дико))))

**Comment by hulygun** [comment]
И когда я говорил про внедрение Rest, то предполагал не только код ревью на ангуляре.... ладно поглядим твой виджет для тегов...)))))

**Comment by fortis** [comment]
да, http://www.weather.com/ тоже для плюшек его взяли к друпалу =)
подгружаться он будет все равно только по запросу, 125кб если еще не в кеше, да и я думаю применим еще где-нибудь на проекте. То что это фреймворк не значит же что на нем делают целиком фронт, может ошибаюсь, но кажется D8 админ меню с Backbone.js сделали, не обламываются)

**Comment by hulygun** [comment]
Я же не отговариваю)))) Ангуляр, так ангуляр. Просто одна либа уже подключена(jQuery), Ща ещё и ангулярка... а к ней в нагрузку как минимум какой нить ngAnimate и ngSanitize для unsafe_mode... Ещё раз повторюсь - я не отговариваю. Я просто высказал свои мысли, касаемые рациональности использования

**Comment by fortis** [comment]
ОЙ ВСЕ ))))
