### ISSUE TITLE
Переезд на домен второго уровня

### ISSUE THREAD

**Issue by drupby** [Niklan/Dru.io#55]
Пора бы уже наверное зарегистрировать домен под этот проект и перебираться на него. Я так понимаю с именем домена еще не определились? Может кто-нибудь в комментах предложит свои варианты.

**Comment by semyondragunov** [comment]
http://www.drucom. [org io]

**Comment by Niklan** [comment]
Хорошо, предлагайте домены. 
Также имейте ввиду что имеется rudrupal.org (у RxB и он нам его спокойной может предоставить).

**Comment by drupby** [comment]
rudrupal звучит как перевернутый  drupalru, что уже не есть хорошо

**Comment by Niklan** [comment]
Без проблем. Предлагайте иной домен, куплю, перенесу.

**Comment by drupby** [comment]
Я предлагаю дождаться в комментах хотя бы несколько вариантов, а потом вынести их в голосование или же в общее обсуждение прямо здесь.

**Comment by Niklan** [comment]
Думаю достаточно будет тут обсудить. Кому надо, авторизуются отпишутся, всё же мы тут не закрылись и в одиноких обсуждаем.

**Comment by drupby** [comment]
чтобы далеко не уходить от текущего имени предлагаю `drupalcommunity.ru` или `drupal-community.ru`

**Comment by Niklan** [comment]
Я вообще придерживаюсь что надо брать .org / .com / .net

**Comment by drupby** [comment]
@Niklan почему?

**Comment by Niklan** [comment]
@drupby ну я не знаю, у меня какая-то неприязнь к .ru домену.
Затем, те можно продлевать сразу на года. 
.org часто используется для сообществ, в особенности OpenSource, что было бы логично там разместиться.
.ru - типа Россия, но мы делаем же "Русскоязычное", а на русском говорят Украинцы, Белорусы, казахи и т.д. и т.п. 
Мои доводы слабые, по сути чисто неприязнь к доменной зоне. Темболее что в этой доменной зоне могут без суда смело разделегировать домен. Мы конечно никому нафиг не нужны со своим доменом и сообществом, но всё же, неприятный момент.

**Comment by drupby** [comment]
Ну так разницы нет, тогда к примеру `drupalcommunity.org`(занят  уже) или `drupal-community.org`

**Comment by Niklan** [comment]
Аж душе приятно видеть на окончании org :D :dancers: Кстати второй свободен, на удивление. Ща какой-нибудь ушлый зарегает его)

**Comment by drupby** [comment]
@Niklan а первый занят сообществом Аргентины (заброшенным сообществом правда)

**Comment by Niklan** [comment]
Лол, видимо аксель оформляет уже)
![](http://storage2.static.itmages.com/i/15/0130/h_1422612616_1782613_f3e0388da2.png)

**Comment by fortis** [comment]
drupalway.ru
drupalway.org

**Comment by Niklan** [comment]
> drupalway.org

Занят :(

**Comment by fortis** [comment]
мой ж)

**Comment by drupby** [comment]
@fortis есть такие сайты http://drupal-way.org/ru, http://drupalway.net/

**Comment by Niklan** [comment]
В общем некоторые домены тут реально ссыкотно выкладывать. Ушлые перекупы типа акселя скупят и не заметят. Может нам стоит на этот момент создать скайп чатик, решить, регнуть и всё? Ибо слишком много хороших доменов реально еще не занято. Домены кидают мне в чатик а не сюда.

**Comment by drupby** [comment]
ну так ты создашь скайп чат и ссылку здесь разместишь, по любому кто захочет и там увидит

**Comment by SemanticsPRO** [comment]
Предлагаю удалить сайт из интернета и не выкладывать ни на какой домен

**Comment by Niklan** [comment]
Так RxB, Дубовской, FORTIS у меня есть в скайпе. Скинь свой, добавлю, xandeadx если хочет пусть подключается. Т.е. я прямо из контакта народ накидаю, фигли, за пару дней может соберем пул доменов и решим. Нам много народа не нужно. Все мы с разными точками зрениями, вполне разнообразные мнения будут, так что вполне хорошая группа для решения задачи)

**Comment by drupby** [comment]
@Niklan мой skype drup.by

**Comment by Niklan** [comment]
Обсудили, решили, купили, делегировали http://dru.io
