### ISSUE TITLE
Логотип

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#57]
Мы прикупили новый домен: http://dru.io
Нужен логотип. Давайте думать, подкидывайте идеи.

**Comment by fortis** [comment]
<dru.io/>
![](http://3xff.net/v76xg30011814.png)

// Lucida Sans Demibold

**Comment by Niklan** [comment]
Может шрифт более строгий? Ты там приложи svg чтоль для модификации ил где ты там рисуешь.

**Comment by Niklan** [comment]
![text2991](https://cloud.githubusercontent.com/assets/2356744/5976138/80b65a06-a8ac-11e4-8931-a288ee861bb3.png)

**Comment by drupby** [comment]
А какая будет цветовая гамма нового дизайна? Черный конечно красивый лого, но не в любой диз впишется.

**Comment by Niklan** [comment]
#44 я так понимаю такой? Раз там никто не выступает против. Только шапку растянем и фон светлы как посоветовал @adubovskoy

**Comment by Niklan** [comment]
![g5886](https://cloud.githubusercontent.com/assets/2356744/5976351/910727ee-a8ae-11e4-9546-475af98a2cad.png)

**Comment by fortis** [comment]
ну осталось синий круг до формы друпликона вытянуть и норм))) шрифт твой лучше да

**Comment by Niklan** [comment]
@fortis не понял, объясни что ты имел ввиду?

**Comment by fortis** [comment]
в зеленый квадрат внутрь друпликона (его позаметнее бы) впишется, в новом дизайне. 
только надпись "Друпал сообщество" наверное куда-то вытащить нужно из квадрата

**Comment by fortis** [comment]
тест)

dru.io
www.dru.io
http://dru.io

**Comment by ArtuGit** [comment]
Да, форма друпликона.

**Comment by Niklan** [comment]
Давайте пока остановимся на варианте <Dru.io/>
Будут идеи, предложения, переоткрывайте ишью.

**Comment by RedElephantDesign** [comment]
Это пока первые наброски на скорую руку. Если актуальна еще тема, то позже выложим еще варианты поинтересней. А пока критикуйте))  Дан основной макет в черном цвете и вариант цветого решения (синий, как на сайте)

![logo-maket](https://cloud.githubusercontent.com/assets/10986896/6183397/a753aca2-b38f-11e4-9d61-9ad2f853c6f0.png)

**Comment by RedElephantDesign** [comment]
Нам кажется сообществу не нужен отдельный логотип с каким-то особенным начертанием капли или русской атрибутикой. Важно подтчеркнуть, что это сообщество Dupal, поэтому капля обязательна, воторой важный момент - название проекта.
Поэтому появились такие варианты. Они очень простые, но думаю это правильно. Ведь главное - это содержание проекта и польза, которую он принесет.

**Comment by RedElephantDesign** [comment]
собственно голосуйте из предложенных вариантов, если что-то понравится. Если сообщество нас не прогонит, то нарисуем еще варианты)

**Comment by fortis** [comment]
здорово, мне больше нравится вариант-2 из-за друпликона в букве 'о'.  
хотя вариант 1 и 4 тоже хороши, ближе к логотипу сообщества и в них больше акцент именно на друпал, и привычнее

**Comment by fortis** [comment]
может быть лучше 'русскоязычное' ?

**Comment by drupby** [comment]
@RedElephantDesign Русскоязычное сообщество Drupal

**Comment by RedElephantDesign** [comment]
Да у них разница именно в акцентах, согласен. Тут все зависит от ощущения. Чего больше хочется:
1. показать Drupal - тогда название сайта возможно не запомнится
2. а вот если вписываем каплю в "О", тогда вроде как больше внимания самой надписи

**Comment by RedElephantDesign** [comment]
@fortis 
@drupby 
Да, наверное, так корректней

**Comment by adubovskoy** [comment]
3/6 нравятся. 
Вообще все хороши.

**Comment by Niklan** [comment]
3,4,6 понравились. Возможно имеет смысл скрестить 6 и 4 :) Но тогда там будет два друпликона и это черезчур. А вообще да, отличные варианты.

**Comment by RedElephantDesign** [comment]
ну раз еть положительные отзывы, тогда сегодня постараемся выложить еще варианты. Есть еще человек со свежим взглядом так сказать.

**Comment by RedElephantDesign** [comment]
Всем привет. Выкладываем обновление по логотипам. Есть хорошие варианты, есть плохие. Показываем все. Решили в поисках вдохновения посмотреть сайты сообществ дрюпаллеров других стран. Вдохновения там не обнаружили. В основном пихают флаги в каплю. Этого очень не хочется, если честно, но вариант сделали. В остальных старались минимизировать и упростить и без того простую капельку. Может повторюсь, но главное чтобы пользователи запоминали адрес сайта и сразу понимали о чем этот сайт. Поэтому получились такие варианты:
![logo2](https://cloud.githubusercontent.com/assets/10986896/6202136/71b99c0e-b511-11e4-8dd7-7977050d6835.png)

**Comment by RedElephantDesign** [comment]
Особое внимание хотим уделить двум вариантам, которые на наш взгляд наиболее интересные:
![logo-nice](https://cloud.githubusercontent.com/assets/10986896/6202142/09741998-b512-11e4-95fe-68ff7403a739.png)
Вариант №11 и №16 показывают основную тематику сайта, не отвлекая внимания от названия.
При этом пользователи будут в голове дорисовывать недостающие элементы, что дополнительно заставит их разглядывать лого.

**Comment by RedElephantDesign** [comment]
Варианта №9 нет - так как думали, что там будет еще вариант с флагом. Но не придумали. Флаг на наш взгляд очень тревиальное решение, но зато, возможно, понятно и однозначно скажет о направлении портала.

**Comment by drupby** [comment]
я за 9-ый вариант :+1: 
а вообще хоть с флагом сама идея мне не нравится, но вот глядя на реализацию мне больше импонируют варианты 7  и 8

**Comment by RedElephantDesign** [comment]
Да, вариант 9, пожалуй, самый лучший из предложенных. Максимально просто:)

**Comment by RedElephantDesign** [comment]
По поводу 7 и 8 есть еще вариант, тут сразу несколько реализаций цветовых)
![2836_800px___1](https://cloud.githubusercontent.com/assets/10986896/6202163/cb4c0cf0-b513-11e4-9a03-1bb071e8e33d.jpg)

**Comment by drupby** [comment]
варианты 12, 13, 14, 15 я бы вообще исключил

**Comment by RedElephantDesign** [comment]
Можно правда подумать над таким вариантом, но боюсь не все сразу узнают храм, Москву и т.д.

**Comment by RedElephantDesign** [comment]
то есть вместо цветов флага, сделать цвета одной из башен

**Comment by drupby** [comment]
@RedElephantDesign наверное все таки цвета куполов?

**Comment by Niklan** [comment]
13, 14, 15 не совсем корректно изображены в круге. У друпала уже куча примеров как глаза изображаются якобы смотрящие прямо. 
![druplicon](https://cloud.githubusercontent.com/assets/2356744/6202261/b577a7e4-b500-11e4-9343-8c324d7f6594.png)

Считаю что он немного некорректен, так как использовался до 2004 года, хотя кто об этом знает и вспомнит ;) Но в кругу, считаю, надо изображать его именно так. Ну и лучше либо без круга, одни глаза, либо в капле. Круг ровным счётом не говорит ничего, а капля имеет прямо отношение к названию.

Тоже нравится 7 и 8, но флаг, как я считаю, нам надо либо исключать, либо делать так, чтобы там были разные флаги, т.е. для большинства стран, по крайней мере для начала, для русскоязычных стран: Белорусь, Украина, Россия, Казахстан и другие. Надо держать в уме что мы делаем Русскоговорящее сообщество Drupal, а не чисто Русское. Русское у нас уже имеется: drupal.ru, спасибо не надо :) А на русском говорят многие другие страны, так что будет немного оскорбительно ставить русский и только русский флаг. Так проще флаг СССР врубить, но это трэшак какой-то будет.

Так вот, в итоге, чисто моё мнение:
-  Флаги стран надо избегать, либо делать сразу для большинства крупных русскоговорящих стран. И делать их либо рандомным выводом, либо гифкой.
-  Круг в логотипе надо избегать. Либо просто глаза, либо капля. На крайний случай, в кругу глаза изображать "правильно".

Понравились задумки:
-  13 - то что буква заходит на логотип с бордером.
-  14 - то что надпись по кругу идёт.

А так, я бы тоже посмотрел на 9 вариант :)

**Comment by RedElephantDesign** [comment]
Пишите еще комменты. На следующей неделе предложим третий набор, он будет очень маленький и включать то, что понравилось с первых двух + что-то новое, гибридное из предыдущих решений.
Таким образом, думаем, что сможем предложить в итоге вариант, который понравится большинству.
В крайнем случае оставим на сайте тот вариант, который есть сейчас.
По поводу других стран, думаю лучше от флагов отойти вообще. У нас ведь написано русскоязычное сообщество. Большего и не надо.

**Comment by adubovskoy** [comment]
М?) 
![front](https://cloud.githubusercontent.com/assets/297623/6542648/2aae3ec8-c510-11e4-9a01-e7ed4f89716e.png)

**Comment by Niklan** [comment]
Ола комраде

**Comment by Niklan** [comment]
На отоспавшуюся голову глянул. Мну нравитцЦо) :cool:

**Comment by xandeadx** [comment]
подвал прибить неплоха бы

**Comment by adubovskoy** [comment]
Ток если так http://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/ .

**Comment by fortis** [comment]
@RedElephantDesign ваши наработки есть в исходниках?

**Comment by RedElephantDesign** [comment]
Есть. Напомните завтра, пожалуйста.--Red Elephant DigitalRussian Digital Agency (China, Beijing)http://redelephant.proTel: +86 010 5912 1130E-mail: info@redelephant.pro22.01.2016, 20:06, "Alan Bondarchuk" notifications@github.com:@RedElephantDesign ваши наработки есть в исходниках?—Reply to this email directly or view it on GitHub.￼

**Comment by fortis** [comment]
@RedElephantDesign напоминаю)

**Comment by Niklan** [comment]
@fortis У них там в Китае новый год вроде как.

**Comment by RedElephantDesign** [comment]
Ага, скоро Китай будет весь греметь. Лого выслал)

-- 
Red Elephant Digital
Russian Digital Agency (China, Beijing)
http://redelephant.pro
Tel: +86 010 5912 1130
E-mail: info@redelephant.pro

24.01.2016, 14:29, "Nikita Malyshev" notifications@github.com:

**Comment by adubovskoy** [comment]
@fortis сюда не забыть положить https://github.com/dru-io/promo

**Comment by fortis** [comment]
> Ага, скоро Китай будет весь греметь. Лого выслал)

@RedElephantDesign таак, а куда?))

**Comment by fortis** [comment]
@RedElephantDesign наверно просто на письмо ответили, а это гитхаб уведомления) если не трудно вот сюда imacoda@gmail.com продублируйте
