### ISSUE TITLE
На странице проекта отсутствует ссылка на проект

### ISSUE THREAD

**Issue by drupby** [Niklan/Dru.io#58]
На странице проекта нет ссылки на проект на орге, а по идее она там нужна. И на странице http://community.drupalife.com/project сортировка по дате добавления, как бы логичнее было бы по алфавиту.

**Comment by adubovskoy** [comment]
Вообще много вопросов в полезности этого раздела в текущем виде.

**Comment by drupby** [comment]
@adubovskoy проекты вообще в принципе нужны только в виде терминов таксономии для фильтрации остального контента

**Comment by Niklan** [comment]
Можно добавить описание и скриншоты. Но как. Либо это делают модераторы, либо как-то отдаём сообществу в руки. 
У раздела хороший потанциал, можно развить.

**Comment by drupby** [comment]
@Niklan я имел ввиду, что на странице нету даже ссылки на сам проект http://drupal.org/project/xxx

**Comment by Niklan** [comment]
Это да, думал ссылками на загрузку обойтись. Добавлю.

**Comment by drupby** [comment]
Что значит анкор "Запросить обновление данных." и с ссылкой http://dru.io/project/views# ?
И на странице http://dru.io/project сортировка должна быть по алфавиту
P.S. Один я не вижу в развитии сообщества товарищей из Украины, Москвы и Питера?

**Comment by Niklan** [comment]
1. "Запросить обновление данных" шлет запрос на сервак, он парсит новые данные. Статус, категорию и версии. Есть проблема, да, из под гостя там ничего сразу не меняется из-за кэширования. А так, по сути обновляет версии и апдейты для модуля. База в дальнейшем разрастется и по крону это дергать нету смысла, плюс апдейты у многих выходят часто и произвольно. Так, зная что был апдейт, или просто ради интереса, гость\пользователь нажимает апдейт и все обновляется. Кнопка видна только если с момента последнего апдейта прошли сутки. А с кэшированием всегда, лол. Надо точечно чистить кэш. Надо бы повесить туда еще cache_clear_all() чтобы у страницы кеш слетал.
2. Хорошо, теперь по алфвиту.

**Comment by Niklan** [comment]
Решено. Ссылка добавлена.
