### ISSUE TITLE
Не работает авторизация через facebook

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#59]
![d5](https://cloud.githubusercontent.com/assets/297623/5987526/7a62b9da-a940-11e4-9a7f-418dd6efa320.png)

**Comment by SemanticsPRO** [comment]
окай, киньте на меня, я с мобилы
31.01.2015 11:59 пользователь "Alexander Dubovskoy" <
notifications@github.com> написал:

**Comment by Niklan** [comment]
Не знаю починил ли RxB, но у меня работает как регистрация, так и авторизация. Видимо на тот момент не вступили в силу обновления нового url.
