### ISSUE TITLE
Раздел: Заказы

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#6]
_Раздел планируется, тут обсуждается как реализовывать._

**Раздел:** Заказы.
**Статус:** Запланирован.
**Описание:**
Каждый желающий может разместить заказ на платную помощь.

**Comment by adubovskoy** [comment]
Мысли о разделе:

Заказ - отдельная сущность, со следующими отображаемыми полями:
1. Автор
2. Заголовок
3. Описание
4. Вложенные файлы / ссылки на тз (если хранить накладно - то в виде ссылок, с инструкцией как пользоваться yandex.disk или др. хранилищами).
4. Бюджет (необязательно)
5. Контактные данные (показываются при клике, клик для счетчика).
6. (авто) Статус. По умолчанию - активный в течение 20/30 дней, потом уходит в архив с оповещением об этом заказчика (может вернуть назад) или в выполненные.
7. Референс к пользователю кто выполнил работу с оценкой (влияет на рейтинг, может быть -- отдельный рейтинг?). Просьба заполнить поле уходит автоматом автору при отправке в архив.

Важные моменты:
1. Заказы не комментируются. Т.к. всегда это выливается в обсуждение бюджета и ругань в сторону заказчика -- отпугивает заказчиков.
2. Участники могут подписаться на раздел (студиям это интересно) -- почтой получать оповещения о новых заказах.
3. Отображается общее количество запросивших контакты (заинтересовавшихся, в общем)
4. Заказ может изменяться автором, но надо хранить ревизии.

Есть некоторые сомнения -- нужно ли давать возможность ответить прямо в топике на предложение. Если и делать - то переписку заказчик-исполнитель делать приватной и никому не показывать (см. п.1 важных моментов).

**Comment by Niklan** [comment]
Пожалуй со всем соглашусь. Единственный момент. Делать переписку на стороне сайта, или же пусть сами связываются. Просто не вижу смысла делать у себя на сайте, но для начальных переписок наоборот, более предпочтительный вариант. Дальше, ясно-понятно, они скорее всего скоординируются в других мессенджерах.

Также добавлю, что лично я, хотел бы внедрить функционал по принципу oDesk:
1.  Заказчик может указать минимальный рейтинг для исполнителя, основанный на рейтинге в сообществе. Допустим мин. рейтинг 1, значит все у кого меньше 1, не увидят контактную информацию.
2.  Сделать не "показать контакты", а форму, где исполнитель может написать сообщение, в котором распишет, что хочет, а также сможет прикрепить какие-нибудь файлы, и возможно привязать работы из портфолио на сайте сообщества. При этом, отсылать клиенту на почту уведомление, сообщение, а также всю контактную информацию исполнителя, которые заполнил форму (брать из профиля) и отправлять письмо "как-бы с его почты", чтобы заказчик мог ответить сразу на это письмо.

**Comment by adubovskoy** [comment]
> Делать переписку на стороне сайта, или же пусть сами связываются

Да, наверное можно дать на усмотрение заказчика и по дефолту открывать возможность прямого общения(показывать контакты). Я к тому что строго говорить "только на сайте" не стоит - может отпугнуть.

**Comment by Niklan** [comment]
Тут не вопрос строго или не строго. Вопрос в целом, нужно ли нам в сообществе приватное общение или нет? Оно же открытое, а для переписок можно и в скайпе и по почте связаться. Если делать переписки, тут и node.js чатики надо подтаскивать, при этом найти того кто это делал уже.

**Comment by adubovskoy** [comment]
Имхо не нужно. Ответ на заявку на работу -> по сути комм.предложение. А его сподручнее почтой/ссылкой в скайпе. Я например, будь у меня выбор, всегда бы почтой на такое отвечал и скайпом проверял получено ли. Не внутри сайта.

**Comment by Niklan** [comment]
Тоже считаю что ненужно, но если тут кто решит что  нужно, наверно на это надо отдельный ишью заводить и думать зачем оно надо.

**Comment by SemanticsPRO** [comment]
Не страдайте перфекционизмом.
Создал заказчик проект, к нему комменты, не на попиздеть, а для выкладки своего портфеля или прикрепления КП.
Всё.
Кому надо связаться - пусть связывается вне сайта

**Comment by Niklan** [comment]
Но тут Александр прав, комменты тут точно ненужны. Если заказ уг, его все пропустят, если нормальный отзовутся. А если сделать комменты, то начнется срач и троллинг как друпал.ру, следовательно негатив и дозволенность тролить, а так хотя бы соблазна не будет.

**Comment by SemanticsPRO** [comment]
Ну так сделать коменты без боди.
Или жоско установить правила, что без базара, базарящим - закрыть комменты, у меня есть модуль, на флаге сделано

**Comment by xandeadx** [comment]
придумалось тут - чтобы при создании заказа клиент выбирал кого он ищет:
1. Профи (дорого)
2. Уверенного разраба (средний прайс)
3. Любого

**Comment by SemanticsPRO** [comment]
@xandeadx все тогда профи искать будут, но по прайсу Петра Иванова из соседнего подъезда, который запилил сайт клана на юкозе

**Comment by Niklan** [comment]
@SemanticsPRO нет. Пойти по принципу oDesk, там такая штука есть кстати говоря и никто не злоупотребляет.

Т.е. у каждой из градации есть мин. цена часа и бюджета которую может указать заказчик.
Допустим любому, любую цену.

А профи жестко 20$/час или выше, и всё. Тогда будут понимать какой ценовой категории им нужен.

Надо порыться на oDesk и его дочке, там заказы очень хорошо организованы. Считаю надо брать идеи оттуда и подгонять.

**Comment by SemanticsPRO** [comment]
@Niklan, ну вот я например знаю некоторых разрабов, вполне себе профи.
Но ставка у них ниже, есть и за 10 баксов работают.

**Comment by Niklan** [comment]
@SemanticsPRO тут ещё очень много зависит от скорости работы. Может они делают функционал профи 20$/час за 2 часа и сумма та же.

Надо обдумать, идея кстати неплохая. Все же надо дать как-то заказчику ограничить слегонца тех кто будет писать. Смысл ему будет читать 100500 новичков если ему нужен профи, а новичкам писать в поисках удачи.

**Comment by SemanticsPRO** [comment]
Я за свободный рынок, особенно в начале.
Кто будет квалификацию разрабов устанавливать?
Я тебе - ты мне?

На д.ру лет 6-7 назад поднимался вопрос сертификации, воз и ныне там

**Comment by Niklan** [comment]
Пофиг, пусть по началу будет свободно. Потом добавить можно, не долго ведь.

**Comment by adubovskoy** [comment]
Можно сделать ход конем и увеличить мотивацию))
Публикуется заказ/вакансия. Первые 12 часов (если что - потом можно цифру подправить) на нее откликнуться могут(увидеть контакты, или маякнут что могут взяться) только 20% пользователей с высоким рейтингом (берем выборку всех, отбираем лучших на данный момент). Через 12 часов откликаться могут все.

**Comment by xandeadx** [comment]
и клиент 12 часов теряет деньги, потому что все профи заняты :)

**Comment by adubovskoy** [comment]
нене, смотри, этим мы:
1. убираем "школьный демпинг" - ко времени низкоценовых предложений заказчик уже скорее всего поболтал с кем-либо из активных участников. 
2. мотивируем всех отвечать и помогать людям (выливается в конкурентное преимущество/деньги)
3. формируем позитивное первое впечатление у заказчика (высокий рейтинг == высокая адекватность. если нет -- надо настроить рейтинг чтобы было так).
4. отсекаем желающих "зарегиться чтобы откликнуться" и всяких роботов.
5. отсекаем от неокрепших умов заказчиков у которых ситуация "аАааА! сРочнО!" - спасаем, практически, молодежь )

все это требует сбора статистики чтобы отобрать оптимальный процент и время.

**Comment by adubovskoy** [comment]
И по поводу комментов - считаю что любое оповещение, где всем видно кто откликнулся, вредно. Почему:
1. Многие знают "конкурентов" (если можно так назвать) по нишам. Т.е. если я откликнусь в теме про создание визитки -- это может сильно отбить желание у других присылать свои предложения)) А результат -- меньше предложений у заказчика, меньше значимость ресурса.
2. Легко поддается "роботизации" (откликаться на все, чтобы светиться на ресурсе). 
3. Ускоряет "смерть вакансии" - мало мотивации, когда видишь что 50 человек уже откликнулись (а может заказчик ни с кем не поговорил? а может это 50 все -- роботы или занятые сейчас, "лишь бы нажать")

**Comment by Niklan** [comment]
Я тоже за то чтобы никто не видел кто откликнулся. Максимум кол-во показывать, но не имена.

**Comment by SemanticsPRO** [comment]
Кстати, стоит взять пример с фрилансим

**Comment by holyorb2** [comment]
> 1. Референс к пользователю кто выполнил работу с оценкой (влияет на рейтинг, может быть -- отдельный рейтинг?). Просьба заполнить поле уходит автоматом автору при отправке в архив.

Лучше каждый месяц письмо автору заказа с просьбой оценить. В письме так же ссылка "не хочу указывать эти данные" что бы отписаться.

> Но тут Александр прав, комменты тут точно ненужны. Если заказ уг, его все пропустят, если нормальный отзовутся. А если сделать комменты, то начнется срач и троллинг как друпал.ру, следовательно негатив и дозволенность тролить, а так хотя бы соблазна не будет.

Комменты нужны, а что бы не было срача нужна модерация + предупреждения в профиль и занесении в личное дело :)

Как вариант комменты видны только автору заказа, остальные видят только счетчик - тут ХХХ коментов. Плюсы:
- отпадает необходимость в приватных сообщениях
- комменты и заказ связаны, как для заказчика, так и для юзеров.
- обсуждение древовидное и заказчик может любую ветку заблокировать что бы не продолжать дисскусию.

**Comment by adubovskoy** [comment]
Часть функционала реализована, раздел есть.
Доработки - в отдельных issue будем поднимать.
