### ISSUE TITLE
Помечать новые ответы и комментарии

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#61]
Сабж. Как на хабре - новые комменты выделяются синей плашкой

**Comment by Niklan** [comment]
#19 имеет непосредственное отношение к сабжу. Это ишью закрываю дабы на ещё не созданный функционал собирать улучшения :), делаю связь чтобы там в нити было упоминание о пометке. Т.е. сейчас без реализованного трекера это все бессмысленно.
