### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#66]
Есть мысль сделать загрузку фото для скриншотов (сейчас неудобно). 

Чтоб не хранить у себя - можно пользоваться чем-нибудь типа https://www.drupal.org/project/flickrup .

**Comment by drupby** [comment]
удваиваю, уже кстати есть похожее есть issue #47, и кроме изображений не стоит забывать про подсветку кода issue #34

**Comment by Niklan** [comment]
Лучше imgur с него быстрее грузится и фотки хранятся крайне долго (вечно?). Ещё не разу не наткнулся на битую фотку с imgur, плюсом они недавно инвестиции получили, так что он развиваться будет дальше.

**Comment by adubovskoy** [comment]
Да, сам не пользовался, не знаю какой лучше, на ваше усмотрение. Это хотелка, которую в issue чтоб не забыть.

**Comment by xandeadx** [comment]
Ну что с картинками? One Click Upload 2 уже достаточно стабилен и поддерживает drag&drop на textarea.

**Comment by Niklan** [comment]
@xandeadx судя по всему он сливает все в папку sites/defaulte/files это не есть гуд. Или я не так понял.

**Comment by xandeadx** [comment]
куда он должен их сливать?

**Comment by Niklan** [comment]
Ну в идеале нам надо будет поле для аттачментов сделать и туда сливать, а там уже filefieldpaths подхватит.

**Comment by xandeadx** [comment]
http://xandeadx.ru/blog/drupal/677
filefieldpaths зачем?

**Comment by Niklan** [comment]
@xandeadx чтобы по папочкам всё лежало, по сути не кретично, но все же всеравно лучше бы в филд всё, чтобы файлы трекались.

**Comment by xandeadx** [comment]
One Click Upload сам умеет по папочкам расскладывать

**Comment by Niklan** [comment]
#47 по сути об одном и том же. Так как тот более общий ишью, туда перекат.
