### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#67]
- Title у главной страницы "Drupal сообщество | dru.io"
- description/keywords прописать
- Title у вопросов сделать из тайтла ноды вопроса

**Comment by drupby** [comment]
Ну тогда уж по теме, только SMM, открыть аккаунты сообщества в твиттере, фейсбуке, вк.

**Comment by fortis** [comment]
+1

**Comment by Niklan** [comment]
https://vk.com/druio
https://facebook.com/druio
https://twitter.com/dru_io - тут уже зареган без _ :(

**Comment by adubovskoy** [comment]
еще надо линки все внешние сделать nofollow, чтоб не было соблазна публиковать статью/вопрос ради живой ссылки. Пока не актуально, но как рейтинг сайта подрастет - полезут.
