### ISSUE TITLE
Интеграция drupal-интернет-ресурсов.

### ISSUE THREAD

**Issue by orion76** [Niklan/Dru.io#69]
Почитал заявки на функционал от сообщества.
Идей хороших, плохих, еще пока непонятно каких - море.
Обсуждение их полезности и утверждение на внесение в TODO dru.io - займет кучу времени и не факт, что к чему нибудь приведет.
А почему бы не дать каждому желающему возможность реализовать его идею на отдельном ресурсе и интегрировать его в основной?
"Взлетело" - отлично, нет - ну чтож, "опыт- сын ошибок трудных".
Плюс - появится возможность у большего числа разработчиков поучаствовать в проекте.

На первом этапе, я думаю, хватило бы организовать **общую регистрацию** и **"сквозную" авторизацию** для всех связанных проектов.

А далее, можно было бы подумать и об центральной поисковой системе, обмене данными между ресурсами и т.д.

**Comment by adubovskoy** [comment]
Что-то в этом есть, но пока не понимаю архитектуры.

По сути -- это просто openid сервер для друпалеров будет. Тогда чем он отличается от любой другой openid реализации или social auth варианта.

С другой стороны, можно подумать в сторону кросслогина и общих сессий... Но это очень большая дыра в безопасности, по сути если взломают один проект -- считайте что взломали все. Кто на это пойдет?

**Comment by adubovskoy** [comment]
Но мы рано или поздно (а скорее рано) переедем на D8, а там можно будет просто организовать нормальные форки конфигураций и деплой. Хотите доработок - вот вам все архивы, вот соглашения по именованию новых разделов, вот политика модерации сообщества нововведений (ну там, посмотреть демку, проголосовать, проверить качество кода и запушить в основной).

**Comment by semyondragunov** [comment]
Чо за изобретание велосипедов? Зачем городить там, где этого не надо?

Хочешь запилить функционал - форкай репу и делай, потом пул реквест. Затем встаиваем в сайт и смотрим взлетит или нет. Если нет, то откатываем.

**Comment by adubovskoy** [comment]
ну, да, примерно. но пока так нельзя просто) d7, база, боль-деплой и т.п.) но на d8 надо переходить и полностью открытый код для легкости форков

**Comment by semyondragunov** [comment]
Я имел ввиду не откат сайта, а тупо выключить новоиспеченный модуль и удалить)

**Comment by adubovskoy** [comment]
Фичами. Ну, да, надо тогда почистить базу пользователей, профили и т.п., просто truncate, чтобы актуальную базу можно было выложить в открытую, с сохранением приватности пользователей..

**Comment by Niklan** [comment]
Идея заманчивая, и даже, оригинальная, но есть косяк. 

Т.е. основный смысл инициативы дать возможность каждому запилить что он хочет и подключить это как отдельный сайт. Но всегда есть одно НО. Вы пишете что можно таким образом принять участие большему количеству человек в развитии проекта, но ведь это подразумевает что человек сам сделает сайт, оформит (?) его и подключит единую авторизацию. Не совсем понятно как в таком случае защищать пользователей основного ресурса. Таким образом, созданный ресурс придется отдавать опять сюда, под полный контроль и выдавать доступы к серверам и админке автору тоже будет и не правильно с точки зрения безопасности, и с моральной стороны не правильно, ведь он делал. Т.е. мы таким образом авторам проектов дадим доступы как минимум к пользователям. А если думать что автор всё отдаст сюда в свободное плавание, так в чем разница какой-то раздел предоставить в качестве Features.

Вообще, идея отличная, но не для Drupal 7 это точно. Мы постараемся как можно быстрее после стабилизации Drupal 8 переехать на неё, а с её новшествами, каждый сможет развернуть точную копию сайта сообщества без БД и следовательно, без различного рода утечек. А внесение функционала будет выполнятся обычным пул реквестом.

По поводу Features. С ними же гемора получим, не? Они, во-первых, переносят далеко не все настройки, так что придётся ещё и покодить почти в каждой фиче. Во-вторых, лично мне, сама идея держать в фичах не очень нравится, они вроде и полезные, но в них явно не хватает многого. Эту проблему решает только D8.

По поводу базы данных сообщества. E-Mail адреса и прочую стандартную инфу очень легко вычистить. Но там хранится не меньше и прочих данных которые надо не забыть вычестить перед выкладыванием базы. Access key различных соц. сетей и т.д. это превратится в извращение. 

В общем и целом я пока не вижу как это делать на 7-ке, это выльется в огромный труд, ведь поддерживать 7-ку на таком уровне будет сложновато. А нам бы сейчас силы лучше не распылять, а направить на допил текущих разделов и добавление новых. И опять же, считаю это целесообразным делать только на 8-ку, поэтому я выступаю за то, чтобы мы делали на 8-ке сразу дистрибутив, для простоты разворачивания сайта для правок и мало ли кому вообще пригодится такое решение.

P.s. нечто подобное есть у stackoverflow. Но там пользователи предлагают идею, в неё все вносят некий "вклад" а потом уже админы stackoverflow реализуют идею сами.

**Comment by orion76** [comment]
> > По сути -- это просто openid сервер для друпалеров будет. Тогда чем он отличается от 
> > любой другой openid реализации или social auth варианта. <<

Ни чем-)) Зато "свой", под полным контролем и ничем не ограниченный.
Ну в общем, дело даже не в общей регистрации-авторизации..
Это так - потренироваться, отладить технологию..

А в идеале, наладить систему обмена данными между связанными ресурсами..
Обыкновенными публичными данными: статьи, базы знаний, кармы-рейтинги пользователей и т.д.
Например, захочет кто-нибудь раздел с локализованным описанием модулей сделать и .. сделает.. 
Полезная информация, можно где-то еще использовать, но как?

**Comment by semyondragunov** [comment]
> Это так - потренироваться, отладить технологию..

А кто мешает? Репа открытая....

> А в идеале, наладить систему обмена данными между связанными ресурсами..

Зачем? Чтоб данные спёли?

> Например, захочет кто-нибудь раздел с локализованным описанием модулей сделать и ..

... и пул реквест в репу.

ИМХО совершенно тупая затея в данном контексте.
Такой подход подошел бы к примеру для CRM-системы, группы компаний.

**Comment by adubovskoy** [comment]
Ну, прятать надо только личные данные пользователей, все остальное не страшно, пусть используют, для того и пишем.

на самом деле это уже решено - почти все полезные ресурсы имеют rss/twitterfeed) т.е. забирать и делать что-то типа drupal planet русскоязычный можно. Но я могу показать чем это заканчивается - http://www.drupal.ru/aggregator .

**Comment by Niklan** [comment]
Там много других данных которые надо вычищать помимо личных данных пользователей.
API ключи и доступы: к соц. сетям, mandrill и прочим сервисам которые подключены к сайту.

**Comment by Niklan** [comment]
Чтобы не висело, я закрываю данный ишью, ибо обсуждение сошло на нет, а вероятность того что такое будет реализовано, по крайней мере на 7-ке, стремится к нулю. Если будет что обсудить, открывайте текущий тикет, или, если нету такой кнопки у не владельцев репозитария, напишите коммент, я октрою.
