### ISSUE TITLE
Раздел: Кейсы

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#7]
_Раздел планируется, тут обсуждается как реализовывать._

**Раздел:** Кейсы.
**Статус:** Запланирован.
**Описание:**
Аналог выставки сайтов, но с детальным описанием, какие модули использовались, какие были поставлены цели и задачи, как решали проблемы, которые были встречены в ходе разработки. Пропускать с жесткой модерацией.

Скорее как-то надо провести линию между кейсом и просто сайтом на показ, чтобы был один разел, кейсы помечать, да и вообще в отдельный материал отделить и жестко модерировать как на орге.

Пока не ясно, приживется ли вообще такой раздел.

**Comment by SemanticsPRO** [comment]
Не читал, но осуждаю(с)
Не стоит ли гайды и кейсы объединить?

**Comment by Niklan** [comment]
Гайды это же обучающие материалы а не рекламного характера.

Кейс подразумевает минимум технической части. Скорее с портфолио объединять надо, расширенные поля какие-то добавить и всё. А для мотивации таким добавлять золотую рамочку.
