### ISSUE TITLE
Множественный выбор лучшего ответа

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#70]
http://dru.io/question/486 собственно сабж. Надо найти дырочку. Та что была в комментах устранена давно, также имеем следующий код https://github.com/Niklan/Dru.io/blob/master/sites/all/modules/dlcommunity/dlcommunity.module#L29-L50

**Comment by drupby** [comment]
Может это не баг, а фича? Почему не может быть 2 правильных ответа?вот пример https://toster.ru/q/88471

**Comment by Niklan** [comment]
Тут вопрос  в том, как они были проставлены. Код получается не отработал.

**Comment by drupby** [comment]
@Niklan так у пользователей же даже после отметки флагом одного ответа, флаги имеются напротив и остальных ответов, на данный момент пользователь может любой  ответ пометить флагом и может снять флаг, независимо от того отмечал ли он другие ответы

**Comment by Niklan** [comment]
Так раньше так и было. Суть в том, что когда он помечает новый, старый снимается кодом. Это на случай если кто-то даст лучше ответ.

**Comment by drupby** [comment]
@Niklan так в том то и дело, что правильных ответов может быть два и более, зачем ограничивать одним?

**Comment by Niklan** [comment]
Вынес на обсуждение #71, от результата и прыгнем, удалять код или фиксить.

**Comment by Niklan** [comment]
На время обсуждения закрываю.
