### ISSUE TITLE
Количество "Лучших ответов" на вопрос.

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#71]
Собственно сабж. #70 всё же баг или фича. Давайте подумаем и решим.

**Comment by drupby** [comment]
Я за множественный выбор лучших (правильных ответов), как пример все тот же тостер привожу https://toster.ru/q/88471

**Comment by Niklan** [comment]
Я пока занимаю нейтральную позицию) Оба варианты логичны. В случае множественного, придётся контролировать злоупотребление.

Можно сделать 1 лучший от автора, и лучший по мнению сообщества, например. Раз уж варианты рассматриваем.

**Comment by semyondragunov** [comment]
ИХМО множественный правильный ответ не совсем то, что надо. Тут же имеется ввиду лучший ответ для автора. Так что я думаю, @Niklan подсказал правильную идею.
Как можно заметить, после "лучшего" ответа от автора, следует самый рейтинговый ответ. Можно его подписать (выбор сообщества и пр.).

**Comment by drupby** [comment]
А почему ответ лучший собственно, а не  правильный? Drupal сам по себе предусматривает несколько вариантов решения той или иной задачи. Поэтому ответов правильных может быть несколько. Тем более, что пользователи сами иногда помечают правильными несколько ответов.

**Comment by Niklan** [comment]
@drupby вот уже интересный агрумент, который, по крайней мере меня, склонил в сторону множественного выбора. Но придётся контролировать, иначе всем в подряд начнут развешивать.

**Comment by RedElephantDesign** [comment]
Автор может выбрать один какой-то понравившийся ответ. Тогда он идет в самый верх списка ответов.
А сообщество может ставить +/- по остальным ответам и сортировка идет по ним. Так автор вытащил лучший ответ по его мнению наверх, а сообщество (общественное мнение) сортирует остальные ответы. По +/- для сообщества можно взять идею с хабра. Упал в минус - комментарий стал серым. Тогда не придется менять местами комментарии в зависимости от +/-. Всем сразу будет видны основные хорошие комментарии, а все плохие будут серым цветом.

**Comment by Niklan** [comment]
@RedElephantDesign сейчас ровно так и реализовано. Но тут другая особенность, человек, зайдя из поиска, на подобных сервисах читает только то, что помечено галочкой зелёной, а как правило, внизу есть реально правильные ответы у которых рейтинг раз в 10 больше чем у верного. Поэтому, надо как-то это тоже учесть. Больше зеленых галок - больше прочитают)

**Comment by RedElephantDesign** [comment]
@Niklan согласен, иначе упустить можно какое-то решение из обсуждения

**Comment by Niklan** [comment]
Пока оставляем всё как есть. Никаких проблем не испытали за такой срок.
