### ISSUE TITLE
Раздел модулей сообщества

### ISSUE THREAD

**Issue by fortis** [Niklan/Dru.io#73]
Идейка, пока на обсуждение просто. 

Часто бывало требовался модуль который когда-то видел в форуме друру, но найти его по прошествии времени было не легко. Возможно стоит предусмотреть галочку в топике чтобы помечать его как содержащий модуль, или аттачить сущность-модуль к топику с полями описания модуля (версия, теги модуля прочее). 

В конечном счете нужна возможность найти модуль в сообществе, который не выложен на орг

**Comment by fortis** [comment]
может быть это должно быть близко к разделу с выставкой сайтов

**Comment by drupby** [comment]
Если предполагается размещение модуля в публикации, то элементарно можно добавить категории к публикациям и сделать допустим термин "Modules "(или "Модули"), ну и понятно на странице публикаций сделать фильтрацию по категориям.

**Comment by Niklan** [comment]
Проще в проект добавить галочку "Сделано сообществом" и всё :)

**Comment by adubovskoy** [comment]
> В конечном счете нужна возможность найти модуль в сообществе, который не выложен на орг

Есть мнение что таких быть не должно) У большинства самописа , выложенного на гитхаб, большие проблемы со стандартами и кодом, недавний пример - http://www.drupal.ru/node/115498 . 
На drupal.org бы долго провисел в песочнице.

**Comment by fortis** [comment]
так для того сообщество и нужно чтобы указать на стандарты)) бывают же и нормальные модули которые просто еще не дошли руки выложить на орг, как модуль с яндекс деньгами для оплаты картами, там вроде он только через пол года появился на орге. плохим модулям можно вешать значки

**Comment by fortis** [comment]
категория модулей у обычного материала не слишком очевидно, галочка к публикации - хорошо и просто, но фильтровать потом как? будут модули и для 7ки и для 8ки, не только модули но и темы еще

**Comment by Niklan** [comment]
@fortis смотри, раздел "Расширения" содержит как модули, дистрибутивы, так и темы. Мы же можем добавить в фасет галочку "Сделано сообществом", а дальше пусть уточняют. Как-то помечать их в общем списке, допустим, золотой рамочкой ненавязчивой.

Отдельный раздел считаю для этого ненужен, собственно как и модули не с орга, тут я полностью поддержу @adubovskoy. Автор того модуля уже вторую статью на главную друпал.ру пихает с таким кодом, в первый раз промолчал, во втором написал. Вот кто-нибудь зайдёт, возьмёт такой "модуль" по незнанию, поставит, потом всплывут проблемы (ведь поддержки никакой вообще), а во всех бедах начнут хаять друпал, ибо модули говяные, нерабочие. Модуль с орга хоть какая-то, но фильтрация. Получить хорошему коду зелёный свет на публикацию на орге не составит труда, а делиться модулем который будет вечно в песочнице тоже неправильно, опять же, потому что его могут взять, и скорее всего возьмут, пользователи, не владеющими ЯП и собственно знаниями Drupal API и потом это выльется в бОльшие проблемы.

Все хорошие модули от русскоязычных разработчиков есть на орге, так что особых проблем не вижу. Есть код в пеосчнице? Ну пусть напишут публикацию и расскажут о нём, но держать их  в общем списке как-то не очень хорошо.

По такому пути намного проще и лучше создать раздел для Code Review, как ты же и предлагал ;)  #54 Чтобы прежде чем лезть на орг помогли на русском языке объяснить проблемы которые будут при проверке.

**Comment by fortis** [comment]
я со всем согласный)
