### ISSUE TITLE
Доработка категорий

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#74]
Нужно:
1. Сделать выбор категорий с помощью chosen
2. Добавить категорию Node API
3. Удалить категории PHP, Routings
4. Вывести категории на странице вопроса

**Comment by adubovskoy** [comment]
п.2, п.3 done.

**Comment by Niklan** [comment]
А чем собстевнно категория Routings не страивает? Актуально для 8-ки

**Comment by xandeadx** [comment]
не представляю вопросов по этой теме

**Comment by xandeadx** [comment]
есть Menu API

**Comment by xandeadx** [comment]
Я тут подумал, может удалить такие категории как Block API, Taxonomy API, Field API и т.п. и создать вместо них модули Drupal Block, Drupal Taxonomy и т.д.?
Т.е. все core модули вынести из категорий в проекты.

В категориях оставить именно общие API не имеющие модулей - Entity API, Form API, Database API, AJAX, File API и т.д.

Мне кажется так более правильно.

**Comment by adubovskoy** [comment]
структурно правильно. Но непонятно - Field API понятнее чем Drupal Field, если будут адресный вопрос задавать - будут искать сочетание field api, наверное.

**Comment by xandeadx** [comment]
я что-то не помню чтобы когда-нибудь искал по "field api" :) обычно "drupal field [вопрос]"
если проблема только в seo, то можно добавить синонимов

**Comment by Niklan** [comment]
Тут вот в чем разинца, они оба воспринимаются по разному:
Field API - это чисто техническая категория. Т.е. сугубо вопросы связанные с написанием своих полей, их расширением в качестве виджетов и т.д.
Drupal Field - это общее, куда и влазит Field API, при этом тут же темизация полей, их создание, добавление, какие-то вопросы по конфигам.

Думаю стоит просто поменять название. То же самое и с блоками и такономией, андеад в принципе правильно написал. Я сначала не понял почему так, сейчас дошло) Тут надо давить не на то что у кого-то есть или нету модулей, а на то что это достаточно общая тема, а текущая многое не охватывает и мы так или иначе добавим предложенные категории.

тут в довесок стоит добавить какую-то категорию характеризующую кодинг. Т.е. фасетный комбо: Кодинг + Drupal Field по сути и будет Field API

**Comment by xandeadx** [comment]
по такой логике надо насоздавать категории views api, panels api, ctools
api :) имхо достаточно имя модуля

**Comment by Niklan** [comment]
Да нет, просто как ты и предложил. Field API -> Drupal Field и всё. Только по ядру.
Вот категория кодинг скорее тоже нужна. Её опять же можно с модулем каким в фасете сделать и увидеть только вопросы кодинга под модуль

**Comment by drupby** [comment]
Почему не сделать тег Fields?

**Comment by xandeadx** [comment]
@drupby в моём понимании должен быть проект Fields, а не тег, ведь это модуль.

**Comment by drupby** [comment]
@xandeadx на DA есть тег Fields (Description - "Fields are custom data that can be attached to Drupal entities.") http://drupal.stackexchange.com/questions/tagged/fields и там содержатся вопросы и по поводу Field API, и по модулю Field

**Comment by xandeadx** [comment]
@drupby на DA нет разбивки вопросов по модулям, там вся категоризация на тегах

**Comment by Niklan** [comment]
Пункт 1 тоже готов. Думаю ишью можно закрывать.
