### ISSUE TITLE
Не совсем корректная подсветка кода

### ISSUE THREAD

**Issue by drupby** [Niklan/Dru.io#76]
При таком объявлении массива (используя language-php)

``` php
$array = array (
  'key1' => 'value1', 
  'key2' => 'value2',
  //'key3' => 'value3',
  //'key4' => 'value4',
);
```

незакомментированные элементы и закомментированные будут иметь один и тот же class="token comment", соответственно одинаковый color

**Comment by Niklan** [comment]
Хм, да вообще странный какой-то у нас код для подсветки синтаксиса: https://github.com/Niklan/Dru.io/blob/master/sites/all/themes/dlcommunity_theme/js/prism.js

Поставил его потому что https://highlightjs.org/ не подсвечивал вообще ничего, одночто автодетект языка, а он даже код не видит, не то что язык определять. Надо будет в новой теме его потестить сного и отказываться от prism, хоть и мозиловский, но он какой-то очень хиленький.

**Comment by Niklan** [comment]
С темой перешли на higlightjs, он намного лучше подсвечивает.
