### ISSUE TITLE
Автодобавление проектов

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#78]
Пф, пришла идейка.

Напишу фильтр, который при обнаружении ссылки на орг, парсил данный проект и автоматически добавлял на сайт сообщества. 

P.s. В дальнейшем, если доведём до ума страницы с проектами, можно будет и подменять ссылки с орга на локальные проекты. Только чтобы так издеваться надо сделать страницу проектов куда круче и информативнее.

**Comment by adubovskoy** [comment]
Катя (kalabro) недавно сказала что хотела бы, как мейнтейнер модулей, получать оповещения по вопросам к тем или иным модулям/подписываться соотв. 

Соотв. предложенный вариант поможет эту страничку http://dru.io/project/views автоматом набивать. А при создании нового вопроса/ответа, мы также можем messages генерить для оповещения, или флаг.

**Comment by semyondragunov** [comment]
Выборка модуля из селекта по локальным проектам.

**Comment by Niklan** [comment]
Ну а что:
1. Делаем флаг на проект "Подписаться" или точечно "Подписаться на вопросы", "Подписаться на материалы". Ибо потом мы ведь можем и к гайдам и прочему цеплять их.
2. Далее хукаем добавление, допустим, вопроса, и всем кто подписан фигачим в трекер или ещё куда оповещение.

Сейчас, суть моего предложения. Ускорить наполнение базы. Т.е. даже упоминания модуля достаточно чтобы его добавить, значит им пользуются.

**Comment by Niklan** [comment]
Суть в том, что когда страницу проекта доведём до ума, мы сможем подменять ссылку на орг на нашу локальную. Где человек на русском языке получит намного больше информции. Тем самым удержав его в сообществе, и организовав какую-никакую экосистему. Разумеется, ссылка на орг будет на видном месте как сейчас.  

Также можно ссылки типа https://www.drupal.org/project/path_breadcrumbs автоматически трансформировать в -> Path Breadcrumbs.

Ещё вариант. Можно как-то оформлять заголовок Path Breadcrumbs, а справа сделать две иконки-ссылки [ ] [ ] и одна ведёт на локальный, другая на орг.
