### ISSUE TITLE
Короткие заметки

### ISSUE THREAD

**Issue by UksusoFF** [Niklan/Dru.io#79]
Столкнулся тут с проблемой что если в любое поле Drupal вставить emoji и попытаться сохранить, то вываливает ошибку работы с базой. Причем это даже на drupal.org
Решение в конвертировании базы в другую кодировку или установка [модуля](https://www.drupal.org/project/strip_utf8mb4) который их просто вырезает.
На публикацию эти пару строк вроде не тянут, а запостить можно было бы что бы потом другие не искали. 
Куда это запостить и надо ли вообще?

**Comment by Niklan** [comment]
Emoji вообще бич какой-то мобильных телефонов. Он нигде нормально не отображается. Считаю что выводить такое точно не надо, максимум срубать фильтрами.

**Comment by UksusoFF** [comment]
Вот этот модуль их как раз и выпиливает. ИМХО его хорошо бы поставить на все сайты где контент могут добавлять пользователи.

Вопрос в том нужно ли такие заметки размещать на сайте.

**Comment by semyondragunov** [comment]
@UksusoFF Ну запости в публикации, думаю интересно будет.

**Comment by xandeadx** [comment]
Попробовал на Drupal 7, никаких ошибок не вываливается, эмоджи отображаются нормально.
База в utf8_general_ci

**Comment by Niklan** [comment]
Собственно проблема не наша, а ядра. Да и никто фиксить походу не собирается на данный момент. Проблема следовательно не актуальна или малозанчима. Тянуть 1 модуль для такого слишком жирно, раз больше нет фидбека о данной проблеме

**Comment by UksusoFF** [comment]
Вопрос был не в том чтобы ставить модуль, а куда писать заметки? :)
