### ISSUE TITLE
Раздел: Конфигуратор

### ISSUE THREAD

**Issue by Niklan** [Niklan/Dru.io#8]
_Раздел планируется, тут обсуждается как реализовывать._

**Раздел:** Конфигуратор.
**Статус:** Запланирован.
**Описание:**
Принцип работы в некотором роде схож с вопрос-ответ. Суть такая, человек пишет задачу: "Нужно реализовать календарь на сайте", каждый желающий может предложить модули, которыми это можно решить, также по желанию добавить описание или пошаговую инструкцию как делать. Также добавить рейтинг, лучшее решение и комментарии, возможно даже галочку "могу сделать за оплату", что пригодится фрилансерам, если человек сам не сможет сделать по гайду или будет просто лень, то будет знать, что ему этот респондент может помочь за оплату.

**Comment by Samodelkin777** [comment]
Думаю стоит объединить с разделом гайды. В смысле если на запрос решили оставить инструкцию что-бы она была доступна и в разделе конфигуратор к определенному запросу и в разделе гайды

**Comment by Niklan** [comment]
Задач возникает слишком много, гайдов на всё ненапастись. Скорее имеет смысл как-то связывать гайды с конфигуратором.

**Comment by Samodelkin777** [comment]
Может не точно выразился. Если нет гайда пишем краткую инструкцию в конфигураторе. Если есть гайд прикрепляем его в качестве ответа в конфигуратор. И сделать это наглядно что-бы человек который решил ответить полной инструкцией добавил ее в гайды а в конфигуратор прикрепил. Да-бы избежать дубликатов. Тут надо прикинуть на сколько часто могут поступать типичные вопросы ответы на которые имеет смысл публиковать как гайды. Если и мало то и свзяь возможно не нужна.

**Comment by Samodelkin777** [comment]
Еще можно объединить с заказами. Поступила задача на определенный функционал, человек готов заплатить. Было-бы хорошо что-бы этот запрос был и в заказах и в конфигураторе.

**Comment by Niklan** [comment]
Если человек готов заплатить ему сразу в заказы.
Конфигуратор это, назовем так, отделение от Вопрос-ответ. Чтобы там не было тупых вопросов: "Как сделать как на том сайте?". Надо чтобы вопросы стали местом где разъясняют непонятное, уточняют и помогают понять. А в конфигураторе решались конкретные задачи, а ответы были конкретными решениями.

**Comment by xandeadx** [comment]
странный раздел. нигде не видел такого. все будут дублировать с вопросов

**Comment by Niklan** [comment]
Идею восприняли, видимо нечто подобное нужно, можно обдумать как реализовать более отделено от вопросов, чтобы четко прослеживалось что и где спрашивать.
