### ISSUE TITLE
Schema.org - разметка  Question/Answer

### ISSUE THREAD

**Issue by drupby** [Niklan/Dru.io#80]
Для вопросов/ответов  имеется разметка Schema.org http://help.yandex.ru/webmaster/supported-schemas/questions.xml, которую принимают и гугл, и яндекс. Можно на странице помечать вопросы, ответы, лучшие ответы, количество голосов за ответ, количество ответов и т.д. Пример такой разметки естественно имеется на http://drupal.stackexchange.com/
Это ишью к тому, кто занимается разработкой темы сайта, потому как такая разметка делается на уровне шаблонов/препроцессов.

**Comment by Niklan** [comment]
Да, будем делать.

**Comment by adubovskoy** [comment]
ага, задачка есть, я помню)
https://github.com/Niklan/Dru.io/issues/35

**Comment by Niklan** [comment]
Закрываю, переходим на #35
