### ISSUE TITLE
Форматы даты, времени

### ISSUE THREAD

**Issue by vistar** [Niklan/Dru.io#81]
Это на странице http://dru.io/question/851, например:
https://docs.google.com/file/d/0B-y7uZTTx536YzRTTlgxQ19jd1U/edit?usp=drivesdk
1. Разные форматы отображения даты, времени.
2. Не соответствие [стандартизованным](https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D0%BB%D0%B5%D0%BD%D0%B4%D0%B0%D1%80%D0%BD%D0%B0%D1%8F_%D0%B4%D0%B0%D1%82%D0%B0) в РФ. У меня такие форматы (/admin/config/regional/date-time/formats):
   - D, d.m.Y H:i
   - d.m.Y H:i
   - l, d F Y H:i

То есть дефис не нужен (не нашёл пока ссылку, откуда брал, и себе поставил везде), либо "в" между датой и временем.
И тут (/admin/config/regional/date-time/locale/ru/edit) они заданы для русского языка.

**Comment by Niklan** [comment]
Спасибо, в новой теме учтём: http://dev.dru.io/question/441
Уже всё ок, приведём к формату нужному.

**Comment by vistar** [comment]
Дефис между датой и временем остался пока…

**Comment by Niklan** [comment]
Исправлено на деве.
