### ISSUE TITLE
Фильтр по сложности вопроса

### ISSUE THREAD

**Issue by dashiwa** [Niklan/Dru.io#83]
Может подумать как организовать вопросы по уровню сложности?
Возможно решение не будет слишком обьективным, но поможет каждой группе пользователей.
Кому-то интересны вопросы для новичков,кому-то средние и тд...

**Comment by Niklan** [comment]
А кто будет определять сложность вопроса. Это слишком субъективное восприятие. То что может для меня быть очень просто, для вас показаться слишком сложно, и наоборот.

Если такое реализовывать, то тут два варианта:
1. Четко продумываем, определяем все виды сложностей с четким описанием что в конкретно каждую категорию попадает.
2.  Какую-то школу измерения добавляем в вопрос. Каждый сам выбирает насколько сложно для него и выводим обще-усредненную оценку - но тут сразу упремся в разное восприятие.

Посмотрю что другие скажут.

**Comment by adubovskoy** [comment]
Имхо не нужно. Лишняя сущность.

Какие реальные проблемы мы решим этой фильтрацией?
Сделать "введение для новичков" так не получится. Простая сортировка -- ничего особо полезного не даст.

**Comment by Niklan** [comment]
Раз фидбек нулевой, @adubovskoy считает не нужным, я тоже, а больше никто не высказался. Закрываем пока не появится очередная надобность в этом.
