### ISSUE TITLE
Апгрейд навигации на сайте

### ISSUE THREAD

**Issue by semyondragunov** [Niklan/Dru.io#84]
Или на главной воткнуть ajax пагинатор для колонок **Последние вопросы** и **Последние публикации** или придумать что-то другое.
Так как конкретно запарило Главная->Вопросы->Пагинатор->Нужный вопрос.
И хотя бы на время вместо трекера в профиль поместить вьюшку с теми вопросами/публикациями, где ты участвовал.

**Comment by adubovskoy** [comment]
Закрываем за давностью. Это уже реализовано в профиле (история участия) и сильно переработана главная.
