### ISSUE TITLE
Хакатон

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#85]
У меня тут локальное событие,
http://www.47hours.org/ . Думаю засесть писать раздел мероприятий для dru.io.
У кого есть возможность (удаленно можно), присоединяйтесь. Кидаю заранее, чтобы время можно было планировать)

**Comment by semyondragunov** [comment]
Немного не понял сути написанного. Что писать? Куда присоеденятся? Мероприйтий по Дру по пальцам...

**Comment by Niklan** [comment]
Будет мероприятие в Ростове, будет предоставлено место и т.д. Александр будет там и зовет других, кто может физически, а кто удаленно.

**Comment by RuZniki** [comment]
Я готов удаленно.
