### ISSUE TITLE
Склейка однотипных вопросов

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#86]
Подумать что делать с:
http://dru.io/question/302
http://dru.io/question/932
такого рода дублями.

Варианты: 
1. Сделать возможность пользователям помимо ответа указывать референс к старому вопросу. С рейтингом и комментариями.
2. Аналогично, но только для админов
3. Предлагать автоподборку из поиска (вопрос выявления ключевых слов, сложно).

**Comment by Niklan** [comment]
Тоже думал о первых двух пунктах. Надо будет делать.

3 больше на #17 походит.

**Comment by drupby** [comment]
К примеру на cyberforum.ru даются ссылки на похожие вопросы-топики (к примеру "Similar Посмотрите здесь:" http://www.cyberforum.ru/php-beginners/thread1404006.html), и если три похожих вопроса и делать ручной референс, то на какой вопрос они должны ссылаться?

**Comment by Niklan** [comment]
Я думаю идея, которую предложил @adubovskoy немного иная. Я так понял добавляется связь на вопрос, который очень похож, но немного отличается.  Такая штука на stakoverflow имеется, но крайне редко используется.

Похожие вопросы мы вообще можем выводить вьюхой основываясь на категории или ещё чем то.

**Comment by drupby** [comment]
@Niklan так потому на stakoverflow редко встречается, так как имеется много нюансов. При большом количестве вопросов сложно это все отслеживать, нужно как то автоматизировать, да и степень схожести вопросов оценивается весьма субъективно, вопросы по одной даже узкой тематике могут заключать в себя совершенно разный контекст. И как из 10 схожих вопросов выделить "главный"?

**Comment by Niklan** [comment]
@drupby в этом и сложность. Нужен алгоритм.

**Comment by UksusoFF** [comment]
https://github.com/Niklan/Dru.io/issues/232

**Comment by UksusoFF** [comment]
Некоторые все-таки можно и объединять. Например как в #232
