### ISSUE TITLE
Подборка ссылок на статьи о модулях

### ISSUE THREAD

**Issue by xandeadx** [Niklan/Dru.io#87]
Сейчас у каждого модуля есть своя страница. На странице модуля можно помимо ссылок на вопросы выводить ссылки на статьи об этом модуле.

Например на странице модуля Search API будет что-то типа:

— Search API и поиск с морфологией (http://xandeadx.ru/blog/drupal/686)
— Intro To Search API (Part 1) - How To Create Search Pages (http://www.webwash.net/tutorials/intro-search-api-part-1-how-create-search-pages)
— Поиск на Drupal 7 с помощью Apache Solr ч.1 — базовая настройка (http://habrahabr.ru/post/175527/)
— ...

Ссылок может быть сколь угодно много. Можно на странице модуля выводить только первые 10, а остальные на отдельной странице.

Чтобы ссылки не дохли, можно при добавлении сохранять их в каком-нибудь http://www.peeep.us/

**Comment by Niklan** [comment]
Так проще сделать раздел для публикации ссылок на внешние статьи. А уже при публикации связывать с проектом. Тогда ложных срабатываний не будет. А для сохранности да, можно сохранять в peeep и хранить до тех пор пока ссылка не отвалится.

**Comment by semyondragunov** [comment]
@xandeadx Идея отличная. У меня есть txt шник со статьями по модулям. Классно бы было всё в одном месте.

**Comment by Niklan** [comment]
#10 - сюда, это как раз про это. Добавим референц на проект и будем выводить.
