### ISSUE TITLE
Сам спросил, сам решил - кнопка

### ISSUE THREAD

**Issue by semyondragunov** [Niklan/Dru.io#88]
Сабж в тайтле. Не понятно решена ли задача. Или дать возможность ответить создавшему топик 1 раз.

**Comment by drupby** [comment]
"Или дать возможность ответить создавшему топик 1 раз." - вполне логично было бы вынести в ответ решение вопроса/проблемы и помечать ответ лучшим/решенным. А нынче я так понимаю автор вопроса сам не может давать ответы?

**Comment by Niklan** [comment]
Да, не может. Тут вопрос в другом. На старте многие начали свои вопросы дополнять ответами - что вообще не хорошо.

**Comment by drupby** [comment]
"На старте многие начали свои вопросы дополнять ответами - что вообще не хорошо."
Ну так ответ то в любом случае один можно написать, а для автора изменить в альтере поле Ответ на к примеру "Решение вопроса" (ну или как то так) и добавить description.

**Comment by Niklan** [comment]
Окей, надо будет сделать.

Вроде такой issue уже был. Надо нарыть. Уже вроде с темой и трекером закончили на деве, думаю скоро надо переносить,а потом и этими улучшениями займемся.

**Comment by Niklan** [comment]
Сделано в ходе #125. Автор вопроса может также дать 1 ответ.
