### ISSUE TITLE
Вторая страница коментариев

### ISSUE THREAD

**Issue by semyondragunov** [Niklan/Dru.io#89]
Когда начинается 2я страница комментов для ответа, то появляеться пагинатор. При переходе на 2ю страницу комментов вся страница обновляеться и делает логичный скролтоп.
Предлагаю использовать для данного пагинатора ajax.

**Comment by Niklan** [comment]
Это да.  У кого есть опыт в аякс пагинации когда их много на странице отзовись

**Comment by fortis** [comment]
нужен вьюшный аякс без скрола? тогда хватит и hook_views_ajax_data_alter в котором убираем скролтоп

**Comment by semyondragunov** [comment]
Кстати ещё заметил, что при переключении пагинатора к примеру на 2ю страницу в каком-нибудь ответе, он переключает все ответы на 2ю страницу. Нужен полный ajax.

**Comment by fortis** [comment]
наверно id пейджера совпадают у всех, там есть во вьюшке настройка

**Comment by Niklan** [comment]
@fortis не понял про скрол. Надо просто пейджеры аяксовыми сделать, чтоюы на лету подменялись, без всяких скролов
Или делать как на stackoverflow, выводить последние 5 комментов, потом "Показать все (N)" и грузит все разом.

**Comment by xandeadx** [comment]
Тут бы подошёл ajax-овый load more вместо пагинатора

**Comment by AvivarK** [comment]
Мои пожелания:
1) Комментарии к ответам и вопросам скрыть при открытии вопроса.
 Если оставить как есть на dru.io, то получается к вопросу бывают много комментариев, которые мешают просмотреть существующие на вопрос ответы. Приходится пролистать их.  Добравшись до первого ответа, сразу видишь комментарии к нему, и приходится их снова пролистать, чтобы добраться до второго ответа  и т.д.
2) Если выполнить первый пункт, то ненужна постраничная навигация, если кому-то нужно посмотреть ветку, то могут ее раскрыть. 
3) Как то темизировать вывод комментариев к ответу(к примеру фон положить с цветом, или ответ с комментарием сделать в общей рамке). Когда комментариев много, теряешь в них.
4) При нажатии на кнопку ответить на комментарий сделать пометку какому пользователю отвечаешь,  типа "@username, ..........". Чтобы было видно к кому обращается пользователь.

**Comment by semyondragunov** [comment]
@AvivarK 1 и 2й пункты: https://github.com/Niklan/Dru.io/issues/36

Кстати да, можно вообще убрать постраничность. И всё под кнопку убрать. И никаких извращений с ajax.

**UPD** А 4й пункт тоже обсуждали, но непомню к чему пришли.
**UPD2** Хотя опять же, с вариантом @xandeadx не надо будет открывать весь кат чтобы посмотреть последние комменты. Но я за вариант @AvivarK

**Comment by drupby** [comment]
Уже вроде где то предлагалось сделать как на тостере (пример https://toster.ru/q/204792), изначально вообще не показывать комменты, а только список ответов. Возле каждого ответа/вопроса выводить кол-во комментов и по клику выводить их.
