### ISSUE TITLE
Свои публикации (вопросы+ответы+комментарии) + уведомления

### ISSUE THREAD

**Issue by Attyla** [Niklan/Dru.io#90]
Добавьте возможность просмотра в профиле своих вопросов, ответов, комментариев+ уведомление о появлении новых ответов и комментариев. Спасибо.

**Comment by adubovskoy** [comment]
В трекере есть уведомления при новых комментах/ответах, а вот истории своих - пока нет, надо делать. Либо в профиле, либо в трекере. Или и там и там) Взял задачку, может на след.неделе будет.

**Comment by UksusoFF** [comment]
Дубликат: https://github.com/Niklan/Dru.io/issues/111 https://github.com/Niklan/Dru.io/issues/32
И вьюхи со своими вопросами же правда несложно сдеалать в профиле?

**Comment by Attyla** [comment]
Сейчас ссылки на свои вопросы храню во вкладках браузера это не очень удобно. Сделайте в профиле вьюху с вопросами текущего пользователя (комментарии и ответы менее важны).

**Comment by UksusoFF** [comment]
Ура!

**Comment by Attyla** [comment]
Ура!

**Comment by Niklan** [comment]
Ура!
