### ISSUE TITLE
Чат для сообщества

### ISSUE THREAD

**Issue by Chi-teck** [Niklan/Dru.io#91]
Предлагаю замутить чат на https://gitter.im, либо через какой нибудь IM клиент
Skype, IRC, Viber, Telegramm и т.д.

**Comment by drupby** [comment]
Есть skype-чат, но он скорее для обсуждения вопросов, касаемых относительно функционирования сайта. Если хотите вопросы по друпалу в чате задавать вместо сайта, то это мне кажется не самая лучшая идея.

**Comment by Niklan** [comment]
Я думаю если и делать чат, то на сайте. Во-первых, сразу понятно с кем общаешься, ибо единый профиль. И универсальность. Во-вторых кто-то не пользуется скайпом, кто-то другими мессенджерами. В принципе я не думаю что сделать общий чатик проблематично, надо найти тех кто знает Node.JS

**Comment by Chi-teck** [comment]
gitter.im привязывается к гитхаб аккаунту и имеет открытое апи и клиенты различные платформы. Я думаю можно сделать трансляцию сообщений на сайте. Для других IM в принципе наверное это тоже возможно.

**Comment by SemanticsPRO** [comment]
Человек без скайпа - почти импосибль.
На пыхе чат делать не стоит

**Comment by Niklan** [comment]
@SemanticsPRO потому им предложил на Node.JS и связать с друпалом. Примеры же есть.

У того же gitter ограничение в 25 человек на комнату, дальше $5/чел. Я  думаю мы лимит в 25 человек моментально израсходуем.

**Comment by Chi-teck** [comment]
Так ведь 25 человек это на **приватную** комнату? Для публичных чатов вроде нет ограничений.
Вот русский чат laravel https://gitter.im/LaravelRUS/chat.
Больше тысячи человек там.

**Comment by xandeadx** [comment]
> Я думаю мы лимит в 25 человек моментально израсходуем

как оптимистично :D

**Comment by Niklan** [comment]
@xandeadx да не, там просто все осядут, вкладки закрепят и будут висеть. Из эти 25 может быть 0 активных будет, но группу то збьет.

**Comment by fortis** [comment]
мне нравится идея проводить время от времени чат-консультации в заданное время определенного дня и анонсировать это на дру.ио, отвечая в чате на вопросы новичков. заранее согласовав когда удобно нескольким разработчикам поучаствовать и давать ответы в течении дня, не слишком часто, и только в рамках проекта, тогда можно и в самом друио встроить
а обсуждать сам проект вроде бы и в скайпе норм. мм?

**Comment by Niklan** [comment]
Hangout - лучше для этого. Ещё запишет и на YouTube зальет.

ИМХО, там это намного лучше всех сделано. Даже показ экрана адекватный а не мыльцо за 2300 как в скайпе.

**Comment by fortis** [comment]
я имел ввиду только текстовый вариант, чтобы сильно не отвлекало, гиттер нравится, так можно приобщать новичков и к гиту, тот же код модуля предложить выложить на гитхаб чтобы подсказать что-то

**Comment by Niklan** [comment]
https://gitter.im/Niklan/Dru.io  создал, давайте попробуем. Он там пул реквест зафигачил с ссылокой я хз пусть весит или принимайте)

**Comment by Niklan** [comment]
test

**Comment by karmazzin** [comment]
Как насчет Slack-чата и форму для инвайтов на сайте?

**Comment by adubovskoy** [comment]
gitter универсальнее. slack далеко не у всех есть и далеко не факт что он нам нужен.) 1 проект, все на гитхабе, gitter более подходит имхо.

**Comment by fortis** [comment]
гиттер подходит. пока закрываю топик
