### ISSUE TITLE
Ссылка на ответ, вопрос в поисковой выдачи.

### ISSUE THREAD

**Issue by RuZniki** [Niklan/Dru.io#92]
Воспользовался поиском http://dru.io/search?s=placeholder
![2015-04-08 00_57_59- _ dru io](https://cloud.githubusercontent.com/assets/1125080/7034579/5cb8e430-dd8a-11e4-989a-554700118298.png)
Нашел ответ, а как найти вопрос?
Перешел на страницу ответа (http://dru.io/answer/944) а там нет ни комментариев, ни вопроса.

**Comment by Niklan** [comment]
Надо результаты поисковой выдачи вообще изменить всем типам. Привести к единому стилю.
