### ISSUE TITLE
Несколько вопросов по новому функционалу/теме

### ISSUE THREAD

**Issue by drupby** [Niklan/Dru.io#93]
1. В чем функционал трекера, кроме сообщения "Нет свежих обновлений."?
2. На главной правый блок "Последние вопросы", а у левого блока заголовка нету почему то.
3. Зачем иконка вопроса напротив вывода каждого вопроса? (особенно на странице /question бросается в глаза)
4. На странице  /question  я бы заменил цвет иконок c черного на серый.
5. Не понятен смысл страниц расширений в нынешнем виде, хотя бы на них сделать вывод вопросов, относящихся к этим проектам.
6. Изображение логотипа размыто.
7. На странице пользователя хотелось бы видеть список его вопросов.
8. Что означает G на фавиконе?
9. На странице /question можно вывести больше десяти вопросов, т.к. снизу остается много свободного места из-за фильтров справа.
10. Когда голосуешь за ответ после клика бросает на верх страницы.
    ...

**Comment by Niklan** [comment]
1.  /summon @adubovskoy 
2.  Вернул, вообще странно почему пропало.
3.  Кто еще за убрать? Если еще кто-то выскажется против, уберу.
4.  :+1: 
5.  Вообще страница расширений получилась болезненной. Не ясно как оформлять загрузки, и докатилось в том виде без загрузок) Чтобы не оттягивать из-за не очень значительного раздела еще на пару месяцев перенос. А сейчас, так как на продакшене, будет больше стимула быстрее починить. Вьюха там вроде как есть, но не выведена, опять же, из-за не ясности как все это оформлять. Пожалуй справа верну. Потом если что переоформим этот тип.
6. Так экспортировалось из вектора. Могу svg скинуть, может кто через иной софт засейвит. Но Insckape отгрузил именно так в png, 1 в 1 размер без потери качества.
7.  Надо поднимать с дна ишью о профилях юзера и начинать пилить.
8.  Да это наследие от темы, надо бы сменить.
9.  Да, пожалуй, и блок убрать с последними вопросами.
10.  О... этот rate API. В прошлой теме пришлось костылем его подпирать чото бы аякс работал, надо вытащить и опять подпереть.

**Comment by Niklan** [comment]
Фавиконку вернул.

**Comment by Niklan** [comment]
Сделал по 15 вопросов на странице с общим списком.

**Comment by adubovskoy** [comment]
В трекере будет список ответов/комментов на твои вопросы. Надо бы туда еще activity log какой-нибудь, типа ленты всего где пользователь участвовал, это еще надо доделать.

**Comment by vortex9** [comment]
А почему сайт сейчас так адски тормозит? Любая страница грузиться около 30 секунд.
Кто такой dev.dru.io:35729?
![pic_3_1](https://cloud.githubusercontent.com/assets/5040287/7041386/903145f8-dde1-11e4-89d4-d739db752705.jpg)

**Comment by Niklan** [comment]
Убран

**Comment by vortex9** [comment]
Теперь снова летает

**Comment by drupby** [comment]
"Кто еще за убрать? Если еще кто-то выскажется против"
На главной в блоке со списком можно оставить, но на странице вопросов /question, где и так понятно, что здесь список вопросов, да и еще в совокупности с черным цветом всех остальных иконок, просто рябит в глазах.

**Comment by Niklan** [comment]
Согласен пожалуй. Уберу.

**Comment by xandeadx** [comment]
мои пять копеек:
1. Увеличить дефолтный line-height до 1.5
2. Ссылки вопросов не реагируют на ховер
3. В блоках с фасетами сделать цвет ссылок как обычный текст
4. Размер шрифта .question__bottom сделать на пиксель меньше - 13px
5. Убрать обрезание текста в блоке "Последние вопросы"
6. Задать марджины .form-item, а то сливаются
7. Аватары на странице с вопросами забирают на себя всё внимание, раньше было лучше

**Comment by Niklan** [comment]
Подавлющее большинство я так понимаю сделано. Если что можно другой ишью завести. Бегло пробежался, вроде всё есть крмое парочки моментов.
