### ISSUE TITLE
Количество материалов в скобках при активном фильтре

### ISSUE THREAD

**Issue by KhabibullinMax** [Niklan/Dru.io#95]
Чтоб было наглядно
При неактивном фильтре количество материалов отображается
![2015-04-08 12 58 18](https://cloud.githubusercontent.com/assets/5961634/7041052/3058b810-ddef-11e4-9a55-52b5b6438a01.png)
А при активном - нет
![2015-04-08 12 59 07](https://cloud.githubusercontent.com/assets/5961634/7041058/3bc2b8d6-ddef-11e4-95b7-d4fb21d8f15f.png)

Думаю, это не совсем логично

**Comment by adubovskoy** [comment]
Тут спорный вопрос. Это фасеты, так уж у них заведено) Но настройки посмотрим, не помню уже - есть ли в UI галочка на такой случай. Переписывать -- слишком накладно.

**Comment by Niklan** [comment]
Пока закрываю. Не критично, но как сказал @adubovskoy, может стать накладным.

Могу в случае фасетов заголовок менять на общий "Найдено N вопросо" но надо ли.
