### ISSUE TITLE
Трекер не работает

### ISSUE THREAD

**Issue by adubovskoy** [Niklan/Dru.io#96]
Пока текстом указал что в разработке. Печалька в том что у меня по работе цейтнот, а завтра я еду в Краснодар, там непонятно будет ли время.

**Comment by drupby** [comment]
"Пока текстом указал что в разработке." 
В разработке - это конечно хорошо, но нужно было бы и на github добавить модуль трекера, чтобы и остальные могли глянуть и поучаствовать.

**Comment by Niklan** [comment]
А он и лежит) 
https://github.com/Niklan/Dru.io/blob/master/sites/all/modules/custom/dlcommunity/dlcommunity_messages.inc

**Comment by Niklan** [comment]
Думаю там ошибка в самой сущности, которая сделана на ECK.

@adubovskoy сущности делаются, вангаю проблема в views.

**Comment by adubovskoy** [comment]
Починил, надо закоммитить изменения будет.
