### ISSUE TITLE
Редактирование ответа на вопрос.

### ISSUE THREAD

**Issue by UksusoFF** [Niklan/Dru.io#99]
Внизу написано: Вы уже дали ответ на данный вопрос. Воспользуйтесь редактированем, если желаете дополнить свой ответ. 

Но кнопки править нигде нет (:

**Comment by UksusoFF** [comment]
А и да, "редактированИем" вдогонку.

**Comment by Niklan** [comment]
![ex](https://cloud.githubusercontent.com/assets/2356744/7110392/98c4b7a4-e1c9-11e4-9401-1033d3357e65.png)

(скрин из под ..хера автора - он не модер, ни админ)

Опечатку поправил

**Comment by UksusoFF** [comment]
Неа, не вопроса. А ответа на вопрос: 
![dru io](https://cloud.githubusercontent.com/assets/1931442/7110429/0dc7276a-e1c2-11e4-8ff6-cdb426cece67.png)

**Comment by semyondragunov** [comment]
Наведи мышь на сообшение там шестеренка появиться, как у редактирования блоков и views. А если нет, то ...хер админ врубите простым смертным сию функцию.

**Comment by UksusoFF** [comment]
Не появится:
![default](https://cloud.githubusercontent.com/assets/1931442/7110439/540c1ff0-e1c2-11e4-90d6-8134a338e41a.png)

**Comment by Niklan** [comment]
Добавил доступ к шестеренке юзерам. Теперь у тебя при наведении тоже будет)

**Comment by UksusoFF** [comment]
Да, теперь работает. Спасибо.
